### ISSUE TITLE
Sharedpreferences doesn't work on IOS

### ISSUE THREAD

**Issue by i-Senku** [supabase/supabase-flutter#10]
When I sign in, I can see the session, but when I restart the application

`client.auth.session()`
`client.auth.user()`
`client.auth.currentUser`

all values return null.

**Comment by SercanKaya0** [comment]
same problem.

**Comment by phamhieu** [comment]
How do you check authentication on app start? can you share your code snippet?

**Comment by bdlukaa** [comment]
@i-Senku only on iOS? Have you tested in other platforms?

**Comment by i-Senku** [comment]
> How do you check authentication on app start? can you share your code snippet?

#
@phamhieu 
on root screen i calling this method. 
```SupaBaseManager.shared.client.auth.user()``` and it's return null.
I thought the app works like firebase.I was hoping to get the logged in user value when I restart the app.
#

> @i-Senku only on iOS? Have you tested in other platforms?
@bdlukaa 

android and web same issue.

or I misunderstood the working logic of the application.

**Comment by bdlukaa** [comment]
> I thought the package works like how firebase works.

It's a bit different. See https://github.com/phamhieu/supabase-flutter-demo for an example of how to use it

**Comment by i-Senku** [comment]
> It's a bit different.

Why is there user(), currentUser and session() functions available.These functions always return null

**Comment by bdlukaa** [comment]
> These functions always return null

Not if the user is logged in...

**Comment by batuhankrbb** [comment]
same problem here. It would be so good if you fix the auth system and make it more useful. (Firebase auth system is a good example)

**Comment by bdlukaa** [comment]
@batuhankrbb You guys can use `https://github.com/bdlukaa/supabase_addons/tree/master/supabase_addons`. It's very simple to use and the user is stored correctly + you guys get Analytics and Crashlytics to your app

**Comment by i-Senku** [comment]
> @batuhankrbb You guys can use [`supabase_addons`](https://github.com/bdlukaa/supabase_addons/tree/master/supabase_addons) (by me). It's very simple to use and the user is stored correctly + you guys get Analytics and Crashlytics to your app

@bdlukaa I was thinking of writing something like this with hive. It's a very helpful package thanks for it

**Comment by phamhieu** [comment]
just want to give more context. `supabase-flutter` comes with 2 helper classes `SupabaseAuthState` and `SupabaseAuthRequiredState` to support authentication flow. 

If you only need supabase client and user session persistent, then the addon from @bdlukaa seems to be a better fit. Take note that you may need to handle session expires on app resume.

**Comment by bdlukaa** [comment]
@phamhieu in my perspective of a Flutter developer, the current implementation is bad. It's not intuitive at all, and depending on a widget to handle authentication is bad. Compared to Firebase, it's just one line:
```dart
await FirebaseApp.initialize();
```

**Comment by phamhieu** [comment]
I will make an issue for this. I agree that recoverSession should be done better.

**Comment by bdlukaa** [comment]
@phamhieu I can make a PR for this, if you don't mind

**Comment by phamhieu** [comment]
That will be great @bdlukaa thank you
