### ISSUE TITLE
Email resend failed assertion '[OtpType.signup, OtpType.emailChange].contains(type)': email must be provided for type email

### ISSUE THREAD

**Issue by feiwhang** [supabase/supabase-flutter#1008]
https://supabase.com/docs/reference/dart/auth-setsession

Following the docs, I found an assertion failed 
`flutter: 'package:gotrue/src/gotrue_client.dart': Failed assertion: line 657 pos 14: '[OtpType.signup, OtpType.emailChange].contains(type)': email must be provided for type email`

1. call resend with provided email and OtpType.email

Should be able to resend confirmation email like docs suggest with out assertion failed.

└── supabase_flutter 2.6.0
    ├── supabase 2.3.0
    │   ├── functions_client 2.3.2
    │   ├── gotrue 2.8.4
    │   ├── postgrest 2.1.4
    │   ├── realtime_client 2.2.1
    │   ├── storage_client 2.0.3

<img width="573" alt="image" src="https://github.com/user-attachments/assets/ea72562d-caa6-4d32-8417-aa446f76c24d">
<img width="707" alt="image" src="https://github.com/user-attachments/assets/0cdb1e5e-d9ea-4177-a918-2190de10ddc1">
<img width="533" alt="image" src="https://github.com/user-attachments/assets/464935c3-17f8-4f45-99a3-69a513b47985">

**Comment by Vinzent03** [comment]
I think the documentation is wrong, and you need to use `OtpType.emailChange`. The js library uses emailChange as well https://supabase.com/docs/reference/javascript/auth-resend
