### ISSUE TITLE
Flutter web app - query on jsonb array of json records not working

### ISSUE THREAD

**Issue by davoutuk** [supabase/supabase-flutter#1010]
I have a Flutter web app that is querying a Supabase database via the Flutter Supabase client library.  One of my queries is not working when I try to query a jsonb column called 'tags' that holds an array of json records. For example:

```
[
  {
    "id": 22,
    "title": "test5",
  },
  {
    "id": 25,
    "title": "test6",
  }
]
```

When I construct a query to find all JSON records with the ID 22, the query returns nothing.

The fetch clause is like:

`.eq('tags->id', 22)`

The URL created by the client app includes a parameter like:

`&tags-%3Eid=eq.22
`
Any suggestions?

**Comment by davoutuk** [comment]
Further to my advice found elsewhere,  I've changed my json data model for the 'tags' column to store things as...

```
{
  "tagEntries": [
    {
      "id": 22,
      "title": "test5",
      "userUid": "cc1b9ad0-c24b-4756-a884-7b8a5e18a5fb"
    }
  ]
}

```
When I try to query on the json data I'm  using....

`.eq('tags->tagEntries[*].id',22)`

... and it still does not work.

Any suggestions??

**Comment by Vinzent03** [comment]
Where did you found the `tagEntries[*].id` syntax? I couldn't find it in the postgrest or postgresql documentation.

**Comment by davoutuk** [comment]
I found a Postgres doc showing json syntax

**Comment by Vinzent03** [comment]
I found the operator [here](https://www.postgresql.org/docs/current/datatype-json.html#DATATYPE-JSONPATH), but this is just postgresql syntax and not everything is supported by postgrest. Their supported json functions are listed [here](https://docs.postgrest.org/en/v12/references/api/tables_views.html#json-columns) and I don't think they support your desired query. So I suggest you to write a [rpc](https://supabase.com/docs/guides/database/functions?queryGroups=language&language=dart) instead.

**Comment by dshukertjr** [comment]
@davoutuk Yup, rpc is probably the easiest. Also you might have some luck playing around with [contains](https://supabase.com/docs/reference/dart/contains). 

The following code is not verified, so it might or might not work, but something like this:

```dart
final data = await supabase
  .from('table')
  .select()
  .contains('tags->tagEntries', { 'id': 22 });
```
