### ISSUE TITLE
phone otp code resend not working

### ISSUE THREAD

**Issue by erkinovalim** [supabase/supabase-flutter#1014]
**Describe the bug**
When I try to resend the otp code using the following code it gives this error:

error:
`
flutter: verification: AuthException(message: {"code":"unexpected_failure","message":"Unable to process request"}, statusCode: 500, errorCode: null)
`
code:

```
onPressed: () async {
                  try {
                    final response = await supabase.auth.resend(
                      phone: widget.phoneNumber,
                      type: OtpType.sms,
                    );

                    print('response: $response'); 
                  } catch (e) {
                    print('verification: $e');
                  }
                },
```

**Expected behavior**
It should resend the code but it gives an unexpected error

**Version (please complete the following information):**
├── supabase_flutter 2.6.0
│   ├── supabase 2.3.0
│   │   ├── functions_client 2.3.2
│   │   ├── gotrue 2.8.4
│   │   ├── postgrest 2.1.4
│   │   ├── realtime_client 2.2.1
│   │   ├── storage_client 2.0.3

**Comment by Vinzent03** [comment]
Are there any [auth logs](https://supabase.com/docs/guides/platform/logs?queryGroups=product&product=auth) in the Supabase dashboard? A 500 status code is uncommon and more often not a client issue.

**Comment by erkinovalim** [comment]
It was a problem with my phone otp provider and I have fixed it. Apparently my phone number was blocked by the provider for a short time for asking to resend the code too much.
