### ISSUE TITLE
Cannot add event after closing

### ISSUE THREAD

**Issue by denghejun** [supabase/supabase-flutter#1016]
Bad state: Cannot add event after closing
flutter: #0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      _CompleterSink.add (package:web_socket_channel/src/sink_completer.dart:90)
#2      RealtimeClient.push.callback.<anonymous closure> (package:realtime_client/src/realtime_client.dart:293)
#3      new RealtimeClient.<anonymous closure> (package:realtime_client/src/realtime_client.dart:137)
#4      RealtimeClient.push.callback (package:realtime_client/src/realtime_client.dart:293)
#5      RealtimeClient.push (package:realtime_client/src/realtime_client.dart:310)
#6      RealtimeClient.sendHeartbeat (package:realtime_client/src/realtime_client.dart:482)
#7      RealtimeClient._onConnOpen.<anonymous closure> (package:realtime_client/src/realtime_client.dart:400)
#8      _rootRunUnary (dart:async/zone.dart:1407)
#9      _CustomZone.runUnary (dart:async/zone.dart:1308)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#11     _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dar<…>
flutter: Bad state: Cannot add event after closing
flutter: #0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      _CompleterSink.add (package:web_socket_channel/src/sink_completer.dart:90)
#2      RealtimeClient.push.callback.<anonymous closure> (package:realtime_client/src/realtime_client.dart:293)
#3      new RealtimeClient.<anonymous closure> (package:realtime_client/src/realtime_client.dart:137)
#4      RealtimeClient.push.callback (package:realtime_client/src/realtime_client.dart:293)
#5      RealtimeClient.push (package:realtime_client/src/realtime_client.dart:310)
#6      Push.send (package:realtime_client/src/push.dart:61)
#7      Push.resend (package:realtime_client/src/push.dart:52)
#8      RealtimeChannel.rejoin (package:realtime_client/src/realtime_channel.dart:563)
#9      RealtimeChannel.rejoinUntilConnected (package:realtime_client/src/realtime_channel.dart:189)
#10     new RealtimeChannel.<anonymous closure> (package:realtime_client/src/realtime_channel.dart:142)

**Comment by Vinzent03** [comment]
Please don't just post the error message into other issues and follow the issue template for bugs. What version are you using? What code did you use?

**Comment by denghejun** [comment]
Very common code from samples:
supabase_flutter: ^2.6.0
```
await Supabase.initialize(
      url: AppConfig.supabaseServerUrl,
      anonKey: AppConfig.supabaseServerAnonKey,
      realtimeClientOptions: const RealtimeClientOptions(eventsPerSecond: 10),
    );

supabase = Supabase.instance.client;

channelPlayerMatch = Application.supabase.channel(
      'AGOODMAINLAND_GLOBAL_PLAYERMATCHCHANNEL',
      // opts: const RealtimeChannelConfig(ack: true),
    );

channelPlayerMatch.on(RealtimeListenTypes.broadcast, ChannelFilter(event: NetCore.EVENT_PLAYER_LEAVE_MATCH),
        (payload, [_]) {
      payload = payload['payload'] ?? payload;
      if (payload == null) return;
      var matchID = payload['matchID'] as String?;
      if (matchID != null && Application.game.player.currentMatchID == matchID) {
        Application.game.player.leaveCurrentMatch();
        Application.game.current?.currentRoom.enemies.forEach((element) {
          element.isFake = false;
        });
        print('[${NetCore.EVENT_PLAYER_LEAVE_MATCH}]: received player leave match[id=${matchID}]');
        MatchWindow.close();
      }
    }).subscribe();
```

**Comment by denghejun** [comment]
Can you rollback your code, you recently released realtime channel version cause big issue for my app. players can not see all other's position in game.

**Comment by denghejun** [comment]
I found the actual issue is the subscribe((status,error){
print(status);
}) the status sometimes always return: RealtimeSubscribeStatus.timedOut

**Comment by Vinzent03** [comment]
With #1019 being merged now, this issue should hopefully be solved now. You can try it by upgrading `supabase_flutter` to `2.7.0`. If you still experience any issues, please **create a new issue**.

**Comment by denghejun** [comment]
Got RealtimeSubscribeStatus.timedOut sometime, from China. The situation is sometime I got subscribed , sometimes I got timeout. Is the realtime API blocked from China? any workaround to fix this?
