### ISSUE TITLE
TextField maxLines isn't working

### ISSUE THREAD

**Issue by erkinovalim** [supabase/supabase-flutter#1017]
**Describe the bug**
when you set TextField's maxLines parameter to anything greater than 1 it doesn't stop the user from typing more lines in the TextField, when you press return in the simulator it just keeps adding more lines and scrolling down with each line being added.

**To Reproduce**
TextField(
      maxLines: 4,
      keyboardType: TextInputType.multiline,
    );

**Expected behavior**
The TextField shouldn't let the user put more lines than what's specified in the maxLines parameter.

**Screenshots**
https://github.com/user-attachments/assets/7b9b071b-2b43-44b7-9f17-5eb696416253

**Comment by dshukertjr** [comment]
Closing as it's not a Supabase issue. 

If this is a Supabase issue, please follow the issue template format and reopen a new one.

**Comment by erkinovalim** [comment]
Oh I'm really sorry, I confused this with the Flutter github repository😅
