### ISSUE TITLE
signUp throwing error about required async storage

### ISSUE THREAD

**Issue by quinnj** [supabase/supabase-flutter#1022]
I have a very bare-bones supabase setup like the following:
```
await Supabase.initialize(
    url: 'https://zvhskklginkuxjktdaqh.supabase.co',
    anonKey: '[anon key]',
  );
```

But when calling `supabase.auth.signUp`, I'm seeing the following error:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:gotrue/src/gotrue_client.dart': Failed assertion: line 201 pos 16: '_asyncStorage != null': You need to provide asyncStorage to perform pkce flow.
```

I tried initializing like the following, but it didn't seem to make any difference:

```
await Supabase.initialize(
    url: 'https://zvhskklginkuxjktdaqh.supabase.co',
    anonKey: '[anon key]',
    authOptions: FlutterAuthClientOptions(pkceAsyncStorage: SharedPreferencesGotrueAsyncStorage()),
  );
```

I then tried to avoid pkce all together and just use implicit, like the following:

```
await Supabase.initialize(
    url: 'https://zvhskklginkuxjktdaqh.supabase.co',
    anonKey: '[anon key],
    authOptions: const FlutterAuthClientOptions(authFlowType: AuthFlowType.implicit),
  );
```
but suspiciously, still see the same error about needing async storage for pkce flow:
```
_AssertionError ('package:gotrue/src/gotrue_client.dart': Failed assertion: line 201 pos 16: '_asyncStorage != null': You need to provide asyncStorage to perform pkce flow.)
```

I feel like i'm maybe missing something basic/obvious here. I'm a bit new to flutter/dart, so let me know if I'm just missing something obvious, but I feel like I've tried to follow the supabase docs for install/initialization.

I'm seeing this error on ios, run from vs code on macos. (I haven't tried android/web)

**Comment by Vinzent03** [comment]
Please follow the issue template when creating an issue. Which package version are you using? Seems like the constructor parameters are not passed on to the gotrue client. Are you sure, you haven't accidentally edited the source files of the packagees?

**Comment by quinnj** [comment]
Yeah, sorry, I'll try to find the exact versions. This is basically a brand new flutter app setup, added supabase package and trying to do an initial call. I haven't edited anything else that I'm aware. It should be latest dart/flutter/package.

**Comment by dshukertjr** [comment]
@quinnj You may have altered your pub cache unintentionally. You can try deleting your cache and retrying it. 
https://dart.dev/tools/pub/cmd/pub-cache#clearing-the-global-system-cache

**Comment by quinnj** [comment]
Ok, I think I figured something out. I had a backend server main.dart file included in the same directory as my flutter app and somehow the supabase client from the backend was getting used on the flutter side. I was using the non-anonymous key, and this is the non-flutter supabase package, so I imagine something there was getting messed up vs. what is expected on the flutter side.

Sorry for the noise and my newb-ness here. But I appreciate the quick responses.

**Comment by mirza-d3x** [comment]
> Ok, I think I figured something out. I had a backend server main.dart file included in the same directory as my flutter app and somehow the supabase client from the backend was getting used on the flutter side. I was using the non-anonymous key, and this is the non-flutter supabase package, so I imagine something there was getting messed up vs. what is expected on the flutter side.
> 
> Sorry for the noise and my newb-ness here. But I appreciate the quick responses.

I'm facing the same issue, can you explain how did you solved

**Comment by ethicnology** [comment]
Same here.

How did you solve that?

I have a dart project for my end-to-end tests

**Comment by alexandrespindola** [comment]
Same here, how can I resolve this?

**Comment by blackvitriol** [comment]
I resolved it by absolving of PCKE:
```
   _supabaseClient = SupabaseClient(
      supabaseUrl!,
      supabaseAnonKey!,
      authOptions: const AuthClientOptions(authFlowType: AuthFlowType.implicit),
    );
  }
```
