### ISSUE TITLE
iOS Deep link not working [Facebook]

### ISSUE THREAD

**Issue by bqubique** [supabase/supabase-flutter#1028]
**Describe the bug**
Signing in with Google works fine on both Android & iOS. 

Doing the same for Facebook login does not work. It stays at the login page and does not trigger the callback (or so I think). I have tried registering deeplink listener using `uni_links` package as an alternative, to no avail.

I have set up the app according to [the docs](https://supabase.com/docs/guides/auth/native-mobile-deep-linking?queryGroups=platform&platform=flutter&queryGroups=os&os=ios) as well as following [this article](https://facebook.meedu.app/docs/7.x.x/ios/) (both ways have been tried together/separately).

My Info.plist is as follows:

<details><summary>Info.plist</summary>
<p>

```
...
        <key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>CFBundleURLTypes</key>
  	<array>
    	<dict>
		<key>CFBundleTypeRole</key>
		<string>Editor</string>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>com.COMPANYNAME.APPNAME</string>
		</array>
    	</dict>
  	</array>
...
```

</p>
</details> 

Right now I always end up in:

Safari can't open the page because it couldn't connect to the server. 

Inside the Safari webview.

This is the Dart code I use to log in using facebook:

```dart
          //I'm using riverpod to reach the client, but the same issue is applicable even w/o it
          await ref.watch(supabaseClientProvider).auth.signInWithOAuth(
            OAuthProvider.facebook,
            redirectTo: kIsWeb ? null : 'com.COMPANYNAME.APPNAME://login-callback',
          );
```

**To Reproduce**

**Expected behavior**
I expect the callback to be called and Safari to return to my app (which has the scheme registered [here](https://supabase.com/dashboard/project/.../auth/url-configuration). 

**Screenshots**

**Version (please complete the following information):**

```
├── supabase_flutter 2.6.0
│   ├── supabase 2.3.0
│   │   ├── functions_client 2.3.2
│   │   ├── gotrue 2.8.4
│   │   ├── postgrest 2.1.4
│   │   ├── realtime_client 2.2.1
│   │   ├── storage_client 2.0.3
```

<details><summary>Flutter doctor output</summary>
<p>

```bash
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
    • Flutter version 3.24.0 on channel stable at /Users/blinqipa/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (6 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/blinqipa/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • iPhone 15 Pro Max (mobile)      • C11F31D8-6E32-4727-9AFD-34AB8A3140AB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.120
    ! Error: Browsing on the local area network for Blin’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</p>
</details>

**Comment by bqubique** [comment]
Something to note, the redirect goes to http://localhost/?code=...
<img width="498" alt="image" src="https://github.com/user-attachments/assets/66965b33-02da-4c0d-bdc7-fe1ba84975fc">

Which is actually what I have set my Site URL as (to test this locally with Flutter Web).
What should it be set to?

**Comment by dshukertjr** [comment]
Site URL doesn't matter so much as long as you have `com.COMPANYNAME.APPNAME://login-callback` set in your Redirect URLs, but do you?

**Comment by bqubique** [comment]
> Site URL doesn't matter so much as long as you have `com.COMPANYNAME.APPNAME://login-callback` set in your Redirect URLs, but do you?

Yes of course they are set up both on Facebook and Supabase.

**Comment by dshukertjr** [comment]
@bqubique On Facebook's end, the deep link should not be set. Instead, your callback URL from the Supabase dashboard should be set. You can read more about how to set it up on the docs here:
https://supabase.com/docs/guides/auth/social-login/auth-facebook

**Comment by bqubique** [comment]
@dshukertjr thank you. 

I believe everything's set up correctly now. I even receive the `access_token` on the logs, I receive these logs as well:
```
flutter: ***** SupabaseAuthState handleDeeplink com.COMPANYNAME.APPNAME://login-callback/?code=CODE_HERE
flutter: onReceivedAuthDeeplink uri: com.COMPANYNAME.APPNAME://login-callback/?code=CODE_HERE
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
```

but Safari does not get closed by itself unless I press the Done button at the top left.

**Comment by bqubique** [comment]
Adding `url_launcher` package and calling `closeInAppWebView()` method did the thing for me, but I'm still unsure if this is needed on my end while the docs don't mention it. Let me know if this is the expected behavior please @dshukertjr. Thanks!

**Comment by dshukertjr** [comment]
@bqubique I guess that will work! You can also open the browser on an external app:
```dart
supabase.auth.signInWithOAuth(
  OAuthProvider.facebook,
  authScreenLaunchMode: LaunchMode.externalApplication,
);
```

**Comment by bqubique** [comment]
I understand, thank you. But why is this happening and why is it not included under Supabase docs? Am I missing some configuration that **only** I ended up in this scenario?

**Comment by dshukertjr** [comment]
@bqubique I guess a lot of people figure it out themselves maybe. Which docs did you refer to when implementing this feature? Where would you say makes the most sense for us to added it to?

**Comment by bqubique** [comment]
I followed [this guide](https://supabase.com/docs/guides/auth/social-login/auth-facebook?queryGroups=language&language=flutter&queryGroups=environment&environment=client&queryGroups=framework&framework=remix). It would make sense to include it here maybe?

**Comment by dshukertjr** [comment]
Thanks for the feedback. I will add the note there to make sure other users aren't confused.

**Comment by bqubique** [comment]
Thank you @dshukertjr for your help as well. Yes please, so others aren't confused with this 🙂.

**Comment by dante-cervantes-rocketlab** [comment]
This is still an issue, since Apple reject apps that sign in opens in external browser, this error has been reported multiple times.

**Comment by AndryRoby** [comment]
Still a live issue, and I think the thread landed on the real shape of it: `LaunchMode.externalApplication` is what actually makes the Facebook (and Kakao/Discord) redirect fire correctly, but Apple's App Store review can reject a submission where sign-in visibly hands off to Safari, while `LaunchMode.inAppWebView` avoids that review risk but then several providers detect the embedded WebView and hang, never handing the redirect back, exactly like this thread found. There isn't a single setting that satisfies both constraints; it's a genuine trade-off, not a missed step.

If you do go with `inAppWebView`, closing it yourself is the reliable path: @bqubique's fix here (calling `url_launcher`'s `closeInAppWebView()`, driven off `onAuthStateChange`) is still the least-bad option I've seen for this combination.

I built a free client-side checker for the config half of this (scheme / allow-list / `Info.plist` / `AndroidManifest.xml` mismatches, plus a direct flag for `LaunchMode.inAppWebView` with Kakao/Discord/Facebook): https://arling.sk/flutter-supabase-doctor/
It won't resolve the Apple-review trade-off for you, but it rules out everything else in under a minute so you know where you actually stand.
