### ISSUE TITLE
Error when querying for contains() in array column

### ISSUE THREAD

**Issue by gcostaapps** [supabase/supabase-flutter#103]
Hi, I have an array column (int8[]) and I was using the below query with a previous version of the library

```
final auxQuery = _client.from('liveLesson').select();
auxQuery.contains('auxiliaryClasses_id', [classId]); //classId is int type
```

Now I've updated to the latest version of supabase (0.3.3) and I'm getting this error

```
code:"22P02"
details:"Array value must start with "{" or dimension information."
hint:null
message:"malformed array literal: "(11)""
```

How should I do the contains() query now?

**Comment by gcostaapps** [comment]
Thanks @dshukertjr , it's working this way!

I think it's best to update the comments in the library before closing this issue (or creating a new one) as it's recommended now to use like this `postgrest.from('users').select().contains('age_range', '[1,2)')`.

Beside this everything is great for me, thank you again!

**Comment by dshukertjr** [comment]
@gcostaapps Thanks for the suggestion. Contains is designed to take list as parameter, so I will take a look at why it stopped working. Thanks for letting us know!

**Comment by Vinzent03** [comment]
Closing this as I don't see any wrong comment anymore. https://github.com/supabase/postgrest-dart/blob/master/lib/src/postgrest_filter_builder.dart#L203

**Comment by Mounix99** [comment]
This issue still actual, I'm struggling with trying to get list of rows where my "used_by" column contains user_id with this filtering
`await supabase.client.from(_plantTable).select().eq('used_by','{$userId}').range(offset + 1, offset + 19)` 
and I'm receiving only this `type 'Null' is not a subtype of type 'String' in type cast`
