### ISSUE TITLE
Listening Database with more than two equality conditions is not working

### ISSUE THREAD

**Issue by Jaew00Shin** [supabase/supabase-flutter#1035]
**Describe the bug**

class SupabaseProjectDataSource {
  SupabaseProjectDataSource({required Supabase supabase})
      : _project = supabase.client.from('projects');

  final SupabaseQueryBuilder _project;

  Stream<ProjectRes> streamProject({
    required String packageName,
    required String platform,
  }) {
    var stream = _project.stream(primaryKey: ['project_id']);

    stream =
    stream.eq('package_name', packageName) as SupabaseStreamFilterBuilder;
    stream = stream.eq('platform', platform) as SupabaseStreamFilterBuilder;

    return stream.map((data) => data.first).map(ProjectRes.fromJson);
  }
}

this is my data source class.

stream.eq('package_name', packageName) this option is not working.

I think it is working only for last applied equality option.

stream.eq('platform', platform) only this code is working.

How can I apply more than two filters when listening to database?

**Expected behavior**

Both equality condition( stream.eq('package_name', packageName) &  stream.eq('platform', platform)) should be working.

**Version (please complete the following information):**
On Linux/macOS
Please run `dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"` in your project directory and paste the output here.

├── supabase_flutter 2.6.0
│   ├── supabase 2.3.0
│   │   ├── functions_client 2.3.2
│   │   ├── gotrue 2.8.4
│   │   ├── postgrest 2.1.4
│   │   ├── realtime_client 2.2.1
│   │   ├── storage_client 2.0.3

On Windows
Please run `dart pub deps | findstr "supabase gotrue postgrest storage_client realtime_client functions_client"` in your project directory and paste the output here.

**Additional context**

I think it should be working like querybuilder so that multiple query condition should be working.

**Comment by Vinzent03** [comment]
The documentation of the filter methods on `.stream()` states that only one filter can be applied. This is a restriction of the realtime server. So for now you can only use one filter. See #338
