### ISSUE TITLE
How manage relationship in real-time stream in Flutter?

### ISSUE THREAD

**Issue by babakoto** [supabase/supabase-flutter#1036]
Hello 
How load data (profile) relationship with streams when chat updated ? 

I'm looking for documentation on how to manage the relationship with Supabase in real-time, but I can't find it. The chat example you provided is very basic and doesn't reflect reality.

I would like to propose Supabase in my company as an alternative. As a lead, I need to be sure that Supabase won't cause any issues in our project, so I'm testing all the features.

```
class Chat {
   id
   room_id
   profile_id
   message 
}
```

```
class Profile {
   id
   firstName
   lastName
   photo

}
```

**Comment by dshukertjr** [comment]
Supabase realtime only allows you to subscribe to a single table with no joins supported. You can combine multiple realtime subscriptions to load joined data if you need all of them in realtime.

In a chat example, you most likely only need the chats in realtime, and you don't need to load the list of profiles in realtime as profiles don't change often, and it's not absolutely critical to keep them up to date. If, for some reason, keeping the profile data up-to-date is essential, you can create additional subscriptions to the profiles table to load them in real time.
