### ISSUE TITLE
Sign In With Apple not working on Android (OAuth)

### ISSUE THREAD

**Issue by mattr12** [supabase/supabase-flutter#1037]
**Describe the bug**
When signing in with Apple on an Android device, a browser opens up with my project's url briefly (<project-id>.supabase.co), then redirects to an Apple sign in form. Upon successful sign in, it just redirects within the browser to a "This site cannot be reached" page with a url on `localhost:3000`. Tried both inside an Android emulator with internet and Play Store service as well as an actual Android physical device--same issue.

Yet, the flow works fine on both my iOS simulator and physical device.

**To Reproduce**
I followed the docs for Flutter, under Android:

https://supabase.com/docs/guides/auth/social-login/auth-apple?queryGroups=environment&environment=client&queryGroups=platform&platform=flutter

1. Made sure to call `signInWithOAuth` since native sign in is reserved for iOS/macOS.
2. Added an `App ID`, `Service ID`, and a private key on my Apple developer account.  Added my domain to the service ID, plus `<project-id>.supabase.co` to "Domains and Subdomains" when configuring service ID, and `https://<project-id>.supabase.co/auth/v1/callback` for "Return URLs". 
3. Used the Supabase Apple client secret generator (found in the docs link above) to generate client secret.
4. Enabled Apple sign in on Supabase auth dashboard, pasted in service ID, client secret, and bundle id (for iOS app under "Authorized Client IDs").

**Expected behavior**
Expected to be able to login after successfully signing into my Apple account. To either be redirected to the Android app or for `onAuthStateChange` to at least emit a new signed in user. Neither occurred. 

**Version (please complete the following information):**
├── supabase_flutter 2.5.3
│   ├── supabase 2.1.3
│   │   ├── functions_client 2.2.0
│   │   ├── gotrue 2.7.0
│   │   ├── postgrest 2.1.2
│   │   ├── realtime_client 2.0.4
│   │   ├── storage_client 2.0.1

**Comment by dshukertjr** [comment]
@mattr12 Could you try to open the sign-in screen on an external browser like this?

```dart
supabase.auth.signInWithOAuth(
  OAuthProvider.apple,
  redirectTo: redirectTo,
  authScreenLaunchMode: LaunchMode.externalApplication,
);
```

**Comment by mattr12** [comment]
> @mattr12 Could you try to open the sign-in screen on an external browser like this?
> 
> ```dart
> supabase.auth.signInWithOAuth(
>   OAuthProvider.apple,
>   redirectTo: redirectTo,
>   authScreenLaunchMode: LaunchMode.externalApplication,
> );
> ```

@dshukertjr Updated `authScreenLaunchMode`. It still causes the same issue, but now I can see the error response in the URL:

http://localhost:3000/?error=server_error&error_code=500&error_description=Unable+to+exchange+external+code%3A+c3740de9aeffb.0.mtux.9YaAgImA#error=server_error&error_code=500&error_description=Unable+to+exchange+external+code%253A+c3740de9aeffb.0.mtux.9YaAgImA

`500: Unable to exchange external code`

**Comment by dshukertjr** [comment]
@mattr12
The error suggests that you have the wrong configuration strings in your Supabase dashboard. Please follow the steps here and double check all of your secrets/ etc. are generated and copied and pasted correctly. 
https://supabase.com/docs/guides/auth/social-login/auth-apple?queryGroups=environment&environment=client&queryGroups=framework&framework=remix&queryGroups=platform&platform=flutter#apple-sign-in-on-android-web-windows-and-linux

**Comment by mattr12** [comment]
I have followed those _exact_  instructions no less than three times, using the secret generator on the page. Remember, I linked that page and provided a list of steps that I took in the original message.

Is there no way to provide a more helpful error message?

**Comment by dshukertjr** [comment]
>Remember, I linked that page and provided a list of steps that I took in the original message.

I know, but I can only ask you to double-check your work. Make sure there are no extra spaces, slashes or anything else when you copy and paste things.

**Comment by mattr12** [comment]
> > Remember, I linked that page and provided a list of steps that I took in the original message.
> 
> I know, but I can only ask you to double-check your work. Make sure there are no extra spaces, slashes or anything else when you copy and paste things.

Understandable, but the iOS side is working perfectly fine, which means that the issue is most likely due to the secret generator, which I am copying directly from the docs page--literally using the page's inbuilt "copy" button.

Of course, i have made sure there are no extra spaces, slashes, or other characters in the `Account ID`, `Secret ID`, and `Key ID`

Is there a working example, demo, or tests of sign in with apple on an Android device?

**Comment by mattr12** [comment]
I was able to get a different `Secret Key` when adding `Key ID` in the secret generator. I did not do this previously because the field is marked optional.

Now I get this as a response, but still, there is no app redirect or login event being emitted:

http://localhost:3000/?code=18a40cc2-f4eb-5a3d-a355-28dab112a8df

**Comment by dshukertjr** [comment]
@mattr12 Okay, it looks like we are very close. Now at this point you just have to add the string that you are passing to the `redirectTo` parameter to the additional URLs on the Supabase dashboard under authentication  > URL Configuration

**Comment by mattr12** [comment]
> @mattr12 Okay, it looks like we are very close. Now at this point you just have to add the string that you are passing to the `redirectTo` parameter to the additional URLs on the Supabase dashboard under authentication > URL Configuration

Thank you, Tyler. It works on my physical device, but for some reason still not so in the emulator.

By the way, I don't think the last tidbit about URL configuration is in the docs--at least not the sign in with apple page. Moreover, the `Key ID` in the secret generator is marked optional, but for me (at least), it was required.

**Comment by dshukertjr** [comment]
> but for some reason still not so in the emulator.

Hmm, what exactly happens on the emulator?

> By the way, I don't think the last tidbit about URL configuration is in the docs--at least not the sign in with apple page.

Great call. I will add it in!

> Moreover, the Key ID in the secret generator is marked optional, but for me (at least), it was required.

There is a note about the key ID that says the following, but was your file maybe renamed?
>If the file you select does not preserve the original name from Apple Developer Center, please enter the key ID.
