### ISSUE TITLE
Community Addition: Offline Supabase

### ISSUE THREAD

**Issue by tshedor** [supabase/supabase-flutter#1039]
Hey Supabase team, this isn't a bug report or a feature request. We've added offline functionality to the [Supabase client in Brick](https://github.com/GetDutchie/brick/issues/445), and I wanted to share it with the larger community.

Brick caches remote data locally so that apps always [function the same offline as they do online](https://getdutchie.github.io/brick/#/offline_first/offline_first_with_supabase_repository). Models are defined in Dart while generated code handles the Supabase/SQLite querying under the hood; the application then uses [a simple ORM](https://getdutchie.github.io/brick/#/data/query) to work with data (and even [react to data](https://github.com/GetDutchie/brick/blob/main/packages/brick_offline_first/lib/src/offline_first_repository.dart#L341-L352)). If a request is made offline, it's retried until the client [comes back online](https://getdutchie.github.io/brick/#/offline_first/offline_queue).

The Brick Supabase integration adds this generation and querying capability for [Supabase apps with a straightforward setup](https://getdutchie.github.io/brick/#/offline_first/offline_first_with_supabase_repository?id=repository-configuration). But Supabase's client can still made offline without using Brick:

```dart
import 'package:brick_offline_first_with_rest/offline_queue.dart';
import 'package:sqflite/sqflite.dart' show databaseFactory;
import 'package:http/http.dart' as http;

final client = RestOfflineQueueClient(
  http.Client(),
  RestRequestSqliteCacheManager(
    'brick_offline_queue.sqlite',
    databaseFactory: databaseFactory,
  ),
  // Don't retry auth or storage requests; optionally add '/functions/v1' to not retry functions
  ignorePaths: {'/auth/v1','/storage/v1'},
);
final queue = RestOfflineRequestQueue(client: client);
await Supabase.initialize(..., httpClient: client); // or SupabaseClient(..., httpClient: client)
await client.requestManager.migrate();
queue.start();
``` 

If this is useful, I'd be happy to write a blog or [more thorough example app](https://github.com/GetDutchie/brick/tree/main/example_supabase) to illustrate using Supabase while offline. 

---

Sorry for opening an issue if this was the wrong place; I don't have Twitter and didn't see a link/email in the Supa Update newsletter to submit community work (although it would be a great honor if Brick's Supabase integration was mentioned in September's update).  cc @devj3ns

**Comment by dshukertjr** [comment]
This is awesome! Feel free to email me at tyler@supabase.io to discuss any collaboration opportunities around it!

**Comment by tshedor** [comment]
@dshukertjr awesome, just sent you an email
