### ISSUE TITLE
Keycloak provider in signInWithIdToken method in the gotrue package

### ISSUE THREAD

**Issue by Ppito** [supabase/supabase-flutter#1045]
I'm using Keycloak as my authentication provider and we need to use the `signInWithIdToken` method in our implementation.
The problem is that the gotrue package limits this method to the Google, Apple and Kakao providers : [gotrue_client.dart](https://github.com/supabase/supabase-flutter/blob/main/packages/gotrue/lib/src/gotrue_client.dart#L392)
Looking at the NodeJs implementation of this same package and function, I noticed that there was no particular blockage to using the Keycloak provider : [GoTrueClient.ts](https://github.com/supabase/auth-js/blob/master/src/GoTrueClient.ts#L631).

And indeed, by authorising Keycloak it works without any problem.

So my question is this: can you add this provider to the list of authorised providers?

**Comment by dshukertjr** [comment]
Sure, would you like to open a PR? Note that it seems like Keycloak is deprecated on the JS library, so there might be chances that it won't be supported in the future.

**Comment by Ppito** [comment]
I'll be unavailable for the next 3 weeks, so if no-one in my team has done a PR I'll do it when I get back.

Keycloak is not deprecated, quite the contrary. He has joined the Cloud Native Computing Foundation and is strongly supported by the RedHat team.
They have restructured the various dev/tools they had and the old SDK is effectively deprecated but not the new one.

**Comment by Ppito** [comment]
PR Merged. 

Thanks again.
