### ISSUE TITLE
RealTime is blocked in China, Got RealtimeSubscribeStatus.timedOut most of time 

### ISSUE THREAD

**Issue by denghejun** [supabase/supabase-flutter#1054]
version: `supabase_flutter: 2.7.0`

Got `RealtimeSubscribeStatus.timedOut` sometime, from China. The situation is sometime I got subscribed , sometimes I got timeout. Is the realtime API blocked from China? any workaround to fix this?

But I believe in the previous version 1.x.x is able to subscribe successfully for a long time.

**Comment by dshukertjr** [comment]
Not entirely sure if our services work on China, but I believe we do not guarantee that it works. I'm sorry, there isn't really much we can do on our end.
