### ISSUE TITLE
Upgraded to newest flutter (java as well) and now get an error when adding supabase for android build

### ISSUE THREAD

**Issue by MissingLinkDev** [supabase/supabase-flutter#1060]
**Describe the bug**
Was switching from firebase to supabase and started getting a java build error when adding supabase_flutter to the project
![image](https://github.com/user-attachments/assets/841ca931-140f-4f73-9abe-59a2e6b59807)

**To Reproduce**
1. Create a new flutter project using the skeleton application
2. Run project (works well)
3. Add in supabase_flutter
4. Rerun and will get the following error on build

**Expected behavior**
Should still build correctly

**Screenshots**
See error above on the error its producing. Here's flutter doctor for my android studio and sdk versions
![image](https://github.com/user-attachments/assets/ae9eef77-90ab-4443-9024-9af8703ec2da)

**Version (please complete the following information):**
Ran the command, but error starts as soon as package is added:
![image](https://github.com/user-attachments/assets/b22d45be-131c-4a94-bcea-8c952cc90232)

**Comment by Vinzent03** [comment]
Have you tried these steps? https://stackoverflow.com/a/79061221/14566634

**Comment by MissingLinkDev** [comment]
> Have you tried these steps? https://stackoverflow.com/a/79061221/14566634

Just tried that (except for downgrading to jdk17) always like to stay on current if possible, but if I need to downgrade I will

**Comment by Vinzent03** [comment]
[Here](https://app.daily.dev/posts/flutter-project-error--tia0sclmi) is another thread about this issue.
But there is nothing we can do on our end. The issue comes from the official and well known [path_provider](https://pub.dev/packages/path_provider) package.
So I close this, because there is no issue in our sdk itself.

**Comment by MissingLinkDev** [comment]
I found opening up just the android project folder in android studio would bring up AGP upgrade wizard and upgrade AGP from 8.1.0 to the required one for you.  Then went back to vscode and it worked

**Comment by esimo13** [comment]
Thanks, let's see if it works for me 🤞

**Comment by esimo13** [comment]
> I found opening up just the android project folder in android studio would bring up AGP upgrade wizard and upgrade AGP from 8.1.0 to the required one for you.  Then went back to vscode and it worked

AGP assistant can't be selected for my flutter application, when I'm opening the project in android studio, it doesn't show any AGP upgrade wizard, even when I'm trying to open the AGP upgrade wizard from Tools, the thing can't be selected ![image](https://github.com/user-attachments/assets/5eb40371-5d05-4ce3-828f-2b16523b240f)

**Comment by MissingLinkDev** [comment]
dont open up the entire flutter project, just teh android folder
