### ISSUE TITLE
Anonymous sign-in does not work as expected. New userid on every restart.

### ISSUE THREAD

**Issue by josefwilhelm-innio** [supabase/supabase-flutter#1062]
**Describe the bug**
I know anonymous sign-in from Firebase and expected the following behaviour:

Expected:
On `Supabase.instance.client.auth.signInAnonymously();` a new user is created in the user table and I can make authenticated function calls and save data for the user in the db. The same user id is used when the app is restarted.

Actual
On the next restart a new user is created. This means I can not save any user realted data. 
See screenshot below of the auth.users table from one day and one device only.

**To Reproduce**
Call `Supabase.instance.client.auth.signInAnonymously();` somewhere. 
Look at userid.
Restart.
userid is different.

**Screenshots**
![CleanShot 2024-10-10 at 16 03 54](https://github.com/user-attachments/assets/63bd1b1b-dfb3-4789-a0d6-b5d11afa99f8)

**Version (please complete the following information):**
`  supabase_flutter: ^2.7.0`

**Comment by Vinzent03** [comment]
Are you calling `signInAnonymously()` on every app start? I don't think you should do that. The previous session should automatically be restored and you automatically get logged in. Just listen to the `onAuthStateChange` stream.

**Comment by dshukertjr** [comment]
@josefwilhelm-innio Yeah, calling `.signInAnonymously()` does what it sounds like it does, it signs a user in anonymously and creates a new session. You should check if there is a session already and only when there isn't call the function.

```dart
if(superbase.auth.currentSession == null) {
  await supabase.auth.signInAnonymously();
}
```

**Comment by josefwilhelm** [comment]
Thanks, could not find that anywhere in the docs. Maybe you can add that line in the docs for anonymous sign-in.
