### ISSUE TITLE
`Supabase.initialize` throws an `AuthException` when an `accessToken` is provided

### ISSUE THREAD

**Issue by gibsorya** [supabase/supabase-flutter#1072]
**Describe the bug**
Hello! I am trying to provide an Auth0 access token to Supabase, but find myself unable to do so. After a little debugging I discovered that the Supabase initialize code is still initializing an instance of `SupabaseAuth` even with an accessCode, which references `Supabase.instance.client.auth`.
I believe this was introduced in #999 

**To Reproduce**
1. Initialize Supabase with an access token

**Expected behavior**
`Supabase.initialize` should accept a custom access token.

**Screenshots**
Here is the call stack for this bug:
![image](https://github.com/user-attachments/assets/31ea0686-bc36-4c81-9161-095790e38af4)

Here is the exception being thrown:
![image](https://github.com/user-attachments/assets/f723bfe7-eb08-49f7-a412-b4f06aa1e1a5)

**Version:**
On Linux/macOS
```
├── supabase_flutter 2.7.0
│   ├── supabase 2.4.0
│   │   ├── functions_client 2.3.3
│   │   ├── gotrue 2.9.0
│   │   ├── postgrest 2.2.0
│   │   ├── realtime_client 2.3.0
│   │   ├── storage_client 2.1.0
```

**Additional context**
For context, here is the code where I am initializing Supabase:
```dart
  final auth0 = Auth0(Environment.auth0Domain, Environment.auth0ClientId);

  await Supabase.initialize(
    url: Environment.supabaseUrl,
    anonKey: Environment.supabaseAnonKey,
    accessToken: () async {
      final credentials = await auth0.credentialsManager.credentials();
      return credentials.accessToken;
    },
  );
```

Here is the exception message:
```
Unhandled Exception: AuthException(message: Supabase Client is configured with the accessToken option, accessing supabase.auth is not possible., statusCode: null, errorCode: null)
```

**Comment by Vinzent03** [comment]
Please show the actual thrown exception. It should contain a `message` or similar to give some context on what's the issue. It should be shown in vscode when debugging and printed to the console, if not caught and handled.
