### ISSUE TITLE
Realtime seems to be creating empty tables daily

### ISSUE THREAD

**Issue by mattr12** [supabase/supabase-flutter#1089]
**Describe the bug**
`realtime` seems to be creating empty tables that are named using the form "messages_year_month_day". 

It is not clear if these tables are auto-deleted or what their purpose is, or how they are being created, but everyday since the 25th, a new table seems to be created.

I have used `realtime` for several weeks now but only noticed this issue now. The earliest table is the "messages_2024_11_25", so it may have began only recently.

Moreover, I have never queried anything against the `realtime` schema directly, but only through its API for Flutter.

**To Reproduce**
Use `realtime` using the Flutter API.

**Expected behavior**
Not to have empty tables being created daily.

**Screenshots**
<img width="219" alt="Screenshot 2024-11-29 at 5 00 39 PM" src="https://github.com/user-attachments/assets/04242709-072b-47ee-9ad7-fb1e914da22f">

**Version (please complete the following information):**
├── supabase_flutter 2.6.0
│   ├── supabase 2.3.0
│   │   ├── functions_client 2.3.2
│   │   ├── gotrue 2.8.4
│   │   ├── postgrest 2.1.4
│   │   ├── realtime_client 2.2.1
│   │   ├── storage_client 2.0.3

**Comment by Vinzent03** [comment]
Are the tables generated in the public schema? I highly doubt the issue lies in this client library as it does not support the apis to alter your schema. Maybe you have some trigger that creates those tables?

**Comment by mattr12** [comment]
No, the tables are under the “realtime” schema.I do not have any triggers on this schema, nor have I ever directly queried it, created any tables in it, etc.On 29. Nov 2024, at 11:42, Vinzent ***@***.***> wrote:﻿
Are the tables generated in the public schema? I highly doubt the issue lies in this client library as it does not support the apis to alter your schema. Maybe you have some trigger that creates those tables?

**Comment by Vinzent03** [comment]
If it's under the realtime schema, I think you should just ignore them as the schema is managed by supabase. I think they are used to apply RLS to private realtime channels.

**Comment by mattr12** [comment]
The list is growing by the day. It seems to have began on Nov 25th. 

Do empty tables not take up space?
