### ISSUE TITLE
Google: Signing out two times gives "Error Bad state: Cannot add new events after calling close"

### ISSUE THREAD

**Issue by maboumra** [supabase/supabase-flutter#1090]
**Describe the bug**
When signing in with google, no matter if is OAuth or native, you can only sign out once. If you sign in again and try to sign out a second time, you receive  "Error Bad state: Cannot add new events after calling close". This happens on Android Emulator running on Linux.

**To Reproduce**
1. Sign in with Google (any method)
2. Sign out by executing: await supabaseClient.auth.signOut()
3. Sign in again
4. Execute: await supabaseClient.auth.signOut() 
5. See the error: "Error Bad state: Cannot add new events after calling close"  

**Expected behavior**
Should sign out and sign in as much as the user needs without errors

**Screenshots**

**Version (please complete the following information):**
supabase_teste 1.0.0+1
└── supabase_flutter 2.8.1
    ├── supabase 2.6.0
    │   ├── functions_client 2.4.0
    │   ├── gotrue 2.11.0
    │   ├── postgrest 2.4.0
    │   ├── realtime_client 2.4.0
    │   ├── storage_client 2.2.0

**Additional context**
Running on Android Emulator.  Linux OS.

**Comment by Vinzent03** [comment]
Could you share the complete stack trace of that error? Where do you get that error? Does the `auth.signOut` call throw or do you receive it via the `onAuthStateChange` stream?

**Comment by maboumra** [comment]
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      Subject._add (package:rxdart/src/subjects/subject.dart:151:17)
#2      Subject.add (package:rxdart/src/subjects/subject.dart:141:5)
#3      GoTrueClient.notifyAllSubscribers (package:gotrue/src/gotrue_client.dart:1294:34)
#4      GoTrueClient.signOut (package:gotrue/src/gotrue_client.dart:861:7)
<asynchronous suspension>
#5      AuthGoogle.signOut (package:supabase_teste/auth/auth_google.dart:40:7)
<asynchronous suspension>
#6      HomePage.build.<anonymous closure> (package:supabase_teste/pages/home_page.dart:68:17)
<asynchronous suspension>

**Comment by maboumra** [comment]
Commenting the firs 4 lines on dispose method makes the error go away:
```
@mustCallSuper
  void dispose() {
    // _onAuthStateChangeController.close();
    // _onAuthStateChangeControllerSync.close();
    // _broadcastChannel?.close();
    // _broadcastChannelSubscription?.cancel();
    _refreshTokenCompleter?.completeError(AuthException('Disposed'));
    _autoRefreshTicker?.cancel();
  }
```

**Comment by Vinzent03** [comment]
Are you somewhere calling that `dispose()` method? If so, you shouldn't. You shouldn't call the dispose method on `SupabaseClient` as well, but only on `Supabase`, where you call `Supabase.initialize()` as well, if needed.

**Comment by maboumra** [comment]
I am sorry, you were correct. dispose was being called.
