### ISSUE TITLE
Streams are not closed when a subscription is cancelled

### ISSUE THREAD

**Issue by noforeignland** [supabase/supabase-flutter#1094]
**Describe the bug**

The cancel method on a stream subscription does not close the underlying connection. 

Conventinoally in Flutter, when you open a stream you keep a reference to it and call its cancel() method to clean up resources when it is no longer needed. 

From the logs, it appears that the Supabase client ignores the cancel call and does not close the stream or its underlying connection.

Using the example in the realtime docs to get a reference to the stream, and demonstrate that the cancel method doesn't clean up the subscription:

```dart
// stream table changes
StreamSubscription stream = Supabase.instance.client.from('countries')
    .stream(primaryKey: ['id'])
    .eq('id', 120)
    .order('name')
    .limit(10).listen((data) {});

// I expected this to close the stream and clean up the connection to the database but it does not:
stream.cancel();
```

Furthermore, the API does not seem to provide a way to get a reference to a stream's underlying channel. 

From what I can see in [the docs](https://supabase.com/docs/reference/dart/removechannel), these appear to be the only two methods available on the Supabase client for closing streams / channels:

```dart
// close a specific channel
final status = await supabase.removeChannel(channel);

// close all channels
final statuses = await supabase.removeAllChannels();
```

The removeAllChannels does close the stream subscription. As the stream's channel cannot be obtained, it is not possible to close it without closing all other channels.

**To Reproduce**
Steps to reproduce the behavior, try the code above and examine the client debug logs.

**Expected behavior**
The cancel method should stop updates, and clean up the resources used by the stream.

**Version (please complete the following information):**

```
├── supabase 2.3.0
│   ├── functions_client 2.3.2
│   ├── gotrue 2.8.4
│   ├── postgrest 2.1.4
│   ├── realtime_client 2.2.1
│   ├── storage_client 2.0.3
├── supabase_flutter 2.6.0
│   ├── supabase...
```

**Comment by Vinzent03** [comment]
This should already be the case. Please try updating to the latest supabase_flutter version 2.8.1

**Comment by dshukertjr** [comment]
Thanks @Vinzent03 for this! @noforeignland I'm going to close this issue as it is resolved in the latest version, but feel free to open another issue if something comes up!

**Comment by noforeignland** [comment]
Thanks for the quick response!
