### ISSUE TITLE
Recovery session should happen automatically 

### ISSUE THREAD

**Issue by phamhieu** [supabase/supabase-flutter#11]
# Bug report

## Describe the bug

Right now recovery session is not called under `Supabase.initialize` which is bad because users won't have access to session, user on app start

## Expected behavior

User should be able to access user and session after `Supabase.initialize` if there is persisted session info. 

## Additional context

Related https://github.com/supabase/supabase-flutter/issues/10

**Comment by i-Senku** [comment]
```
auth.currentUser
auth.user()
auth.session()
```
+ The functions are confusing.
+ Instead, only the auth.session() function should be able to access the user value and session information from within this function.
+ session information should be saved with hive.

**Comment by bdlukaa** [comment]
Fixed in #12
