### ISSUE TITLE
Slow responses from queries

### ISSUE THREAD

**Issue by spideythewebhead** [supabase/supabase-flutter#14]
# Bug report

## Describe the bug

When doing queries or even sign in, on a desktop app (havent tried with flutter web), the responses are very very slow
taking about ~5 seconds each.

## To Reproduce

for example even a simple query as

```dart
supabase.client.from('collections').select().execute().then((response) {
  ...
}

```
is very slow, for example running 2-3 times i got a response after 5 seconds

i dont know if it has to do with cold start, but it seems even after i send multiple requests,
some times it responses fast and some the casual 5seconds

![supabase](https://user-images.githubusercontent.com/55633618/128733618-4a7f11dc-1bf0-4481-85d9-e16d4defcb83.png)

## Expected behavior

Afterwards i tested with a newly created project, with js and everything was running smoothly,
both servers are located at eu-central-1.

In the browser (pure js) it run like instant, but on the desktop version gives a very bad experience

## System information

flutter doctor -v: 

[✓] Flutter (Channel unknown, 2.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.1 at /home/paradox11/fvm/versions/2.2.1
    • Framework revision 02c026b03c (2 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/paradox11/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/paradox11/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.1
    • cmake version 3.21.1
    • ninja version 1.10.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/paradox11/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.77

• No issues found!

supabase plugins:

supabase_flutter: 0.0.8
supabase: 0.0.8

**Comment by bdlukaa** [comment]
Could you post your benchmarks here?

**Comment by spideythewebhead** [comment]
Hi, i added to be able to login from the web too (so its same app on linux and web):
[benchmarks.txt](https://github.com/supabase/supabase-flutter/files/6960314/benchmarks.txt)

some times on the linux it responds fast, but in general its pretty unstable on desktop, idk maybe it has to do with the flutter/http

**Comment by bdlukaa** [comment]
This seems to be a problem with either your connection or your computer. I could not reproduce this issue on windows

Here are the result of my benchmarks using the example app:

```
0:00:02.222168 (first, query data)
0:00:00.667673 (second, insert data)
0:00:00.668617 (third, update data)
0:00:00.635208 (fourth, delete data)
```

```terminal
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [versÃ£o 10.0.19043.1110], locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.59.0)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by spideythewebhead** [comment]
My only concern is, why it's works fine on the web part  and the problem seems on Linux. I will try it on a new pc and connection, will report u back in a few days

**Comment by spideythewebhead** [comment]
Hi, I have tested on Mac with different internet connection , and it seems to work fine now! Even the first query didn't have a delay. I don't know if it's my connection or something with my linux setup. I guess it's something with my linux because the connection I have on Linux is better than the current one.

 I am closing the issue, thanks for the help
