### ISSUE TITLE
Migrate To Null Safety

### ISSUE THREAD

**Issue by SamarpanCoder2002** [supabase/supabase-flutter#18]
# Need migrate to null safety

## Is your feature request related to a problem? Please describe.

Now Flutter new project by default using with null safety. To use it in a broad manner with a large audience, we need to migrate it to null safety.

## Describe the solution you'd like

Anybody can fork it, migrate to the null safety, and can send a pull request

## Describe alternatives you've considered

Mentioned Above

## Additional context

Null safety addition will be a good addition for current flutter projects

**Comment by bdlukaa** [comment]
I'm on it.

**Comment by dshukertjr** [comment]
Asked pub.dev team for help with this issue and got a nice answer https://github.com/dart-lang/pub-dev/issues/5061#issuecomment-907588243

For now, it seems like we would have to wait for this issue on Flutter to be resolved. 
https://github.com/flutter/flutter/issues/44937
