### ISSUE TITLE
Make SupabaseQueryBuilder generic

### ISSUE THREAD

**Issue by programmador** [supabase/supabase-flutter#186]
PostgrestQueryBuilder is generic while it's descendant SupabaseQueryBuilder is not.
As a consequence the only available result type is `dynamic` while actually under the hood it's predominately `List<Map<dynamic>>` or even `List<Map<String,dynamic>>` which could be determined while debugging (though I have no idea what _JsonMap is).

Could it be implemented as generic? Moreover there is postgrest-dart 0.2 where PostgrestQueryBuilder is a descendant of Future (which is also generic).

**Comment by dshukertjr** [comment]
We now have this supported thanks to https://github.com/supabase/postgrest-dart/pull/94

You can use it like this:
```dart
// data is `List<Map<String, dynamic>>`
final data = await supabase.from('users').select<List<Map<String, dynamic>>>();

// data is `Map<String, dynamic>`
final data = await supabase.from('users').select<Map<String, dynamic>>().eq('id', myId).single();
```
