### ISSUE TITLE
Monorepo for all Dart packages

### ISSUE THREAD

**Issue by Vinzent03** [supabase/supabase-flutter#199]
Let's say I have a problem with realtime there are currently 3 repositories where an issue could be tracked: `supabase-flutter`, `supabase-dart`, `realtime-dart`. This is **really** annoying. (By the way, why is `supabase-flutter` still at `supabase` and the others at `supabase-community`?). 

I think by combining them into one repo, but still separated packages, you get a better overview. You could use [Melos](https://melos.invertase.dev/) by Invertase to manage them. Versioning should be easier too.

**Comment by dshukertjr** [comment]
@Vinzent03 

>I see that supabase-flutter is moved, but issues are still split between all repos. I would move all issues to supabse-flutter/ supabase-dart and disable issues on the rest.

Thanks for reminding me of this! I have disabled issues on all sub repositories. I created some basic issue templates on the Supabase-flutter repository as well. Something that I should have done long time ago...

**Comment by dshukertjr** [comment]
@Vinzent03 
After all these time, I have finally implemented your idea to the sub repos 🎉

**Comment by Vinzent03** [comment]
Great implementation via linking to the repo!

**Comment by dshukertjr** [comment]
@Vinzent03 @bdlukaa @DanMossa 

Just a heads up, but I plan to consolidate all the sub repos including yes_another_jaon_isolate into a mono repo using [Melos](https://melos.invertase.dev/) adding all of them into the supabase_flutter repo in the coming days if there is no big obstacles. We have a few open PRs, but once they are clear, I think we are good to do. Let me know if there are any concerns with it 💪

All the repos of the sub libraries will be archived with a link in their readme to the new location within supabase-flutter.

**Comment by Vinzent03** [comment]
That are great news! I'm just curious. Has anything in particular changed? Is there a similar plan for the other languages libraries? I guess the main reason is easier releasing?

**Comment by dshukertjr** [comment]
@Vinzent03 
> Has anything in particular changed? Is there a similar plan for the other languages libraries?

At the moment, no plans for other languages, but I'm really hoping the Flutter library can lead the way, because I really think it makes sense for all the languages to have a mono repo in general. 

> I guess the main reason is easier releasing?

Yup, this and quality assurance. I felt a strong need after seeing this issue. https://github.com/supabase/supabase-flutter/issues/430

**Comment by dshukertjr** [comment]
Closing as complete here https://github.com/supabase/supabase-flutter/pull/461
