### ISSUE TITLE
Flutter Web Popup login

### ISSUE THREAD

**Issue by nomanmurtaza786** [supabase/supabase-flutter#2]
Hi there, 
Do you know, how we can do flutter web pop up login and return back to same screen?

**Comment by phamhieu** [comment]
Right now, `supabase-flutter` doesn't support popup. I will close this as duplicated thread.

**Comment by mariopepe** [comment]
@phamhieu you said

>  I will close this as duplicated thread.

Which one is the main issue to track? I am waiting for pop up login on Flutter Web too, thanks...

**Comment by dshukertjr** [comment]
@mariopepe supabase_flutter currently does not support opening the OAuth sign-in screen as a pop-up, and we don't have any plans of adding support for it due to lack of demand.
