### ISSUE TITLE
Filters in db stream query

### ISSUE THREAD

**Issue by aarjan** [supabase/supabase-flutter#210]
The range query and multiple filter operator on stream query has been a major missing any plans on adding support for these?

**Comment by dshukertjr** [comment]
@aarjan 
Not being able to support multiple filter operator is due to limitation on our realtime server. For anything further like multiple filters or additional filter type, it would be great if you could open an issue on the [realtime repo](https://github.com/supabase/realtime/issues). 

For supporting range operators, I would like to hear what kind of use cases you have.

**Comment by rlee1990** [comment]
> @aarjan Not being able to support multiple filter operator is due to limitation on our realtime server. For anything further like multiple filters or additional filter type, it would be great if you could open an issue on the [realtime repo](https://github.com/supabase/realtime/issues).
> 
> For supporting range operators, I would like to hear what kind of use cases you have.

I would also say that range would be a major requirement. For example being able to paginate chat messages in realtime while also limiting the number of request we have to make to the database.

**Comment by Vinzent03** [comment]
I think we can support it by using the range operator in the initial postgrest call and ignoring update and delete events of not loaded rows. But I don't know what to do with insert events. If the rows are sorted it may cause issues, right?

**Comment by rlee1990** [comment]
> I think we can support it by using the range operator in the initial postgrest call and ignoring update and delete events of not loaded rows. But I don't know what to do with insert events. If the rows are sorted it may cause issues, right?

I think inserts would still be good to have it could allow for the developer to choose to show something like new post or for chats to allow them to just insert it. Right now i am using realtime along with making database calls to use pagination.

**Comment by dshukertjr** [comment]
>I think we can support it by using the range operator in the initial postgrest call and ignoring update and delete events of not loaded rows. But I don't know what to do with insert events. If the rows are sorted it may cause issues, right?

Yup, supporting `.range()` operator would break things once an insert event is received. 

>For example being able to paginate chat messages in realtime while also limiting the number of request we have to make to the database.

In general, pagination on realtime data could be tricky. The way I would do it right now is to increase the number of you pass on `.limit()` as the user scrolls through your chat history. You could also explore options where you retrieve the past chat history with just plain `.select()` calls to your database, and combine those data with the `.stream()` data on client side. It sounds a bit complicated, but again, pagination on realtime data will be complicated no matter which route you take.
