### ISSUE TITLE
Querying data is slower on supabase-flutter v1

### ISSUE THREAD

**Issue by ayomessenger** [supabase/supabase-flutter#229]
**Describe the bug**

Every query we execute takes considerably longer than in the 0.3.3 version.

A simple select query on any of our tables now lasts between 2 and 7 seconds, whereas with the version 0.3.3 it lasts between 200 and 350ms. 

**To Reproduce**

We can reproduce this everytime, on every query, on mutliple devices and on multiple OS.

**Expected behavior**

Queries and functions be executed as fast as in version 0.3.3

**Screenshots**

With version 0.3.3 (327ms)
![fast_response](https://user-images.githubusercontent.com/99839615/194352028-f0179b28-4cd2-40f1-84b9-742f3973f088.png)

With version 1.0.0-dev.9 (2435ms)
<img width="834" alt="Capture_decran_2022-10-06_a_17 21 56" src="https://user-images.githubusercontent.com/99839615/194353194-822d9809-897b-4858-af3c-a316d6110ead.png">

**Smartphone (Google Pixel 6):**
 - 1.0.0-dev.9

**Smartphone (iPhone XR iOS 16):**
 - 1.0.0-dev.9

**Additional context**

**Comment by dshukertjr** [comment]
Could you provide sample schema of your table you are querying from as well as roughly how many rows you have in that table?

**Comment by ayomessenger** [comment]
Here is the schema of Message table:
<img width="988" alt="Capture d’écran 2022-10-10 à 16 22 13" src="https://user-images.githubusercontent.com/99839615/194888847-21b5f70f-eaa8-464b-83a9-2065afc46235.png">

We have approximately 300 rows in the message table, but the performance issues are on all the tables. This issue only occurs with this version and not with the 0.3.3.

**Comment by dshukertjr** [comment]
Thanks for the details. I am able to confirm that query runs slower on the developer preview version. Trying to pin point where the delay is right now.

**Comment by dshukertjr** [comment]
@ayomessenger 
With supabase-flutter after v1.0.0-dev.1, we started using isolates so that the library will not junk up the main thread when parsing large json  string. This isolate seems to be the cause of slow response times. However, I have tested the same code on release mode, and saw that the performance drop was gone. Could you try to test your app in release mode with supabase-flutter 1.0.0-dev.9 and see if your query is still slow?

**Comment by dshukertjr** [comment]
@supabase-community/dart-maintainers 
After a quick research, I couldn't really find issues on using isolates on debug mode, but I wonder if there is a way to speed it up on debug mode so that it does not feel buggy to the users.

**Comment by Vinzent03** [comment]
@dshukertjr Does it make sense to use isolates for bigger json only? Maybe check the length of the string?
@ayomessenger Which Flutter/Dart version are you using? There was some huge update to isolates creation time. But I don't know which version.

**Comment by dshukertjr** [comment]
@Vinzent03 I like that idea! Let's do it!

**Comment by Vinzent03** [comment]
@dshukertjr But how do we get the best length? We need some tests finding the spot, where parsing a long json compensates the effort of creating an isolated. Or instead, can we keep a once created isolated in the postgrest client?

**Comment by dshukertjr** [comment]
@Vinzent03 Oh, yeah. Reusing isolates seems like a more viable solution. It might be worth a while to see if the performance improves!
https://blog.logrocket.com/multithreading-flutter-using-dart-isolates/#reusing-flutter-isolates

**Comment by Vinzent03** [comment]
I would combine json size check with isolated reuse. But when do we want to create the isolated? On first json encoding or in the `PostgrestClient` constructor? Creating in the constructor might be an unexpected side affect...

**Comment by bdlukaa** [comment]
In the `PostgrestClient`, otherwise the first json encoding/decoding would be slow and only subsequent calls would speed up. We just need to make sure the isolate is created.

Also, I believe it's time for us to add some benchmarks to the client.

**Comment by ayomessenger** [comment]
Indeed these performance problems only seem to occue in Debug mode of the application. I guess as long as the release versions are fluid that's the most important.

We have tried updating Flutter and Dart to versions **3.4.3** and **2.18.2** but is still slow in Debug mode.
Thanks for your responses everyone.

**Comment by dshukertjr** [comment]
@ayomessenger Thanks for the confirmation! We are working on making it fast for the debug mode as well, but this one might take a while. Glad to know that you are happy as long as it's working fast in release mode!

**Comment by ayomessenger** [comment]
Sounds good! Please let us know when you have managed to improve the performances on debug mode :)
