### ISSUE TITLE
Multiple streams per table

### ISSUE THREAD

**Issue by Vinzent03** [supabase/supabase-flutter#231]
**Is your feature request related to a problem? Please describe.**
It's currently not possible to stream the same table multiple times, because the topic is the same.

**Describe the solution you'd like**
We can either centralize the stream and return the existing stream on a new method call. Or (much simpler) use a more random topic, because the topic can be anything, right? So instead of using`<schema>:<table>` use `<schema>:<table>:<incrementing_id>`.

What do you think?

**Comment by dshukertjr** [comment]
Yup, love the idea of taking care of this on the client side. It seems to be where people get stuck on.

I'd like to properly return the in memory cache when the user subscribers to the same table at some point. Should we implement the one where we randomly chance the topic for every stream for now for a quick fix, and revisit this issue later on?

Related https://github.com/supabase-community/supabase-flutter/issues/94

**Comment by Vinzent03** [comment]
Depends on the complexity of the implementation. Do we want to reuse channels in realtime-dart or reuse streams in supabase-dart or both?

**Comment by dshukertjr** [comment]
In my opinion, I think it's better to not mess with the realtime channels for now to leave the low level control up to the user. Let's try to take care of this in the stream class of supabase-dart!

**Comment by Vinzent03** [comment]
Makes sense. May we continue here https://github.com/supabase-community/supabase-dart/pull/142 before that. Makes merging later easier.

**Comment by dshukertjr** [comment]
Although I said the following [here](https://github.com/supabase/supabase-flutter/issues/231#issuecomment-1273139637)
>In my opinion, I think it's better to not mess with the realtime channels for now to leave the low level control up to the user. Let's try to take care of this in the stream class of supabase-dart!

Implementing it would require quite a bit of rework, wouldn't it? 

```dart
supabase.from('table').stream(['id']);
supabase.from('table').stream(['id']).eq('column': 'something');
```

We could update the code to include the filters in the topic [here](https://github.com/supabase/supabase-dart/blob/main/lib/src/supabase_stream_builder.dart#L268), but it feels like if we are doing that, why not just implement the idea proposed [here](https://github.com/supabase/supabase-flutter/issues/231#issue-1402264808) by @Vinzent03 to add a increment id in the topoic. This would solve the above issue as well as allow users to listen to the same stream multiple times. Sorry for changing my opinion, but let's implement this for now for a quick fix!

schema:table:incrementing_id

**Comment by sunilguptasg** [comment]
supabase_flutter 1.2.2

Stream<List<UserActions>> _messagesStream = client
  .from(Constants.userActionsDbName)
  .stream(primaryKey: ['id'])
  .order('id', ascending: false)
  .eq('sent_to_uid', CurrentUser().uid)
  .map((maps) => maps.map((map) {
        return UserActions.fromMap(map: map);
      }).toList());

Stream<List<UserActions>> _messagesStream2 = client
  .from(Constants.userActionsDbName)
  .stream(primaryKey: ['id'])
  .order('id', ascending: false)
  .eq('sent_from_uid', CurrentUser().uid)
  .map((maps) => maps.map((map) {
        return UserActions.fromMap(map: map);
      }).toList());


the (eq) is different. 

With two streams on the same table - real time changes stop. What am I doing wrong?

**Comment by dshukertjr** [comment]
@sunilguptasg 
Your code looks fine, and I cannot seem to be able to reproduce your issue. 

Could you double check that realtime updates are coming through when listening to only one stream?

**Comment by sunilguptasg** [comment]
Yes, one stream works. 

I have created a duplicate table and listen that that for the second stream, for now, I know this is not the best way...
