### ISSUE TITLE
Could not find the updated record using Stream

### ISSUE THREAD

**Issue by rejesthm** [supabase/supabase-flutter#234]
Hello. Trying to debug it for a week. But I can't find a solution to fix it. 

Do you have any idea why it always says "Could not find the updated record" every time there are changes in supabase backend? It doesn't update the record in frontend and need to refresh and call stream() again to update it.

I'm using **supabase: ^0.3.6**. 
<img width="1044" alt="Screenshot 2022-10-12 at 8 29 51 PM" src="https://user-images.githubusercontent.com/61548260/195342898-e41c23f9-3ec1-4b78-ba66-2a5b5ad5a0c9.png">

**Comment by Vinzent03** [comment]
Do you pass the list of primary keys to `.stream`? Please share your code.

**Comment by rejesthm** [comment]
<img width="455" alt="Screenshot 2022-10-12 at 9 27 34 PM" src="https://user-images.githubusercontent.com/61548260/195355245-5fd54c24-2e47-4eeb-9238-2600f841b281.png">
This is how it looks like @Vinzent03

**Comment by Ruud14** [comment]
Am having the same issue here.

Table: 
![image](https://user-images.githubusercontent.com/40769366/200380055-3792c770-7378-4c31-848a-5b7f3d6881bd.png)

Code:
```Dart
joinedTable = _database.from('joined');
return joinedTable.stream(primaryKey: ['user', 'session']).eq("session", session.id);
```

I am using Supabase 1.1.0

**Comment by dshukertjr** [comment]
I think this issue was solved with https://github.com/supabase/supabase-dart/pull/167. Please upgrade your package version, make sure that you pass only the primary key columns to `primaryKey` parameter, and retry it again. 

I'm going to close this issue for now, but feel free to reopen it if the issue persists.
