### ISSUE TITLE
Add MFA support

### ISSUE THREAD

**Issue by dshukertjr** [supabase/supabase-flutter#238]
**Is your feature request related to a problem? Please describe.**
Multi Factor Authentication is coming to Supabase, and the basic implementation is there for JS SDK [here](https://github.com/supabase/gotrue-js/tree/mfa). We can implement it on gotrue-dart as well! 

**Describe the solution you'd like**
Add MFA support similar to js sdk.

**Describe alternatives you've considered**
N/A

**Comment by dshukertjr** [comment]
Actually, we will hold off on this one. MFA will be released as an experimental feature on js SDK first, and once it's stable we will add it to Flutter SDK as well.

**Comment by dshukertjr** [comment]
Okay, we are good to add this to Flutter SDK as well at this point!

**Comment by Vinzent03** [comment]
@dshukertjr so you gonna add the pr or what's the plan?

**Comment by dshukertjr** [comment]
@Vinzent03 Anyone can work on it. Feel free to assign yourself and start working on it if you would like!

**Comment by dshukertjr** [comment]
No pressure at all though! Just wanted to be respectful if you were eager to work on it and have the bandwidth to do it, but please don't feel like you need to!

**Comment by Vinzent03** [comment]
@dshukertjr Yeah sure I know! I started now, so we can work on the same base.
