### ISSUE TITLE
Unexpected behavior with SupabaseAuth.instance.initialSession and signOut method

### ISSUE THREAD

**Issue by devon2018** [supabase/supabase-flutter#245]
**Describe the bug**
The signOut method does not seem to be working after updating to v1.0.0, not sure exactly what is going on here but when triggering the signout method with debug mode enabled i get the following message:

```**** onAuthStateChange: AuthChangeEvent.signedOut ``` 
But if i reload my app when calling `final initialSession = await SupabaseAuth.instance.initialSession` there still seems to be an active session, this could just be a documentation issue, as the docs still seem to be pointing to the pre v1 release. 

**To Reproduce**
1. Authenticate a user
2. use the `supabase.auth.signOut()` method
3. reload the app with a `final initialSession = await SupabaseAuth.instance.initialSession` in one of your initial methods

**Expected behavior**

**Screenshots**
<img width="517" alt="Screenshot 2022-10-20 at 12 07 32" src="https://user-images.githubusercontent.com/46196252/196932814-2d7b1715-7298-481c-ae41-2c745ad15844.png">
<img width="443" alt="Screenshot 2022-10-20 at 12 07 54" src="https://user-images.githubusercontent.com/46196252/196932897-f43ab23d-6396-4563-9bb2-d17953541ebe.png">

**Smartphone (please complete the following information):**
 - Version iphone 14 pro max sim, ios 16

**Additional context**

**Comment by Vinzent03** [comment]
Did you hot reload, hot restart or full restart? (https://docs.flutter.dev/development/tools/hot-reload#how-to-perform-a-hot-reload)

**Comment by devon2018** [comment]
@Vinzent03 tried both and tried closing the app completely and reopening, all have the same issue.

**Comment by Vinzent03** [comment]
Hmm I can't reproduce currently. May you verify this line is executed on sign out with `data.event == AuthChangeEvent.signedOut`? https://github.com/supabase-community/supabase-flutter/blob/5b242ed0e5f92ae33be328f90b9bf3b8810c509a/lib/src/supabase_auth.dart#L77
In addition, are you using a custom local storage implementation?

**Comment by devon2018** [comment]
@Vinzent03 nope not using anything custom.

**Comment by devon2018** [comment]
Not sure if this will help at all but this is my console logs

```
flutter: **** onAuthStateChange: AuthChangeEvent.signedOut
flutter: onAuthStateChanged
flutter: null

Performing hot restart...                                               
Restarted application in 363ms.
flutter: ***** Supabase init completed Instance of 'Supabase'
flutter: ***** SupabaseDeepLinkingMixin startAuthObserver
flutter: ***** SupabaseAuthState handleDeeplink myapplink://app/login#access_token=wsRzN01gP26gNWGjsvwpcDwwvko&expires_in=3600&refresh_token=vOWLgjH59g4amGSQ3A2p5g&token_type=bearer&type=magiclink
flutter: onReceivedAuthDeeplink uri: myapplink://app/login#access_token=eyJ...&token_type=bearer&type=magiclink
flutter: null
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
flutter: {"currentSession":{"access_token":"eyJhbGcisRzN01gP26gNWGjsvwpcDwwvko","expires_in":3600,"refresh_token":"vOWLgjH59g4amGSQ3A2p5g","token_type":"bearer","provider_token":null,"user":{"id":"6ee6b249-3470-4dee-bc33-25fdf736b622","app_metadata":{"provider":"email","provide<…>
flutter: onAuthStateChanged
flutter: {access_token: eyJ...GVkI
```

I've implemented an onAuthStateChange listener and printed out the session value as follows: 

<img width="476" alt="Screenshot 2022-10-20 at 17 21 37" src="https://user-images.githubusercontent.com/46196252/197004291-f9b01b82-c693-4a4b-a64f-8f6e9c38a861.png">

As you can see from the logs, the listener is triggered on signOut and outputs null, but after a hot restart of the app it seems there is still a valid session.

Not I edited the tokens above to keep the word count down, the actual ones that i'm getting are valid.

**Comment by Vinzent03** [comment]
I think the session is coming from the deep link. Seems like you open a link with an access token. Or am I missing something?

**Comment by cgestes** [comment]
had this issue also with hot reload. The deeplink re-sign-in the user.

Restarting the app does not exhibit the behavior.

**Comment by Vinzent03** [comment]
So you used deep link to sign in and every hot restart/reload reused that link to sign in?

**Comment by devon2018** [comment]
So the deep link was used to sign in but I did not use it after I restarted the app, so it must be caching somehow. 

It does seem similar to @cgestes issue how ever this is definitely happening on restart for me as well.

__Side_ note, should the tokens from emails not invalidated after use, seems like a security issue that they can be used more then once?_

**Comment by dshukertjr** [comment]
>Side note, should the tokens from emails not invalidated after use, seems like a security issue that they can be used more then once?

Hmm tokens are invalidated after a single use. Let me try to reproduce this and see if we can fix it over the weekend.

**Comment by devon2018** [comment]
@dshukertjr have you had any luck reproducing?

Not sure if it would help or not but i'm happy to hop on a call or whatever else might help.

**Comment by dshukertjr** [comment]
@devon2018 
I was able to reproduce it and I think this is the expected behavior. 

1. You open the link, which redirects you to a deeplink that is something like this
    ```
    io.supabase.new://login-callback/#access_token=mytokenJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhlfjdsaoFDSAWFEASdffsdaSFAhdGVkIiwiZXhwIjoxNjY2NDQ3NTE3LCJzdWIiOiI4ZjM1YzQzOS03OTRlLTQxYTItYjhjZC0mI2NTY1YWEiLCJlbWFpbCI6ImRzaHVrZXJ0anJAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6Wy
    ```
2. When you restart the app that you opened via deeplink, the deeplink remains there, and app parses the above deeplink again. Since the link contains access_token, the user is signed in again, and therefore the previous signout does not matter. 

I think this is just how deeplinks work, and it is not something an actual user of the app will ever face. You should be able to close the app and open the app again to reset the deeplink state.

**Comment by cgestes** [comment]
just stop the app and restart it. 

I have the same understanding than Tyler. Normal and only happening during dev. Just stop & restart the app when testing this.

**Comment by devalensio** [comment]
hi @dshukertjr, i also face the same issue when signing out user. is this a bug or expected behaviour?


![3](https://user-images.githubusercontent.com/33699574/216756811-8d977e9b-ac0e-4a1d-afca-939d031e62fb.png)


![4](https://user-images.githubusercontent.com/33699574/216756815-5a3a82be-f633-4877-9a01-4409eadbb46e.png)


![1](https://user-images.githubusercontent.com/33699574/216756820-4ff49765-7521-47a4-b179-c1c210a9ae00.png)


![2](https://user-images.githubusercontent.com/33699574/216756824-f7f855d2-7a67-4972-8703-ea207a32cbff.png)


before migrating to version 1, it never caches the session after signed out

**Comment by Vinzent03** [comment]
@devalensio Did you use a deep link to login?

**Comment by devalensio** [comment]
@Vinzent03 yes i use getOAuthSignInUrl to log in.

**Comment by Vinzent03** [comment]
@devalensio Then I think this is the expected behavior. You shouldn't see the issue in production, because the deep link is only handled multiple times on hot restart. More is described in the [comment above](https://github.com/supabase/supabase-flutter/issues/245#issuecomment-1287797807).

**Comment by dshukertjr** [comment]
Closing this issue. If you are experiencing this issue, please read the [comment above](https://github.com/supabase/supabase-flutter/issues/245#issuecomment-1287797807).

**Comment by nexbotai** [comment]
> @devon2018 I was able to reproduce it and I think this is the expected behavior.
> 
> 1. You open the link, which redirects you to a deeplink that is something like this
>    ```
>    io.supabase.new://login-callback/#access_token=mytokenJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhlfjdsaoFDSAWFEASdffsdaSFAhdGVkIiwiZXhwIjoxNjY2NDQ3NTE3LCJzdWIiOiI4ZjM1YzQzOS03OTRlLTQxYTItYjhjZC0mI2NTY1YWEiLCJlbWFpbCI6ImRzaHVrZXJ0anJAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6Wy
>    ```
> 2. When you restart the app that you opened via deeplink, the deeplink remains there, and app parses the above deeplink again. Since the link contains access_token, the user is signed in again, and therefore the previous signout does not matter.
> 
> I think this is just how deeplinks work, and it is not something an actual user of the app will ever face. You should be able to close the app and open the app again to reset the deeplink state.

Is there any known way to remove the deep link state though? it would be convenient if the deep link state is removed after Hot Restart
