### ISSUE TITLE
Create missing admin auth functions.

### ISSUE THREAD

**Issue by dshukertjr** [supabase/supabase-flutter#254]
**Is your feature request related to a problem? Please describe.**
supabase-js has several admin auth methods that can be called on the server side using service role key. 
https://supabase.com/docs/reference/javascript/auth-admin-createuser

It would be great to have them on the Dart library as well.

**Describe the solution you'd like**
Add server side methods to the library

**Comment by Vinzent03** [comment]
Delete user already exists as pr on the go-true repo.

**Comment by Vinzent03** [comment]
@avalanche-tm I don't think the storage api supports that. I suggest you to use different `SupabaseClient` instances with different users logged in.

Closing this as already implemented https://github.com/supabase/gotrue-dart/pull/106

**Comment by avalanche-tm** [comment]
@Vinzent03 I'm still unable to create users using auth.admin.createUser function https://github.com/supabase/supabase-flutter/issues/356
