### ISSUE TITLE
Inserting items into table returns null on success in v1.0.1

### ISSUE THREAD

**Issue by avalanche-tm** [supabase/supabase-flutter#257]
Let's take this simple table for example:

```sql
  create table if not exists public.article (
    id uuid not null primary key default uuid_generate_v4(),
    value text not null
  );
```

And try to insert a record using this code:

```dart
  await Supabase.instance.client.from('article').insert({
    'value': 'test',
  }).then((value) {
    debugPrint(value);  // value is null!
  }).catchError((error) {
    debugPrint(error);
  });

```

Even though insert finishes successfully, returned data is null instead of dynamic 'article' as it used to be in v0.3.3. This is very handy feature as I can get auto generated id from the value instead of making another request.

Also, if .then() block is omitted and only .catchError() is present I get this:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/97057865/197494378-756b6d6d-2bf9-45ea-b057-f7a211a21808.png">

**Comment by Vinzent03** [comment]
You need to append a `select()`. See the [migration doc](https://supabase.com/docs/reference/dart/upgrade-guide#insert-without-returning-inserted-data)

**Comment by avalanche-tm** [comment]
> 
@dshukertjr 
This code was taken from larger codebase where I actually transform data with .then and .catch and await it later in different part of app. I think there are some people (like myself) who prefer to build requests with .then and .catch as it offers more functional approach to the problem. Try/catch blocks are mostly not aesthetically pleasing, cause indentation and force developer to declare nullable variables outside block when return value is needed outside the block. Just wanted to share this in case you are (hopefully not) thinking about deprecating this feature.

**Comment by dshukertjr** [comment]
@avalanche-tm Using `then` is fine, and it is not going anywhere so no worries there. My point was that you were using both `await` and `then` In your code, which could cause unnecessary confusion. You can omit the `await` and write it like this if you prefer using `then/ catch`:

```dart
Future<void> myfunction() {
  return Supabase.instance.client.from('article').insert({
      'value': 'test',
    }).then((value) {
      debugPrint(value);
    }).catchError((error) {
      debugPrint(error);
    });
}
```

>force developer to declare nullable variables outside block when return value is needed outside the block

I am curious to hear how using `then/catch` solves this problem. 

Closing this issue as I have opened another one to take care of the catchError unimplemented bug. 
https://github.com/supabase-community/supabase-flutter/issues/259

**Comment by avalanche-tm** [comment]
@dshukertjr 
I do understand what you are saying and I am not awaiting futures like in the code snippet I posted. That was because I pasted code into main function to make sure it runs in isolation and nothing else is influencing it. I had to await that one otherwise program would terminate.

Try/catch comes handy when you try to write code in a functional way. Something similar like this library promotes https://pub.dev/packages/fpdart. The idea is your functions should return abstract Result structure that can either be Success or Failure where S and E is type of your data and error. Then you can do something like this:

```dart
abstract class Result<S, E> {}

class Success<S, E> implements Result<S, E> {
  S data;
  Success(this.data);
}

class Failure<S, E> implements Result<S, E> {
  E error;
  Failure(this.error);
}

// ...
```


```dart
typedef CreateConvResult = Result<FullConversation, AppError>;
typedef CreateConvSuccess = Success<FullConversation, AppError>;
typedef CreateConvFailure = Failure<FullConversation, AppError>;
// ...

abstract class IMessagingRepository {
  Future<CreateConvResult> createConversation(NewConversation newConversation);
  // ...
}

```

```dart
class MessagingRepository implements IMessagingRepository {
  late final SupabaseClient _client;

  MessagingRepository({SupabaseClient? client})
      : _client = client ?? Supabase.instance.client;

  final _conversationTable = 'conversation';
  
  @override
  Future<CreateConvResult> createConversation(NewConversation newConversation) {
    return _client
        .from(_conversationTable)
        .insert(NewConversationDTO.from(newConversation))
        .select()
        .then((data) => _handleCreateConvSuccess(data))
        .catchError(_handleCreateConvFailure);
  }

  CreateConvResult _handleCreateConvFailure(dynamic error) {
    return CreateConvFailure(
      // error handling logic
    );
  }

  CreateConvResult _handleCreateConvSuccess(List data) {
    return CreateConvSuccess(
      // data handling logic
    );
  }

  // ...
}
```

And later when you want to call the function:
```dart
// ...
final res = await _messagingRepository.createConversation(newConversation)
// res is Result type which can be either Success or Failure, so you are forced to deal
// with both possibilities. 
res.match(
   data: (data) => // ...
   error: (error) => // ...
);
// ...
```
Having try/catch blocks would defeat the purpose of this functional approach as the idea is to get rid of try/catch block in favour of more declarative code that can be easier to reason about and can be cut down into simple functions which are easier to test and reuse. This is of course just tip of the iceberg of all the advantages this approach offers.

**Comment by dshukertjr** [comment]
I'd like to close this issue as the original issue seems to be solved!
