### ISSUE TITLE
Creating stream throws 'Bad state: Stream has already been listened to.' in v1.0.1

### ISSUE THREAD

**Issue by avalanche-tm** [supabase/supabase-flutter#258]
I have this simple stream code which worked without problem in v0.3.3, but in v1.0.1 throws 'Bad state: Stream has already been listened to.' on the first call. I have set breakpoint on 'return res' to make sure that was indeed first call to this function.

```dart
    final res = Supabase.instance.client
        .from('conversation')
        .stream(primaryKey: ['id']) 
    return res;
```

**Comment by dshukertjr** [comment]
@avalanche-tm 

Thanks for opening this issue. Could you share the part of the code where you actually listen to the stream or use it in a StreamBuilder?

**Comment by avalanche-tm** [comment]
@dshukertjr I'm using hooks_riverpod: ^1.0.4 so the code looks something like this:

```dart
final conversationStreamProvider =
    StreamProvider<List<FullConversation>>((ref) async* {

  final conversationStream = Supabase.instance.client
        .from('conversation')
        .stream(primaryKey: ['id']) 

  await for (final conversation in conversationStream) {
    yield conversation;
  }
});
```

And something like this in the widget:
```dart
class Messaging extends HookConsumerWidget {
  const Messaging({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final conversationStream = ref.watch(conversationStreamProvider);

    return Column(
      children: [
        Expanded(
          child: conversationStream.when(
            loading: () => const Center(
              child: CircularProgressIndicator(),
            ),
            error: (error, stack) => Center(
              child: Text(error.toString()),
            ),
            data: (conversations) => conversations.isEmpty
                ? const Center(child: Text('No messages'))
                : ListView.builder(
                    itemCount: conversations.length,
                    itemBuilder: (context, index) {
                      return ConversationView(
                        conversation: conversations[index],
                      );
                    },
                  ),
          ),
        )
      ],
    );
  }
}
```
Error gets thrown immediately, the same moment .stream() function is called

**Comment by thecavus** [comment]
Hello, I am also having this problem. As soon as I start the project, I get a"Error: Bad state: No element " error, I couldn't find the reason. 

```dart
startListen() async {


 final  genelDinleyiciSubscription= client
        .channel("*")
        .on(RealtimeListenTypes.postgresChanges ,
ChannelFilter(event: 'UPDATE' ,
 filter: 'uid=eq.1'}'  ,
 schema: 'public' ,
 table: 'kayitlar' ),  (payload , [ref]) async {
      print("dinleyici genel TETİKLENDİ");

    
    }); genelDinleyiciSubscription.subscribe();
        genelDinleyiciSubscription.onError((p0) {print(p0);});
  }  
  }
```

**Comment by Vinzent03** [comment]
@thecavus Your error message is different from this issue, so I don't think they are directly related.

**Comment by avalanche-tm** [comment]
@Vinzent03 I also get the same error as @thecavus with the simple stream subscription code I posted originally.

**Comment by Vinzent03** [comment]
@avalanche-tm So you get two exceptions? Did you try supabase-flutter `v1.1.0`? I can't reproduce currently.

**Comment by avalanche-tm** [comment]
Hey, @Vinzent03 

Sorry for the late response. I have updated supabase_flutter to v1.1.0 and here are the errors that I get with this code:

```dart
// THIS THROWS 'Bad state: Stream has already been listened to' ERROR
  final res1 = Supabase.instance.client
      .from('conversation')
      .stream(primaryKey: ['id']) 
      .asyncMap((event) => event.map((e) => e).toList());
      
// THIS WORKS OK
  final res2 = Supabase.instance.client
      .from('conversation')
      .stream(primaryKey: ['id']);
```
So the difference is .asyncMap() function. I'm not sure if I'm using this function wrong, but this worked as expected in v0.3.3

If I ignore that and let debugger go on, I get another error which is (maybe) consequence of the previous one:

 <img width="1053" alt="image" src="https://user-images.githubusercontent.com/97057865/201045674-f2b158d9-8a68-460d-b4f9-5c308950f368.png"> 
  
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/97057865/201045593-34452a61-d430-4985-829a-f5c43d57bd8a.png">
