### ISSUE TITLE
Clarify documentation for returning data on inserts/updates

### ISSUE THREAD

**Issue by d-e-h-i-o** [supabase/supabase-flutter#265]
**Describe the improvement**
The update/insert part of the docs are confusing: The [docs](https://supabase.com/docs/reference/dart/update) suggest that an update (or insert) without `.select()` returns data:

`final data = await supabase
  .from('cities')
  .update({ 'name': 'Middle Earth' })
  .match({ 'name': 'Auckland' });`
(from the docs)

The variable name `data` suggests the data is returned, however, it will always be `null` without `.select()`, which can lead to confusion when following the example. 

**Suggested solution**
The [migration guide for v1](https://supabase.com/docs/reference/dart/upgrade-guide#insert-without-returning-inserted-data) has a clearer description of the behavior, maybe you coud add that to the 'Database' documentation too?

**Comment by dshukertjr** [comment]
Closing this issue as there has been an additional clarification added to the docs! Feel free to reopen it if it's not sufficient!
