### ISSUE TITLE
Inner Join produces nested fields

### ISSUE THREAD

**Issue by muezz** [supabase/supabase-flutter#267]
**Describe the bug**
When trying to fetch data from a table that has foreign keys, the inner join keywords do not produce the results as expected.

**To Reproduce**
1. Create table `guests` with `guestId`
2. Create table `events` with `eventId`
3. Create table `signups` with `eventId` and `guestId` (both are foreign keys)
4. Run the following query in the SQL editor:
```sql
SELECT * FROM signups
INNER JOIN guests ON signups."guestId" = guests."guestId"
INNER JOIN events ON signups."eventId" = events."eventId";
```
5. Then, from a Flutter app, run the following query:
`await supabase.from('signups').select('*, guests!inner(*), events!inner(*)');`

**Expected behavior**
The query that was run in the SQL editor in step 4 produces a single row with all of the columns from both `guests` and `events` table. However, the query in step 5 produces a result that looks like this:
```
[
  {
    signupId: 8653e1d0-57a8-4138-b2bf-7ae078570c5c, 
    eventId: da7fe194-78a3-47e8-b9ce-0ee57cdfc247, // This is a foreign key from table events 
    guestId: e9482062-9c0e-4025-a1b1-d03e9d8c7910, // This is a foreign key from table guests
    // other field/column values from signups table
    guests: {
      guestId: e9482062-9c0e-4025-a1b1-d03e9d8c7910, 
      guestName: James, 
      guestPhoneNumber: +1-3091234567
    }, 
    events: {
      eventId: da7fe194-78a3-47e8-b9ce-0ee57cdfc247, 
      eventName: Annual Company Meeting, 
      eventVenue: The Continental, 
      eventDateTime: 1667300987442
    }
  }
]
```
I would like to get the result in a linear format like the one produced by the raw query. This seems like an unexpected behavior because the equivalent query written in SQL produces result in a different format.

**Comment by Vinzent03** [comment]
Supabase uses PostgREST for queries, which I don't think supports your use case: https://postgrest.org/en/stable/api.html#resource-embedding

**Comment by muezz** [comment]
@Vinzent03 I was hoping there was a way to get the data in a linear or table-like format. At the moment, I am just trying to make do with what I am allowed to do. It is just a hassle to maintain and use two different data models (within my flutter app) where one serializes `Map`/`json` from  supabase and the other serializes data to supabase as the format of the data going and coming from it are completely different.
