### ISSUE TITLE
Float column with whole number return int type instead of double type

### ISSUE THREAD

**Issue by robpot95** [supabase/supabase-flutter#269]
**Describe the bug**
Having float column and value with e.g 2. Will return a int when you select the column

**To Reproduce**
```
final result = await supabase.from('product').select('price');
print(result[0]["price"].runtimeType);
```

**Expected behavior**
Should return a double not a int

**Comment by Vinzent03** [comment]
I don't think we have control over that, because I guess postgREST sends values like `4` in float type as `4` and not `4.0` so Dart can't determine the correct type from the JSON.

**Comment by TommyLCox** [comment]
@robpot95  - In dart/flutter, does this cause any specific error in your application such as when you convert from Json?

**Comment by Vinzent03** [comment]
Closing as there's nothing to do on our side. You have to cast each column to your actual application's type.
