### ISSUE TITLE
http send error : Connection failed #0      IOClient.send (package:http/src/io_client.dart:88:7)

### ISSUE THREAD

**Issue by Reinoal** [supabase/supabase-flutter#276]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Connection failed
#0      IOClient.send (package:http/src/io_client.dart:88:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#2      _withClient (package:http/http.dart:164:12)
<asynchronous suspension>
#3      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:164:20)
<asynchronous suspension>

With supabase deployed on PCS on the local LAN, mobile phone requests can normally return data, and macOS requests will report HTTP errors. url like this: 'http://192.168.8.182:8000',

**Comment by dshukertjr** [comment]
Hi @Reinoal 
If you could reopen an issue following the format of the issue template, we will be happy to take a look at the issue!
