### ISSUE TITLE
http request error on macOS

### ISSUE THREAD

**Issue by Reinoal** [supabase/supabase-flutter#277]
**Describe the bug**
 Supabase deployed on Linux on the local LAN, real mobile phone requests can normally return data, and macOS requests will report HTTP errors. url like this: 'http://192.168.8.182:8000/'

**To Reproduce**
this error appears in all http requests

**Additional context**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.71.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by Vinzent03** [comment]
Hey, now your error message is missing in the issue. May you try normal https requests without the supabase package to your server?

**Comment by Reinoal** [comment]
Error messages:
http version: 0.13.5 
postgrest 1.1.1
Connection failed, StackTrace: #0      IOClient.send (package:http/src/io_client.dart:88:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#2      _withClient (package:http/http.dart:164:12)
<asynchronous suspension>
#3      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:164:20)
<asynchronous suspension>
#4      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:397:24)
<asynchronous suspension>

**Comment by Vinzent03** [comment]
Can you access your server in your mac app with any other http request via Dart http package?

**Comment by Reinoal** [comment]
macOS needs you to request a specific entitlement in order to access the network. To do that open macos/Runner/DebugProfile.entitlements and add the following key-value pair.
<key>com.apple.security.network.client</key>
<true/>
thanks for https://stackoverflow.com/questions/65458903/socketexception-connection-failed-os-error-operation-not-permitted-errno-1

**Comment by Reinoal** [comment]
set config macos/Runner/DebugProfile.entitlements
add key-value:  key: com.apple.security.network.client, value: true
