### ISSUE TITLE
getPublicUrl does not check if file exists

### ISSUE THREAD

**Issue by jstdk** [supabase/supabase-flutter#279]
**Describe the bug**
Not sure this is a bug or a feature, but the Storage function getPublicUrl always returns a public url, even is the file does not exist. Firebase Storage provides a null in that scenario, which can then be used in the application to show an upload form. With the current Supabase flow, I need to test myself if the file exists (not sure how to be honest) and then show a form. 

**To Reproduce**
Create a bucket, make it public, leave it empty. Create  a function to query a specific file
![image](https://user-images.githubusercontent.com/115603308/202650900-0f4ba683-106e-403b-8c70-d8b7e653954c.png)
![image](https://user-images.githubusercontent.com/115603308/202650706-4d5fcc46-d6f2-4ef1-9f24-1de4fffbf164.png)

**Expected behavior**
A response that either errors or nulls

**Screenshots**
![image](https://user-images.githubusercontent.com/115603308/202651091-5f9d284e-dff6-42e0-90e0-19bd4b049088.png)

**Smartphone (please complete the following information):**
 - Version 1.1.0, Flutter 3.3.8

**Additional context**
Repo: https://github.com/jstdk/starter

**Comment by dshukertjr** [comment]
@jstdk 
`getPublicUrl` is just a method that constructs a url from given parameters such as supabase url, bucket name, and path, so no it does not check if a file exists or not.

You can use the `createSignedUrl` method to get a URL if a file exists, or throw an error if it does not exist.

**Comment by Vinzent03** [comment]
@dshukertjr But isn't `createSignedUrl` only for private buckets useful? Isn't creating your own `exists` function more suited? See #176

**Comment by dshukertjr** [comment]
@Vinzent03 @jstdk You can still use `createSignedUrl` on public buckets. Also, in the original issue, it brings up how Firebase storage is able to detect whether a file exists or not. In Firebase storage, every URL it returned in a signed URL, the use case is exactly the same as calling `createSignedUrl` on Supabase. 

If you don't want to use `createSignedUrl`, nothing is stopping you from making a HTTP request to the URL to see if it returns 404 or not. You could make a [HTTP HEAD request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) to efficiently see if a file exists or not.
