### ISSUE TITLE
Initialize Bug

### ISSUE THREAD

**Issue by mreky** [supabase/supabase-flutter#283]
I am initiliazing Supabase in the main function as I'm supposed to like:
![main dart - firstapp - Visual Studio Code 11_21_2022 10_00_23 PM (2)](https://user-images.githubusercontent.com/118037596/203210849-bf55cbf4-d548-44cc-9df3-6e91e470ece9.png)

Then I use Supabase.instance in my headless task as so:
![errors_patch dart - firstapp - Visual Studio Code 11_21_2022 10_05_34 PM (2)](https://user-images.githubusercontent.com/118037596/203211414-7eba90a8-2e24-4238-ade3-3ded5b91ae86.png)

Which whenever I run gives me the error:
![errors_patch dart - firstapp - Visual Studio Code 11_21_2022 10_04_05 PM (2)](https://user-images.githubusercontent.com/118037596/203211434-bf535ac5-a860-4a7c-b0f1-ed43158a04e6.png)

So then I reinitialize inside the headless task by doing:
![errors_patch dart - firstapp - Visual Studio Code 11_21_2022 10_11_05 PM (2)](https://user-images.githubusercontent.com/118037596/203212107-1aa14646-b80f-496f-9c39-64a5e27ce616.png)

But then this gives me the error:
![errors_patch dart - firstapp - Visual Studio Code 11_21_2022 10_09_18 PM (2)](https://user-images.githubusercontent.com/118037596/203212124-20abd4cc-def6-4157-90eb-867323894e8f.png)

Which doesn't make any sense and makes me stuck in a loop. I can use SupabaseClient() inside the headless task without needing to reinitialize but then I can't get the user's id because that returns a null currentUser, which I have to get by using SupabaseAuth.instance.initialSession.user.id, but then I get an error. I tried initializing SupabaseAuth also but doesn't help.

**Comment by mreky** [comment]
> Oh, this seems like a very awesome use case of Supabase!
> 
> This is certainly not a proper fix, but one quick and dirty way to get it going would be to just catch the assertion error and just ignore it like this.
> 
> ```dart
> try {
>   await Supabase.initialize(
>     url: supabaseUrl,
>     anonKey: supabaseKey,
>   );
> } on AssertionError catch (e) {
>   // ignore the assertion error
> }
> ```

This works, thank you.

**Comment by khanakia** [comment]
Is there a way to check if supabase is already initialized i am getting the same error when used in Background functions.

I do not see supabase exposes any function to check the state

**Comment by dshukertjr** [comment]
@khanakia You can just wrap it in a try catch block like this and ignore the assertion error!

```dart
try {
  await Supabase.initialize(
    url: supabaseUrl,
    anonKey: supabaseKey,
  );
} on AssertionError catch (e) {
  // ignore the assertion error
}
```
