### ISSUE TITLE
supabase-flutter v2 feature tracker

### ISSUE THREAD

**Issue by dshukertjr** [supabase/supabase-flutter#287]
Let's keep all the features that we want to add/ remove/ modify in supabase-flutter v2.

**Comment by dshukertjr** [comment]
## Immutability

Instead of modifying the properties of Postgrest classes, create a copy every time calling filter/ modifier methods. 

For example, queries like the following should work. 
```dart
var fooQuery = myQuery.eq('some_col', 'foo');
var notFooQuery = myQuery.neq('some_col', 'foo');
```

https://github.com/supabase/supabase-flutter/issues/162#issuecomment-1324226510

**Comment by dshukertjr** [comment]
### Minimal Dart SDK Version

It depends on when exactly v2 is released, but  2.18.0 might be a good one maybe?

**Comment by dshukertjr** [comment]
Better type support on realtime. Currently, all properties of `ChannelFilter()` is string. Haven't put too much thoughts into it yet, but I feel like we can do better here.

**Comment by Vinzent03** [comment]
## New Hive box location for authentication

Currently, the box is stored in the default location of [hive_flutter](https://pub.dev/packages/hive_flutter), which is the Application Documents directory. This corresponds on Linux to `$HOME/documents`, which is very strange. The Application Support directory suits much better and is supported on all platforms as well. (They come from the [path_provider](https://pub.dev/packages/path_provider#supported-platforms-and-paths) package)

I've commented an example migration code in #294

**Comment by dshukertjr** [comment]
## Use `LaunchMode.inAppWebView` as the default value for doing OAuth sign-in.

Currently, it;s `LaunchMode.externalApplication`, but `LaunchMode.inAppWebView` should provide better user experience. 
Related https://github.com/supabase/supabase-flutter/pull/323

**Comment by dshukertjr** [comment]
## Remove deprecated `returning` option on `.delete()`

Related https://github.com/supabase/postgrest-dart/pull/105#discussion_r1082396094

**Comment by dshukertjr** [comment]
## Explorer using the Dart native isolate feature to replace yet another json isolate

We might be able to use the new isolate feature introduced in Dart 2.19.0 depending on which minimum SDK version that we decide on.
https://medium.com/dartlang/better-isolate-management-with-isolate-run-547ef3d6459b

**Comment by TC3000** [comment]
Allow realtime joins. Currently we can only listen to realtime events from a single table. It would be really nice to join data from multiple tables, i.e fetch `Post` and `Comments` as a stream.

**Comment by dshukertjr** [comment]
## Properly type `RealtimeClientOptions`

realtime-dart receives `params` of type `Map<String, dynamic>`, but on js SDK, this is properly typed like the following:

https://github.com/supabase/realtime-js/blob/master/src/RealtimeClient.ts#L16

**Comment by dshukertjr** [comment]
## Cleanup the `createClient` parameters

supabase-js has its parameters neatly separated for different sub-libraries. 

https://github.com/supabase/supabase-js/blob/master/src/lib/types.ts#L10

**Comment by DanMossa** [comment]
# Better support for native auth.

Either with instructions or helper methods.

**Comment by TC3000** [comment]
### Cascade Delete
____

Allow for a way to easily and cleanly delete associated records without resorting to SQL. Something very similar to this.. 

 ```dart
   Future<void> deleteUser(String id) async {
    await supabase
        .from('users')
        .delete(options: DeleteOptions(cascadeDelete: true))
        .eq('id', id);
    }

**Comment by Vinzent03** [comment]
@TC3000 From my understanding, there is nothing to do for cascade delete on the client. It as to be implemented in your table schema. Regarding your realtime join, there is nothing we can do on the client as well, as it's not supported by the realtime server currently.

We have locked this issue, so we only collect issues here that can be solved in the near future and don't depend on upstream issues.

**Comment by dshukertjr** [comment]
## Update `signInWithOAuth` launch mode to `inAppWebView`

related https://github.com/supabase/supabase-flutter/pull/355

**Comment by dshukertjr** [comment]
## Update `.stream()` so that multiple filters cannot be chained on each other.

Here is a PR that implements it https://github.com/supabase/supabase-dart/pull/179

**Comment by dshukertjr** [comment]
## Remove `SupabaseAuth.initialSession`

I personally regret introducing `SupabaseAuth.initialSession`, and I think all auth states should be listenable, including errors, using `auth.onAuthStateChanged`.

**Comment by dshukertjr** [comment]
## Remove `authCallbackUrlHostname ` from `Supabase.initialize`

Now that we are only parsing the URL when certain auth related parameters are present, we probably don't need it

**Comment by dshukertjr** [comment]
## Rename `Provider` in goture to something else 

The name `Provider` conflicts with the state management provider that is often used in Flutter. We can change our `Provider` to `OAuthProvider` or `SocialProvider` or something.

**Comment by dshukertjr** [comment]
## Rename `is_` and `in_` to `isFilter` and `inFilter`.

**Comment by dshukertjr** [comment]
## Rename `toJson()` to `toMap()`

I think the standard is, `toJson()` returns `String`, and is the stringified version of the map. If the return type is a Map, I think it should be called `toMap()`.

**Comment by Vinzent03** [comment]
I actually don't think so. See [flutter doc](https://docs.flutter.dev/data-and-backend/json) or the [json_serializable package](https://pub.dev/packages/json_serializable) or some `toJson` [method I found](https://api.flutter.dev/flutter/services/TextEditingValue/toJSON.html) in flutter via quick google search

**Comment by dshukertjr** [comment]
That is an interesting naming convention 😂 `toJson` sounds like you are converting something to json, but if you pass the output to `jsonEncode` to convert it to json?? 😂 I guess the definition of the word `JSON` has some wiggle room as to whether it means the object or the string representation of it. Alright, we can keep the `toJson` method.

**Comment by dshukertjr** [comment]
Use proper postgrest error codes for `PostgrestException`

`PostgrestException.code` currently contains the status codes, e.g. '406', etc., but postgrest provides proper error codes. Let's use these instead, and maybe we can add `status` field in `PostgrestException` to also keep the status codes. 

https://postgrest.org/en/stable/references/errors.html

**Comment by dshukertjr** [comment]
@bdlukaa @DanMossa
Just an FYI, but @Vinzent03 suggested that it might be about time we introduce these changes, and I checked with the team that they don't plan to release any major version upgrade to the JS client library in the next 6 months or so, so I think we can start bringing these breaking changes over. If you have anything that you would like to change that requires a breaking change, now is the time!

I think we can create a `next` branch and merge all the v2 changes there. That way, we can still update v1 if we need to until v2 comes out of developer preview. `next` will be merged to `main` when v2 comes out of developer preview for a stable release.

**Comment by dshukertjr** [comment]
## Set PKCE as the default authentication flow.

**Comment by dshukertjr** [comment]
v2 has been released 🎉
