### ISSUE TITLE
Flutter Realtime Stream .or

### ISSUE THREAD

**Issue by mreky** [supabase/supabase-flutter#289]
Is it possible to use .or() somehow in .stream() in Flutter? It seems like every filter is included in .stream() but .or(), is it possible to achieve the same result in stream by another way? Thank you.
`_stream = supabase.from('message_rooms').stream(primaryKey: ['id']).or('user1.eq.${user.id}, user2.eq.${user.id)}`);

**Comment by dshukertjr** [comment]
@mreky 
Thanks for the suggestion. At the moment, the realtime server does not accept `.or` filter at the moment. More on that [here](https://github.com/supabase/realtime/issues/222).

As a workaround, you can listen to the two streams individually, combine the emitted data and emit a emit the combined stream as a new stream.

**Comment by mreky** [comment]
> @mreky Thanks for the suggestion. At the moment, the realtime server does not accept `.or` filter at the moment. More on that [here](https://github.com/supabase/realtime/issues/222).
> 
> As a workaround, you can listen to the two streams individually, combine the emitted data and emit a emit the combined stream as a new stream.

Thank you, I will try to make it work using the workaround you provided.

**Comment by sunilguptasg** [comment]
@mreky were you able to accomplish this "As a workaround, you can listen to the two streams individually, combine the emitted data and emit a emit the combined stream as a new stream." - when I try two streams on the same table I do not get any real time updates anymore... is there a setting or different way to set up the stream in Flutter?

**Comment by mreky** [comment]
> @mreky were you able to accomplish this "As a workaround, you can listen to the two streams individually, combine the emitted data and emit a emit the combined stream as a new stream." - when I try two streams on the same table I do not get any real time updates anymore... is there a setting or different way to set up the stream in Flutter?

The only efficient way I solved it was sorting the ID I needed locally and then querying for it using .eq. But you should be able to listen to two different streams and sort the data locally however you need it.

**Comment by dshukertjr** [comment]
I will close this issue as there is a workaround for it.
