### ISSUE TITLE
Allow HiveLocalStorage to accept custom directory path

### ISSUE THREAD

**Issue by kaboc** [supabase/supabase-flutter#294]
**Is your feature request related to a problem? Please describe.**

`Hive.initFlutter()` is used in the default local storage in supabase_flutter. It uses the directory obtained with `getApplicationDocumentsDirectory()`, so the data is stored in the document folder on windows. I don't think it is a suitable place for app data. (I haven't checked on other platforms.)

Besides that, in desktop apps, I'd like to store the session data for debug build in another place and for release build in the same directory as the executable. It'll be great if it is possible to specify the directory.

**Describe the solution you'd like**

https://github.com/supabase/supabase-flutter/blob/ce2056f0804d152f65546ddcb843ae6f5c54b7a3/lib/src/local_storage.dart#L64-L71

```dart
class HiveLocalStorage extends LocalStorage {
  const HiveLocalStorage({this.directory})
      : super(
          initialize: _initialize,
          hasAccessToken: _hasAccessToken,
          accessToken: _accessToken,
          removePersistedSession: _removePersistedSession,
          persistSession: _persistSession,
        );

  final String? directory;
```

```dart
await Supabase.initialize(
  url: 'SUPABASE_URL',
  anonKey: 'SUPABASE_ANON_KEY',
  localStorage: const HiveLocalStorage(directory: 'path/to/dir'),
);
```

The property name may be other then `directory`, like `path` or `directoryPath`.

**Comment by Vinzent03** [comment]
@dshukertjr  I think we should generally switch to `Application Support`(https://pub.dev/packages/path_provider#supported-platforms-and-paths), because current `Application Documents` stores the auth hive box on linux in `$HOME/documents/auth/..`, which I think is VERY strange. 
I've already written a migration code in my own application, which I could reuse for this package.

**Comment by dshukertjr** [comment]
@Vinzent03 How would the migration script work? Maybe we can do it for v2.0
https://github.com/supabase/supabase-flutter/issues/287

**Comment by Vinzent03** [comment]
@dshukertjr 
```dart
import 'dart:io';

import 'package:hive/hive.dart';
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';

Future<void> migrateAndInitHive() async {
  if (!kIsWeb) {
    final supportDirPath = (await getApplicationSupportDirectory()).path;
    final documentsDir = await getApplicationDocumentsDirectory();

    if (!await Directory(supportDirPath).exists()) {
      await Directory(supportDirPath).create();
    }

    // If the old location exists, we start looking for old DB files to copy.
    if (await documentsDir.exists()) {
      final filesToCopy = <File>[];

      await documentsDir.list().forEach((event) {
        final extension = path.extension(event.path);

        // If the item is a file and has an extension of .hive, add it and the
        // matching .lock file to the copy array.
        if (event is File && extension == '.hive') {
          filesToCopy.add(File(event.path));

          filesToCopy.add(File('${path.withoutExtension(event.path)}.lock'));
        }
      });

      await Future.wait(filesToCopy.map(
        (e) => e
            .copy(path.join(supportDirPath, path.basename(e.path)))
            .then((_) => e.delete()),
      ));
    }
    Hive.init(supportDirPath);
  }
}
``

**Comment by Vinzent03** [comment]
@dshukertjr Do we want to provide the option to override the default hive box location? I mean, it's already possible by copying the `HiveLocalStorage` and just changing the path.

@kaboc Yeah that is correct. My script moves all hive files. We need to adapt it to only move files from this package.

**Comment by dshukertjr** [comment]
>Do we want to provide the option to override the default hive box location? I mean, it's already possible by copying the HiveLocalStorage and just changing the path.

Agree. I don't think we need to provide the option when the users can already achieve it themselves.

**Comment by kaboc** [comment]
My issue is that all the methods of `HiveLocalStorage` are private. It prevents me from overriding only the `_initialize()` method, so I have to copy the entire class to customise only a small portion of it to use a different path, which is why I filed this issue.

I'm fine even if the improvement is not considered worthwhile as I can still achieve what I want to do although it is a bit tedious. It may be better to change the title in that case.

**Comment by Vinzent03** [comment]
I just noticed the weird style. @dshukertjr Why are all these methods not actually methods, but properties from the abstract class and set via constructor?

@kaboc You would need to override the other methods as well, because the box is opened in every method.

Since we don't plan to make the box path configurable, I think we can close this issue. I'll add the application support directory to #287.

**Comment by dshukertjr** [comment]
> Why are all these methods not actually methods, but properties from the abstract class and set via constructor?

What is your alternative suggestion here?

**Comment by kaboc** [comment]
@Vinzent03 
> because the box is opened in every method.

I don't really get it. The box is opened in `_initialize()`. The method is assigned to the `initialize` property of the super class, and it appears that the property is called only from `Supabase.initialize()`. Why is the box opened "in every method"?

> It prevents me from overriding only the _initialize() method

I had a misunderstanding about it. `_initialize()` is a static method, so it's not possible to override it. How about changing `LocalStorage` to have public instance methods without body? @dshukertjr 

```dart
const hiveBoxName = 'supabase_authentication';

abstract class LocalStorage {
  Future<void> initialize();
  Future<bool> hasAccessToken();
  Future<String?> accessToken();
  Future<void> removePersistedSession();
  Future<void> persistSession(String persistSessionString);
}

class HiveLocalStorage implements LocalStorage {
  const HiveLocalStorage();

  static String? encryptionKey;

  @override
  Future<void> initialize() async { ... }

  @override
  Future<bool> hasAccessToken() { ... }

  ...
}
```

This way, the issue of the strange structure Vinzent mentioned is resolved, and it also becomes possible to configure the path.

<details>
<summary><b>CustomHiveLocalStorage</b> (Click to open)</summary>

```dart
class CustomHiveLocalStorage extends HiveLocalStorage {
  const CustomHiveLocalStorage({this.path});
  
  final String? path;
  
  @override
  Future<void> initialize() async {
    if (path == null) {
      super.initialize();
    } else {
      _initializeWithCustomPath();
    }
  }
  
  Future<void> _initializeWithCustomPath() async {
    HiveCipher? encryptionCipher;
    final encryptionKey = HiveLocalStorage.encryptionKey;
    if (encryptionKey != null) {
      encryptionCipher = HiveAesCipher(base64Url.decode(encryptionKey));
    }
    
    Hive.init(path!);
    await Hive.openBox(hiveBoxName, encryptionCipher: encryptionCipher);
  }
}
```
</details>

**Comment by Vinzent03** [comment]
Oh you are right. The box init with its path is in `initialize`. I just saw that the box is called in every method by its name, which is a private property, but you can keep that as it is of course.

Your code is exactly what I meant. The classic OOP abstract class overriding.

**Comment by dshukertjr** [comment]
Close this as we plan to introduce some fixes around Hive storage in the next major version.
