### ISSUE TITLE
Not able to import CountOptions enum

### ISSUE THREAD

**Issue by hareendranmg** [supabase/supabase-flutter#30]
# Bug report

## Describe the bug

Not able to import CountOptions enum.
When clicking the Quick Fix in VS Code, it only showing create class, local variable and mixin.
It is not showing the library to import.  

## To Reproduce

```
await supabase
          .from(tableName)
          .select()
          .eq(column, value)
          .execute(count: CountOptions.exact);
```

## Screenshots
![image](https://user-images.githubusercontent.com/19310197/135762457-a777ec1d-f33a-4b82-82a3-ba7fbb68572b.png)
![image](https://user-images.githubusercontent.com/19310197/135762462-77f6acf3-a62f-45a4-91d9-243492429080.png)

## System information

- OS: Ubuntu 20.04
- Version of supabase_flutter: 0.2.8
- Version of flutter: 2.5.1

**Comment by dshukertjr** [comment]
@hareendranmg This should now be fixed in the latest version of `supabase_flutter`!
