### ISSUE TITLE
Supabase error at initialize: Session is not cleared when debugging in 2 devices w/ same account.

### ISSUE THREAD

**Issue by anggoran** [supabase/supabase-flutter#305]
**Describe the bug**
Reporting this issue, in case it is a bug. So, few days ago, I tried to debug my code at Mac and Windows, to test platform-specific feature. I was using the same email to login, then I log out at my Mac. When I tried to debug at my Windows, it returns invalid refresh token: not found. Then I realized that the account session is still not cleared in Windows.

**To Reproduce**
1. Debug at two different devices.
2. Login with the same email on both devices.
3. Log out one of the devices.
4. Debug at both devices.
5. The device which still has the account logged in, receive an error at initialize like in the ss I provided on my Windows. While the device that has already logged out didn't receive an error like on my Mac ss.
6. This happened because the session is not cleared at the device that still logged in.

**Expected behavior**
1. Error of this issue shouldn't stop the code run, cause it is hard to know why at first.
2. Remove the stored session from Hive if the refresh token is not found.

**Screenshots**
![WhatsApp Image 2022-12-09 at 05 52 06](https://user-images.githubusercontent.com/66579441/206591185-7fe6710d-e362-4522-8d67-08f5b742f659.jpeg)
<img width="1440" alt="Screenshot 2022-12-09 at 07 08 45" src="https://user-images.githubusercontent.com/66579441/206592826-3bb899b3-1076-49e7-9d35-aa36ac837773.png">

**Additional context**
Package version: v.1.2.2

**Comment by dshukertjr** [comment]
Thanks for opening this issue. This is actually the expected behavior. 

Currently in Supabase, signing out from one device will sign out the user from all devices that are signed in with the same account. 
https://github.com/supabase/gotrue/issues/248#issuecomment-1251873472
