### ISSUE TITLE
Views Are No Longer Working

### ISSUE THREAD

**Issue by rlee1990** [supabase/supabase-flutter#306]
For some reason my views are no longer working. When I try in app or in the SQL Editor  and it always now returns no rows when I know their are rows. If I do the select manually it shows the rows. This was working about a week or so ago.

```
create or replace view user_feed as select user_public.is_verified, user_p.username as shared_username, profile_p.url as shared_profile_photo, profile_p.file_path as shared_profile_path, user_public.username, post.shared_mentions, profile_photo.url, profile_photo.file_path, post.shared_post_created_at, post.is_shared_location, post.shared_post_text, post.shared_post_owner, post.shared_post_id, post.created_at, post.updated_at, post.post_text, post.has_file, post.file_count, post.files, post.is_shared, post.mentions, post.has_shared_files, post.shared_files, post.is_pinned, post.is_location_post, post.location_data, post.shared_location_data, post.to_expire, post.id, post.post_owner, shared_count.reaction_count as share_count, liked_count.reaction_count as like_count, commented_count.reaction_count as comment_count from post 
inner join user_public on user_public.id = post.post_owner
inner join profile_photo on profile_photo.id = post.post_owner
inner join user_public as user_p on user_p.id = post.shared_post_owner
inner join profile_photo as profile_p on profile_p.id = post.shared_post_owner
inner join reactioncount as shared_count on shared_count.parent_id = post.id and shared_count.reaction_value = 'share'
inner join reactioncount as liked_count on liked_count.parent_id = post.id and liked_count.reaction_value = 'like'
inner join reactioncount as commented_count on commented_count.parent_id = post.id and commented_count.reaction_value = 'comment';
```

**Comment by rlee1990** [comment]
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0 22A380 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by dshukertjr** [comment]
Thanks for reporting this @rlee1990, and sorry the trouble. 

>If I do the select manually it shows the rows

What exactly do you mean by `select manually`.

**Comment by rlee1990** [comment]
> Thanks for reporting this @rlee1990, and sorry the trouble.
> 
> > If I do the select manually it shows the rows
> 
> What exactly do you mean by `select manually`.

@dshukertjr  So if I go to the Supabase dashboard and use the SQL Editor to do a select on the same fields that I am doing in the view it returns the row.

**Comment by dshukertjr** [comment]
Oh wait, you mentioned that you can no longer query data using the view through SQL either, right? e.g. `select * from YOUR_VIEW_NAME;` does not return any data.

If that is the case, could you contact support from your Supabase dashboard?
<img width="1160" alt="Screen Shot 2022-12-09 at 11 45 02" src="https://user-images.githubusercontent.com/18113850/206612584-73b35c29-eb0c-440a-9252-05a867d0120a.png">

**Comment by rlee1990** [comment]
Okay will do thanks.

> Oh wait, you mentioned that you can no longer query data using the view through SQL either, right? e.g. `select * from YOUR_VIEW_NAME;` does not return any data.
> 
> If that is the case, could you contact support from your Supabase dashboard? <img alt="Screen Shot 2022-12-09 at 11 45 02" width="1160" src="https://user-images.githubusercontent.com/18113850/206612584-73b35c29-eb0c-440a-9252-05a867d0120a.png">
