### ISSUE TITLE
Provide a way to listen or react to storage upload status

### ISSUE THREAD

**Issue by dshukertjr** [supabase/supabase-flutter#308]
**Is your feature request related to a problem? Please describe.**

Now that the retry feature is here, it would be nice to have a way to just call `storage.upload()` and listen or read the upload status later on. 

Would love to discuss what ways we can provide this feature on this issue!

**Comment by Vinzent03** [comment]
What are these possible statuses? Do you mean a percentage of data already being uploaded or only when we retry?

**Comment by dshukertjr** [comment]
@Vinzent03
Percentage would be nice, but the server does not have that feature at the moment, so maybe another time. 

I was thinking more about how many times retries have run or whether an upload has succeded or not and maybe a better way to catch errors if errors did occur. 

I was thinking maybe we can add some of those capabilities on the StorageRetryController, but wanted to discuss whether we really need them, and if we do, what kind of APIs we should provide.

**Comment by Vinzent03** [comment]
@dshukertjr I think you already know if the uploaded succeeded or not by wrapping the upload in try catch. How do you want to improve the error handling even more? Errors not caught by `retryIf` are rethrown.

**Comment by KirioXX** [comment]
Thanks, @dshukertjr for opening this issue.

We use for the upload at the moment a background service with a local database that tries to upload all captured files over and over until it succeeds. We have to do this because our users are in a setting with very limited to no network connection but we are legally required to make sure that all files arrive on the server.  

With the retry feature, this already became much easier, but at the moment the upload is a bit of a black box. 
We do not know what is happening until the future is finished. This means we can not determine if it makes sense to keep the upload running and also cannot give the user feedback.

What would be awesome is a stream that we can just listen to, a bit like this package did https://github.com/fluttercommunity/flutter_uploader. I appreciate that it might be overkill for now and that it might come in the future with the upload restart anyways.

**Comment by Vinzent03** [comment]
@KirioXX What information should the stream contain? The only thing that comes to my mind is when a new upload retry begins.

**Comment by KirioXX** [comment]
Helpfull would be the retry count, the remaining retries and when a retry fails the exception.
If the success could also come via the stream I guess it even could run in the background 
without the need of actively awaiting a response.

**Comment by dshukertjr** [comment]
@KirioXX
Something along the lines of this, correct?

```dart
final retryController = StorageRetryController();

retryController.retries.listen((retries) {
  // upload retries
});
retryController.result.listen((result) {
  // upload results
});
```

Alternatively we could bundle the result and retries together like this?
```dart
retryController.events.listen((event) {
  final retries = event.retries; // int value of number of attempts
  final result = event.result; // Upload.progress, Upload.done or Upload.fail
});
```

**Comment by KirioXX** [comment]
@dshukertjr yes that looks great!
If you have multiple uploads at the same time how would you identify the event?
Would you use the file path for that or would it be possible to give the upload a tag to identify it?

**Comment by dshukertjr** [comment]
@KirioXX 
>If you have multiple uploads at the same time how would you identify the event?
Would you use the file path for that or would it be possible to give the upload a tag to identify it?

In the above use case, you would create a `RetryController` instance per upload, pass it to the `upload()` method, and keep it in memory as a variable.

Also was wondering if it is important to know the number of retry attempts. Currently, we could do the following to get notified via stream when the upload is complete, or when there has been an exception. 

This does not contain any information about how many attempts have been made, but was wondering if we need that information at all. 

```dart
final stream = supabase.storage.from('my_bucket').upload('file/path', file);
stream.asStream().listen((result) {
  // `result` contains the return value of the function
  // which is the file path
}).onError((error) {
  // handle error here
  // Can catch when all retry attempts have failed
});
```

**Comment by KirioXX** [comment]
@dshukertjr happy new year! 
Sorry for the delayed answer just got back from holiday.

I think that would be very helpful. 
We could count the attempts if we want the exact number 
but I guess it is more likely that we have a pause condition that pauses the upload when it fails too often. 

I had a call with Fabrizio from the storage team before Christmas and he told me that upload progress and upload restart will come in not so far future. 
Do you think it would be better to wait for that new feature and then get a combined solution? 
Don't want to burn your time when you probably already have a plan for those things.

**Comment by dshukertjr** [comment]
@KirioXX 
No problem at all, and happy new year!

Yeah, if it's fine waiting for that feature to land, then waiting for the upload progress and pause/restart feature will certainly make things easier to implement!

**Comment by KirioXX** [comment]
Cool, then let's park this until the upload progress is coming. 👍

**Comment by dshukertjr** [comment]
I will close this issue as we are waiting for a feature on the Supabase backend to introduce the feature.
