### ISSUE TITLE
Making The Presence Class Accessible

### ISSUE THREAD

**Issue by rlee1990** [supabase/supabase-flutter#309]
It would be nice if the presence class was accessible and if the presenceState was of a type and not just dynamic. This would make it easier on the devolopers.

**Comment by dshukertjr** [comment]
Hi @rlee1990 
I think the presence classes are exported, so you should be able to use them, but are there anything in particular that you want to access, but can't access at the moment?

Also, `presenceState` should be type `Map<String, dynamic>` and not `dynamic`, but is that somewhat better?

**Comment by rlee1990** [comment]
@dshukertjr Nope that should be good was playing around with it today thanks.
