### ISSUE TITLE
Using OAuth causes App Store Rejection (iOS only)

### ISSUE THREAD

**Issue by oliverbytes** [supabase/supabase-flutter#311]
**Describe the bug**
This is not actually a bug but a critical issue to report. The current OAuth flow for iOS of Supabase is not acceptable in the App Store. My app has been rejected because the supabase-flutter SDK OAuth flow opens in an external browser instead of the in-app Safari web view controller as they suggested. 

**To Reproduce**
Submit your iOS Flutter app to the app store with OAuth sign in

**Expected behavior**
Get approved

**Screenshots**
![NexSnap-Dec-18-2022_05-50-54_AM](https://user-images.githubusercontent.com/396366/208267223-abebed6e-f0c7-4516-8fa2-e6e13c3fbc65.png)

**Smartphone (please complete the following information):**
 - Version 16.2 iPhone 14 Max (simulator)

**Additional context**
Because of this, I am stuck. I cannot publish new versions of my app. The only workaround for me right now is to use Magic Links or regular username, and password sign-ups which is not a great experience.

**Comment by oliverbytes** [comment]
I tried refactoring the signInWithOAuth() function. I forced url_launcher to launch in in-app web view. But after signing in to Google/Apple it redirects to my Web app URL instead of invoking the correct URI.

```
// use safari web view controller
  // to get approved on the app store
  Future<bool> customSignInWithOAuth(
    Provider provider, {
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) async {
    final res = await auth.getOAuthSignInUrl(
      provider: provider,
      redirectTo: redirectTo,
      scopes: scopes,
      queryParams: queryParams,
    );
    final url = Uri.parse(res.url!);
    final result = await launchUrl(
      url,
      mode: LaunchMode.inAppWebView,
      webOnlyWindowName: '_self',
    );
    return result;
  }
```

I also wish that Native Sign In https://github.com/supabase/supabase-flutter/issues/5 will be supported ASAP as this is the best solution and experience for the end user.

**Comment by oliverbytes** [comment]
The above comment https://github.com/supabase/supabase-flutter/issues/311#issuecomment-1356485555 is the only workaround right now. It got approved. I hope to see the native sign-in feature implemented soon.

**Comment by theniceboy** [comment]
This is a P0 bug. I hope it gets fixed soon. Currently looking to switch to Supabase.

**Comment by dshukertjr** [comment]
You can now launch the in app webview to do OAuth sign in, which should solve this. https://github.com/supabase/supabase-flutter/pull/323
```dart
await supabase.auth.signInWithOAuth(
  Provider.goodle,
  authScreenLaunchMode: LaunchMode.inAppWebView,
);
```

**Comment by oliverbytes** [comment]
Thanks for the solution. However it would be even better if the native sign in gets implemented soon too.
