### ISSUE TITLE
Sign Up won't work for me

### ISSUE THREAD

**Issue by fHpro0** [supabase/supabase-flutter#316]
**Describe the bug**
I tried to use the SignUp function for my flutter page and I am getting this error

`flutter: Invalid argument(s): No host specified in URI /auth/v1/signup?redirect_to=io.supabase.xxx%3A%2F%2Flogin-callback%2F`

**To Reproduce**
Any tutorial, I followed it step by step

**Smartphone:**
 - Simulator iPhone 14 Plus
 - iPhone 13
 
 I think the error comes from wrong Supabase URL configuration (free version), but i followed the tutorial

**Comment by dshukertjr** [comment]
@fHpro0 
Hmm, could you share the code where you are calling `Supabase.initialize()`? Does it look something like this?
```dart
Future<void> main() async {
  await Supabase.initialize(
    url: 'https://nlbsnpoablmkiykdbmer.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCIIkpXVCJ9.eyJy2xlIjoiYW5vbiIsImlhCI6MTYyOTE5DEwMiwiZXhwIjoxOTQ0Nzc0MTAyfQ.XZWLz95pyU9msumQNsZKNBXfyss-g214iTVAwyQLPA',
  );
  runApp(const MyApp());
}

```

**Comment by fHpro0** [comment]
> @fHpro0 Hmm, could you share the code where you are calling `Supabase.initialize()`? Does it look something like this?
> 
> ```dart
> Future<void> main() async {
>   await Supabase.initialize(
>     url: 'https://nlbsnpoablmkiykdbmer.supabase.co',
>     anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCIIkpXVCJ9.eyJy2xlIjoiYW5vbiIsImlhCI6MTYyOTE5DEwMiwiZXhwIjoxOTQ0Nzc0MTAyfQ.XZWLz95pyU9msumQNsZKNBXfyss-g214iTVAwyQLPA',
>   );
>   runApp(const MyApp());
> }
> ```


my initialize looks like this

```dart 
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Supabase.initialize(
      url: Constants.supabaseUrl,
      anonKey: Constants.supabaseAnnonKey,
      authCallbackUrlHostname: 'login-callback');
  runApp(const App());
}
```
