### ISSUE TITLE
StorageException: jwt expired

### ISSUE THREAD

**Issue by Wizzel1** [supabase/supabase-flutter#318]
I am encountering an error when trying to upload a file to storage: 
```StorageException (StorageException(message: jwt expired, statusCode: 400, error: jwt expired))```
 even when I refresh the session with 
 ```dart
await Supabase.instance.client.auth.refreshSession();
```
before uploading.
Is this a bug or am I missing something?

**Comment by dshukertjr** [comment]
@Wizzel1 
Could you provide a minimal code to reproduce your issue?

**Comment by Wizzel1** [comment]
Well there isn't much code to provide here: 

```dart
void main(){
    await Supabase.initialize(
    url: 'myUrl',
    anonKey: 'myKey',
    );
}

Future<void> uploadImage(Uint8List imageData) {
    return Supabase.instance.client.storage
    .from('myBucket')
    .uploadBinary('path/to/file', imageData, fileOptions: const FileOptions(contentType: 'image/png'));
}
```

after some time logged in, this throws an error. Even when I change the upload function to this:
```dart
Future<void> uploadImage(Uint8List imageData) {
    await Supabase.instance.client.auth.refreshSession();
    return Supabase.instance.client.storage
    .from('myBucket')
    .uploadBinary('path/to/file', imageData, fileOptions: const FileOptions(contentType: 'image/png'));
}
```

**Comment by Wizzel1** [comment]
@dshukertjr  Nevermind, I forgot to remove some helper code... Thanks for looking into this though
