### ISSUE TITLE
Storage download() and list() systematically return 404

### ISSUE THREAD

**Issue by boeledi** [supabase/supabase-flutter#324]
Using supabase plugin version 1.2.0 or 1.3.0, using download() or list(), both return 404.

**Reproduction**:

Create a "public" bucket, named "translations" and upload a file, named "locale_en.json"
In Flutter, execute the following:
* await Supabase.instance.client.storage.from("translations").download("locale_en.json")
or 
* await Supabase.instance.client.storage.from("translations").list()

Both return an exception:

StorageException(message: The resource was not found, statusCode: 404, error: Not found)

Logs on Supabase reveal an extra "/info/" in the URL being used.

**Context**:

* Flutter 3.3.10
* supabase: 1.2.0 or 1.3.0
* supabase_flutter: 1.2.2

**Comment by dshukertjr** [comment]
Thanks @boeledi for opening this issue. 

Have you configured RLS policies for the `translations` bucket? Public buckets allows you to access the stored objects through a public URL, which you can obtain by calling `supabase.storage.getPublicUrl()`, but they still require proper RLS policies if you want to perform `.download()` or `.list()` operations on them. 

We could probably address this is the comments docs of each method, so I will add it to my queue to add some comments about it.

**Comment by boeledi** [comment]
Thanks @dshukertjr for your answer.

I have just tried to configure such RLS policy, but I still have the same issue with the following policy definition
```
((bucket_id = 'translations'::text) AND (storage.extension(name) = 'json'::text) AND (lower((storage.foldername(name))[1]) = 'public'::text) AND (role() = 'anon'::text))
```
my bucket is "translations" and I have 2 folders.

Here is an extract of the logs I see on Supabase, in which we clearly see the word "info" (see highlighted)
```
[
  {
    "context": [
      {
        "host": "ip-........eu-central-1.compute.internal",
        "pid": 29
      }
    ],
    "err": [],
    "error": [
      {
        "__fault": null,
        "__metadata": [],
        "address": null,
        "cause": [],
        "code": null,
        "config": [],
        "detail": null,
        "errno": null,
        "expiredAt": null,
        "file": null,
        "httpStatusCode": null,
        "length": null,
        "line": null,
        "message": null,
        "metadata": [
          {
            "bucketId": "translations",
            "name": "folder1/locale_en.json",
            "names": []
          }
        ],
        "name": null,
        "originalError": [],
        "port": null,
        "postgresError": [
          {
            "code": "PGRST116",
            "details": "Results contain 0 rows, application/vnd.pgrst.object+json requires 1 row",
            "hint": null,
            "message": "JSON object requested, multiple (or no) rows returned"
          }
        ],
        "routine": null,
        "severity": null,
        "stack": null,
        "status": 406,
        "statusCode": null,
        "syscall": null,
        "validation": [],
        "validationContext": null
      }
    ],
    "job": [],
    "level": "info",                       <<<<<<<<<<<<<<<<<<<<< IS THIS NORMAL ?
    "project": "........",
    "req": [
      {
        "headers": [
          {
            "accept": null,
            ...
            "content_length": null,
            "content_range": null,
            "content_type": null,
            "date": null,
            "host": "storage-api-lb-eu-central-1-ext.storage.supabase.com",
            "referer": null,
            "transfer_encoding": null,
            "user_agent": null,
            "x_client_info": null,
            "x_client_trace_id": null,
            "x_forwarded_proto": "https"
          }
        ],
        "hostname": "storage-api-lb-eu-central-1-ext.storage.supabase.com",
        "method": "GET",
        "remoteAddress": ".......",
        "remotePort": 31810,
        "url": "/object/info/translations/folder1/locale_en.json"
      }
    ],
    "reqId": "........-BRU",
    "res": [
      {
        "statusCode": 400
      }
    ],
    "responseTime": 434.9250420033932,
    "results": [],
    "tenantId": ".............................."
  }
]
```

**Comment by dshukertjr** [comment]
@boeledi Yeah, I can see the same log on my working project as well, so accessing `info` shouldn't be the problem.

I would try to debug the RLS policy. One thing I noticed is that you have `role() = 'anon'::text` if you are making the API call from a user that has been signed in, this would be false, but any chance you are doing that? I would personally remove that statement, just because it's not adding any security.

**Comment by dshukertjr** [comment]
I will close this issue for now, as it seems like it's a matter of setting up the correct RLS policy but feel free to reopen it if the issue persists.
