### ISSUE TITLE
Duplicate bucket name when generating public URL

### ISSUE THREAD

**Issue by GenisMC** [supabase/supabase-flutter#329]
**Describe the bug**
When using the `getPublicUrl()` function to generate a public URL for an image stored in a Supabase bucket, the resulting URL contains the bucket name twice, which makes the URL invalid.

**To Reproduce**
1. Create a Supabase bucket.
2. Upload an image to the bucket.
3. Use the Supabase Flutter client to generate a public URL for the image using the `getPublicUrl()` function.
```
  var supabase = Supabase();
      final String path = await supabase.storage.from('shopitems').uploadBinary(
            '$productId/$i.png',
            images[i],
            fileOptions: const FileOptions(cacheControl: '3600', upsert: false),
          );

      final publicUrl = supabase.storage.from('shopitems').getPublicUrl(path);
      paths.add(publicUrl);
```

**Version:**
Supabase version: 1.2.2
Flutter version: 3.3.10

What i get:
https://dhghuxfdtdhzngrqtjrm.supabase.co/storage/v1/object/public/shopitems/shopitems/imageurl/1.png"
What works:
https://dhghuxfdtdhzngrqtjrm.supabase.co/storage/v1/object/public/shopitems/imageurl/1.png"

**Comment by Vinzent03** [comment]
Your method call is a bit strange. `getPublicUrl()` doesn't have a uuid parameter.

**Comment by Vinzent03** [comment]
The response from `uploadBinary` contains the bucket id(`shopitems/productId/id.png`), thus you pass the bucket id first in `from()` and then as argument for `getPublicUrl()`. You need to remove the prefixed bucket id before passing it to `getPublicUrl()`.

**Comment by GenisMC** [comment]
Right makes sense, my apologies. Closing issue.
