### ISSUE TITLE
supabase dart package not getting exported/imported with supabase_flutter, causing type not found errors

### ISSUE THREAD

**Issue by andrew-r-thomas** [supabase/supabase-flutter#334]
Im on supabase_flutter version 1.0.1

I have the basic default flutter counter app with supabase initialized in the main function, my app will not build because it seems like the dart supabase package is not getting integrated correctly with the supabase_flutter package, the first error in the call stack is 

: Error: Error when reading 'lib/supabase.dart': No such file or directory
export 'package:supabase/supabase.dart';
^

this is referring to line 6 of the main supabase_flutter.dart file

happy to help fix this if I can get pointed in the right direction

**Comment by bdlukaa** [comment]
Did you try `flutter pub get`?

**Comment by andrew-r-thomas** [comment]
so I did that, and got this message after running `flutter pub get` :

Because supabase_flutter >=1.1.0 <1.2.0 depends on supabase ^1.1.0 and supabase_flutter >=1.0.1 <1.1.0 depends on supabase ^1.3.0, supabase_flutter >=1.0.1 <1.2.0 requires supabase ^1.1.0.
And because supabase_flutter >=1.2.0 depends on supabase ^1.2.0, supabase_flutter >=1.0.1 requires supabase ^1.1.0.
So, because supabase depends on supabase_flutter ^1.0.1 and supabase is 1.0.0+1, version solving failed.


I get the same error with all versions other than 1.0.0 which reproduces my original error

**Comment by dshukertjr** [comment]
@andrew-r-thomas 
I can't seem to be able to reproduce your issue. Would you be able to copy and paste your dependencies section of your `pubspec.yaml`?

**Comment by andrew-r-thomas** [comment]
@dshukertjr 
Started a fresh project and the problem is solved, must've been something on my end
