### ISSUE TITLE
Automatic Package Publishing

### ISSUE THREAD

**Issue by Vinzent03** [supabase/supabase-flutter#336]
Starting from today, it's possible to publish package automatically via GitHub actions, as announced [here](https://medium.com/dartlang/screenshots-and-automated-publishing-for-pub-dev-9bceb19edf79) and documented [here](https://dart.dev/tools/pub/automated-publishing).
Do we want to enable that? Currently, I think @dshukertjr always has to merge the pr and manually publish the package locally.

There might be one issue though:
> Pub.dev only allows automated publishing from GitHub Actions when the workflow is triggered by pushing a git tag to GitHub. Pub.dev rejects publishing from GitHub Actions triggered without a tag.

As you can't add a tag to a pull request, one still must add a tag manually? Or can this be automated as well for merges from the `chore/publish` branch? I'm not sure and just throwing some ideas here.

**Comment by dshukertjr** [comment]
Wow, this is huge! Thanks for sharing this! We have been wanting this for a very long time. Let me test this thing out with a dummy package that I have and come up with a nice flow!
