### ISSUE TITLE
Stream with .eq and calling inside a json data

### ISSUE THREAD

**Issue by Erchil66** [supabase/supabase-flutter#340]
This is my sample for listening to some table which is filtered with id as a variable as json.

Here, Am using stream to specific column which inside is json now the problem is it only listen once, But when there are changes happening to the same data nothing will show it's just it only good for first start but later this on wont actually listen.
```
 base.from("monitoring_sheet")
    .stream(primaryKey: ["id"])
       /// From this part is the one problem when removing this it will listen everything although i want only
       /// a specific row to listen at. 
       .eq("some_id->>my_id","36sth26537")
```
So whenever i change in the db, Still  won't listen is there a way to fix this?

**Comment by dshukertjr** [comment]
@w3b6x9 Do we support eq filters for json values like this `some_id->>my_id=eq. 36sth26537`?

**Comment by Erchil66** [comment]
The sample from supabase documention from json to read is like that but when only run it by` ->` only like that PostgrestException will show invalid format but if i dual it with` ->>` to read json data it show data. So i didnt pry that much since it gives me result.

**Comment by dshukertjr** [comment]
@Erchil66 Could you provide the link to the sample you mention here? I think it might just be a sample code for using the rest API and not the realtime functionality.

**Comment by Erchil66** [comment]
@dshukertjr Yes it does on the documentation but on the package you can filter 1 on the streams right? 

`https://supabase.com/docs/reference/dart/using-filters`

from here: 
![image](https://user-images.githubusercontent.com/92772509/214758314-00c7d6de-a007-4852-8848-9d9d2cfc9103.png)

then i tried to apply it on my end as my sample input

![image](https://user-images.githubusercontent.com/92772509/214758434-063e1249-bb9e-4660-ab21-153f699eaa14.png)
but when i tried to run this with only `->` it gives me postgrestexception which is kind a first to me 
the sample error am having with:
![image](https://user-images.githubusercontent.com/92772509/214762816-9bba6d41-03aa-48d3-9ca9-f69d12409f11.png)

then when am using like this `->>`
![image](https://user-images.githubusercontent.com/92772509/214762882-1a8d85c9-b03c-4e65-b725-1e7abf9998c0.png)
i got the actual data match

So is this possible to listen? since i put `.eq` and at the end i can put the` .listen` which also it can be listenable, But it only listen once thus it over shadow the stream due to the `.eq`? Is this possible to listen.

**Comment by dshukertjr** [comment]
@Erchil66 Yeah, it seems like our realtime server does not support json columns at the moment. 

You can open a feature request in our Github discussion to ask for json support in realtime!
https://github.com/supabase/supabase/discussions/categories/feature-requests
