### ISSUE TITLE
'or' filter not supporting nested 'and', in contradiction to docs

### ISSUE THREAD

**Issue by davoutuk** [supabase/supabase-flutter#341]
I am trying to build a query against a Supabase table, like:

`goalType = 'steppingStone' OR (goalOpen = true AND goalType != steppingStone)`

From my Flutter app,  I am using the 'or' filter and the following string parameters

`goalType.eq.steppingStone,all(goalOpen.eq.true,goalType.neq.steppingStone)`

This is in line with the docs at https://supabase.com/docs/reference/dart/or

However,  when I use this I get a postgress error...

`PostgrestException(message: "failed to parse logic tree ((goalType.eq.steppingStone,all(goalOpen.eq.true,goalType.neq.steppingStone)))" (line 1, column 33), code: PGRST100, details: unexpected "(" expecting letter, digit, "-", "->>", "->" or delimiter (.), hint: null)
`

**Comment by dshukertjr** [comment]
@davoutuk It seems you have `all` instead of `and` in the middle. Hopefully this works.

```
goalType.eq.steppingStone,and(goalOpen.eq.true,goalType.neq.steppingStone)
```

**Comment by davoutuk** [comment]
Duh!   its so obvious - thanks for your time and patience
