### ISSUE TITLE
CORS in Flutter web when calling edge-functions

### ISSUE THREAD

**Issue by westlinkin** [supabase/supabase-flutter#347]
**Describe the bug**
While debugging in Flutter Web, calling edge functions will get CORS error, but when I do the http post myself, it is OK. I already did [this](https://supabase.com/docs/guides/functions/cors) in edge functions.

**Screenshots**
![image](https://user-images.githubusercontent.com/1687198/216869763-b4cdc446-c666-4bb4-b619-b9c25dbcb839.png)

when do the http post my self, it worked:

<img width="806" alt="WeChata00c9f526a3a715e6fac07b335770804" src="https://user-images.githubusercontent.com/1687198/216870832-4212e7c4-e646-42bb-a282-96b3a57fb16f.png">

**Version (please complete the following information):**
 - 1.4.0

**Comment by dshukertjr** [comment]
@westlinkin 
The cause is most likely not on the client library, but on the source code of the edge functions. Could you share your edge functions source code?

**Comment by westlinkin** [comment]
@dshukertjr  thanks, here is the edge function, I removed some sensitive data:

```
// Follow this setup guide to integrate the Deno language server with your editor:
// https://deno.land/manual/getting_started/setup_your_environment
// This enables autocomplete, go to definition, etc.

import { serve } from "https://deno.land/std@0.131.0/http/server.ts"
import { createClient, SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2'


const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey',
}

console.log('Function "xxx" up and running!')

serve(async (req) => {
  // This is needed if you're planning to invoke your function from a browser.
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    // Create a Supabase client with the Auth context of the logged in user.
    const supabase = createClient(
      'https://abc.supabase.co',
      'eyJ...',
      { global: { headers: { Authorization: req.headers.get('Authorization')! } } }
    )

    const {
      data: { user },
    } = await supabase.auth.getUser()

    if (user == null) {
      return new Response('',
        {
          headers: { ...corsHeaders, 'Content-Type': 'application/json; charset=utf-8' },
          status: 403,
        })
    }

    const { name } = await req.json()

    const data = {
      message: `Hello ${name}!`,
    }

    return new Response(
      JSON.stringify(data),
      { headers: { "Content-Type": "application/json" } },
    )

  } catch (e) {
    return new Response(JSON.stringify({ error: e.message }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json; charset=utf-8' },
        status: 500,
      })
  }
})

```

The **same** function, use it by ` Supabase.instance.client.functions.invoke('function-name', body: {'name': 'Hello'});` , get CORS. call it by plain http post method, it works fine. (only Flutter Web)

Thanks in advance

**Comment by dshukertjr** [comment]
@westlinkin 
Is the issue happening, because the `content-type` header is not listed in the allowed headers? Could you update your `corsHeaders` like this and retry it?

```typescript
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}
```

**Comment by westlinkin** [comment]
@dshukertjr Thanks, the error still occurs after I added `content-type`

**Comment by dshukertjr** [comment]
@westlinkin Could you literally copy and paste the code [here](https://supabase.com/docs/guides/functions/cors) and see if it runs without any errors?

**Comment by westlinkin** [comment]
@dshukertjr Sorry, it works. I mistakenly put `'Access-Control-Allow-Origin': '*',` into header when invoke function, once it is removed, the edge function went through. 

Thanks for your time.

**Comment by dshukertjr** [comment]
@westlinkin Glad to hear that it's working fine now!
