### ISSUE TITLE
Need help with setting up social auth for flutter

### ISSUE THREAD

**Issue by Wizzel1** [supabase/supabase-flutter#349]
I am trying to setup discord authentication for my windows app but I got a bit lost with it. 

I saw that it got implemented with this PR https://github.com/supabase/supabase-flutter/pull/136. 
and I have completed the setup steps that are required for the https://pub.dev/packages/app_links package to run. (Altering the files in windows/runner)

What am I supposed to do now? Is there any documentation for this?

**Comment by dshukertjr** [comment]
Once you have setup deeplinks as instructed on the app_links's page on Windows, calling `signInWithOAuth` should work launch the web browser, and upon completing the sign-in, it should bring you back to the app, but is it not? 

```dart
await supabase.auth.signInWithOAuth(
  Provider.google,
  redirectTo: kIsWeb ? null : 'io.supabase.flutter://reset-callback/',
);
```

If you have the `redirectTo` specified and you have setup [addition redirect URLs](https://pub.dev/packages/supabase_flutter#deep-link-config) and the app is still not opening upon successfully signing in, you may consider opening an issue with app_links.

**Comment by Wizzel1** [comment]
I didn't see the deep-link section in the package before, I will do it step by step again to make sure I didn't miss anything. 

One question though: I am not sure how this `'io.supabase.flutter://reset-callback/'` is built up. 
Should it look like `'io.myApp.flutter://reset-callback/'` or `'io.supabase.myApp://reset-callback/'`

**Comment by dshukertjr** [comment]
The deep link section can use some improvement. If you will, please let us know if anything is hard to understand!

So the URI can actually be anything actually. It doesn't have to include `supabase` or `reset-callback` at all. 

`foo://callback` is a valid deep link as well as `io.my-domain.app://login-callback`. It should look like the later, because deep links have to be unique across the installed device, so developers typically use the inverted domain that they own.

**Comment by Wizzel1** [comment]
@dshukertjr I see. The thing that got me confused is the following: 

When setting up discord as auth provider I need to enter a "redirection link" on the discord page. 
The link I entered there is the one thats shown at  `Authentication -> Providers -> Discord -> Redirect URL` and it looks something like this: `https://xyz.supabase.co/auth/v1/callback`. 

Isn't this supposed to be the same link as the link in 
```dart
await supabase.auth.signInWithOAuth(
  Provider.google,
  redirectTo: kIsWeb ? null : 'io.supabase.flutter://reset-callback/',
);```

I tried to use `io.my-domain.app://login-callback' but it throws an error on the discord side 'invalid redirect url'

What is the difference between this `redirectTo` and the link I need to paste into discord?

**Comment by Wizzel1** [comment]
@dshukertjr Understood. So when I am calling the signIn method like so: 
```dart
await supabase.auth.signInWithOAuth(
  Provider.google,
  redirectTo: kIsWeb ? null : 'io.supabase.flutter://reset-callback/',
);
```

do I still need to create this `io.supabase.flutter://reset-callback/'` at `Authentication -> Providers -> Discord -> Redirect URL`?  

Or in other words: Is the parameter in 
```dart
  redirectTo: kIsWeb ? null : 'io.supabase.flutter://reset-callback/',
  ```
a reference to a redirection link from `Authentication -> Providers -> Discord -> Redirect URL` or can one exist without the other?

**Comment by Wizzel1** [comment]
@dshukertjr yes, sorry. Instead of `Authentication -> Providers -> Discord -> Redirect URL` I meant `Authentication -> URL Configuration -> Redirect URLs`

**Comment by Wizzel1** [comment]
@dshukertjr I will give this a try and reopen this issue if I get stuck again. Thanks for helping!
