### ISSUE TITLE
Sing in with Google does not work correctly on macOS

### ISSUE THREAD

**Issue by solid-oleksandrhordiienko** [supabase/supabase-flutter#350]
**Describe the bug**
Sign in with Google do not set current user on macOS

**To Reproduce**
1. Call 
```
GoTrueClient().signInWithOAuth(
        Provider.google,
        redirectTo: '',
      );
```
method.
2. Select needed account in opened browser window 
3. After selecting it redirects us to local-host with error page (see screenshot)

**Expected behavior**
It must authenticates us inside app and set `currentUser` for supabase client

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/113910662/217350114-194804fe-548a-431f-a768-13e93e8e11ff.png">

**Version (please complete the following information):**
 - supabase_flutter - 1.4.0
 - supabase - 1.5.0

**Additional context**
`signInWithOAuth()` method returns true, but does not set currentUser
Also everything works correctly for another platform (web)

**Comment by dshukertjr** [comment]
@solid-oleksandrhordiienko 
In order to complete sign-in using OAuth on platform that is not web, you need to configure deep links. 

Please refer to the steps [here](https://pub.dev/packages/supabase_flutter#deep-link-config) on how to complete those steps. 

```dart
await supabase.signInWithOAuth(
        Provider.google,
        redirectTo: '[YOUR_SCHEME]://[YOUR_AUTH_HOSTNAME]',
      );
```

**Comment by solid-oleksandrhordiienko** [comment]
@dshukertjr Thanks!
