### ISSUE TITLE
Calling rpc from code does nothing, calling from SQL Editor works

### ISSUE THREAD

**Issue by Wizzel1** [supabase/supabase-flutter#354]
# Bug report

## Describe the bug
I have created this postgres function from the SQL Editor :
```sql 
CREATE OR REPLACE FUNCTION 
delete_latest_platform_items (
  platform_id_input text
) RETURNS void AS $$
DECLARE 
  last_updated DATE;
BEGIN
SELECT last_update_timestamp from platform_accounts where platform_accounts.id::text = platform_id_input into last_updated ;
DELETE FROM
  sales_items
  WHERE sales_items.order_date >= last_scraped
  and sales_items.source_platform_id::text = platform_id_input;
END;
$$ language plpgsql;
```

When I call it from the SQL Editor like so: 
```sql 
select delete_latest_platform_items('b22fd080-a8ad-11ed-a8c3-a185f30069f8');
```
it works as expected.

However when I call it from code : 

```dart
 await Supabase.instance.client.rpc(
    'delete_latest_platform_items',
    params: {
      'platform_id_input': 'b22fd080-a8ad-11ed-a8c3-a185f30069f8',
    },
  );
``` 

it doesn't have any effect but it also doesn't throw an exception.
Any idea whats happening here?

**Comment by dshukertjr** [comment]
@Wizzel1 
Does your user have permission to delete the records via RLS? If not, that is probably the reason why calling `.rpc()` from the client is not doing anything. 

Your function is a security invoker, which means that it will respect the permission of the caller of the function. When you execute the function from the SQL editor, you are calling it via the Postgres role, which has permission to delete anything. When you call it from the client though, it has the permission level of the caller, hence nothing was deleted. In Postgres, trying to delete an empty dataset does not throw, and that is why no error was thrown.

You can read more about security invoker and security definer on our [official database function guide](https://supabase.com/docs/guides/database/functions#security-definer-vs-invoker).
