### ISSUE TITLE
Dart auth.admin.createUser returns 'Invalid authentication credentials'

### ISSUE THREAD

**Issue by avalanche-tm** [supabase/supabase-flutter#356]
Following code returns AuthException(message: Invalid authentication credentials, statusCode: 401)

```dart
final supabase = SupabaseClient(supabaseUrl, supabaseServiceRoleKey);

await supabase.auth.admin
        .createUser(AdminUserAttributes(
          email: 'user@example.com',
          password: 'test123'
        ));
```

I'd like to dynamically seed users from my dart program. I'm using supabase: ^1.5.1

**Comment by Vinzent03** [comment]
Are you sure your api key is correct? The [test](https://github.com/supabase/gotrue-dart/blob/main/test/admin_test.dart#L107) passes.
