### ISSUE TITLE
select query for concrete supertable/base table

### ISSUE THREAD

**Issue by chirastefan** [supabase/supabase-flutter#358]
Is there a way in supabase flutter to query select a relationship as described here for the "Concrete supertable(Base parent table)" https://stackoverflow.com/questions/922184/why-can-you-not-have-a-foreign-key-in-a-polymorphic-association and here https://www.slideshare.net/billkarwin/practical-object-oriented-models-in-sql?

```
await supabase.from(_table).select<PostgrestList>('''

''')
```

**Comment by dshukertjr** [comment]
Hmm, I don't know much about rails, but Supabase has feature to automatically detect relationships between tables. Could you try if this would this give you the data you want?

```dart
final data = await supabase.from('my_table').select('*, my_associated_table(*)');
```

**Comment by chirastefan** [comment]
Hi, I know about that syntax from supabase-flutter SDK, but that is not enough. That stackoverflow answer is not strictly related to rails, it's the concept/solution explained in this slide https://www.slideshare.net/billkarwin/practical-object-oriented-models-in-sql.
I created a schema similar to my project schema which reflects the schemas explained in that thread/slide.

<img width="926" alt="Screenshot 2023-02-18 at 00 04 09" src="https://user-images.githubusercontent.com/16649178/219802509-6066419d-fdce-4a61-b541-862e773c8c3c.png">
I need to get the response something like this:

```
{ 
   parties: [{
      people: [all people aggregated with all their nested data]
   }]
}
```
How should the query look in this case?

```
await BackendHelper().getSchema(SupabaseSchemas.x01Game).from(_table).select<PostgrestList>('''
        *,
        people:people!adults!adults_fk( // ???
           *,
           clothes(*, 
              pants(*)
           )
        )
      ''').eq('id', partyId);
```

**Comment by dshukertjr** [comment]
You can always use [database functions](https://supabase.com/docs/guides/database/functions) to query complex queries like this.
