### ISSUE TITLE
Already cancelled error on isolates

### ISSUE THREAD

**Issue by ahndwon** [supabase/supabase-flutter#361]
**Describe the bug**
I updated my app to supabase-flutter from 1.2.2 to 1.4.0 and started getting `Already cancelled` error on any
database tasks. After that error, any database tasks made from client fails with same error.
When the app has restarted, it is working well for sometime, but it occurs again.
The stack trace is at below. 

**To Reproduce**
1. Update to 1.4.0
2. Make requests.
3. Make request until error occurs.

**Expected behavior**
No error.

**StackTrace**
```
Bad state: Already cancelled, #0      StreamQueue._checkNotClosed (package:async/src/stream_queue.dart:521)
#1      StreamQueue.next (package:async/src/stream_queue.dart:175)
#2      YAJsonIsolate.decode (package:yet_another_json_isolate/src/_isolates_io.dart:50)
#3      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:216)
#4      PostgrestBuilder._execute (package:postgrest/src/postgrest_builder.dart:198)
<asynchronous suspension>
#5      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:400)
<asynchronous suspension>
```

**Version (please complete the following information):**
 - [1.4.0]

**Additional context**
My app is currently using custom auth by JWTTokens.

**Comment by Vinzent03** [comment]
Do you pass your own YAJsonIsolate instance to the initialize method? Are you calling Supabase.dispose() somewhere?

**Comment by ahndwon** [comment]
I do not pass any YAJsonIsolate instance to the initialize method.
But I am calling Supabase.dispose() to reinitialize with my custom token.
Is this the problem?

I am using it as below.
```
    Supabase.instance.dispose();
    await Supabase.initialize(
      url: env.supabaseUrl,
      anonKey: env.anonKey,
      headers: {
        'Authorization': 'Bearer $token',
      },
    );
```

**Comment by Vinzent03** [comment]
Are you always getting the client via `Supabase.instance` or are you storing your `SupabaseClient` instance somewhere else? You may use an "outdated" `SupabaseClient` instance.

**Comment by ahndwon** [comment]
Wow thanks! That was the problem. I thought I was getting the new instance, But I wasn't.
Changed it as below and it works now.
Thank you again!
```
// before
final supabase = Supabase.instance.client;

// after
SupabaseClient get supabase => Supabase.instance.client;
```
