### ISSUE TITLE
AuthChangeEvent signedIn called after passwordRecovery event

### ISSUE THREAD

**Issue by miljepetrovic** [supabase/supabase-flutter#365]
I am implementing password recovery feature and using `resetPasswordForEmail` method. After method is called, I am getting an email with **Reset Password** link. The deep linking is set up and after clicking on the link in email, my app is opened and I events are triggered in the following order: 

1. AuthChangeEvent signedIn 
2. AuthChangeEvent passwordRecovery
3. AuthChangeEvent signedIn

In my opinion it is expected that **signedIn event is triggered first followed by passwordRecovery event**, but **the signedIn event after passwordRecovery is unexpected**, since it does not allow me to handle the reset password that I am aiming to. 

To subscribe on events I use listen() method on supabaseClient.auth.onAuthStateChange.

I have noticed that after I do **RESTART** of an application I am not getting third sigendIn event, but this is not real life scenario and I can not expect that user opens 2 times app in order to reset password. 

**Version:**
 - [1.4.0]

Could you please advice?

**Comment by rokk4** [comment]
@miljepetrovic Have you solved this? I am facing the same.

**Comment by dshukertjr** [comment]
@rokk4 @miljepetrovic 
For password recovery, would you be able to setup [Flutter native deep link](https://docs.flutter.dev/development/ui/navigation/deep-linking) and redirect the user to a password recovery page something like `your-deep-link/reset-password`?

**Comment by Vinzent03** [comment]
@rokk4 I think your link is wrong.

**Comment by dshukertjr** [comment]
@miljepetrovic @rokk4 
`onAuthStateChange` now only emits `passwordRecovery` event when performing password recovery, which makes it easier to handle the case. 
https://github.com/supabase/supabase-flutter/blob/main/packages/gotrue/lib/src/gotrue_client.dart#L703

I'm going to close this issue as complete, but feel free to reopen if anything isn't working out.
