### ISSUE TITLE
Flutter web login

### ISSUE THREAD

**Issue by Padi142** [supabase/supabase-flutter#366]
Hi,
Iam trying to figure out how to use supabase flutter auth for OAUTH login on the web. However, I got stuck at the final redirect. For some reason, supabase always redirects me to an url like `example.com/#/login-callback#access_token=XXXX...`. The `#` symbol between `login-callback` and `access_token` makes it impossible for me to retrieve those URL params, because they do not get send to the client. I tried changing the callback url in the supabase console to a lot of different things but it always ends up like this. 
Is there any way to change the `#` to `?` so I can get the values as URL params ?

Thanks a lot

**Comment by dshukertjr** [comment]
Hi @Padi142 ,

Sorry for the late response here. There is no way to have Supabase return the auth parameters with `?` currently, but would using [url_strategy](https://pub.dev/packages/url_strategy) package solve what you want to achieve here?

**Comment by Padi142** [comment]
Thanks @dshukertjr , 
I tried that but unfortunatelly what the library does is that i refreshes the page in order to get rid of the `/#/` and it removes the parameter returned by supabase :/ I think its because Flutter navigator sees the params as [Archor or web fragment](https://www.freecodecamp.org/news/how-you-can-share-links-that-anchor-to-any-text-on-a-webpage/) .

**Comment by dshukertjr** [comment]
Hmm, I was able to properly sign in and navigate to the `login-callback` page get it working with [go_router](https://pub.dev/packages/go_router) and URL_strategy like this, but would this help? If not, would you be able to share how you are configuring your routes in main.dart file?

```dart
final _router = GoRouter(
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) => const HomePage(),
    ),
    GoRoute(
      path: '/login-callback',
      builder: (context, state) => const LoginCallbackPage(),
    ),
  ],
);

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}
```

**Comment by dshukertjr** [comment]
I'm going to close this issue as an solution has been presented, but if anyone finds them stuck in the same situation, feel free to reopen it!

**Comment by pedromassango** [comment]
Hey, as in your Code, using github sign in, i'm redirected back to the `login-callback` path/page. what should we do there with the received parameters?

ALso, after github auth redirect me back to `login-callback` Suabase current user is still null :(

**Comment by Padi142** [comment]
@pedromassango  Hey! Well, how to put it. I did not managed to get Supabase Auth working on Flutter web, so I've built a middleware app in React and I redirect my SupabaseAuth calls to this page. I parse the url arguments there and then I make a custom redirect with working url params to my Flutter Web page. 
I'ts been a while but I could dig up the exact code which Iam using if you are interested.

**Comment by pedromassango** [comment]
This is so frustrating for paying customers :(

**Comment by pedromassango** [comment]
This is crazy, for loca development, they say to add this in the config file: `redirect_uri = "http://localhost:54321/auth/v1/callback"`

But what is supposed to happen on  `auth/v1/callback` webage of my app?

**Comment by dshukertjr** [comment]
@pedromassango 
Have you tried the solution I have presented [here](https://github.com/supabase/supabase-flutter/issues/366#issuecomment-1451528292)? I have tested and it works. Supabase SDK does automatically handle sign-in upon redirecting back to the app.

**Comment by pedromassango** [comment]
> @pedromassango Have you tried the solution I have presented [here](https://github.com/supabase/supabase-flutter/issues/366#issuecomment-1451528292)? I have tested and it works. Supabase SDK does automatically handle sign-in upon redirecting back to the app.

I am getting redirected back to my auth page (as I want to) but then, the `Supabase.instance.client.auth.currentSession` is still null after redirecting back to my page

**Comment by dshukertjr** [comment]
@pedromassango 
Okay. Could you copy and paste your `Supabase.initialize()` call? Also, what version of supabase_flutter are you using?

**Comment by pedromassango** [comment]
`supabase_flutter: ^2.3.4`

```
  await Supabase.initialize(
    url: 'http://localhost:8080',
    anonKey: supabaseAnonKey,
    debug: false,
  );
```

**Comment by pedromassango** [comment]
My redirect url: `http://localhost:8080/admin/auth`

**Comment by dshukertjr** [comment]
@pedromassango 
Okay, if you are on v2.3.4, and are initializing Supabase with the default options, then you shouldn't even need url_strategy package. 

When you complete your OAuth sign-in, what URL do you see? You should have a query parameter with `code` key. Do you see it?

**Comment by pedromassango** [comment]
> hen you shouldn't even need url_strategy package.

I need it to update my website url (remove the #)

**Comment by pedromassango** [comment]
It redirects to: `http://localhost:8080/admin/auth?code=e2add488b815ee58aed5&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTAwNzE0NTEsInNpdGVfdXJsIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwiaWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJmdW5jdGlvbl9ob29rcyI6bnVsbCwicHJvdmlkZXIiOiJnaXRodWIiLCJyZWZlcnJlciI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hZG1pbi9hdXRoIiwiZmxvd19zdGF0ZV9pZCI6IjE4YmE0OGQzLTU1YTEtNDhjZi05OWMyLWYzMzEwZTEwMjUxNiJ9.M24pdfl8vSovGOoUBw-Ro4Hnm30sdBONDYwftVk-UyY`

**Comment by dshukertjr** [comment]
@pedromassango 
Starting v2 of supabase_flutter, we use a different auth flow called pkce by default, and you are using that one. PKCE doesn't use the `#`, so you don't need the url_strategy package, at least for Supabase OAuth login. If you still want it for other purposes, feel free to keep it.

So it seems like you are getting the code properly. Then it probably has to do with how you are checking to see if there is a session. 

You mentioned that after redirecting back, the `currentSession` is null, but when, where, and how are you checking this?

Obtaining session after coming back to the app does not happen instantly, and it is completed after making one final HTTP request. Therefore, if you are checking the session at the very moment you arrive back to the page, the session would be null. 

The proper way of handling this it so use the `onAuthStateChange` stream and listen for `signIn` events to fire.

**Comment by pedromassango** [comment]
I am using the following code:

```dart
    supabaseAuth.onAuthStateChange.listen((authState) {
      print(authState.event);
    });
```

it prints twice, one after I open my auth page, and second time once I get redirected from the GitHub OAuth:
```
AuthChangeEvent.initialSession
AuthChangeEvent.initialSession
```

**Comment by dshukertjr** [comment]
@pedromassango 
Are you using any other deep link handling packages on your app? It might be that those are colliding with supabase_flutter and the link is not being properly handled.

**Comment by pedromassango** [comment]
No, url_strategy is the only one.

**Comment by pedromassango** [comment]
I've enabled debug mode and I see it:

```dart
***** Supabase init completed Instance of 'Supabase'
***** SupabaseDeepLinkingMixin startAuthObserver
***** SupabaseAuthState handleDeeplink http://localhost:8080/admin/auth?code=2c04eb481fb7d1b52023&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTAwNzU4NTIsInNpdGVfdXJsIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwiaWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJmdW5jdGlvbl9ob29rcyI6bnVsbCwicHJvdmlkZXIiOiJnaXRodWIiLCJyZWZlcnJlciI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC8jL2FkbWluL2F1dGgiLCJmbG93X3N0YXRlX2lkIjoiYjkzMjNiYjAtNGMxNS00NmY3LWE2MzItNjllOTNjMjhkNjkyIn0.rE5qXPXBj_RCR6cd7k0URi-s_aSWdFWyEWg7fvqxAow
onReceivedAuthDeeplink uri: http://localhost:8080/admin/auth?code=2c04eb481fb7d1b52023&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTAwNzU4NTIsInNpdGVfdXJsIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwiaWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJmdW5jdGlvbl9ob29rcyI6bnVsbCwicHJvdmlkZXIiOiJnaXRodWIiLCJyZWZlcnJlciI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC8jL2FkbWluL2F1dGgiLCJmbG93X3N0YXRlX2lkIjoiYjkzMjNiYjAtNGMxNS00NmY3LWE2MzItNjllOTNjMjhkNjkyIn0.rE5qXPXBj_RCR6cd7k0URi-s_aSWdFWyEWg7fvqxAow
AuthException(message: invalid flow state, no valid flow state found, statusCode: 403)
../packages/gotrue/src/fetch.dart 99:7                                          request
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
../dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
../dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
../dart-sdk/lib/async/future_impl.dart 838:44                                   handleValueCallback
../dart-sdk/lib/async/future_impl.dart 867:13                                   _propagateToListeners
../dart-sdk/lib/async/future_impl.dart 643:5                                    [_completeWithValue]
../dart-sdk/lib/async/future_impl.dart 713:7                                    callback
../dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
../dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
AuthException(message: invalid flow state, no valid flow state found, statusCode: 403)
../packages/gotrue/src/fetch.dart 99:7                                          request
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
../dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
../dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
../dart-sdk/lib/async/future_impl.dart 838:44                                   handleValueCallback
../dart-sdk/lib/async/future_impl.dart 867:13                                   _propagateToListeners
../dart-sdk/lib/async/future_impl.dart 643:5                                    [_completeWithValue]
../dart-sdk/lib/async/future_impl.dart 713:7                                    callback
../dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
../dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
**** onAuthStateChange: AuthChangeEvent.initialSession
Router User-id: null
AuthChangeEvent.initialSession

```

**Comment by pedromassango** [comment]
I guess I found the issue...

**Comment by dshukertjr** [comment]
@pedromassango 
Just to eliminate any possibilities, what is the URL of the page that you initiate the login process?

Also, I want to go back to [this comment](https://github.com/supabase/supabase-flutter/issues/366#issuecomment-1987019094). 

>This is crazy, for loca development, they say to add this in the config file: redirect_uri = "http://localhost:54321/auth/v1/callback"

Who are `they`, and what config file are you talking about here?

**Comment by pedromassango** [comment]
> Just to eliminate any possibilities, what is the URL of the page that you initiate the login process?

This is my login page: `http://localhost:8080/admin/auth`

This is my Github auth redirect url (the one on my github app settings): `http://localhost:8080/admin/auth`

After the login process, I get redirected back to `http://localhost:8080/admin/auth?code=...` but the auth state change callback still returns `AuthChangeEvent.initialSession`


'they' -> the Supabase doc, the docs explains it as if we're supposed to redirect to a backend endpoint,

**Comment by dshukertjr** [comment]
@pedromassango 

>After the login process, I get redirected back to http://localhost:8080/admin/auth?code=... but the auth state change callback still returns AuthChangeEvent.initialSession

Yup, that's because of the `AuthException(message: invalid flow state, no valid flow state found, statusCode: 403)` error. 

You should be able to see more details about this error on the logs of your Supabase dashboard. Could you share what the log says?

>the docs explains it as if we're supposed to redirect to a backend endpoint,

Could you provide the link to this page?

**Comment by pedromassango** [comment]
> You should be able to see more details about this error on the logs of your Supabase dashboard. Could you share what the log says?

```
[
  {
    "component": "api",
    "error": "403: invalid flow state, no valid flow state found",
    "level": "info",
    "method": "POST",
    "msg": "403: invalid flow state, no valid flow state found",
    "path": "/token",
    "referer": "http://localhost:8080/",
    "remote_addr": "172.30.0.1",
    "time": "2024-03-10T13:36:23Z",
    "timestamp": "2024-03-10T13:36:23Z"
  }
]
```

**Comment by pedromassango** [comment]
> Could you provide the link to this page?

See: https://supabase.com/docs/guides/cli/local-development#use-auth-locally

**Comment by dshukertjr** [comment]
Okay, I guess the logs didn't have much. 

Thanks for providing the docs. To clarify your confusion [here](https://github.com/supabase/supabase-flutter/issues/366#issuecomment-1987019094), the `redirect_uri = "http://localhost:54321/auth/v1/callback"` is there just to display the correct redirect_uri in your local Supabase dashboard. As long as you have `http://localhost:54321/auth/v1/callback` set as the redirect URL on your GitHub App, it should be fine, but do you have it set on your GitHub app? 

>But what is supposed to happen on auth/v1/callback webage of my app?

`auth/v1/callback` is the Gotrue end point where Supabase Auth handles the authentication, and it's not pointing to your web app.

**Comment by pedromassango** [comment]
> As long as you have `http://localhost:54321/auth/v1/callback` set as the redirect URL on your GitHub App, it should be fine, but do you have it set on your GitHub app?

I have this on my Github: http://localhost:8080/admin/auth

**Comment by dshukertjr** [comment]
@pedromassango 
That's the issue. You have to have `http://localhost:54321/auth/v1/callback` instead.

**Comment by pedromassango** [comment]
Alrighty, I'm gonna try that tomorrow and let you know the results. Spent 2 days on this already 🥹

**Comment by dshukertjr** [comment]
@pedromassango 
Yeah, how to set up a GitHub login is explained here in our docs by the way. 
https://supabase.com/docs/guides/auth/social-login/auth-github#find-your-callback-url

**Comment by pedromassango** [comment]
Hi @dshukertjr 
I've updated my code based on your last comment and now I got a different error.

After the github auth, I'm being redirected to `http://localhost:54321/auth/v1/callback?code=fe5d34b0-342b-42fb-b77a-e335bfc2f1ba`. But as you can see the state parameter isn't coming along with the redirect

On my webpage I see: 
<img width="801" alt="Screenshot 2024-03-12 at 9 35 09 PM" src="https://github.com/supabase/supabase-flutter/assets/33294549/ffbe031e-aafb-4596-be1c-7e4955826a1a">

**Comment by dshukertjr** [comment]
@pedromassango 
You most likely have the wrong redirect URL in the wrong places. 

- In `supabase/config.toml` file, set the `redirect_uri` to `http://localhost:54321/auth/v1/callback` as it says on [the docs](https://supabase.com/docs/guides/cli/local-development#use-auth-locally)
- In GitHub, set the redirect URL to `http://localhost:54321/auth/v1/callback` as it says in the docs [here](https://supabase.com/docs/guides/auth/social-login/auth-github#find-your-callback-url)
- In your Flutter code, set the `redirectTo` parameter of the `signInWithOAuth()` call to `http://localhost:8080/admin/auth`

**Comment by pedromassango** [comment]
Yeah, it finally works as expected, now that I (finally) understand how it works, I might consider writing a Blog post about it.

Btw, is your doc (`https://supabase.com/docs/guides/auth/social-login/auth-github#find-your-callback-url`) open-sourced? I may propose some changes for clarity,

**Comment by andrew-a-hall** [comment]
I've read through this thread and I'm still confused. 

When trying to use Google OAuth signin or magic link email signin, neither show me an authstatechange event as per your comments above after receiving a valid "code" parameter. Can someone please confirm with supabase_flutter: ^2.5.8, if I'm required to manually parse the token from the returned redirect and call the verifyOTP method?

Thanks,
