### ISSUE TITLE
Type cast error after oauth sign in

### ISSUE THREAD

**Issue by ahndwon** [supabase/supabase-flutter#371]
**Describe the bug**
Type cast error is suddenly happening on production. I haven't touched any auth related code.
My project is using only Google and Apple sign in.
Tried older client versions but happens same.
Tried upgrading supabase-flutter to 1.4.0 but same.
Was using 1.3.1.
Also I can't see any logs on Supabase Auth Log dashboard.
Tried restarting the supabase server, but still happens.

I added the logs at the bottom.

Is it just me that's getting this error?

**To Reproduce**
1. Sign in
2. Fails handling callback
3. onAuthStateChange not called.

**Logs**
```

flutter: ***** SupabaseAuthState handleDeeplink <LOGIN_CALLBACK_URL + ACCESSTOKEN>
flutter: onReceivedAuthDeeplink uri: <LOGIN_CALLBACK_URL + ACCESSTOKEN>
flutter: type 'Null' is not a subtype of type 'String' in type cast
```

**Version (please complete the following information):**
 - [e.g. 1.3.1, 1.4.0]

**Additional context**

**Comment by DanMossa** [comment]
I'm able to confirm that I'm not experiencing sign in issues using sign in with Google on Android.

**Comment by dshukertjr** [comment]
Looking into this issue now.

**Comment by dshukertjr** [comment]
@ahndwon 
Would you be able to provide more details on the reproduction steps? Is this happening on iOS, Android, web, or all? Also would you be able to share the stack trace of when this error happens?

**Comment by dshukertjr** [comment]
Hmm, can't seem to reproduce the issue on iOS and Android with Google login on my end. @ahndwon If you could share any additional details to reproduce thee issue, it would be helpful for us to reproduce the issue.

**Comment by ahndwon** [comment]
Hello, thanks for the comment. I'll add some more details.

1. My client platform is only Android and iOS.

2. It is happening on Google Sign In and Apple sign in. 

3. There is no stack traces due to no exceptions, only logs are printed on the console.
The logs above seems its from supabase-flutter sdk,
because the log "onReceivedAuthDeeplink uri: " is from supabase_auth.dart _handleDeeplink method.
All the logs from my code, has a [log] tag, because I'm using the log from dart:developer. But those don't.
This is the main reason I have opened this issue. I think it's happening from supabase-flutter.

4. This is the only project I have that is using supabase auth, so I am having trouble reproducing.
I'll try to find ways to reproduce.


<details open>
<summary>Full logs</summary>
<pre>
flutter: ***** SupabaseAuthState handleDeeplink opo.typing.xyz://login-callback/#access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjc3MjI2NDU2LCJzdWIiOiIxYTAyNWUxNC01NTQyLTQwNDgtODBiZi0wYjkwOGMwMDlmZmYiLCJlbWFpbCI6ImdhaGxvazI0QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZ29vZ2xlIiwicHJvdmlkZXJzIjpbImFwcGxlIiwiZ29vZ2xlIiwiZ29vZ2xlIiwiZ29vZ2xlIiwiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiYXZhdGFyX3VybCI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FHTm15eGJxSGs3aHJYeFdPSzB3X3ltZUl1WEw0cGdhZWVpcVExQk40a0phYVE9czk2LWMiLCJlbWFpbCI6ImdhaGxvazI0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmYnVzZXIiOnsiZGlzYWJsZWQiOmZhbHNlLCJlbWFpbCI6ImdhaGxvazI0QGdtYWlsLmNvbSIsImVtYWlsVmVyaWZpZWQiOnRydWUsIm1ldGFkYXRhIjp7ImNyZWF0aW9uVGltZSI6IldlZCwgMDQgTWF5IDIwMjIgMDU6MTA6MTYgR01UIiwibGFzdFJlZnJlc2hUaW1lIjoiVGh1LCAxOSBKYW4gMjAyMyAxNToyMjoxNyBHTVQiLCJsYXN0U2lnbkluVGltZSI6IlNhdCwgMTQgSmFuIDIwMjMgMTI6MTE6MzggR01UIn0sInByb3ZpZGVyRGF0YSI6W3siZGlzcGxheU5hbWUiOiJEb25nIFdvbiBBaG4iLCJlbWFpbCI6ImdhaGxvazI0QGdtYWlsLmNvbSIsInBob3RvVVJMIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUVkRlRwNVdhSXhNT29OVDNXcHdEQ2RoaDY0N1U4WTZ2QnpsRGhpQV9oRzBXZz1zOTYtYyIsInByb3ZpZGVySWQiOiJnb29nbGUuY29tIiwidWlkIjoiMTAyMzIxMzEzNDkxMTgzMTUyNTA5In0seyJlbWFpbCI6ImdhaGxvazI0QGdtYWlsLmNvbSIsInByb3ZpZGVySWQiOiJhcHBsZS5jb20iLCJ1aWQiOiIwMDA2ODAuZmZhNGM4MmQ4Njg2NDdmYjg4MzQ2YmEzMWE2NTJmNDkuMDg0NSJ9LHsiZW1haWwiOiJnYWhsb2syNEBnbWFpbC5jb20iLCJwcm92aWRlcklkIjoiYXBwbGUuY29tIiwidWlkIjoiMDAwNjgwLmNkNWRjOGM4MTFjYzQ0YzFhZDc5NWQ0ZDg1MjlhZDlhLjA2NDQifV0sInRva2Vuc1ZhbGlkQWZ0ZXJUaW1lIjoiV2VkLCAwNCBNYXkgMjAyMiAwNToxMDoxNiBHTVQiLCJ1aWQiOiJkQmV1SnNPUjBiTVoyeWlyQlBTRXBWUjlYUUczIn0sImZ1bGxfbmFtZSI6IkRvbmcgV29uIEFobiIsImlzcyI6Imh0dHBzOi8vYXBwbGVpZC5hcHBsZS5jb20vYXV0aC9rZXlzIiwibmFtZSI6IkRvbmcgV29uIEFobiIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BR05teXhicUhrN2hyWHhXT0swd195bWVJdVhMNHBnYWVlaXFRMUJONGtKYWFRPXM5Ni1jIiwicHJvdmlkZXJfaWQiOiIwMDA2ODAuZmZhNGM4MmQ4Njg2NDdmYjg4MzQ2YmEzMWE2NTJmNDkuMDg0NSIsInN1YiI6IjAwMDY4MC5mZmE0YzgyZDg2ODY0N2ZiODgzNDZiYTMxYTY1MmY0OS4wODQ1In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoib2F1dGgiLCJ0aW1lc3RhbXAiOjE2NzcyMjI4NTZ9XSwic2Vzc2lvbl9pZCI6ImE3OTM1ODVkLWZiYWYtNGNiMi1iNzQ4LTcyMTEwYzg3ZDZhNSJ9.rwlhpoa0YWP9wSDbGXBAVwmGnXFD9J5Ck6IiM-geBFQ&expires_in=3600&provider_refresh_token=r2c5241f6465446469ebacea5cd5e95a4.0.swyq.Vw6FnF8vCprHwVWRGDjzYw&provider_token=af73cde4e01274d6d8f7a115eadad4e2d.0.swyq.AzBeOsp-Z9kkSUBM1W-ROA&refresh_token=5UyOSvx1TD_g7-NCeqg-hg&token_type=bearer
flutter: onReceivedAuthDeeplink uri: opo.typing.xyz://login-callback/#access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjc3MjI2NDU2LCJzdWIiOiIxYTAyNWUxNC01NTQyLTQwNDgtODBiZi0wYjkwOGMwMDlmZmYiLCJlbWFpbCI6ImdhaGxvazI0QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZ29vZ2xlIiwicHJvdmlkZXJzIjpbImFwcGxlIiwiZ29vZ2xlIiwiZ29vZ2xlIiwiZ29vZ2xlIiwiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiYXZhdGFyX3VybCI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FHTm15eGJxSGs3aHJYeFdPSzB3X3ltZUl1WEw0cGdhZWVpcVExQk40a0phYVE9czk2LWMiLCJlbWFpbCI6ImdhaGxvazI0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmYnVzZXIiOnsiZGlzYWJsZWQiOmZhbHNlLCJlbWFpbCI6ImdhaGxvazI0QGdtYWlsLmNvbSIsImVtYWlsVmVyaWZpZWQiOnRydWUsIm1ldGFkYXRhIjp7ImNyZWF0aW9uVGltZSI6IldlZCwgMDQgTWF5IDIwMjIgMDU6MTA6MTYgR01UIiwibGFzdFJlZnJlc2hUaW1lIjoiVGh1LCAxOSBKYW4gMjAyMyAxNToyMjoxNyBHTVQiLCJsYXN0U2lnbkluVGltZSI6IlNhdCwgMTQgSmFuIDIwMjMgMTI6MTE6MzggR01UIn0sInByb3ZpZGVyRGF0YSI6W3siZGlzcGxheU5hbWUiOiJEb25nIFdvbiBBaG4iLCJlbWFpbCI6ImdhaGxvazI0QGdtYWlsLmNvbSIsInBob3RvVVJMIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUVkRlRwNVdhSXhNT29OVDNXcHdEQ2RoaDY0N1U4WTZ2QnpsRGhpQV9oRzBXZz1zOTYtYyIsInByb3ZpZGVySWQiOiJnb29nbGUuY29tIiwidWlkIjoiMTAyMzIxMzEzNDkxMTgzMTUyNTA5In0seyJlbWFpbCI6ImdhaGxvazI0QGdtYWlsLmNvbSIsInByb3ZpZGVySWQiOiJhcHBsZS5jb20iLCJ1aWQiOiIwMDA2ODAuZmZhNGM4MmQ4Njg2NDdmYjg4MzQ2YmEzMWE2NTJmNDkuMDg0NSJ9LHsiZW1haWwiOiJnYWhsb2syNEBnbWFpbC5jb20iLCJwcm92aWRlcklkIjoiYXBwbGUuY29tIiwidWlkIjoiMDAwNjgwLmNkNWRjOGM4MTFjYzQ0YzFhZDc5NWQ0ZDg1MjlhZDlhLjA2NDQifV0sInRva2Vuc1ZhbGlkQWZ0ZXJUaW1lIjoiV2VkLCAwNCBNYXkgMjAyMiAwNToxMDoxNiBHTVQiLCJ1aWQiOiJkQmV1SnNPUjBiTVoyeWlyQlBTRXBWUjlYUUczIn0sImZ1bGxfbmFtZSI6IkRvbmcgV29uIEFobiIsImlzcyI6Imh0dHBzOi8vYXBwbGVpZC5hcHBsZS5jb20vYXV0aC9rZXlzIiwibmFtZSI6IkRvbmcgV29uIEFobiIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BR05teXhicUhrN2hyWHhXT0swd195bWVJdVhMNHBnYWVlaXFRMUJONGtKYWFRPXM5Ni1jIiwicHJvdmlkZXJfaWQiOiIwMDA2ODAuZmZhNGM4MmQ4Njg2NDdmYjg4MzQ2YmEzMWE2NTJmNDkuMDg0NSIsInN1YiI6IjAwMDY4MC5mZmE0YzgyZDg2ODY0N2ZiODgzNDZiYTMxYTY1MmY0OS4wODQ1In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoib2F1dGgiLCJ0aW1lc3RhbXAiOjE2NzcyMjI4NTZ9XSwic2Vzc2lvbl9pZCI6ImE3OTM1ODVkLWZiYWYtNGNiMi1iNzQ4LTcyMTEwYzg3ZDZhNSJ9.rwlhpoa0YWP9wSDbGXBAVwmGnXFD9J5Ck6IiM-geBFQ&expires_in=3600&provider_refresh_token=r2c5241f6465446469ebacea5cd5e95a4.0.swyq.Vw6FnF8vCprHwVWRGDjzYw&provider_token=af73cde4e01274d6d8f7a115eadad4e2d.0.swyq.AzBeOsp-Z9kkSUBM1W-ROA&refresh_token=5UyOSvx1TD_g7-NCeqg-hg&token_type=bearer
flutter: type 'Null' is not a subtype of type 'String' in type cast
</pre>
</details>

**Comment by dshukertjr** [comment]
@ahndwon Also if you are able to, could you try upgrading the supabase_flutter version 1.4.1 that was just  published? You should be able to get stack trace for your errors, which should help identifying the cause!

**Comment by ahndwon** [comment]
@dshukertjr Thanks for your support!
I updated the supabase_flutter version. The stack trace is at below.

I think this error is happening because my project's has been migrated from Firebase Auth.
Some of migrated user's `auth.identities.last_sign_in_at`  is null on Supabase Database.
New users are not having this problem.

But it was working from a month ago.
So there must've been a change from the backend few days ago.

I have just updated last_sign_in_at with current_timestamp and it is now working.
I haven't submit the ticket for the auth team. If I should please tell me.

```
flutter: type 'Null' is not a subtype of type 'String' in type cast
flutter: #0      new UserIdentity.fromMap (package:gotrue/src/types/user.dart:153:44)
flutter: #1      User.fromJson.<anonymous closure> (package:gotrue/src/types/user.dart:80:29)
flutter: #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
flutter: #3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
flutter: #4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
flutter: #5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
flutter: #6      new List.of (dart:core-patch/array_patch.dart:52:28)
flutter: #7      ListIterable.toList (dart:_internal/iterable.dart:214:7)
flutter: #8      User.fromJson (package:gotrue/src/types/user.dart:81:10)
flutter: #9      new UserResponse.fromJson (package:gotrue/src/types/auth_response.dart:36:66)
flutter: #10     GoTrueClient.getSessionFromUrl (package:gotrue/src/gotrue_client.dart:463:31)
flutter: <asynchronous suspension>
flutter: #11     SupabaseAuth._recoverSessionFromUrl (package:supabase_flutter/src/supabase_auth.dart:272:7)
flutter: <asynchronous suspension>
flutter: #12     SupabaseAuth._handleDeeplink (package:supabase_flutter/src/supabase_auth.dart:266:5)
flutter: <asynchronous suspension>
```

**Comment by dshukertjr** [comment]
@ahndwon Thanks for sharing the cause, and glad to hear that the issue was resolved for you. Yup, if you could still open a ticket so that we have a reference to your project, that would be great!

**Comment by ahndwon** [comment]
@dshukertjr Ok, I have opened a ticket. I mentioned the issue above and also the problem with the logs not showing up on Supabase Logs Dashboard. I'll close the issue cause it is resolved.
Thanks for all the help!
