### ISSUE TITLE
AuthException (AuthException(message: Invalid Refresh Token: Refresh Token Not Found, statusCode: 400))

### ISSUE THREAD

**Issue by KevDev99** [supabase/supabase-flutter#377]
**Describe the bug**
runs into an `AuthException` although code is in a try-catch block

```
Exception has occurred.
AuthException (AuthException(message: Invalid Refresh Token: Refresh Token Not Found, statusCode: 400))
```

I think there is somehow an issue with retrieving the token from the storage - what is also strange that the try catch block don't catch the error:

the whole code is:
```
try {
    WidgetsFlutterBinding.ensureInitialized();

    await dotenv.load(fileName: ".env");

    await Supabase.initialize(
      url: dotenv.env['SUPABASE_URL']!,
      anonKey: dotenv.env['SUPABASE_ANON_KEY']!,
    );

    runApp(const App());
  } catch (err) {
    print(err);
  }
```

of course it is possible to resolve such an issue directly with completely uninstall and reinstall the app - but still how is this catch able ? 

it happens somehow between the supabase initalize and runApp - the initialize function runs through:
`flutter: ***** Supabase init completed Instance of 'Supabase'`

**Version (please complete the following information):**
 - 1.4.1

**Comment by dshukertjr** [comment]
@KevDev99 
I haven't verified for sure if it works in this particular scenario, but would handling the error like this work? 
```dart
supabase.onAuthStateChanged.onError()
```

**Comment by KevDev99** [comment]
@dshukertjr  THERE we go :) i could reproduce the issue with logging in and deleting the refresh token.

with listening to the onAuthStateChange i could catch it:
```
final authSubscription = supabase.auth.onAuthStateChange.listen((data) {
  final AuthChangeEvent event = data.event;
  final Session? session = data.session;
});

 authSubscription.onError((e) {
      // handle error
      print(e);
 });
```

**Comment by dshukertjr** [comment]
I'm glad to hear that you were able to listen to the error! This definitely needs to be documented. Will add it to the comments docs!
