### ISSUE TITLE
BUG: Android 12 Deeplink NOT DETECTED

### ISSUE THREAD

**Issue by shashankdaima** [supabase/supabase-flutter#379]
**Describe the bug**
I was using Google Provider of Supabase Auth([link](https://supabase.com/docs/guides/auth/social-login/auth-google)). This method utilises the usage of Deeplink in android. But Android12 deeplinking does require [website verification.](https://doordash.engineering/2022/01/25/your-deep-links-might-be-broken-web-intents-and-android-12/). 
**To Reproduce**
1. Just install this application on Android 12+ device, [Movie Booking App](https://github.com/shashankdaima/movie-booking-app). 
2. And trying logging in with Google account. You might need to make your own supabase account, if mine was paused. 

**Expected behavior**
Login should be complete as deeplink should direct towards the application. 

**Screenshots**
No Screenshots.

**Version (please complete the following information):**
 - Flutter package of Supabase ^1.2.2

**Suggestion[IMP]**
 - There is a way to launch Account Picker in Android look at this. [Account Picker](https://developers.google.com/android/reference/com/google/android/gms/common/AccountPicker) and [AccountManager](https://developer.android.com/reference/android/accounts/AccountManager#newChooseAccountIntent(android.accounts.Account,%20java.util.ArrayList%3Candroid.accounts.Account%3E,%20java.lang.String[],%20boolean,%20java.lang.String,%20java.lang.String,%20java.lang.String[],%20android.os.Bundle))

**Comment by dshukertjr** [comment]
Hi @shashankdaima,

Whether a URL is verified or not has nothing to do with Supabase here. It's not your Supabase URL that needs to be verified, it's your own URL that needs to be verified if you want to use it for app links.

Also, it seems like this policy of Google only applies to deep links with http or https schema. If you have no plans on launching a web app, you can just use something like `io.supabase.newlink://login-callback` and the deep link should work without any verification process.

With that, I'm going to close this issue, but feel free to ask further questions if anything is confusing!

**Comment by shashankdaima** [comment]
Hey thanks for answering this question, I was thinking if we can incorporate google account selection dialog (the one used in firebase auth as well). I think that doesn't require you to redirect to particular url. While in iOS (and other platforms) the normal browser based auth can work. What do you think?

**Comment by dshukertjr** [comment]
[Native sign in](https://github.com/supabase/supabase-flutter/issues/5) is not yet supported in Supabase, so at the moment we have to stick to browser based login for all platforms unfortunately.
