### ISSUE TITLE
Oauth Provider and Refresh Token dissapearing 

### ISSUE THREAD

**Issue by Flajt** [supabase/supabase-flutter#380]
**Describe the bug**
At some point in time, my OAuth Provider Token and RefreshToken disappear (I would assume due to the fact that they are expired).
Currently, I'm using Spotify to get an access token to interact with the Spotify web API and Spotify SDK. However, it's odd if the token is not there and the user needs to log in again. (Especially with background services)

**To Reproduce**
1. Setup Supabase with Spotify
2. Sign in
3. Wait
4. Token disappears after some time

**Expected behavior**
Tokens don't disappear/get refreshed.

**Screenshots**

**Version (please complete the following information):**
 - Package Version: 1.4.0
 - OS: Android
 - Device: Galaxy A51

**Additional context**
I'm running the Spotify SDK-related logic in a foreground task, where I init Supabase and try to get the token.
I'm currently trying to figure out if it matches the token duration of one hour,
I can also provide some code if needed.

**Comment by Flajt** [comment]
I've checked with an alarm clock.
After 1h the Token vanished.

**Comment by dshukertjr** [comment]
Hi @Flajt ,
Supabase only takes care of refreshing the Supabase auth tokens, and does not refresh OAuth providers' auth tokens. If you want to refresh the Spotify Access token, you would have to do so by your self using the refresh token returned from the initial sign in using your own backend.
