### ISSUE TITLE
After auth.signOut, the session from magic link can be recreated

### ISSUE THREAD

**Issue by WasaLordy** [supabase/supabase-flutter#383]
**Describe the bug**
If you login with a magic link and use auth.signOut somehow the deep link is still available (in cache?).
Using "Flutter Hot Restart" (Android Studio) automatically performs a sign in which shouldn't be possible.
(Closing + reopening the app works like expected: No session can be fetched)

**To Reproduce**
1. `supabase.auth.signInWithOtp`
2. Open the link from the email inside the emulator (Android Studio)
3. `supabase.auth.signOut`
4. Click "Flutter Hot Restart"

**Expected behavior**
After signOut and restart Supabase.initialize should not be able to fetch a session.

**Code**

```
Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initializeSupabase(); // Supabase.initialize(...);
  runApp(const MyApp());
}

final supabase = Supabase.instance.client;

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Column(
        children: [
          Text(supabase.auth.currentUser?.email ?? 'no user'),
          TextButton(
              onPressed: () async {
                const redirect = 'XXX://login-callback/';
                await supabase.auth.signInWithOtp(email: 'XXX', emailRedirectTo: redirect);
                setState(() {});
              },
              child: const Text('signIn')),
          TextButton(
              onPressed: () async {
                await supabase.auth.signOut();
                setState(() {});
              },
              child: const Text('signOut')),
        ],
      ),
    );
  }
}
```

**Version (please complete the following information):**
 - Flutter 3.7.3
 - supabase_flutter: 1.4.1

**Additional context**
Maybe this isn't a problem for production, but during developing I don't want to close and reopen the app 100 times a day.

**Comment by Vinzent03** [comment]
That's how deeplinks work. They are reread after hot restart. This won't be an issue in production as you can't hot restart your app. For more context see https://github.com/supabase/supabase-flutter/issues/245#issuecomment-1287797807
