### ISSUE TITLE
Could not build module 'app_links'

### ISSUE THREAD

**Issue by elhe26** [supabase/supabase-flutter#385]
**Describe the bug**
App doesn't on startup when running it on iOS.

**To Reproduce**

1. install `supabase-flutter` (relies on `app_links`: ^3.2.0)
2. The app doesn't start.
3. Error:

```bash
User-Defined Issue (Xcode): Unsupported Swift architecture
/Users/business/build/ios/Debug-iphonesimulator/app_links/app_links.framework/Headers/app_links-Swift.h:284:1


Parse Issue (Xcode): Could not build module 'app_links'
/Users/business/ios/Runner/GeneratedPluginRegistrant.m:9:8
```

**Version (please complete the following information):**

supabase_flutter : version: 1.4.2
iOS : 15.5

**Comment by DanMossa** [comment]
I had to do the following:

https://stackoverflow.com/a/59405918/4310761

**Comment by elhe26** [comment]
Thanks @DanMossa. The issue was with a custom config inside `Podfile`.

The custom config was the following:

```bash
 post_install do |installer|
   installer.pods_project.targets.each do |target|
     flutter_additional_ios_build_settings(target)

     target.build_configurations.each do |config|
       config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'

     end
  end
 end

```

I removed it and everything's working as-is.
