### ISSUE TITLE
Help : Get session (access_token and user infos) from supabase_auth with signInWithOAuth

### ISSUE THREAD

**Issue by Mktotoy** [supabase/supabase-flutter#386]
Hi,

I am currently working on a Flutter Flow app and I am trying to implement a sign in flow using Supabase Flutter library. I am using the "signInWithOAuth()" method provided by the library to authenticate with Supabase using a third-party authentication provider. The sign in flow works fine, but I am having trouble retrieving the access token / refresh_token / user infos at the end of the authentication process.

I have tried looking at the Supabase Flutter library code and documentation, but I am having difficulty understanding how to retrieve the access token after the sign in flow is completed. I would like to use the access token to perform authenticated operations with Supabase.

```
  final response = await supabase.auth.signInWithOAuth(Provider.google,
      redirectTo: redirect,
      authScreenLaunchMode:
          !kIsWeb ? LaunchMode.inAppWebView : LaunchMode.externalApplication);
```

i first try return that response output is a bool, not token.

Can someone please provide some guidance or code snippets on how to properly retrieve the access token after signing in with Supabase using the "signInWithOAuth()" method in Flutter Flow?

Sorry if it's kind a stupid question, i m not familiar yet with all the flutter stuff

Thank you in advance for your help.

**Comment by dshukertjr** [comment]
Hi @Mktotoy ,

Before going into details, the FlutterFlow Supabase integration is built and maintained by FlutterFlow team, so they probably can give you better guidance. With that being said, I can do my best to guide you. 

Are you building this application for web, or iOS and Android? If you are targeting iOS and Android, you have to setup deep links. You can find the instruction to do so [here](https://pub.dev/packages/supabase_flutter#deep-link-config).

**Comment by Mktotoy** [comment]
Thx for answer ! 

I actually exchange with the FF team for a complete supapabse integration in FF.

Waiting for futures releases, im triyng to develop a custom code to answer this kind.

It's an android app, i'm actually using deep linking and identified a possibilty by taking callback parameters where i can access the #access_token by the callback. 
I have some errors and that s why i was thinking about getting the access_token from supabase localstorage directly if its possible and if it correspond to what i need.

**Comment by chuonglam-astg** [comment]
I think you can make a subscription listening to the change of the AuthState like this:
```
_supabaseClient.auth.onAuthStateChange.listen((authState) {
});
```
the `authState` may contain what you need.

**Comment by dshukertjr** [comment]
>It's an android app, i'm actually using deep linking and identified a possibilty by taking callback parameters where i can access the #access_token by the callback.

@Mktotoy  Just to double check, you did follow the steps [here](https://pub.dev/packages/supabase_flutter#for-android) to setup deep links, correct? If so, you should be able to get the session information just like how chuonglam-astgsuggests!

**Comment by dshukertjr** [comment]
@Mktotoy 
If you are making an authenticated request to Supabase, the access token will automatically be attached to the request, so all you have to do is to just make the request using the supabase_flutter client library. 

If you want to retrieve the OAuth provider's tokens and meta data, you can get it by accessing the session object after the sign in process is complete. 
```dart
final session = supabase.auth.currentSession;
session.providerToken; // access token of the provider
session.providerRefreshToken; // refresh token of the provider
final user = session.user;
user.userMetadata; // OAuth meta data such as username
```

I'm going to close this issue for now, but feel free to reopen it if you have issues retrieving these information.

**Comment by GhostLabs94** [comment]
The issue can be on the closed state, i only want to leave information here for users finding this issue with google searches.

The problem was only one line.

When you configured the intent-filter within AndroidManifest.XML, you need to add this line to supabase intializing.

  await Supabase.initialize(
      url: YOUR_SUPABASE_URL'
      anonKey: ANON_KEY,
      authCallbackUrlHostname: 'login-callback' <---- THIS LINE NEEDS the same value as you inserted into AndroidManifest.XML (android:host="login-callback")
);


Everything you need to do is in the docs for deep-links.

https://supabase.com/docs/guides/getting-started/tutorials/with-flutter?platform=ios#setup-deep-links
