### ISSUE TITLE
We need more examples like Flutterfire

### ISSUE THREAD

**Issue by hugetiny** [supabase/supabase-flutter#390]
**Is your feature request related to a problem? Please describe.**
We need more example like Flutterfire,please.

**Describe the solution you'd like**
I hope supabase could provide examples

**Comment by dshukertjr** [comment]
@hugetiny 
Thanks for the request! Do you have any specific examples that you would like to see?

**Comment by hugetiny** [comment]
yeah,just like Flutterfire.
One example for one functionality 
I find out supabase only got a just authentication example now.

**Comment by dshukertjr** [comment]
@hugetiny 
Just to double check, you are referring to the example directory here, correct?
https://pub.dev/packages/supabase_flutter/example

If that is the case, fair enough. Let me add a task queue to myself to add more example code to cover all the functionalities!

**Comment by hugetiny** [comment]
> @hugetiny Just to double check, you are referring to the example directory here, correct? https://pub.dev/packages/supabase_flutter/example
> 
> If that is the case, fair enough. Let me add a task queue to myself to add more example code to cover all the functionalities!

Sorry I didn't make that clear.We need both easy to use supabase widget like 
https://github.com/firebase/flutterfire
Flutterfire and easy to start example like
https://github.com/firebase/quickstart-flutter

**Comment by dshukertjr** [comment]
@hugetiny 

I agree that having more examples could be beneficial for the community, but could you elaborate more on what you mean by `easy to use supabase widget` here? We have [supabase_auth_ui](https://pub.dev/packages/supabase_auth_ui) package as a quick start widget for implementing Supabase auth. Is this what you are looking for?

**Comment by hugetiny** [comment]
> @hugetiny
> 
> I agree that having more examples could be beneficial for the community, but could you elaborate more on what you mean by `easy to use supabase widget` here? We have [supabase_auth_ui](https://pub.dev/packages/supabase_auth_ui) package as a quick start widget for implementing Supabase auth. Is this what you are looking for?

yes,it should be`easy to use supabase package`. 
I am writing an open source ChatGPT Flutter + Supabase app. 
- https://github.com/hugetiny/easy-ChatGPT

I have no idea of how to write  User-related database operations.
just a  like/dislike logic:
 add/delete like/dislike to user's table
add/minus 1 like/dislike to the main table

**Comment by hugetiny** [comment]
desire for one more example of github action
1.developing with localhost SUPABASE_URL and SUPABASE_ANON_KEY...
2.release/publish with github action secret(remote server SUPABASE_URL and SUPABASE_ANON_KEY)

**Comment by dshukertjr** [comment]
For local development, you can look at [the docs](https://supabase.com/docs/guides/cli/local-development) for how to launch it, note that the supabase_flutter can be used the exact same way with local and remote development. You can find Github actions examples [here](https://github.com/supabase/supabase-action-example).

You can find a lot of  example apps built with Supabase [here](https://github.com/supabase/supabase/tree/master/examples). Note that this example folder contains apps built with other tools/ frameworks as well.
