### ISSUE TITLE
App throws when backgrounding and foregrounding quickly in succession.

### ISSUE THREAD

**Issue by DanMossa** [supabase/supabase-flutter#393]
**Describe the bug**
When a user opens my app and then puts it in the background, they may get a notification that opens the app back up. If this repeats a few times, the following exception throws: `Unhandled Exception: AuthException(message: Access token refresh retry limit exceeded., statusCode: null)`

**To Reproduce**
Background and resume the app quickly.

**Expected behavior**
Silently handle the error when we call `_recoverSupabaseSession()` and it throws the error: `Unhandled Exception: AuthException(message: Access token refresh retry limit exceeded., statusCode: null)`

**Additional context**
This is happening here:

https://github.com/supabase/supabase-flutter/blob/24287bef5c3576dc7cfd938c21d6ae841a1c7dbd/lib/src/supabase_auth.dart#L142

```
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    switch (state) {
      case AppLifecycleState.resumed:
        _recoverSupabaseSession();
        break;
      case AppLifecycleState.inactive:
        break;
      case AppLifecycleState.paused:
        break;
      case AppLifecycleState.detached:
        break;
    }
  }
```

**Comment by Vinzent03** [comment]
You should be able to fix this now by running `flutter pub upgrade gotrue`.
