### ISSUE TITLE
Unhandled Exception - Invalid Refresh Token (400)

### ISSUE THREAD

**Issue by cliftonlabrum** [supabase/supabase-flutter#394]
I'm not entirely sure how my app ended up in this state, but on every app launch, I get the following error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: AuthException(message: Invalid Refresh Token: Refresh Token Not Found, statusCode: 400)
```
Here's the stack trace:
```
#0      GotrueFetch.request
fetch.dart:99
<asynchronous suspension>

#1      GoTrueClient._callRefreshToken
gotrue_client.dart:664
<asynchronous suspension>

#2      GoTrueClient.recoverSession
gotrue_client.dart:549
<asynchronous suspension>

#3      SupabaseAuth.initialize
supabase_auth.dart:90
<asynchronous suspension>

#4      Supabase.initialize
supabase.dart:91
<asynchronous suspension>

#5      main
main.dart:9
<asynchronous suspension>
```

**To Reproduce**
All I know is that I signed in to my app using magic link auth. Then the next time I started my Flutter macOS app, this exception occurs on launch.

**Expected behavior**
supabase-Flutter should catch this exception.

**Version (please complete the following information):**
 `supabase-flutter 1.4.2`

**Comment by chuonglam-astg** [comment]
I think this bug also causes an issue that I'm facing: after a period of time logging in success, I try to get the current user id by calling:
`supabaseClient.auth.currentUser?.id;`
and this line returns null.
Please help.

**Comment by blueturningred** [comment]
I was just about to create an issue for this. Same issue.

I expect SupaBaseAuth not to crash at all and not just to catch the error. Why the refresh token is invalid in the first place?

**Comment by dshukertjr** [comment]
@cliftonlabrum @chuonglam-astg @blueturningred 
There could be multiple reasons why the token is invalid, but is this happening in debug mode, or do you see this happening in production?

If this happens in debug mode, and you use deep links to handle sign-in, this issue could be related to https://github.com/supabase/supabase-flutter/issues/245#issuecomment-1287797807, where the session is recovered from the deep link after opening the app via deep link and refreshing the app just fetches the session from deep link again. This is something that will not happen in production mode, and this is just the nature of how deep links work in debug mode.

Let me know if this seems like the cause.

**Comment by cliftonlabrum** [comment]
@dshukertjr That is a very astute observation. As far as I can tell, that is exactly what is going on here. Thank you!

**Comment by blueturningred** [comment]
@dshukertjr for me, even when I restart the app or even kill the simulator altogether, it still crashes with the same mentioned error.

**Comment by dshukertjr** [comment]
@blueturningred 
Once you have a bad token because of a refresh after signing in with deep link, the token will stay there. I guess this is a bit problematic, so maybe we should sign out the user when we get an invalid refresh token. For now, you would have to sign out from the app when this error happens!

**Comment by cliftonlabrum** [comment]
@dshukertjr Perhaps this issue should be reopened at least until the exception is caught and handled properly by `supabase_flutter`. 

It is a little frustrating to have my debugger pause for this every time my app builds. 😊

**Comment by dshukertjr** [comment]
@cliftonlabrum 
I have created https://github.com/supabase/supabase-flutter/issues/412, so we can probably keep this one closed!
