### ISSUE TITLE
StorageException(message: jwt expired) when using createSignedUrl();

### ISSUE THREAD

**Issue by Wizzel1** [supabase/supabase-flutter#402]
**Describe the bug**
I am creating a signed url with `expiresIn: 3600` to download my files. 
After some time I am getting the error and I don't understand why. Am I supposed to refresh my session before creating a signed URL?

This is the full error message: 

`StorageException (StorageException(message: jwt expired, statusCode: 400, error: jwt expired))`

**To Reproduce**
1. Create a private bucket and upload a file
2. Get your url like this.
```dart 
      final url = Supabase
          .instance
          .client
          .storage
          .from('myBucket')
          .createSignedUrl(
            'myImage.png',
            3600,
          );
```
3. Wait some time (I could not pin down how long exactly but usually 5-10 minutes)
4. Try to get the url again.

**Expected behavior**
I expected to be able to create the signed url again

**Version (please complete the following information):**
 - 1.5.0

**Comment by dshukertjr** [comment]
I know you have provided an example code, but perhaps could you be requesting signed URL like this where you have your storage client separately?

```dart
final storage = Supabase
    .instance
    .client
    .storage;
...
final url = await storage
    .from('myBucket')
    .createSignedUrl(
      'myImage.png',
      3600,
    );
```

If so, this issue is probably related to this issue https://github.com/supabase/supabase-flutter/issues/376

**Comment by Wizzel1** [comment]
I am using riverpod for dependency injection and I have created a storage provider like so: 

```dart
@Riverpod(keepAlive: true)
SupabaseStorageClient supabaseStorage(SupabaseStorageRef ref) {
  return Supabase.instance.client.storage;
}
```
so yes, I am technically creating a. global variable for the storage object.

**Comment by Vinzent03** [comment]
@Wizzel1 please run `flutter pub upgrade supabase` and try again.

**Comment by Vinzent03** [comment]
@Wizzel1 I see you liked my comment, does that mean your problem is solved, so we can close this issue?

**Comment by Wizzel1** [comment]
@Vinzent03 No it means that I liked your help but wasn't able to test it yet. I will close this asap.
