### ISSUE TITLE
Can't get session and user after success call supabase.auth.signInWithOAuth(Provider.******)

### ISSUE THREAD

**Issue by r-serega** [supabase/supabase-flutter#403]
After signing into the app with supabase.auth.signInWithOAuth(Provider.******);
it is clear that everything worked correctly, the user's photo appears in the window.
But I can't get session and user: Supabase.instance.client.auth.currentSession == null
and Supabase.instance.client.auth.currentUser == null.
In the supabase console, the new user is not added to the user list. Prompt the decision of reception of session and the user after OAUTH authorization.

**Comment by dshukertjr** [comment]
Hi @r-serega 

If you do not see the user in the Supabase dashboard, it is most likely that the sign in was not complete. When you say the user's photo appears in the window, do you mean that you just see the consent screen like this?

![image](https://user-images.githubusercontent.com/18113850/225492064-7ef6df50-f1ca-4e36-8f03-408c193f14e4.png)

Or are you able to complete the sign in from the consent screen and come back to the app via deep link?

**Comment by r-serega** [comment]
# I demonstrate this with an example:
![supabase_oauth1](https://user-images.githubusercontent.com/97946139/225533712-f4eeb4c1-9c42-43b4-8188-6d168d53d9fa.jpg)
![supabase_oauth2](https://user-images.githubusercontent.com/97946139/225533757-26a3895b-0207-463a-a5ef-5d208b8ee24b.jpg)
![supabase_oauth3](https://user-images.githubusercontent.com/97946139/225533792-9fe79494-4f4b-4abf-a557-60a6c083d1ea.jpg)

**Comment by DanMossa** [comment]
Can you post a code snippet?

**Comment by r-serega** [comment]
```
    @override
    void onInit() async {
      super.onInit();
      await loadItem();
    }
  
    Future<void> loadItem() async {
      final ConfigModel model = await ConfigProvider().getItem();
      url = model.url;
      key = model.key;
      await Supabase.initialize(url: url, anonKey: key);
      final session = Supabase.instance.client.auth.currentSession;
      print(session);
      final user = Supabase.instance.client.auth.currentUser;
      print(user);
      final data = Supabase.instance.client.auth.currentSession;
      print(data);
    }
  
    google() async {
      final r = await Supabase.instance.client.auth.signInWithOAuth(Provider.google);
      print(r);
      final session = Supabase.instance.client.auth.currentSession;
      print(session);
      final user = Supabase.instance.client.auth.currentUser;
      print(user);
    }
```
```
output console VSCode

true
null
null
Flutter Web Bootstrap: Programmatic
***** Supabase init completed Instance of 'Supabase'
Got object store box in database supabase_authentication.
***** SupabaseDeepLinkingMixin startAuthObserver
null
null
null


After the call OAUTH - there is a return to the application with a link, then re-initialization, the user appears in the circle, but I can’t get the session and the user.

In the supabase console, a new user with the name of the provider does not appear either.

**Comment by r-serega** [comment]
Just tried a similar approach implemented for Firebase. According to the same algorithm, only replaced the calls. Everything worked brilliantly!!! Authorization has been completed, the user's email has been received, and a new, newly selected user has been added to the Firebase console.

Why this approach does not work with Supabase remains a mystery to me?

**Comment by dshukertjr** [comment]
@r-serega 
This probably is due to Flutter using `#` for its routing and Supabase also using `#` to send auth tokens. 

Would you be able to use [URL strategy](https://docs.flutter.dev/development/ui/navigation/url-strategies#configuring-the-url-strategy) to remove the `#` for routing in Flutter and try it again?

**Comment by dshukertjr** [comment]
I'm going to close this issue as a [solution](https://github.com/supabase/supabase-flutter/issues/403#issuecomment-1474564132) has been suggested, but feel free to reopen it if you still encounter issues in the same way.
