### ISSUE TITLE
Which Flutter version do we want to support?

### ISSUE THREAD

**Issue by Vinzent03** [supabase/supabase-flutter#404]
Even with https://github.com/supabase/gotrue-dart/pull/120, `meta` `^1.8.0` is too high for flutter version `2.8.0`. (See [failed github action](https://github.com/supabase/supabase-flutter/actions/runs/4411706562/jobs/7730473289)).
So we can either downgrade `meta` in gotrue again or remove the flutter `2.8.0` test.

**Comment by DanMossa** [comment]
I'm all for upgrading the minimum flutter version

**Comment by dshukertjr** [comment]
I actually might prefer if we lower the version meta! Upgrading the minimum Flutter version would probably have very small impact on the community, but just to be extra careful.

**Comment by DanMossa** [comment]
@dshukertjr I can update this in the next few days to remove the increased minimum version or you can go ahead if you'd like to!

https://github.com/supabase/supabase-dart/pull/184
