### ISSUE TITLE
OAuth not working on MacOS

### ISSUE THREAD

**Issue by Wizzel1** [supabase/supabase-flutter#406]
**Describe the bug**
After setting up deep links for MacOS, authenticating with an OAuth service **does** bring up the App Window, but the user doesn't get logged in.

I am using [uni_links_desktop](https://github.com/leanflutter/uni_links_desktop) to set up deep links. 

Under macOS -> Runner I have added this section:
```xml
<key>CFBundleURLTypes</key>
<array>
<dict>
	<key>CFBundleTypeRole</key>
	<string>Editor</string>
	<key>CFBundleURLName</key>
	<string></string>
	<key>CFBundleURLSchemes</key>
	<array>
		<string>io.supabase.{myApp}</string>
	</array>
</dict>
</array>
```

When I test this on Windows, everything works as expected. 

**Version (please complete the following information):**
 - [e.g. 1.5.0]

**Comment by Vinzent03** [comment]
The plugin uses [app_links](https://pub.dev/packages/app_links), which may conflict with your uni links implementation.

**Comment by Wizzel1** [comment]
The app_links package doesn't support registering windows protocols and the recommended solution [url_protocol](https://pub.dev/packages/url_protocol) hasn't been updated in 2 years. 

Is there any other way to register protocols besides doing it in the registry?

**Comment by Wizzel1** [comment]
Nevermind, I have forked the url_protocol package and updated it myself. 
OAuth now works on macOS as well, thanks
