### ISSUE TITLE
Add the different callback messages as constants

### ISSUE THREAD

**Issue by DanMossa** [supabase/supabase-flutter#408]
When trying to determine what the type of callback message is during a subscription, it would be nice to have an enum added to Constants to check against instead of using a String.

I currently see:
* `SUBSCRIBED`
* `CHANNEL_ERROR`
* `CLOSED`
* `TIMED OUT`

**Comment by dshukertjr** [comment]
Closing this issue as I have edited the comment here https://github.com/supabase/supabase-flutter/issues/287#issuecomment-1334831071
