### ISSUE TITLE
mock supabase initialized for flutter unit test,

### ISSUE THREAD

**Issue by fimaljo-inunity** [supabase/supabase-flutter#409]
_instance._initialized': You must initialize the supabase instance before calling Supabase. how to solve this this error showing while unit test and we using supabase only for aythentication and access token

**Comment by Vinzent03** [comment]
Is there an issue with actually initializing Supabase?

**Comment by fimaljo-inunity** [comment]
> 

no

**Comment by Vinzent03** [comment]
So you can either call `Supabase.initialize()` and mock it then or initiate your own `SupabaseClient()` from the `supabase` package and mock that.

**Comment by fimaljo-inunity** [comment]
> So you can either call `Supabase.initialize()` and mock it then or initiate your own `SupabaseClient()` from the `supabase` package and mock that.

yes tried still same issue

**Comment by fimaljo-inunity** [comment]
we are not using supabaseclint . only for authentication and acces token. we using supabase

**Comment by Vinzent03** [comment]
What happens when you put `await Supabase.initialize()` in `setUp`?

**Comment by fimaljo-inunity** [comment]
> 

PlatformException (PlatformException(channel-error, Unable to establish connection on channel., null, null))

**Comment by fimaljo-inunity** [comment]
You must initialize the supabase instance before calling Supabase.instance
same error while adding in setUp

**Comment by fimaljo-inunity** [comment]
> > 
> 
> PlatformException (PlatformException(channel-error, Unable to establish connection on channel., null, null))

this error showing while puting test main fuction

**Comment by fimaljo-inunity** [comment]
supabase_flutter: 0.3.3 this is the version am using

**Comment by Vinzent03** [comment]
That version is heavily outdated. Please use the latest version.

**Comment by fimaljo-inunity** [comment]
yea am changing everything

**Comment by fimaljo-inunity** [comment]
still not working upgraded every outdated packages

**Comment by Vinzent03** [comment]
"still not working" is not specific. Please show your code and the error you get.

**Comment by fimaljo-inunity** [comment]
> ![Screenshot 2023-03-21 at 2 54 28 PM](https://user-images.githubusercontent.com/113964043/226565239-02441b45-1b99-4322-84a4-52dc93b73711.png)

same as this in setup i initilized supabase

**Comment by Vinzent03** [comment]
Please call `Supabase.initialize()` in `setUp`. I think you have to provide your own `localStorage`.
Something like 
```dart
    await Supabase.initialize(
      url: supabaseUrl,
      anonKey: supabaseKey,
      localStorage: MockLocalStorage(),
    );
    ```

**Comment by fimaljo-inunity** [comment]
![Screenshot 2023-03-24 at 6 17 44 PM](https://user-images.githubusercontent.com/113964043/227525287-0a9ca0f8-f3a0-4336-80a9-692408e49c9c.png)

**Comment by fimaljo-inunity** [comment]
ok let me try .thank you
