### ISSUE TITLE
Cannot login when auth.identities last_sign_in_at is NULL

### ISSUE THREAD

**Issue by Gerald-Gmainer** [supabase/supabase-flutter#414]
**Describe the bug**
In `auth.identities`, some users have `last_sign_in_at` as a NULL value at. When trying to login with such a user, the login fails

**To Reproduce**
I dont know to reproduce why some users have a NULL `last_sign_in_at`.

1. at database: u`pdate auth.identities set last_sign_in_at=null where user_id='user_id';`
2. at flutter: `await supabase.auth.signInWithPassword(email: email, password: password);`

**Expected behavior**
* gotrue should be able to login even if `last_sign_in_at` is NULL
* `auth.identities last_sign_in_at` should not be NULL

**Screenshots**
E/flutter ( 6074): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
E/flutter ( 6074): #0      new UserIdentity.fromMap (package:gotrue/src/types/user.dart:153:44)
E/flutter ( 6074): #1      User.fromJson.<anonymous closure> (package:gotrue/src/types/user.dart:80:29)
E/flutter ( 6074): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
E/flutter ( 6074): #3      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
E/flutter ( 6074): #4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
E/flutter ( 6074): #5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter ( 6074): #6      new List.of (dart:core-patch/array_patch.dart:51:28)
E/flutter ( 6074): #7      ListIterable.toList (dart:_internal/iterable.dart:213:44)
E/flutter ( 6074): #8      User.fromJson (package:gotrue/src/types/user.dart:81:10)
E/flutter ( 6074): #9      Session.fromJson (package:gotrue/src/types/session.dart:39:18)
E/flutter ( 6074): #10     new AuthResponse.fromJson (package:gotrue/src/types/auth_response.dart:16:27)
E/flutter ( 6074): #11     GoTrueClient.signInWithPassword (package:gotrue/src/gotrue_client.dart:186:39)

**Version (please complete the following information):**
 - 1.3.1 and 1.5.0 (both have same error)

**Additional context**
Login in with same user works with supabase-js.

**Comment by dshukertjr** [comment]
Hi @Gerald-Gmainer 
Thanks for reporting this. We will publish a update to fix this ASAP. 

While the fix is being published, a SQL query something like this that will back fill the last_sign_in_at will resolve the bug.

```sql
update auth.identities
  set last_sign_in_at = '2023-03-26'
  where
    last_sign_in_at is null and
    provider = 'email' and
    id = user_id::text;
```
