### ISSUE TITLE
Session not persisted on auth.refreshSession() in Flutter Web Release Mode

### ISSUE THREAD

**Issue by TommyLCox** [supabase/supabase-flutter#421]
See PR for this.. #422 

**Describe the bug**
On calling auth.refreshSession(), the new refreshToken is not being persisted in Flutter Web Release Mode Only. It works in Flutter Web Debug mode. The reason it works in debug mode is that in debug mode on auth.refreshSession both the AuthChangeEvent.tokenRefreshed AND AuthChangeEvent.signedIn events fire. In release mode, only the AuthChangeEvent.tokenRefreshed fires on refreshSession(). Supabase Auth only persists the session on the signedIn event, not on the tokenRefreshed event.

**To Reproduce**
Short Version:
1) Authenticate in a flutter web app using email/pwd.
2) refresh session with auth.refreshSession()
3) refresh browser
4) refresh session again with auth.refreshSession()
5) throws invalid refresh token  error.

Long version to test/observe:
To test, you first login, execute something that calls auth.refreshSession () and does a debugPrint of the refreshToken before and after the call to auth.refreshSession(). One can see that first token is different than the second token which comes after auth.refreshSession() which is good. (The first token in my test was supabase.auth.currentSession!.refreshToken. Then called auth.refreshSession() The second token was in the AuthStateChange listener(data) as data.session!.refreshToken. I am running another test to also check supabase.auth.currentSession!.refreshToken in the AuthStateChange listener after the auth.RecoverSession as well.) The key point here is that you login, run the auth.refreshSession, note the value token1 (before refresh) and then note value of  token2 (after refresh). Next, you refresh your web browser. Then, you run auth.refreshSession again and note the value of token1 just prior to this second auth.refreshSession(). You will see that in debug mode, token1 equals the value of token2 that was new new value after the first auth.refreshSession just before the web browser was refreshed. That is the EXPECTED behavior. It meant that the first auth.refreshSession acquired a new refresh token and held that new value AFTER the browser refresh.  HOWEVER, in release mode, this is not the case. After a browser refresh, you run auth.refreshSession where you check for token1 (just before the refresh) and you will see that token1 is the same as the first token1 back before the very first refreshSession(). So, the new token after the first refreshSession was LOST after a browser refresh in Release mode.

**Expected behavior**
The exepected behavior is that if you refresh the session with auth.refreshSession() so that a new token is generated, then refresh the browser, then the new token should have been retained. 

**Version (please complete the following information):**
Flutter version 3.7.7. Supabase_flutter 1.6.1

**Additional context**
supabase_auth.dart only persists the session (line 187) for AuthChangeEvent.signedIn - Not AuthChangeEvent.tokenRefreshed
  ```
void _onAuthStateChange(AuthChangeEvent event, Session? session) {
    Supabase.instance.log('** onAuthStateChange: $event');
    if (event == AuthChangeEvent.signedIn && session != null) {
      Supabase.instance.log(session.persistSessionString);
      _localStorage.persistSession(session.persistSessionString);
    } else if (event == AuthChangeEvent.signedOut) {
      _localStorage.removePersistedSession();
    }
  }
```

**Comment by TommyLCox** [comment]
I put in a PR #422

**Comment by Vinzent03** [comment]
@TommyLCox We saw the pr and already left a review.

**Comment by elliottetzkorn** [comment]
The session is not persisting for me on mobile either - this bug might extend beyond web

**Comment by Vinzent03** [comment]
Since the pr is merged and solved the issue, I'm closing this.
