### ISSUE TITLE
supabase-flutter 1.6.1 depends on old version webview_flutter (^3.0.4)

### ISSUE THREAD

**Issue by jstdk** [supabase/supabase-flutter#423]
**Describe the bug**
Since supabase-flutter depends on an old version of webview flutter, I am unable to use it in combination with packages that use the 4+ webview_flutter package version. The strange things is that this error did not occur with supabase-flutter 1.5.0. Did Supabase downgrade the webview package in upgrade to 1.6.1?

**To Reproduce**
Install a package that uses webview_flutter 4+, and then run flutter run or flutter pub get. Examples are Quil html editor and youtube_iframe

**Expected behavior**
Application to work

**Screenshots**
![2023-03-31T20:14:05,734665308+06:30](https://user-images.githubusercontent.com/115603308/229137559-09675901-a5e1-466c-a036-cc1a5b1c5e44.png)

**Version (please complete the following information):**
Flutter 3.7.9 | Supabase-flutter 1.6.1

**Additional context**

**Comment by Vinzent03** [comment]
We currently still want to support flutter 2.8.0 which is incompatible with `webview_flutter: ^4.0.0`. We didn't downgrade, but added it in `1.6.0`. @dshukertjr What do you think? Should we increase our aimed min Flutter version because of this version conflict?

For now you may try dependency override.

**Comment by dshukertjr** [comment]
@Vinzent03 
Yeah, this issue seems critical for anyone using the webview plugin. I think we can update the min Flutter version to `3.0.0` and use `webview_flutter: ^4.0.0`.
