### ISSUE TITLE
Auth token is not set correctly in storage, functions and realtime clients, when resuming a session.

### ISSUE THREAD

**Issue by esDotDev** [supabase/supabase-flutter#424]
When making calls to the storage client, Flutter is sending along the anon-token, but when I make calls to the database, it is sending the correctly authenticated token.

Roughly speaking the code looks like:
```
await client.storage.from('users').upload(path, File(...));  // anon
await client.from('notebooks').upsert(notebookData).select(); //authenticated
```

You can see the results below. Here are 2 calls to the API shortly after one another:
![image](https://user-images.githubusercontent.com/736973/229184983-2d77800c-53b1-4e39-9f4a-7e33f52ad6f0.png)

First one is a call to `storage.from().upload()`, and it is sending an anon-token
![image](https://user-images.githubusercontent.com/736973/229185160-782ee490-aebe-4923-a929-cb3446ac0f5c.png)

In the next call, to `.upsert()` the correct token is passed:
![image](https://user-images.githubusercontent.com/736973/229185372-2604515a-e491-4fb8-a142-59319f7b5ffd.png)

**Comment by esDotDev** [comment]
It appears that calling this after initializing the client fixes the issue:
```
database.storage.setAuth(database.auth.currentSession!.accessToken);
```

It seems that when I resume a session, this `SupabaseClient._handleTokenChanged` method is not called with the correct token, and so it skips the subsequent call to  `storage.setAuth`. If I logout, and back in manually, the auth key is set correctly.

**Comment by Vinzent03** [comment]
Please use the bug report issue template next time, because we can help you the best by knowing the exact package versions. Please do the following from the template:
> On Linux/macOS
Please run `dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"` in your project directory and paste the output here.
> 
> On Windows
Please run `dart pub deps | findstr "supabase gotrue postgrest storage_client realtime_client functions_client"` in your project directory and paste the output here.

**Comment by esDotDev** [comment]
```
????????? supabase_auth_ui 0.1.0+2
???   ????????? supabase_flutter...
????????? supabase_flutter 1.6.1
???   ????????? supabase 1.6.1
???   ???   ????????? functions_client 1.1.1
???   ???   ????????? gotrue 1.5.6
???   ???   ????????? postgrest 1.2.2
???   ???   ????????? realtime_client 1.0.3
???   ???   ????????? storage_client 1.2.5
```

I can kinda see what happens, when resuming `_handleTokenChanged` is called, but it is passed `null` as the token. Because of this it skips the section where it should inject the token, and then the change handler is never called again.
![image](https://user-images.githubusercontent.com/736973/229193884-978cd758-0210-4ede-a2c5-6e23a7cc7e65.png)

This seems to be because `onAuthStateChange` only fires once, and when it does `data.session` is null.

**Comment by Vinzent03** [comment]
Are you manually signing in, before that `onAuthStateChange` event? or is it right after startup? Are there more events after that with a different event type, but with an token?

**Comment by esDotDev** [comment]
I'm resuming a session, so I have previously logged in (using a magic link), with an existing session I just do something like this at startup:
```
await Supabase.initialize(
      url: url,
      anonKey: anonKey,
    );
print(auth.currentSession?.accessToken); // authenticated
print(_client.storage.headers['Authorization']); // anon
```

After that your internal `_authStateSubscription` broadcasts an event, and  `_handleTokenChanged` is called with the null token.

Then my code proceeds to the next line, where `auth.currentSession.accessToken` is valid, but the `storage.headers['Authorization']` is still `anon`.

Print output:
`auth.currentSession?.accessToken = `
_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjgwODg5MDE5LCJzdWIiOiI2OGQwY2Q3YS0yYWFlLTRmOTktYTk4MC1kNWY1MTAxOWQ5YzgiLCJlbWFpbCI6InNoYXduYmxhaXM4MUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvdHAiLCJ0aW1lc3RhbXAiOjE2ODAyODQyMTl9XSwic2Vzc2lvbl9pZCI6IjEzY2IxMzA0LWM4MGQtNGIyOS1hYmVlLTljM2VhMDhjNDI4MyJ9.CQzzvYCiGyyX_3aLgsz7wq-UrXl_1K21MWzmNrirTkw_

`_client.storage.headers['Authorization']=`
_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3bWluam1nbXF6bGlpemhxd3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzcyMTI1NTQsImV4cCI6MTk5Mjc4ODU1NH0.uIJ_NBX7a9x-tlDXjC1KjOvuVz8tv2wlbpjQB_6Eaac_

**Comment by Vinzent03** [comment]
Ah I've missed one package version check. Please upgrade `gotrue` to `1.5.7`.

**Comment by esDotDev** [comment]
Works  now, thx!
