### ISSUE TITLE
Invalid Refresh Token error won't go away

### ISSUE THREAD

**Issue by elliottetzkorn** [supabase/supabase-flutter#425]
**Describe the bug**
I've been developing for Flutter with Supabase for about four months, and this week for some reason I am getting hit non-stop with "Invalid Refresh Token 400" bugs whenever I try to develop. The only way to get it to go away is to completely uninstall and reinstall the app, but then after enough time it will come back again. My released app is having the same bug. Any idea why this might be happening? 

**Version (please complete the following information):**
iOS/ Android

**Comment by elliottetzkorn** [comment]
Guessing this is related to https://github.com/supabase/supabase-flutter/pull/422. So in that case, chiming in to say that mobile platforms are definitely being affected.

**Comment by dshukertjr** [comment]
> My released app is having the same bug.

What version of supabase_flutter is your released app using?

**Comment by elliottetzkorn** [comment]
It was 1.6.0, but it looks like the bugs have gone away with the new releases - thanks for cleaning up auth!
