### ISSUE TITLE
Upload byteData or base64 to Supabase Storage (like JS client)

### ISSUE THREAD

**Issue by jstdk** [supabase/supabase-flutter#440]
**Is your feature request related to a problem? Please describe.**
The supabase-flutter package misses an upload option that the Javascript library has. The current lib requires a File for upload, which is not always available. As a result, it is not possible to convert bytes/base64 using Flutter Web

**Describe the solution you'd like**
This function to be available for flutter. Ref: https://supabase.com/docs/reference/javascript/storage-from-upload

```
import { decode } from 'base64-arraybuffer'

const { data, error } = await supabase
  .storage
  .from('avatars')
  .upload('public/avatar1.png', decode('base64FileData'), {
    contentType: 'image/png'
  })
```

**Describe alternatives you've considered**
I have tried universal_io package etc to mitigate the dart.io limitations for Flutter web, but it all results in nothing. For now I use base64 inside my Supabase database instead of Supabase Storage

**Comment by Vinzent03** [comment]
There is `storage.from("").uploadBinary()`, which should fit your needs.

**Comment by jstdk** [comment]
@Vinzent03, thanks for your suggestion. The method you describe is not in the docs, nor is it recognized in (my) VScode. Do you have an example of a simple implementation?

**Comment by jstdk** [comment]
Sorry, error on my side. I have it now. Thanks!
