### ISSUE TITLE
Feature request: allow multiple bundle IDs for Apple provider auth

### ISSUE THREAD

**Issue by frmatthew** [supabase/supabase-flutter#444]
**Is your feature request related to a problem? Please describe.**

At the moment, the Apple auth provider requires that the app bundle ID be specified on the backend, and only one bundle ID is allowed. This means that only one app can auth via the Apple provider for any given Supabase project. In our case, we have several related apps that interface with the same backend, and they have unique bundle IDs because they serve different purposes (for example, an admin app vs the main user app). They should all be able to auth with the backend project via the Apple provider, despite having different bundle IDs.

**Describe the solution you'd like**
If it doesn't create security problems: allow the client to provide the bundle ID to use. Alternatively, allow multiple bundle IDs to be added on the backend for the Apple auth provider.

**Describe alternatives you've considered**
Not really any way around this I can think of if the backend restricts all Apple auths on a project to a single bundle ID.

**Additional context**

I've had an email exchange with a Supabase auth support engineer who noted that this was not too difficult of a change to make and that the issue was already being investigated. No doubt this feature request will require some changes on the backend provider. Adding this feature request to track progress on it for inclusion in the Flutter api.

**Comment by dshukertjr** [comment]
Closing in favor of https://github.com/supabase/supabase-flutter/issues/399
