### ISSUE TITLE
functions.invoke Web Fails iOS works. 

### ISSUE THREAD

**Issue by JulianSwales** [supabase/supabase-flutter#446]
**Describe the bug**
I am using Edge Functions running the exact same code against iOS and Web. iOS works perfectly fine and Web fails.. 

**To Reproduce**
The call to the function: 
```
final response = await Supabase.instance.client.functions
        .invoke('create_payment_intent', body: {
      'orderId': orderId,
      'amount': amount,
    });
```
The edge function:
```
import { serve } from "https://deno.land/std@0.131.0/http/server.ts";
import { createPaymentIntent } from "../_utils/stripe.ts";

serve(async (req) => {
  const minAmount = 1;
  console.log('Before req.json');
  console.log(req);
  const { orderId, amount } = await req.json();
  console.log(orderId + " / " + amount);
})
```

The process fails at the req.json() line with the following message in the log: 

SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at packageData (ext:deno_fetch/22_body.js:362:14)
    at consumeBody (ext:deno_fetch/22_body.js:239:12)
    at async Server.<anonymous> (file:///src/index.ts:7:35)
    at async Server.#respond (https://deno.land/std@0.131.0/http/server.ts:219:24)

My guess is there's no content, based on the fact the console.log(req) shows "content-length": "0" on the web call but "content-length":"62" on the iOS call? 

**Expected behavior**
No error on Web Request to Edge Function

**Screenshots**

**Version (please complete the following information):**
On Linux/macOS
Please run `dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"` in your project directory and paste the output here.

flutter_stripe_supabase 1.0.0+1
'-- supabase_flutter 1.7.0
    |-- supabase 1.6.3
    |   |-- functions_client 1.1.1
    |   |-- gotrue 1.5.7
    |   |-- postgrest 1.2.3
    |   |-- realtime_client 1.0.3
    |   |-- storage_client 1.3.0

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.2, on macOS 13.3.1 22E261 darwin-arm, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.77.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Additional context**
I'm just trying out Edge Functions for the first time, so I may have missed something, so just let me know what else you might need.. Thanks, Julian..

**Comment by Vinzent03** [comment]
I think you need to handle the `OPTIONS` case for `req.method`. https://supabase.com/docs/guides/functions/cors

**Comment by JulianSwales** [comment]
@Vinzent03 Thank you for the pointer. That was exactly the problem....
