### ISSUE TITLE
Hot Reload/Restart Freeze when using Supabase with Flutter Web

### ISSUE THREAD

**Issue by MichealReed** [supabase/supabase-flutter#447]
**Describe the bug**
Hot reload/restart hangs when making changes on web due to supabase auth.

**To Reproduce**
Create a web project with supabase auth -- maybe use https://verygood.ventures/blog/flutter-app-very-good-cli-supabase.
Deploy to web.
Change something on screen after logging in.
The app has to be manually restarted after each change.

**Expected behavior**
The app should be able to refresh states of onscreen widgets.

**Screenshots**

**Version (please complete the following information):**
Tried with latest stable and master flutter versions.

On Windows
????????? supabase_auth_client 0.0.0
???   ????????? supabase_flutter...
????????? supabase_database_client 0.0.0
???   ????????? supabase_flutter...
????????? supabase_flutter 0.3.3
???   ????????? supabase 0.3.6
???   ???   ????????? gotrue 0.2.3
???   ???   ????????? postgrest 0.1.11
???   ???   ????????? realtime_client 0.1.15+1
???   ???   ????????? storage_client 0.0.6+2

**Comment by Vinzent03** [comment]
Same as in #448

**Comment by MichealReed** [comment]
@Vinzent03 can you please re-open? Thanks for the upgrade guide, I completed the upgrades shown and am now on 1.7.0, but still am seeing freezes on reload. The log sticks at `***** SupabaseDeepLinkingMixin startAuthObserver`.

**Comment by Vinzent03** [comment]
What exactly do you mean with freeze? What makes you think supabase is the issue?

**Comment by MichealReed** [comment]
Apologies, after a clean, things seem to be in order. Must've been build artifacts from before I upgraded.
