### ISSUE TITLE
HCaptcha Flutter Integration as in REACT

### ISSUE THREAD

**Issue by elkSal** [supabase/supabase-flutter#450]
Hi all,

as per documentation on React, it is possible to use the Hcaptcha token for registering or logging in.
https://www.youtube.com/watch?v=em1cpOAXknM

I'm creating a mobile app on Flutter and I would like to use Hcaptcha as well. I managed to develop a web page and showing it as a webview therefore obtaining a Hcaptcha token in case of success.
https://www.hcaptcha.com/post/implementing-hcaptcha-in-your-flutter-app

Unfortunately the signin and signup methods don't take the Hcaptcha token as a potential optional parameter to be used (only AuthOptions(redirectTo, scopes) ).

**Can you please add the Hcaptcha in the auth flutter supabase methods as implemented in React?**

I opened a pull request but as I am new to Github, I don't know where the request should be added.

PS: documentation implementation would be appreciated as well in future, thanks for the great service :)

**Comment by elkSal** [comment]
Hi Tyler,

thanks a lot for the solution!
I was using an older version of supabase and you are indeed right.
I have one other issue now and I was wondering if you have any idea.
When I obtain the token and send it with the signInWithPassword it says "AuthException(message: hCaptcha verification process failed, statusCode: 500)". 
I noticed that all my tokens start with "P1_" and tried to remove this substring but still no success.
Any idea?

Thanks again and have a good day

**Comment by dshukertjr** [comment]
@elkSal 
Just published a new gotrue version. Could you run `dart pub upgrade gotrue` to use the latest gotrue package and see if the error goes away?

**Comment by elkSal** [comment]
Hi Tyler,

with the `dartpub upgrade gotrue`  it finally works, thanks a lot!

PS: my tokens start with "P1_" and they work well without any substring manipulation.
