### ISSUE TITLE
Persistence support

### ISSUE THREAD

**Issue by gaetschwartz** [supabase/supabase-flutter#458]
**Describe the solution you'd like**
It would be great to support persistence like [Firebase](https://firebase.google.com/docs/firestore/manage-data/enable-offline).

**Describe alternatives you've considered**
Implementing a simple persistence system by my own, but it's highly inconvenient.

**Additional context**
My initial idea was to have an SQLite db on the device, and mirror the queries done by the PostGrest client to the local database. Whether we decide to tightly couple it with the PostGrest client or managed by the supabase instance itself is a decision to make.

**Comment by dshukertjr** [comment]
Thanks for the request. We have a GitHub discussion for this actually. 

https://github.com/orgs/supabase/discussions/357
