### ISSUE TITLE
Invalid Refresh Token: Already Used

### ISSUE THREAD

**Issue by Gerald-Gmainer** [supabase/supabase-flutter#459]
**Describe the bug**
The authenticated user is not restored correctly on app start ( Supabase.initialize()). It seems that the session can be restored once, but not a 2nd time

Happens on supabase-flutter version 1.6.1 and 1.8.1

**To Reproduce**
1. Set token expiry to 1 min 
2. start the app and login with user
3. close the app and wait > 1min
4. start the app --> user session is restored
5. close the app and wait > 1min
6. start the app --> error

And `supabase.auth.onAuthStateChange.listen` will fire a `AuthChangeEvent.signedOut` event

**Expected behavior**
That the user session is restored, even after multiple app restarts

So that `supabase.auth.onAuthStateChange.listen` will fire a `AuthChangeEvent.signedIn` event

**Log**
`I/flutter (19044): ***** Supabase init completed Instance of 'Supabase'

I/flutter (19044): Invalid Refresh Token: Already Used

I/flutter (19044): 0      GotrueFetch.request (package:gotrue/src/fetch.dart:99:7)

I/flutter (19044): 1      GoTrueClient._callRefreshToken (package:gotrue/src/gotrue_client.dart:669:24)

I/flutter (19044): 2      GoTrueClient.recoverSession (package:gotrue/src/gotrue_client.dart:549:26)

I/flutter (19044): 3      SupabaseAuth.initialize (package:supabase_flutter/src/supabase_auth.dart:104:30)

I/flutter (19044): 4      Supabase.initialize (package:supabase_flutter/src/supabase.dart:91:5)`

**Comment by Gerald-Gmainer** [comment]
@dshukertjr Thank you for your support. I am using email/password login
I am sorry, it isnt that easy reproduce. Yesterday, it happens many times. Today I released that my user was also used from colleagues. Maybe that was the problem. With another user, it does not happen.
If you want, please close the issue.

**Comment by dshukertjr** [comment]
@Gerald-Gmainer 
Hmm, interesting. I will definitely keep this issue in the back of my mind. I will close this issue for now, but please feel free to reopen it whenever you encounter it again!
