### ISSUE TITLE
Postgrest HTTP 200 empty response instead of Auth failure

### ISSUE THREAD

**Issue by tomekit** [supabase/supabase-flutter#460]
**Describe the bug**
In some cases Flutter client might not have valid Supabase session at the time (e.g. when initialization of Supabase failed due to network issues) 

If you then manage to get some data from Postgrest:
```dart
# Part of: https://vercel.com/templates/next.js/subscription-starter
final List<dynamic> subscriptions = await supabase
        .from('subscriptions')
        .select('*, prices(*, products(*))')
        .in_('status', ['trialing', 'active'])
        .order('created', ascending: false )
        .limit(1);
```
It will then return empty: `subscriptions` array **instead of failing hard !**

This is because if there is no valid session for some reason in the `Authorization` header the anon key is being provided, which makes the request to pass JWT validation, but has no user context.
It seem to me that Supabase client shall either use valid user session or fail hard with some **AuthException** instead of loose empty 200OK which has entirely different meaning.

Packages
```
supabase_flutter: ^1.8.1 
# gotrue 1.6.0 
# postgrest: 1.2.3
```

```
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (2 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
```

**To Reproduce**
Unfortunately I wasn't able to prepare exact instructions yet. 

**Expected behavior**
Supabase Postgrest client shall return AuthException in case of an invalid user session instead of sending the request with the JWT anon token which returns 200OK from Postgrest.

**Additional context**

**Code likely to blame**

```dart
# ...pub-cache/hosted/pub.dev/supabase-1.6.1/lib/src/supabase_client.dart
 Map<String, String> _getAuthHeaders() {
    final authBearer = auth.currentSession?.accessToken ?? supabaseKey;
    final defaultHeaders = {
      'apikey': supabaseKey,
      'Authorization': 'Bearer $authBearer',
    };
    final headers = {...defaultHeaders, ..._headers};
    return headers;
  }
```

Any reason to pass `SupabaseKey` if `accessToken` isn't available? 
Perhaps it would be good to configure that default / fallback behavior.
```dart
final authBearer = auth.currentSession?.accessToken ?? supabaseKey;
```

**Curl**
200OK empty response example
```
> GET /rest/v1/subscriptions?select=*%2Cprices(*%2Cproducts(*))&status=in.(trialing%2Cactive)&order=created.desc.nullslast&limit=1 HTTP/2
> Host: ....
> user-agent: curl/7.85.0
> accept: */*
> apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICAgInJvbGUiOiAiYW5vbiIsCiAgICAiaXNzIjogInN1cGFiYXNlIiwKICAgICJpYXQiOiAxNjgwODE4NDAwLAogICAgImV4cCI6IDE4Mzg2NzEyMDAKfQ.9qkCkoHDbvX4MZO3EDUOYM0TQXsQR0vWlO4z3lv-434
> authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICAgInJvbGUiOiAiYW5vbiIsCiAgICAiaXNzIjogInN1cGFiYXNlIiwKICAgICJpYXQiOiAxNjgwODE4NDAwLAogICAgImV4cCI6IDE4Mzg2NzEyMDAKfQ.9qkCkoHDbvX4MZO3EDUOYM0TQXsQR0vWlO4z3lv-434
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 200 
< server: nginx/1.23.3
< date: Tue, 02 May 2023 16:32:23 GMT
< content-type: application/json; charset=utf-8
< content-range: */*
< content-location: /subscriptions?limit=1&order=created.desc.nullslast&select=%2A%2Cprices%28%2A%2Cproducts%28%2A%29%29&status=in.%28trialing%2Cactive%29
< content-profile: public
< access-control-allow-origin: *
< x-kong-upstream-latency: 2
< x-kong-proxy-latency: 0
< via: kong/2.8.3
< 
```

**Comment by dshukertjr** [comment]
Thanks for opening this issue. 

This is actually the expected behavior. By protecting the your database with RLS, select never fails, but it will just return whatever you have permission to select. This does come with pros and cons, for sure, but is what allows Supabase to just query the entire table and have it return the rows that the user has access to. 

In the particular example that you brought up, you could append `.single()` at the end to have it throw an error when it could not query any rows. 
```dart
// The following will throw if no rows were queried
final Map<String, dynamic> subscriptions = await supabase
        .from('subscriptions')
        .select('*, prices(*, products(*))')
        .in_('status', ['trialing', 'active'])
        .order('created', ascending: false )
        .limit(1)
        .single();
```

**Comment by tomekit** [comment]
Thanks for your reply.

> In the particular example that you brought up, you could append .single() at the end to have it throw an error when it could not query any rows.

Unfortunately: `single()` doesn't solve problem for us, as we support multiple products at once (e.g. user might have Pro self-hosted package available and also be subscribed to monthly managed 100GB plan).

> The reason why we pass the anonKey as a fallback is because there are cases where you want to query the database without being signed in.

I understand that, however in our case we want to query database when being signed in which I believe is the main idea behind RLS. The issue that we have with the current default that if for some reason there is some sort of session issue at the moment our users lose entitlements, because no rows -> no subscriptions.

I believe there are many DB related libraries which allow to configure their behavior (E.g. strict fail, throw exception), perhaps Supabase could allow explicitly define type of request and either use RLS or public key? I can't see a reason why one would want to send anon key for RLS type of request.

I think there shall be clear split (e.g. it shall be possible to specify type of request - RLS or public) and introduce certain guard checks. Current behavior reminds me the old MySQL world which for the sake of not failing was doing stupid assumptions. World has changed since then and industry agreed that typed languages or strict behavior are the way to go. Providing invalid defaults it's not a defensive programming, it's asking for troubles.

Current behavior is unpredictable and dangerous and combined with other session issues that we experience on Android that we haven't got to yet, it only makes this problem worse.

On Android (not only, but mostly) we're experiencing quite a few issues:
- From time to time Hive issues: flutter: Recovering corrupted box.
- Invalid Refresh Token: Refresh Token Not Found, statusCode: 400
- Sometimes AuthChangeEvent.tokenRefreshed is stuck in the loop
Combined with: Invalid Refresh Token: Already Used

That's our stance obviously, regardless of your decision we will have it sorted on our end. I've thought I'll take time to report this, as I was requested here: https://www.reddit.com/r/Supabase/comments/123yogq/comment/jerf67a

Thanks !
