### ISSUE TITLE
Select entries from a date range

### ISSUE THREAD

**Issue by RobertBrunhage** [supabase/supabase-flutter#47]
# Bug report

## Describe the bug

I am trying to make a request and only get the data between two dates. I thought this would work but maybe I am completely wack haha.

Right now it doesn't apply both the `gte` and `lte` but rather it takes the last applied one. How would I go about this?

startdate = 2021-11-1
enddate  = 2021-11-30

```
final response = await supabase
        .from('expenses')
        .select(
            'id, amount, transaction_date, categories (id, name), profiles (id, name)')
        .eq('household_id', householdId)
        .gte('transaction_date', startDate.toIso8601String())
        .lte('transaction_date', endDate.toIso8601String())
        .execute();
```

## To Reproduce

startdate = 2021-11-01
enddate  = 2021-11-30

```
final response = await supabase
        .from('someTable')
        .select('id, date')
        .gte('date', startDate.toIso8601String())
        .lte('date', endDate.toIso8601String())
        .execute();
```

## Expected behavior

I expect to only see items within that year and month.

## System information

- OS: Windows
- Browser (if applies) [e.g. chrome, safari]

## Additional context

![image](https://user-images.githubusercontent.com/26344867/142733046-dcc284c7-2696-4c7f-a8b3-81b058cb7869.png)

**Comment by RobertBrunhage** [comment]
This worked for me right away in the dashboard of supabase

```
SELECT * FROM expenses
WHERE expenses.transaction_date BETWEEN '2021-11-01' AND '2021-11-30';
```


Where this doesn't work with the following message: 
`"operator does not exist: timestamp without time zone &> unknown"`
```
final response = await supabase
    .from('expenses')
    .select()
    .rangeGte('transaction_date', '[2021-11-01,2021-11-30)')
    .execute();
```

**Comment by RobertBrunhage** [comment]
Making the dates in to milliseconds doesn't seem to work as well:

```dart
.gte('transaction_date', startDate.millisecondsSinceEpoch)
.lte('transaction_date', endDate.millisecondsSinceEpoch)
```

**Comment by phamhieu** [comment]
@RobertBrunhage, i added unit test for date range filter on `postgrest-dart` https://github.com/supabase/postgrest-dart/commit/10ed48b840412b067c54a7128c47de5f614277b8

it works properly. Let me know if you are still facing the problem.

**Comment by RobertBrunhage** [comment]
@phamhieu is still the same issue, I am using milliseconds now as that was the recommended approach. One of those is for the last month but still get it with the current query.

If I query between Oct I get 1 entry, Between November I get 3 entries, and December 3 entries, which is not correct. It only does the `gte`, and ignores my `lte`

![image](https://user-images.githubusercontent.com/26344867/144562338-5198eb10-eb6f-45c3-bff3-1f6e1d36dede.png)
![image](https://user-images.githubusercontent.com/26344867/144562353-79cb3db0-f654-401e-8b01-cb9378ddc716.png)

![image](https://user-images.githubusercontent.com/26344867/144562272-0b8eaec6-47a8-4d58-8c83-d0efc622e599.png)

Here is the exact code
```dart
final response = await supabase
        .from('expenses')
        .select(
            'id, amount, transaction_date, categories (id, name), profiles (id, name)')
        .eq('household_id', householdId)
        .gte('transaction_date', startDate.millisecondsSinceEpoch)
        .lte('transaction_date', endDate.millisecondsSinceEpoch)
        .execute();
```

**Comment by phamhieu** [comment]
If you can provide step by step to reproduce the issue, I can help take a look again. 

As in my unit test https://github.com/supabase/postgrest-dart/commit/10ed48b840412b067c54a7128c47de5f614277b8, the date range works properly.

**Comment by RobertBrunhage** [comment]
@phamhieu Thanks for taking the time, I am not sure how more accurate I can reproduce it.

1. I have 4 entries in the database: 
![image](https://user-images.githubusercontent.com/26344867/144596922-c2385d34-0e95-4cc2-9e5c-f79096e1e0d8.png)

2. I query between these two milliseconds since epoch:
![image](https://user-images.githubusercontent.com/26344867/144596961-8c523e5d-9a90-4669-91b1-2d1b88974029.png)

**Expected**
Gets 2 entries

**Actual**
Gets 4 entries

I simplified the query to this
```dart
final response = await supabase
    .from('expenses')
    .select()
    .gte('transaction_date', 1635721200000)
    .lte('transaction_date', 1638226800000)
    .execute();
```

**Comment by bdlukaa** [comment]
@phamhieu your tests use ISO strings while @RobertBrunhage uses milliseconds since epoch.

**Comment by dshukertjr** [comment]
@phamhieu BTW, is it possible to apply more than two filters? By looking at the code [here](https://github.com/supabase/postgrest-dart/blob/master/lib/src/postgrest_builder.dart#L179), it seems like only the last filter would be applied per column.

**Comment by phamhieu** [comment]
https://github.com/supabase/postgrest-dart/pull/50

Good new @RobertBrunhage, we found the error for this issue.


@dshukertjr yes, you are right.

**Comment by RobertBrunhage** [comment]
@phamhieu @Vinzent03 Awesome, well done!

@phamhieu  When will this be published to [pub.dev](pub.dev) to try out?

**Comment by bdlukaa** [comment]
@RobertBrunhage we're rolling out a bunch of changes to all of our dart packages. They will be published all at once soon.
