### ISSUE TITLE
Custom domain breaks function calls.

### ISSUE THREAD

**Issue by MichealReed** [supabase/supabase-flutter#481]
**Describe the bug**
Providing a custom domain works for auth but not functions. This has been documented as a limitation of custom domains here -- https://supabase.com/docs/guides/platform/custom-domains

**To Reproduce**
Setup supabase with a custom domain and provide this to the client as the project url.
Authentication will work but calls using the inbuilt cloud function mechanism will be rooted to the custom domain instead of the supabase domain, causing calls to fail.

**Expected behavior**
Users should be warned or the client should somehow get the appropriate url for function calls.

**Comment by dshukertjr** [comment]
Thanks for the suggestion. We actually do have plans for supporting invoking edge functions through custom domains, so I'm going to close this one.

**Comment by dshukertjr** [comment]
@MichealReed 
We will release a new version containing this change on Monday, but right on time, this feature has landed!
https://github.com/supabase/supabase-flutter/pull/496
