### ISSUE TITLE
pgvector Queries

### ISSUE THREAD

**Issue by MelbourneDeveloper** [supabase/supabase-flutter#489]
**Is your feature request related to a problem? Please describe.**

I need to make pgvector queries with the Dart client.

**Describe the solution you'd like**

Probably some way to make raw SQL queries without the Dart syntax like this

```dart
final data = await supabase
  .from('cities')
  .select('name, country_id')
  .order('id', ascending: true);
```

**Describe alternatives you've considered**

It may be possible to store the query as a stored procedure and then call it from dart...

**Additional context**

This is pgvector
https://github.com/pgvector/pgvector

**Comment by dshukertjr** [comment]
You can create a [database function](https://supabase.com/docs/guides/database/functions) and call it via [rpc](https://supabase.com/docs/reference/dart/rpc).

**Comment by davidmigloz** [comment]
@dshukertjr any plans to port [vecs](https://github.com/supabase/vecs) to Dart? 🙂
(we are looking into how to integrate Supabase Vector in [LangChain.dart](https://github.com/davidmigloz/langchain_dart))
