### ISSUE TITLE
Login with signInWithOAuth doesn't return an error from the Supabase

### ISSUE THREAD

**Issue by solid-danylokhvan** [supabase/supabase-flutter#498]
I have a trigger installed on the `auth.users` table, which can throw an exception if anything happens. On the client I want to catch this error. But `try catch` with `signInWithOAuth` doesn't work + function itself returns just boolean variable instead of response. 
In case of onAuthStateChange, if we set handleError or onError, no error is thrown there. 

Earlier we could catch an error with onErrorAuthenticating, but now I can't find where the error is thrown

Can you tell me how to catch such errors on the client, if the trigger logic with RAISE EXCEPTION

**Comment by Vinzent03** [comment]
`signInWithOAuth` uses `GoTrueClient.getOAuthSignInUrl`, which just creates an url, without any call to the server and thus nothing to catch. Haven't tested it, but I guess opening the url shows some kind of error?

**Comment by Vinzent03** [comment]
Closing because of no response. Just comment if you have still problems, and I'm open to reopen the issue.
