### ISSUE TITLE
How to add back button and loading state to LaunchMode.inAppWebView?

### ISSUE THREAD

**Issue by laeo** [supabase/supabase-flutter#502]
The webview page shows me a pure white page without loading state indicator at first, this may causing panic.

So i want to add a `AppBar` and loading state indicator to the webview page.

It seems that url_launcher does not provide an embedded webview widget. 

How you guys use with this function? Or keep it as it is?

**Comment by Vinzent03** [comment]
We decided to no longer support in app webview in the package as for google and apple provider native auth is much better. However, you can still use the webview yourself and use `getOAuthSignInUrl` to get the url.
