### ISSUE TITLE
oAuth(with provider) flutter

### ISSUE THREAD

**Issue by andim27** [supabase/supabase-flutter#503]
**Describe the bug**
I use signInWithOAuth(Provider.facebook) according to documentation.Record created - all is ok but redirect screen does not close after registration on android
![records_facebook](https://github.com/supabase/supabase-flutter/assets/4599713/44fa39a8-1810-4e1e-97d4-9367fe09d7bd)

![facebook_redirect](https://github.com/supabase/supabase-flutter/assets/4599713/3bd14bf4-3000-42b8-a003-0e82336c7c5b)

**Comment by dshukertjr** [comment]
@andim27 
Could you check if you have [setup deep links](https://pub.dev/packages/supabase_flutter#deep-link-config), and set `redirectTo` parameter when performing `signInWithOAuth()` so that the user is redirected back to the app after completing the sign in?

**Comment by andim27** [comment]
I use flutter app without external site with redirect url.Please write down instruction how to setup deep link(for android).The  documentation does not show correct way of this

**Comment by dshukertjr** [comment]
@andim27 

> I use flutter app without external site with redirect url.

Yup, you still need to setup deep link for the user to come back to the app. No external website is required to set it up. You just need to make a little change in your Flutter app. 

> The supabase account in the settings uses two site url(Site URL and redirect).Which is correct?

You can actually add the deep link as the site URL or the redirect URL, but in the example instructions, it adds it to the redirect URL as you can see on the screenshot.

![image](https://github.com/supabase/supabase-flutter/assets/18113850/cbb7bb07-4852-49e1-ab4c-fb7fd57dfd02)

> In the plugin docs you use deep link params as (YOUR_SCHEME://YOUR_HOST) What's this?

Deep link can be anything you would like, and `YOUR_SCHEME://YOUR_HOST` is just describing that. You can google deep link if you want to learn more about it! Here, we use `io.supabase.flutterdemo` as the scheme, and `login-callback` as the host just as an example, but it just has to match what you have in your Flutter app.

> Please write down instruction how to setup deep link(for android) for social plugin.The documentation does not show correct way of this

You can find the instructions for Android [here](https://pub.dev/packages/supabase_flutter#for-android). 

Although the guide is for setting up magic link, [this guide](https://supabase.com/docs/guides/getting-started/tutorials/with-flutter#setup-deep-links) is also a good resource providing step by step instructions on how to setup deep links. The deep link part of the guide works the same for both OAuth login and magic link.

Once you setup deep links, you should be able to call the following to get oauth login working.

```dart
await supabase.auth.signInWithOAuth(
  Provider.facebook,
  redirectTo: 'io.supabase.flutter://reset-callback/',
);
```

**Comment by dshukertjr** [comment]
@andim27 
I will need more information in order to help you out. Can you precisely explain what happens `auth.signInwithOAuth()` method step by step? Providing screen recording always helps as well in these situations.

**Comment by trongtindev** [comment]
@andim27 you can try [pull/518](https://github.com/supabase/supabase-flutter/pull/518)

**Comment by dshukertjr** [comment]
I'm going to close this issue for now, but if anyone finds themselves in a same situation, please feel free to reopen it.
