### ISSUE TITLE
Persist Auth State with OTP not working.

### ISSUE THREAD

**Issue by mreky** [supabase/supabase-flutter#513]
I'm trying to sign in users with OTP(SMS). The signIn process works but when I try to persist the auth state the session is not retrieved. 

Assuming they have an account already, I sign in the user like this:

```dart
void signinWithPhone(String phoneNumber, BuildContext context) async {
    try {
      await supabase.auth
          .signInWithOtp(phone: phoneNumber, shouldCreateUser: false);
      await context.pushNamed(verifyOTPRouteName, queryParameters: {
        'phoneNumber': phoneNumber.toString(),
      });
    } catch (e) {
      print(e.toString());
    }
  }
```
Then verify the OTP:

```dart
void verifyPhoneNumber(String phoneNumber, String verificationCode,
      WidgetRef ref, BuildContext context) async {
    try {
      final res = await supabase.auth.verifyOTP(
        token: verificationCode,
        type: OtpType.sms,
        phone: phoneNumber,
      );
      if (res.user != null) {
        ref.read(userIdProvider.notifier).state = res.user!.id;
        ref.read(verifyOTPShowErrorProvider.notifier).state = false;
        context.go('/home');
      }
    } catch (e) {
      print(e.toString());
      ref.read(verifyOTPShowErrorProvider.notifier).state = true;
    }
  }
```
All of this works, the user is signed in but then whenever I restart the app and try to persist the auth state of the user:

```dart
persistAuthState(WidgetRef ref, BuildContext context) async {
    try {
      final initialSession = await SupabaseAuth.instance.initialSession;
      if (initialSession != null) {
        final userId = initialSession.user.id;
        ref.read(userIdProvider.notifier).state = userId;
        context.go('/home');
      } else {
        context.go('/welcome');
      }
    } catch (e) {
      print(e.toString());
    }
  }

```

The session is never returned, the initialSession is always null.

**Comment by dshukertjr** [comment]
Hi @mreky 

Just a quick shot in the dart, but would replacing this line
```dart
final initialSession = await SupabaseAuth.instance.initialSession;
```
with this fix it?
```dart
final initialSession = supabase.auth.currentSession;
```

If not, could you also share the code where you call `Supabase.initialize()`?

**Comment by mreky** [comment]
Hi @dshukertjr,

That doesn't work either, I don't get back any session/user back at all.

This is how I call init in my main:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Supabase.initialize(
      url: supabaseUrl,
      anonKey: supabaseAnonKey);
  runApp(const ProviderScope(child: MyApp()));
}
```

**Comment by mreky** [comment]
This is what I get in debug console when I restart the app.

```
flutter: ***** Supabase init completed Instance of 'Supabase'
flutter: ***** SupabaseDeepLinkingMixin startAuthObserver
```
The initialSession is always null when I print it to the console.

**Comment by dshukertjr** [comment]
@mreky 
Thanks for sharing this. Another question just to sanity check: if you perform a regular email + password login or any other login method, will the auth state be persisted?

**Comment by mreky** [comment]
@dshukertjr 

I just tried and no it didn't persist the auth state. This is very interesting since I have other apps in prod using Supabase and they are working with email. It seems I did something wrong while setting the project up. Do you have any guesses to what could have caused this since the user is logged in successfully, I can get the user info but then when I restart there is no session. Worst case I just restart the project.

**Comment by dshukertjr** [comment]
@mreky 
Yeah, this is very interesting...

As far as I know, there shouldn't be any settings within Supabase dashboard that will prevent you from automatically persisting the auth state, so not going to lie, I'm a bit lost as well.

Creating a whole new project seems like would be the quickest solution here.

**Comment by mreky** [comment]
Alright, thank you.

**Comment by novas1r1** [comment]
Hey @emreky5,
have you found any solution to this? I'm having the same problem. Fresh project, fresh supabase instance. I'm never getting the session when using OTP and therefore user always has to login. Any idea or solution available?
