### ISSUE TITLE
Support customizing auth folder

### ISSUE THREAD

**Issue by LucasXu0** [supabase/supabase-flutter#523]
Currently, for the non-sandbox macOS app, the auth information is saved in `/Users/.../Documents`.

<img width="1032" alt="Screenshot 2023-06-26 at 16 00 07" src="https://github.com/supabase/supabase-flutter/assets/11863087/36c9e2f9-7184-4150-bb75-7fa845262da1">

I would suggestion the SDK will provide a path parameter for customzing the data folder.

**Comment by dshukertjr** [comment]
Hi @LucasXu0 

You have the full capability to customize where and how your auth info is stored by providing your own customer local storage!
https://pub.dev/packages/supabase_flutter#custom-localstorage
