### ISSUE TITLE
SupabaseStreamBuilder emits "null" error

### ISSUE THREAD

**Issue by Wizzel1** [supabase/supabase-flutter#527]
**Describe the bug**
I am handling a supabase stream with a streamtransformer:

```dart
final streamTransformer = StreamTransformer.fromHandlers(
      handleData: handleData,
      handleError: handleError,
  ); 

  void handleData(
    List<Map<String, dynamic>> data,
    EventSink<List<PlatformAccount>> sink,
  ) {
    if (data.isEmpty) return sink.add([]);

    final snapshotResult = data.map((json) {
      return PlatformAccount.fromJson(json);
    }).toList();
    sink.add(snapshotResult);
  }

Future<void> handleError(
  Object error,
  StackTrace stk,
  EventSink<List<PlatformAccount>> sink,
) async {
   print(error); //prints "null"
   print(stk); //prints "SupabaseStreamBuilder._addError"
}

final stream = Supabase.instance.client.from('myTable').stream(primaryKey: ['id']).transform(streamTransformer);
```
Every now and then, the stream emits a string that says "null" and I don't know why. Any Idea?

```
????????? supabase_flutter 1.10.6
???   ????????? supabase 1.9.5
???   ???   ????????? functions_client 1.3.2
???   ???   ????????? gotrue 1.9.0
???   ???   ????????? postgrest 1.3.2
???   ???   ????????? realtime_client 1.1.1
???   ???   ????????? storage_client 1.5.1
```

**Comment by elliottetzkorn** [comment]
Having the same issue - the stream just randomly dies on me like this some percent of the time.

**Comment by dshukertjr** [comment]
@Wizzel1 Does the stream emit `null` or throw `null`?

**Comment by Wizzel1** [comment]
@dshukertjr It emits "null" as a string.

**Comment by dshukertjr** [comment]
@Wizzel1 Okay, you seemed to have only shared your error handling code, but could you also share the code you use for listening to the data?

**Comment by Wizzel1** [comment]
@dshukertjr  You mean the `handleData` part?

**Comment by dshukertjr** [comment]
@Wizzel1 Yup.

**Comment by Wizzel1** [comment]
@dshukertjr Added it to the original post

**Comment by dshukertjr** [comment]
@Wizzel1 Wait, I'm a bit confused. Do you see the `null` in your `handleError` callback or the `handleData` callback? You said the stream emits `null`, but am I correct to say that it throws `null` and your `handleError` catches it?

**Comment by dshukertjr** [comment]
@Wizzel1 Also, `_addError` was renamed to `_addException` some time ago. Would you be able to use the most recent version of supabase_flutter to see what you get?

**Comment by Wizzel1** [comment]
@dshukertjr Yes, you are right about the emitting part. I am using supabase_flutter version 1.10.6 which seems to be the latest version, at least at pub.dev

**Comment by dshukertjr** [comment]
@Wizzel1 You have shared that the stack trace for when this error occurs is `SupabaseStreamBuilder._addError`, but could you share the full stack trace when this happens?

**Comment by Wizzel1** [comment]
@dshukertjr please check the screenshot below. 

<img width="1604" alt="Bildschirmfoto 2023-07-05 um 13 10 41" src="https://github.com/supabase/supabase-flutter/assets/43343510/ebc4dec3-dbb9-44c2-8eba-965d6d1083b4">

I just noticed that the session got automatically refreshed when before I ran into this breakpoint. Maybe that helps

**Comment by dshukertjr** [comment]
@Wizzel1 Thanks, this is very helpful!

**Comment by Vinzent03** [comment]
I've identified the reason. It's a failed heartbeat, causing the connection to get closed https://github.com/supabase/supabase-flutter/blob/e6008b94db139e5c0d513c1f8c4df243716af3ee/packages/realtime_client/lib/src/realtime_client.dart#L431

This causes the `onDone` stream listener to get called.
https://github.com/supabase/supabase-flutter/blob/e6008b94db139e5c0d513c1f8c4df243716af3ee/packages/realtime_client/lib/src/realtime_client.dart#L137

The `null` comes from being `ref` null here:
https://github.com/supabase/supabase-flutter/blob/e6008b94db139e5c0d513c1f8c4df243716af3ee/packages/realtime_client/lib/src/realtime_channel.dart#L566

That `null` is a string is because of this line:
https://github.com/supabase/supabase-flutter/blob/e6008b94db139e5c0d513c1f8c4df243716af3ee/packages/realtime_client/lib/src/realtime_channel.dart#L329

That's the full stacktrace:
```
#0      <removed from me, doesnt matter>
#1      RealtimeChannel.subscribe.<anonymous closure> (package:realtime_client/src/realtime_channel.dart:200:39)
#2      RealtimeChannel.onError.<anonymous closure> (package:realtime_client/src/realtime_channel.dart:329:36)
#3      RealtimeChannel.trigger (package:realtime_client/src/realtime_channel.dart:566:22)
#4      RealtimeClient._triggerChanError (package:realtime_client/src/realtime_client.dart:395:15)
#5      RealtimeClient._onConnClose (package:realtime_client/src/realtime_client.dart:376:7)
#6      RealtimeClient.connect.<anonymous closure> (package:realtime_client/src/realtime_client.dart:137:11)
#7      _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#8      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#9      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#10     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#11     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
#12     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161:13)
#13     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#14     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#17     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:784:19)
#18     _StreamController._closeUnchecked (dart:async/stream_controller.dart:639:7)
#19     _StreamController.close (dart:async/stream_controller.dart:632:5)
#20     _RootZone.run (dart:async/zone.dart:1655:54)
#21     _FutureListener.handleWhenComplete (dart:async/future_impl.dart:190:18)
#22     Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:754:39)
#23     Future._propagateToListeners (dart:async/future_impl.dart:810:11)
#24     Future._completeWithValue (dart:async/future_impl.dart:584:5)
#25     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:657:7)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#29     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#30     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#31     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

That being said, I'm not sure on where, how and what exactly to fix here.

**Comment by VittorioParagallo** [comment]
Happening the same here, before fixing it is possible to supply an error text like "failed heartbit, connection closed"? so that we know that we should just reload the widget and it'll not happen afeter fixing?
