### ISSUE TITLE
 _ClientSocketException: Failed host lookup

### ISSUE THREAD

**Issue by Wizzel1** [supabase/supabase-flutter#529]
**Describe the bug**
I am getting regular 
```
_ClientSocketException
Failed host lookup: 'rhfwwqrwdplqqjxcprww.supabase.co' on my Windows app. 
```

Any idea why this happens?

```
????????? supabase_flutter 1.10.6
???   ????????? supabase 1.9.5
???   ???   ????????? functions_client 1.3.2
???   ???   ????????? gotrue 1.9.0
???   ???   ????????? postgrest 1.3.2       
???   ???   ????????? realtime_client 1.1.1 
???   ???   ????????? storage_client 1.5.1  
```

**Comment by Vinzent03** [comment]
It simply means you don't have an internet connection. I suggest you to do quick google searches before creating an issue. This shows something liks [this](https://stackoverflow.com/questions/54551198/how-to-solve-socketexception-failed-host-lookup-www-xyz-com-os-error-no-ad)

**Comment by Wizzel1** [comment]
If I hadn't done a Google search I wouldn't have created an issue. I have found your linked issue as well but since I am on windows, I don't need to set any permissions

**Comment by Vinzent03** [comment]
Can you do other https requests in your flutter app? Or is the issue specific to the supabase client or server?

**Comment by Wizzel1** [comment]
Apparently this only happens when I try to upload multiple images at the same time to a storage bucket: 

```dart
final futures = imageDataList.map((imageData) async {
   return Supabase.instance.client.storage
          .from('my-images')
          .uploadBinary(
            'my/imagepath/image.png',
            imageData,
            fileOptions: const FileOptions(contentType: 'image/png'),
        );
});
await Future.wait(futures);
```

When I run a for loop it works every time: 

```dart
for (final imageData in imageDataList) {
    await Supabase.instance.client.storage
        .from('my-images')
        .uploadBinary(
          'my/imagepath/image.png',
          imageData,
          fileOptions: const FileOptions(contentType: 'image/png'),
    );
}
```

**Comment by Vinzent03** [comment]
I don't have a mac device, but I can't reproduce your issue with an online supabase project in the client tests:
```dart
final bucketName = 'with-limit-${DateTime.now()}';
await storage.createBucket(bucketName);
final list = List.generate(50, (index) => index);

final futures = list.map((e) => storage.from(bucketName).uploadBinary(
    "$e", file.readAsBytesSync(),
    fileOptions: FileOptions(contentType: 'image/png')));

await Future.wait(futures);
      ```

**Comment by Wizzel1** [comment]
@Vinzent03 Okay thanks for testing this, I will keep an eye out for this error.

**Comment by Wizzel1** [comment]
Couldn't reproduce it so I closed this for now

**Comment by meulencv** [comment]
Hello,
I'm getting the same error Failed host lookup: 'mydbname.supabase.co' error
all at once.
Do you know what it could be? I have an internet connection and have tried different networks.
Thanks

**Comment by Vinzent03** [comment]
@meulencv On which platform? Can you query other websites via `http` package?

**Comment by meulencv** [comment]
Hello,
Right now I get the error on android, it seems to me that on web the error
is not shown.
Yes, the internet works, in fact, the app loads .json files and photos from
the internet.
Also, if I disable the errors breakpoints in the debug, the app works
correctly.

**Comment by MattL-NZ** [comment]
I am also getting this error all of a sudden after upgrading Flutter to version `3.13.0` I have tried on both emulators and real devices. If you push through the exception, it still fetches the results from the database without any issues. I have logged a ticket here but happy to close that if this one is to be reopened. https://github.com/supabase/supabase-flutter/issues/595

**Comment by meulencv** [comment]
I got the error in the same version, I think it's related as you said.

**Comment by chidera-ugonwa** [comment]
I also get this same error, this  mine happens when authenticating a client... it happens on windows, if I push through the exception everything works fine.

**Comment by thefredo1000** [comment]
I do get the same error, I'm on Mac running an app on Android, any updates on this?

**Comment by dshukertjr** [comment]
The cause is most likely not Supabase. Check that you have given internet permission on your app and see if your app can make HTTP requests to other servers.

**Comment by stanislavlysenko0912** [comment]
Anybody still has error? 
I got exception after some request to supabase 🤷‍♂️

**Comment by michelemarchetto** [comment]
Error is still there. My setup is:
Flutter 3.27.4 • channel stable • https://github.com/flutter/flutter.git
Tools • Dart 3.6.2 • DevTools 2.40.3

If this is not going to be addressed/investigated i'm forced to move to another provider.

**Comment by thiagoneves1** [comment]
Error is still there for me too.

**Comment by Vinzent03** [comment]
All of you having this issue. Please ensure that you can access other services like google.com with the `http` package. This won't be an issue with the Supabase platform and probably not an issue with the client library as well.
Remember to allow internet access in the main manifest on android.

**Comment by michelemarchetto** [comment]
I can access the web and everything else using http package without problems.

If could help, i'm experiencing problems during access of private APIs (after authentication). Public APIs do not suffer from this issue.

**Comment by Vinzent03** [comment]
@michelemarchetto Could you share your exact exception please with stacktrace?

**Comment by michelemarchetto** [comment]
@Vinzent03 unfortunately i already moved to firebase. I will try to setup the project again and share the information you need.

**Comment by Vinzent03** [comment]
I honestly don't think that's necessary. Failed to host lookup refers to DNS and resolving an ip address. This is independent of the specific path for the https protocol and whether they need authentication or not.
