### ISSUE TITLE
onAuthStateChange doesn't fire when pressing link from signup

### ISSUE THREAD

**Issue by FerdiHr** [supabase/supabase-flutter#532]
**Describe the bug**
I follow the tutorial https://supabase.com/docs/guides/getting-started/tutorials/with-flutter for the setup. 
I recieved the mail and press the link expect here I dont have any event fire from the listener.
When I'm back in the application the user is validated in the back-office, but still no current session in my app and no event trigger. 

**To Reproduce**
I followed the steps descrided [here](https://supabase.com/docs/guides/getting-started/tutorials/with-flutter)
Here is my initState function: 
```
void initState() {
_authStateSubscription = supabase.auth.onAuthStateChange.listen((data) {
      print('data: $data');
      final session = data.session;
});
    super.initState();
```

**Expected behavior**
From what I understand it should trigger a new event and my user should be connected with a non-null session.

**Screenshots**
I do recieve a intent with everything :
```
D/com.llfbandit.app_links(12213): handleIntent: (Action) android.intent.action.VIEW
D/com.llfbandit.app_links(12213): handleIntent: (Data) domain.com://login-callback/#access_token=abcdef&expires_in=3600&refresh_token=ghij&token_type=bearer&type=signup
```

**Version (please complete the following information):**
On macOS
```
├── supabase_flutter 1.10.6
│   ├── supabase 1.9.5
│   │   ├── functions_client 1.3.2
│   │   ├── gotrue 1.9.0
│   │   ├── postgrest 1.3.2
│   │   ├── realtime_client 1.1.1
│   │   ├── storage_client 1.5.1
```

(And thanks for the amazing job here !  🙏 )

**Comment by Vinzent03** [comment]
Did you edit the `Info.plist` for macos as shown [here](https://github.com/supabase/supabase-flutter#for-mac-os)?

**Comment by FerdiHr** [comment]
Sure, on android too (I'm currently testing on my android phone) the redirection seems to have no issue

**Comment by FerdiHr** [comment]
Yeah created today ! 

The intent url should have a code query ?

**Comment by Vinzent03** [comment]
Please show your `Supabase.initialize()` method. If you are using pkce it should contain a `code` parameter instead of the `access_token` parameter.

**Comment by Vinzent03** [comment]
I thought you were using `signInWithOTP`, because that's used in the tutorial. But you found a bug, because pkce should be implemented for signUp as well. Created the linked pr to fix this.
