### ISSUE TITLE
 column does not exist while using rpc().in_, code: 42703

### ISSUE THREAD

**Issue by ib-8** [supabase/supabase-flutter#538]
**Describe the bug**
I'm trying to fetch restaurant list with sort based on location. I created an sql function to fetch restaurants. It is working fine but when I tried to filter by array contains using rpc().in_ it throws error

**Sql Function**
```sql
create or replace function nearby_restaurants(lat float, long float)
returns setof record
language sql
as $$
  select id, name, products, st_astext(location) as location, st_distance(location, st_point(long, lat)::geography) as dist_meters
  from public.restaurants
  order by location <-> st_point(long, lat)::geography;
$$;
```

Flutter Client:
```dart   
final response = await Supabase.instance.client
       .rpc('nearby_restaurants',
                  params: {
                    'lat': 37.4220656,
                    'long': -122.1201386
                  },
                  options: const FetchOptions(count: CountOption.exact))
              .in_('products', ['juice']);
```

**Error**
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PostgrestException(message: column nearby_restaurants.products does not exist, code: 42703, details: Bad Request, hint: null)

Do I need to make any changes in the sql function or is it a bug from Flutter SDK?

**Comment by Vinzent03** [comment]
I think you have to return a table from reading the [doc](https://postgrest.org/en/stable/references/api/stored_procedures.html#table-valued-functions). 

So replace `returns setof records` with `RETURNS TABLE(f1 int, f2 text)` (use your correct types here instead).

**Comment by ib-8** [comment]
Thanks! closing the issue
