### ISSUE TITLE
Allow for handling non-supabase related deep link /applink urls

### ISSUE THREAD

**Issue by RMcGhee** [supabase/supabase-flutter#541]
**Is your feature request related to a problem? Please describe.**
Currently, the way that supabase handles app links, it automatically figures out if an incoming link is related to an auth changes, and updates the auth state accordingly, which is great. However, I have a need to also handle other kinds of links in my app, and doing so with uni_links or uni_links_desktop breaks the supabase url handling flow, where uni_links_desktop will catch the url instead of supabase, and auth state is no longer updated. I'd like to be able to handle the following:
supabase auth links, like signing in via a magic link email
supabase reset-password link: com.mycompany.myapp://reset-password < supabase currently does a reset password workflow, but when this link is clicked from a user's email, Supabase-flutter signs the user in, and doesn't expose the url to the app, as far as I can tell.
custom url scheme: com.mycompany.myapp://share/some-share-id

**Describe the solution you'd like**
If supabase could expose a stream to the uriLinkStream, or expose a stream that allows us to handle links that supabase doesn't do anything with, that would be ideal. AFAICT, in supabase_auth._handleDeepLink(), after checking _isAuthCallbackDeeplink(uri) if the link isn't a supabase auth link, it simply returns without doing anything. If instead, it could emit the url to another stream, or just emit all urls received to a stream (to handle the reset-password case mentioned above), that would be great.

**Describe alternatives you've considered**
I initially started trying to handle the deepLinks myself, and then using Supabase.instance.client.auth.getSessionFromUrl(uri), but linking on desktop vs mobile is different enough that I encountered unexpected problems. Primarily, on macOS, you can preempt the deep link handler that supabase uses with uni_links_desktop, but on android/iOS, I wasn't able to get preemption working. I'm sure I could get this working eventually, but I feel like the solution would be fairly fragile, since uni_links_desktop is beta, and I'm not sure if preemption would be stable on different versions of the same OS.

**Additional context**
Love y'alls product, it's been a blast working with supabase!

**Comment by Vinzent03** [comment]
So you listened to the `linkStream`, but it didn't emit any events? Did the initial link method return `null` as well?

**Comment by RMcGhee** [comment]
Correct, if I set up my own instance of AppLinks, and listen to the uriLinkStream, no events are received. As well, getInitialAppLink returns null, but that's expected since these are links that come in when the app has been running already.
Supabase still handles urls properly in this case.

**Comment by Vinzent03** [comment]
I thought you are using `uni_links`? The method you mentioned now are from `app_links`.

**Comment by RMcGhee** [comment]
Correct, I did try uni_links, but due to the beta status, and different handling on different platforms (uni_links_desktop is a different package from uni_links), I decided to try using AppLinks instead, since I believe it's using a broadcast stream, and should allow multiple listeners. Trying that, however, also didn't work.

**Comment by Vinzent03** [comment]
Where are you listening to the stream? I think it has to be after `runApp()`. So best somewhere in your widget tree. I have no issues to add my own listener that way.

**Comment by RMcGhee** [comment]
In one of my pages, which is built after runApp is called. I've tried working on this a few different ways, but if it's just a problem in my app, then I suppose it's not really a feature to request for the library.

**Comment by dshukertjr** [comment]
Closing with this PR merged
https://github.com/supabase/supabase-flutter/pull/848

**Comment by proformance** [comment]
Reference: https://github.com/supabase/supabase-flutter/pull/605#issuecomment-2267171726

I tried to solve it here https://github.com/llfbandit/app_links/pull/145, let's hope it gets merged

**Comment by proformance** [comment]
It's now available in [6.2.0](https://pub.dev/packages/app_links/changelog) 🎉
