### ISSUE TITLE
Enhancement Request: Include User's Full Name in Sign in with Apple in Supabase SDK

### ISSUE THREAD

**Issue by takuya-ohmuro** [supabase/supabase-flutter#545]
Is your feature request related to a problem? Please describe.
Yes, the current implementation of Sign in with Apple in the Supabase SDK does not retrieve the user's full name during the authentication process. This presents a problem as per Apple's App Store Review Guidelines, which stipulate that applications using Sign in with Apple must retrieve the user's full name during account creation, in addition to the email.

Describe the solution you'd like
I would like the Supabase SDK to be updated to include the retrieval of the user's full name during the Sign in with Apple authentication process. This data is available in the Apple ID and should be returned alongside the email.

Describe alternatives you've considered
An alternative would be to ask the user to manually input their full name during the account creation process. However, this is not ideal as it goes against the streamlined user experience that Sign in with Apple aims to provide.

Additional context
This enhancement is crucial for any developers wanting to comply with Apple's guidelines while offering a seamless sign-in experience to their users. It would be a much-appreciated addition to the Supabase SDK's feature set.

**Comment by dshukertjr** [comment]
@takuya-ohmuro 
Currently, Supabase does request for email and full name scope when performing Apple sign in. You can retrieve the full name like this:

```dart
final response = await supabase.auth.signInWithApple();
print(response.user?.userMetadata?['full_name']);
```

**Comment by takuya-ohmuro** [comment]
@dshukertjr 
Thank you for your response. However, it seems that I'm unable to retrieve the full_name during account creation. Is there any particular setup needed for this? I have been trying this with a new setup, after deleting the authentication from Apple Signin.

 The version of Supabase I'm using is 1.10.8.
