### ISSUE TITLE
Provide a delete user method

### ISSUE THREAD

**Issue by Ben1980** [supabase/supabase-flutter#546]
I'm missing a function to delete a user from within flutter. The user of my iOS app needs to be able to delete their account as this is a requirement of apple.

Might it make sense if I try to provide a PR or should I go with a procedure?

**Comment by dshukertjr** [comment]
@Ben1980 
There is a [deleteUser](https://github.com/supabase/supabase-flutter/blob/main/packages/gotrue/lib/src/gotrue_admin_api.dart#L73) method that you can call from your server. Supabase auth currently requires service role for the delete user endpoint to be called, so this method has to be called from your server using the service role key.
