### ISSUE TITLE
could not find array type for data type text[] : 42704

### ISSUE THREAD

**Issue by ib-8** [supabase/supabase-flutter#552]
**Describe the bug**
Querying based on any value in a given array contains in a column of text[].  select().in_() method throws exception

**Flutter Client**
  var result = await Supabase.instance.client
        .from('my_table')
        .select()
        .in_('my_column', ['value']);

**Exception**
PostgrestException (PostgrestException(message: could not find array type for data type text[], code: 42704, details: Bad Request, hint: null))

**Comment by Vinzent03** [comment]
Please share the type of your column. I guess it's `text[]`. That's not how the [in operator ](https://www.postgresql.org/docs/current/functions-comparisons.html#FUNCTIONS-COMPARISONS-IN-SCALAR)works. The column needs to be of type `text`.

I guess you are searching for `@>`, but take a look at the [list of array operators](https://www.postgresql.org/docs/current/functions-array.html) and the conversion of these [operators to postgrest](https://postgrest.org/en/stable/references/api/tables_views.html#operators)

**Comment by ib-8** [comment]
Yes, the type is text[]. Sorry, I'm new to the sql/supabase world. 
Closing the issue.
Thanks

**Comment by ib-8** [comment]
`query.in()` is used to query for the "text" data type not "text[]". 
For my use case, I used `query.contains('fruits', [apple, grape]);`

Reference: https://supabase.com/docs/reference/dart/contains
