### ISSUE TITLE
flutter_appauth causing MacOS client unable to receive Google Sign In Deep Link

### ISSUE THREAD

**Issue by oliverbytes** [supabase/supabase-flutter#554]
**Describe the bug**
I'm happy to read that native Google sign-in is now here. Unfortunately, it only works on all platforms but MacOS. I can confirm that when you add the `flutter_appauth` package it makes a conflict—resulting in deep links not getting received by the macOS client.

**To Reproduce**
1. Using the latest supabase package version
2. Make sure you've implemented all instructions
3. Sign in to Google

**Expected behavior**
The macOS client should receive the deep link and continue authentication.

**Version (please complete the following information):**
On Linux/macOS

```
├── supabase_auth_ui 0.2.1
│   └── supabase_flutter...
├── supabase_flutter 1.10.9
│   ├── supabase 1.9.7
│   │   ├── functions_client 1.3.2
│   │   ├── gotrue 1.11.0
│   │   ├── postgrest 1.3.3
│   │   ├── realtime_client 1.1.1
│   │   ├── storage_client 1.5.1
```

**Additional context**
None

**Comment by dshukertjr** [comment]
@oliverbytes 
Could you share more detailed step by step instructions on how one could reproduce the issue you are experiencing?

**Comment by romaingyh** [comment]
> @oliverbytes Could you share more detailed step by step instructions on how one could reproduce the issue you are experiencing?

I confirm the issue. `uriLinkStream` events from `app_links` are not fired on macos when `flutter_appauth` is in depencies. Here is the simplest way to illustrate:

```bash
flutter create --platforms=ios,macos deeplinks
cd deeplinks 
flutter pub add app_links flutter_appauth
```

Open ios/Runner/Info.plist and macos/Runner/Info.plist and add this : 
```
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>deeplinkstest</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>deeplinks</string>
			</array>
		</dict>
	</array>
``` 

Inside `lib/main.dart`:

```dart
import 'dart:async';

import 'package:app_links/app_links.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late final StreamSubscription<Uri> _linkSubscription;
  final List<Uri> _links = [];

  @override
  void initState() {
    super.initState();

    _linkSubscription = AppLinks().uriLinkStream.listen((uri) {
      debugPrint('Got uri: $uri');
      setState(() => _links.add(uri));
    });
  }

  @override
  void dispose() {
    super.dispose();
    _linkSubscription.cancel();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: ListView.builder(
        itemCount: _links.length,
        itemBuilder: (context, index) {
          final uri = _links[index];
          return ListTile(
            title: Text(uri.toString()),
          );
        },
      ),
    );
  }
}
```

Now you can run the apps, if you open `deeplinks://test` in the iOS simulator it's handled, but if you click the link on macos nothing happens

**Comment by romaingyh** [comment]
Hello,

Unfortunately it appears that [app_links](https://pub.dev/packages/app_links) and [flutter_appauth](https://pub.dev/packages/flutter_appauth) are strongly incompatible on macos.

They both use `setEventHandler` method from `NSAppleEventManager` and from [Apple Documentation](https://developer.apple.com/documentation/foundation/nsappleeventmanager#overview) :

> Each application has at most one instance of NSAppleEventManager

> If an event handler is already registered for the specified event class and event ID, removes it

I don't know if there is a workaround but it explains the issue now

**Comment by oliverbytes** [comment]
> setEventHandler

Thanks for getting to the root of the problem. So it appears Supabase both uses **app_links** and recommends **flutter_appauth**, which are incompatible. I hope they make a solution to this ASAP.

**Comment by oliverbytes** [comment]
![NexSnap-Sep-21-2023_04-25-32_PM](https://github.com/supabase/supabase-flutter/assets/396366/c57a16d2-b96e-49d7-b94e-97c5fea02a46)
I unknowingly disabled this code for the macOS plugin and voila! Everything works as expected! 😂

**Comment by oliverbytes** [comment]
Temporarily force-upgrading the underlying app_links version below fixes the issue

```
dependency_overrides:
  app_links: ^3.5.0
```
