### ISSUE TITLE
[Question] The re-direct url with dot(.) doesn't work on Windows

### ISSUE THREAD

**Issue by LucasXu0** [supabase/supabase-flutter#556]
**Describe the bug**
Hey there! I followed the guide and set up the redirect URL to `io.xxx.xxx`. However, when I registered this scheme on Windows, it didn't work (although it works perfectly on macOS).

I think it's related to the `app_links` library. I just want to confirm if you have successfully set up the scheme on Windows before?

~~Updated: `io-xxx-xxx` works perfectly on Windows too.~~

**Comment by LucasXu0** [comment]
Hi, @dshukertjr. Can you help confirm that?

**Comment by dshukertjr** [comment]
Hi @LucasXu0 

No I have never set up deep links for Windows, and I don't think anyone working on this library has. We definitely should take some time to try it out, but unfortunately were blocked due too other tasks. 

Reading thought your issue on app_link, I can see that you know this, but the scheme can be anything you would like, so you don't necessary have to include `io.supabase` like the docs says. 

I'm going to close this issue as I can see that you have opened an issue on app_link repo.  https://github.com/llfbandit/app_links/issues/69
