### ISSUE TITLE
Flutter documentation for setting up different auth solutions

### ISSUE THREAD

**Issue by RobertBrunhage** [supabase/supabase-flutter#56]
# Improve documentation

## Link 

https://supabase.com/docs/guides/with-flutter

## Describe the problem

In the documentation, it's explained to use `AuthState` which becomes quite tedious and not very straightforward. Comparing this to Firebase equivalent https://firebase.flutter.dev/docs/auth/usage which is super straightforward and can be implemented with any kind of architecture.

For example, if you are using `Riverpod` you don't have `StatefulWidget` or `StatelessWidget` making the current documentation a pain to follow.

## Describe the improvement

A section for only the code-related parts similar to how Firebase does it. I would like to go to "Flutter" -> "Auth" and then see the documentation for how to set up auth.

## Additional context

I will link the FlutterFire documentation because that is super easy to follow even if you are using different architectures etc
https://firebase.flutter.dev/docs/auth/usage

**Comment by MisterJimson** [comment]
I agree. I think the user-management-starter example and documentation should stay away from getting into state management. There are so many ways to manage state and needing to use a State subclass clashes with most of them.

**Comment by MisterJimson** [comment]
If someone from the Supabase team confirms we want this change in the getting started docs, I can PR a revision of that guide.

**Comment by phamhieu** [comment]
Great idea 👍👍👍 

i'm looking forward to your PR @MisterJimson

**Comment by Vinzent03** [comment]
We don't use `AuthState` anymore, so this is outdated.
