### ISSUE TITLE
Upsert with primary key null should insert data rather than throwing error

### ISSUE THREAD

**Issue by sahalMoidu** [supabase/supabase-flutter#574]
**Is your feature request related to a problem? Please describe.**
Ex. I'm always frustrated when [...]
Upserting with id column set to null throws an error
Exception has occurred.
```
PostgrestException (PostgrestException(message: null value in column "id" of relation "object_table" violates not-null constraint, code: 23502,)
```

**Describe the solution you'd like**
The SDK should perform insert operation when primary key is set to null or does not conflict (in case of  id not generated by db)

**Comment by dshukertjr** [comment]
@sahalMoidu 
This behavior is intended as some columns are nullable and the SDK should be able to insert `null` as values when performing upsert or insert operation. 

What you can do instead is to only pass the primary key to the data when the value is not null.
```dart
final String? myId = 'some primary key value';
final data = {
  if(myId != null) 'id': myId,
  'other_columns': 'foo',
};
await supabase.from('my_table').upsert(data);
```

**Comment by sahalMoidu** [comment]
@dshukertjr 
I understand that the sdk should be able to insert null values to nullable fields. 

My request was regarding primary key and primary key usually are non nullable. 

The same way the sdk considers primary key when onConflict is mentioned,would be helpful if null primary inserts the record

**Comment by dshukertjr** [comment]
@sahalMoidu 
The SDK will not handle this as the SDK is not aware of which column is the primary key. You can open an request on [Postgrest](https://github.com/PostgREST/postgrest) repo for feature requests on the API.

**Comment by steve-chavez** [comment]
> in case of id not generated by db
> I understand that the sdk should be able to insert null values to nullable fields.

If you want PostgREST/PostgreSQL to generate ids then you must omit `null` values.

Converting an **explicit `null`** to a generated value is not planned. PostgREST relies on PostgreSQL to keep the data integrity. It aims to be transparent to PostgreSQL.

That being said, if you really want to convert a `null` to a generated value you can do so via triggers. There's a snippet on https://github.com/supabase/postgrest-js/issues/173#issuecomment-825124550.
