### ISSUE TITLE
ChannelEvents not exposed by `supabase_flutter`

### ISSUE THREAD

**Issue by christinachimi** [supabase/supabase-flutter#582]
**Describe the bug**
The `ChannelEvents` enum from the `realtime_events` package doesn't seem to be exported by `supabase_flutter`.

**To Reproduce**
1. Import `supabase_flutter` into a local module.
2. Write some code to send a message.
3. The `push` method takes as its first argument a `ChannelEvents` typed variable, which I can't create, at least not easily.

**Expected behavior**
The necessary type would be exported by the package.

**Version (please complete the following information):**

chat_supabase 0.0.1
├── realtime_client 1.1.3
└── supabase_flutter 1.10.11
    ├── supabase 1.9.9
    │   ├── functions_client 1.3.2
    │   ├── gotrue 1.11.2
    │   ├── postgrest 1.4.0
    │   ├── realtime_client...
    │   ├── storage_client 1.5.1

**Additional context**
Workaround is to import 

```
import 'package:realtime_client/src/constants.dart' show ChannelEvents;
```

which the linter doesn't like but is allowed.

**Comment by Vinzent03** [comment]
I see that documentation is missing, but I don't think you need the `push()` method. Instead, you should use `send()` to send broadcast messages like [shown here](https://supabase.com/docs/guides/realtime/broadcast).

**Comment by christinachimi** [comment]
Ok, that's helpful. It wasn't clear that the NodeJS api was relevant, so I
was relying on the documentation which didn't distinguish between them. I
will switch.

**Comment by dshukertjr** [comment]
@christinachimi Which documentation were you referring to? It would be great for us to fix it.
