### ISSUE TITLE
Supabase Realtime stream cancel and initialize again

### ISSUE THREAD

**Issue by iampopal** [supabase/supabase-flutter#585]
**Describe the bug**

We are using Supabase realtime for a chat app, and we are facing an unusual behavior with stream and channels  1) We have a global cubit that listens to room status name RoomStatusCubit 
This RoomStatusCubit is initialized by listening to the room_status table:

```
initStream() {
  var realstream = from('room_status')
      .stream(primaryKey: ['id'])
      .eq('to_uid', supabase.uid)
      .order('at');
  var subscription = realStream!.listen(
    (event) {
      log('realtime 0 listen event: $event');
      emit(
        state.copyWith(
          rooms: RoomStatus.listFrom(event),
          status: RealtimeStatus.result,
        ),
      );
    },
    onError: (e, s) {
      log('realtime 1 error: $e \ns:$s');
      if (e.toString() == '' || e.toString() == '{}') return;
      emit(state.copyWith(status: RealtimeStatus.error, error: e));
    },
  );
}
```

The above cubit has worked well for a while but has an issue when  
1) the internet disconnects and reconnects  
2) when for a long time there is no internet
 3) when an error happens  
 
 To solve our above issue we have decided to close current channel and reinitalize stream   
 
```

Future cancelStream() async {
    try {
      await subscription?.cancel();
      subscription = null;
    } catch (e, s) {
      subscription = null;
      loges(e, s, type: 'realtime cancelStream');
    }
  }

  List<RealtimeChannel> get roomStatusChannels => supabase
      .getChannels()
      .where((e) => e.topic.contains('room_status'))
      .toList();

  Future cancelChannel() async {
    for (RealtimeChannel c in roomStatusChannels) {
      log('realtime cancel topic ${c.topic}');
      await supabase.removeChannel(c);
    }

    await cancelStream();
  }
```
  
The issue is when we call cancelChannel() and then initStream() the stream is not working anyway.   currently, we need to restart our app to solve this issue and we need a better solution for restarting superbase realtime channel to work correctly so users do not close and open their app. 

**To Reproduce**
1) Create an app with realtime stream in a cubit
2) Try to cancelChannel() and initStream()

**Expected behavior**
Allow us to cancel a realtime stream and init stream again without any error and stream shall work like restarting an app

**Version (please complete the following information):**
On Linux/macOS
Please run `dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"` in your project directory and paste the output here.
│   └── supabase 1.10.0
│       ├── functions_client 1.3.2
│       ├── gotrue 1.11.2
│       ├── postgrest 1.5.0
│       ├── realtime_client 1.1.3
│       ├── storage_client 1.5.1
├── supabase_flutter 1.10.12
│   ├── supabase...

**Additional context**
We sometime also see  `heartbeat timeout` issue and not understand how this is related
and sometime see `Bad state: Cannot add event after closing` error event or cubit is not closed and working correctly

**Comment by iampopal** [comment]
We are also getting an empty error while listening to the stream
in the following error-> there is no error
and stock-> is the stocktrace of error.
```
[log] error->  
stock->:#0      SupabaseStreamBuilder._addException
package:supabase/src/supabase_stream_builder.dart:442
#1      SupabaseStreamBuilder._getStreamData.<anonymous closure>
package:supabase/src/supabase_stream_builder.dart:348
#2      RealtimeChannel.subscribe.<anonymous closure>
package:realtime_client/src/realtime_channel.dart:202
#3      RealtimeChannel.onError.<anonymous closure>
package:realtime_client/src/realtime_channel.dart:331
#4      RealtimeChannel.trigger
package:realtime_client/src/realtime_channel.dart:569
#5      RealtimeClient._triggerChanError
package:realtime_client/src/realtime_client.dart:408
#6      RealtimeClient._onConnClose
package:realtime_client/src/realtime_client.dart:389
#7      RealtimeClient.connect.<anonymous closure>
package:realtime_client/src/realtime_client.dart:147
#8      _RootZone.runGuarded (dart:async/zone.dart:1581:10)
#9      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
```

**Comment by maxfornacon** [comment]
Your error 2 seems to be similar to the issue I descibed in #579. Could be related.

**Comment by iampopal** [comment]
> Your error 2 seems to be similar to the issue I descibed in #579. Could be related.

Yea, looking like #579 is related to this, and we need to cancel the stream and reinitialize its feature.

**Comment by iampopal** [comment]
How's the progress of this going? we need to be able to close and re-initialize streams because the internet may come and go.

**Comment by Vinzent03** [comment]
With #1019 being merged now, these issues should be solved now. You can try it by upgrading `supabase_flutter` to `2.7.0`. If you still experience any issues, please **create a new issue**.
