### ISSUE TITLE
Public Anon key cannot read realtime data

### ISSUE THREAD

**Issue by ClarissaGazalaEvanthe** [supabase/supabase-flutter#587]
I tried using the public anon key but can't read realtime updates how can I do that

**Comment by Yogesh-Dubey-Ayesavi** [comment]
What's the error you are getting?  Ensure that you have enabled realtime for your messages table from the supabase dasboard secondly you can check whether RLS is enabled on your project or not

**Comment by Yogesh-Dubey-Ayesavi** [comment]
> ![Screenshot from 2023-08-13 02-01-08](https://github.com/supabase/supabase-flutter/assets/84509715/ec0e09db-31c5-4a02-afba-06e186278307)
> 

Have you tried disabling rls?

**Comment by Yogesh-Dubey-Ayesavi** [comment]
Use Supabase.inatance.client instead of realtime client
