### ISSUE TITLE
Update build.gradle to add support for Android Gradle Plugin 8

### ISSUE THREAD

**Issue by DanMossa** [supabase/supabase-flutter#590]
Unable to build app due to the current app_links version dependency not supporting AGP 8.
This is fixed in the latest app_links.
https://github.com/llfbandit/app_links/commit/181fdcc4ca08489f01328adb253752e50b2d2ec6

**Comment by dshukertjr** [comment]
I'm going to close this issue due to reasons outlined here
https://github.com/supabase/supabase-flutter/pull/591#issuecomment-1677923031
