### ISSUE TITLE
Failed host lookup after updating to Flutter version 3.13.0

### ISSUE THREAD

**Issue by MattL-NZ** [supabase/supabase-flutter#595]
**Describe the bug**
I'm not sure if this is related directly to Supabase or Flutter itself but since upgrading to version `3.13.0`, I am now experiencing a handshake/socket issue trying to connect to my Supabase database.

**To Reproduce**
1. Make sure you are on Flutter version 3.13.0'
2. Initiailse Supabase
```
Future<void> main() async {

  // Initialise supabase
  WidgetsFlutterBinding.ensureInitialized();
  await Supabase.initialize(
      url: 'https:/xxxxxxxx.supabase.co',
      anonKey: 'xxxxxxxxxxx');

  runApp(const ProviderScope(child: MyApp()));
}
```
3. Try to access data from your database
```
class Test extends AsyncNotifier<List<TestModel>> {
  @override
  Future<List<TestModel>> build() async {
    return getTest();
  }

  Future<List<TestModel>> getTest() async {
    final response = await Supabase.instance.client.from('test').select().order('id', ascending: true);
    return (response as List<dynamic>).map((map) => TestModel.fromMap(map)).toList();
  }
}
```
4. Thows unhandled exception on "Failed host lookup:  xxxxxx.supabase.co" 
![image](https://github.com/supabase/supabase-flutter/assets/2846782/a83b35d0-06d7-4ad2-8a3f-02f59afaf875)

If you push through the exception, everything still works as expected and the results still manage to come through.

Downgrading Flutter to version 3.10.6 seems to resolve the issue.

**Comment by dshukertjr** [comment]
It seems like this is a Flutter issue 
https://github.com/flutter/flutter/issues/132840

**Comment by MattL-NZ** [comment]
Thanks, happy to close and track the issue over with #132840

**Comment by dshukertjr** [comment]
I'm going to close this issue as it seems like a Flutter issue.
