### ISSUE TITLE
Can't run Flutter web

### ISSUE THREAD

**Issue by hesty98** [supabase/supabase-flutter#602]
Hi!
I am using 1.10.14. Somehow my Flutter App won't even build for Chrome. Building for MacOs works just fine.

Getting following error in AppLinksPluginWeb:
../../../../../.pub-cache/hosted/pub.dev/app_links-3.4.3/lib/src/app_links_web.dart:11:24: Error: Undefined name 'window'.
  final _initialLink = window.location.href;

Is this my error or simply broken?
Cheers, 
Linus

EDIT: Maybe a bug for the app_links team?

**Comment by Vinzent03** [comment]
Have you edited that file? It should be available by the `dart:html` import in that file. But yeah that's more an issue from that package.

**Comment by bdlukaa** [comment]
What flutter/dart version are you using? Please post the output of `flutter doctor -v`

**Comment by hesty98** [comment]
Vincent was correct - idk how I deleted the line since Android Studio still asked me if I want to edit the file.

But it works now. Thank you! :)
