### ISSUE TITLE
await on signInWithOtp() does not return when exception occurs in flutter

### ISSUE THREAD

**Issue by MrudulAddipalli** [supabase/supabase-flutter#607]
**Describe the bug**
await on signInWithOtp() does not return when exception occurs in flutter

**Expected behavior**
function should return when error occurs
o0r should get caught in try catch

**Version (please complete the following information):**

Flutter Version - 3.13
supabase_flutter: ^1.10.14
Please run `dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"`
└── supabase_flutter 1.10.14
    ├── supabase 1.11.1
    │   ├── functions_client 1.3.2
    │   ├── gotrue 1.11.2
    │   ├── postgrest 1.5.0
    │   ├── realtime_client 1.2.1
    │   ├── storage_client 1.5.1

**Comment by Vinzent03** [comment]
What exceptions are you talking about?
