### ISSUE TITLE
Duplicate Error When Attempting to Delete File in Bucket

### ISSUE THREAD

**Issue by garysm** [supabase/supabase-flutter#609]
**Describe the bug**
I am attempting to remove a single file from a folder with the user's id (12345/example.png).  I have the following policies present for authenticated users:

```sql
create policy "Users can read their own files in a folder with their uid"
on storage.objects for select using (
  bucket_id = 'files'
  and auth.uid()::text = (storage.foldername(name))[1]
  and auth.role() = 'authenticated'
);

create policy "Users can insert their own files in a folder with their uid"
on storage.objects for insert with check (
  bucket_id = 'files'
  and auth.uid()::text = (storage.foldername(name))[1]
  and auth.role() = 'authenticated'
);

create policy "Users can update their own files in a folder with their uid"
on storage.objects for update using (
  bucket_id = 'files'
  and auth.uid()::text = (storage.foldername(name))[1]
  and auth.role() = 'authenticated'
);

create policy "Users can delete their own files in a folder with their uid"
on storage.objects for delete using (
  bucket_id = 'files'
  and auth.uid()::text = (storage.foldername(name))[1]
  and auth.role() = 'authenticated'
);
```
I've verified that the other statements work, as users are able to insert the files themselves.

When I run the code to delete the file,

```dart
final uid = supabase.auth.currentUser?.id;
if (uid != null) {
  final String filePath = '$uid/$fileName';
  await supabase.storage.from('files').remove([filePath]);
}
```

I get the following error: `Error: StorageException(message: The resource already exists, statusCode: 409, error: Duplicate)`

The only other thing that I have done with Storage is to trigger several functions whenever a file is created/updated/deleted, but these are all executed after the fact, so I don't believe that this would affect the Flutter client.

**To Reproduce**
1. Create appropriate policies on `storage.objects`
2. Run Flutter/Dart code
3. See error

**Expected behavior**
File is deleted successfully from Storage.

**Version:**
dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"
└── supabase_flutter 1.10.14
    ├── supabase 1.11.1
    │   ├── functions_client 1.3.2
    │   ├── gotrue 1.11.2
    │   ├── postgrest 1.5.0
    │   ├── realtime_client 1.2.1
    │   ├── storage_client 1.5.1

**Additional context**

**Comment by Vinzent03** [comment]
Do the trigger insert new files? I think all triggers are in fact bundled in a transaction and when one fails, everything fails and you get the error on the client.

**Comment by garysm** [comment]
> Do the trigger insert new files? I think all triggers are in fact bundled in a transaction and when one fails, everything fails and you get the error on the client.

Interesting, I wasn't aware of that behavior. I can try without those triggers and see what happens.

**Comment by garysm** [comment]
After removing each trigger the issue still remains on the client.  I also removed the built-in `update_objects_updated_at` trigger to test.

**Comment by garysm** [comment]
After some more digging, I believe the issue was that there was a foreign key present in one of my other tables.  I was able to successfully delete the file from the Supabase dashboard after adjusting the trigger to fire _before_ the delete and remove the appropriate rows in the other table, but it doesn't seem to do so when attempting to delete from the Flutter client.  I still get the following error:

"update or delete on table "objects" violates foreign key constraint "files_id_fkey" on table "files""

**Comment by Vinzent03** [comment]
Since we don't know your table definitions and trigger, we can't really help here. But I'm pretty sure it's no issue with the client itself. You are saying it's working from the dashboard, but not from the client? Maybe your RLS doesn't allow some other deletions, which produce that key constraint error
