### ISSUE TITLE
I don't know whether its only me facing this issue but supabase.auth is showing errors it is well imported and the dependance is add, but auth requires me to create a greater variable i don't understand this, its my first time to use supabase and am looking  to start working with it.

### ISSUE THREAD

**Issue by kasujjabash** [supabase/supabase-flutter#612]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
On Linux/macOS
Please run `dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"` in your project directory and paste the output here.

On Windows
Please run `dart pub deps | findstr "supabase gotrue postgrest storage_client realtime_client functions_client"` in your project directory and paste the output here.

**Additional context**

**Comment by Vinzent03** [comment]
Please use the issue body for the issue description and find a concise description for the title. Please show what exact error you are facing with code example, etc.

**Comment by dshukertjr** [comment]
I'm going to close this issue for now. If you are still facing the same issue, please follow the issue template the provide the necessary information.
