### ISSUE TITLE
FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by otopba** [supabase/supabase-flutter#614]
**Describe the bug**
If the Edge Function completes its execution due to a timeout, we receive a JSON parsing error. Although, it would be more logical to receive a timeout error

**To Reproduce**
1) Write a function that will run for a very long time.
2) Call this function in a Flutter application.
3) Expect an error.

**Expected behavior**
It would be correct to receive a timeout error

**Screenshots**
<img width="947" alt="Screenshot 2023-09-04 at 11 10 36" src="https://github.com/supabase/supabase-flutter/assets/4225279/429e9429-763e-4a94-9151-0704c6172760">
<img width="1406" alt="Screenshot 2023-09-04 at 11 10 50" src="https://github.com/supabase/supabase-flutter/assets/4225279/7ef94c2c-47a1-4a1a-bd7c-14e93d31b775">

**Version (please complete the following information):**
├── supabase_flutter 1.10.14
│   ├── supabase 1.11.1
│   │   ├── functions_client 1.3.2
│   │   ├── gotrue 1.11.2
│   │   ├── postgrest 1.5.0
│   │   ├── realtime_client 1.2.1
│   │   ├── storage_client 1.5.1

**Comment by Vinzent03** [comment]
The best fix for this issue needs some breaking changes, which will come in v2. For now, I suggest you to wrap it in a try catch and handle the error yourself.

**Comment by Vinzent03** [comment]
This is now fixed with v2 #673
