### ISSUE TITLE
Google OAuth login hangs with unresponsive "Sign in with Google" pop up form

### ISSUE THREAD

**Issue by davoutuk** [supabase/supabase-flutter#621]
I have a Flutter web app that is using Supabase authentication via this package.

The email/password authentication route is working fine, and I am now trying to add support for Google OAuth authentication. I've setup the client ID's and secret in Supabase, and the redirect API's in GCP.

However, when I run the following code....

 ```
 Future<bool> loginGoogle() async {
    try {
      final aResponse = await Supabase.instance.client.auth.signInWithOAuth(Provider.google);
      return true;
    } catch (e) {
      return false;
    }
  }
```

... the 'Sign in with Google' pop up forms appears, but I cannot type anything into the 'Email or phone' text control. In fact all the controls on the Google pop up form are unresponsive.

![image](https://github.com/supabase/supabase-flutter/assets/25985256/6cf840d5-ee12-4d25-82ab-c840929a9bf3)

Any suggestions On what is going wrong?

**Comment by Laybackup** [comment]
Hello! Have you ever encountered and successfully resolved this issue? I'm facing a similar problem and would appreciate your insights or guidance.

**Comment by davoutuk** [comment]
I did.   The problem is caused by the fact that Google OAuth only works with production code releases.    In my case its a Flutter web app,  where if I run it from the IDE the Google login always fails.  If I build the webapp using 'flutter build web' and then deploy it to my server then the Google login works fin.

**Comment by livtanong** [comment]
@davoutuk If it's only for use in production, then how were you able to develop? Also, if this is known behavior, perhaps it should be added to documentation, in which case we should alert the maintainers of this.
