### ISSUE TITLE
Upserting into tables with constraints expects 1 positional argument

### ISSUE THREAD

**Issue by livekeen** [supabase/supabase-flutter#623]
## Describe the bug

Android Studio does not allow this exact script to run with two arguments:
await supabase.from('submitted_prices').upsert({ 'username': 'supabot' }, { 'onConflict': 'username' });

## To Reproduce

- Write an insert: for example `await supabase.from('submitted_prices').insert( 'username': 'supabot' );`
- Replace insert with an upsert with constraints: for example `await supabase.from('submitted_prices').upsert({ 'username': 'supabot' }, { 'onConflict': 'username' });`

## Expected behavior

To run, and post data—overwriting if 'username' matches a pre-existing `username` in supabase table.

## System information

- OS: macOS
- Browser: Chrome
- Flutter (supabase-flutter): 1.10.14

**Comment by maxfornacon** [comment]
Try using one Map for your data as a single argument like this:

```
await supabase.from('submitted_prices')
   .upsert({ 
     'username': 'supabot',  
     'onConflict': 'username' 
   });
```

**Comment by maxfornacon** [comment]
I think the docs are wrong or outdated:

Try this:
```
await supabase.from('submitted_prices').upsert({ 'username': 'supabot' }, onConflict: 'username' });
```

**Comment by dshukertjr** [comment]
Yup, this is a typo in the docs. Thanks for finding it. You can fix it by editing this file, but would any one like to contribute?
https://github.com/supabase/supabase/blob/master/spec/supabase_dart_v1.yml#L995
