### ISSUE TITLE
PostgREST Dart Client - new payload in _getStreamData on 'UPDATE' missing column

### ISSUE THREAD

**Issue by MelbourneDeveloper** [supabase/supabase-flutter#627]
* PostgreSQL version: PostgreSQL 15.1 (Ubuntu 15.1-1.pgdg20.04+1) on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
* PostgREST version: 1.5
* Operating system: macOS

## Issue One - Missing Column (resume)
Supabase seems to limit one of the columns in the payload of incoming websocket calls. This is probably just a quote issue, however, I'm not seeing any error logs on the back-end or through the websocket client.

If I send an UPDATE (PATCH) to the server for the `resume` column, the record appears in the payload via the websocket, and the record column (quite large) is in the payload. If I send an UPDATE for a different column, a similar payload appears, but the `resume` column is missing, perhaps because of a [quota issue](https://supabase.com/docs/guides/realtime/quotas).  

The problem is that I don't see anything in the back-end logs, and I don't see anything in the websocket payload

Server logs
<img width="1109" alt="image" src="https://github.com/supabase/supabase-flutter/assets/16697547/bbb85e0e-b36e-4d29-9bec-bda4721aae15">

Incoming Websocket Payloads
You can see here that it has removed the `resume` column.
```JSON
{
    "data": {
        "columns": [
            {
                "name": "id",
                "type": "varchar"
            },
            {
                "name": "resume",
                "type": "text"
            },
            {
                "name": "embedding",
                "type": "vector"
            },
            {
                "name": "minsalaryperday",
                "type": "int4"
            },
            {
                "name": "minsalaryperyear",
                "type": "int4"
            },
            {
                "name": "locationtext",
                "type": "varchar"
            },
            {
                "name": "location",
                "type": "geography"
            },
            {
                "name": "preferredworktypes",
                "type": "_text"
            },
            {
                "name": "preferredcommutetypes",
                "type": "_text"
            }
        ],
        "commit_timestamp": "2023-09-16T20:58:03.554Z",
        "errors": null,
        "old_record": {
            "id": "c315090a-0cca-4f07-adfa-78c6fe433f2a"
        },
        "record": {
            "embedding": null,
            "id": "c315090a-0cca-4f07-adfa-78c6fe433f2a",
            "location": "0101000020E61000004703780B24E842C0789CA223B9844140",
            "locationtext": "Melbourne",
            "minsalaryperday": 156,
            "minsalaryperyear": 1003,
            "preferredcommutetypes": [
                "remote"
            ],
            "preferredworktypes": [
                "contract"
            ]
        },
        "schema": "public",
        "table": "profiles",
        "type": "UPDATE"
    },
    "ids": [
        109688006,
        12391632,
        13182892
    ]
}
```

I am logging the incoming websocket payloads - possibly only the non-errors. But, I don't see anything about quota errors:
<img width="737" alt="image" src="https://github.com/supabase/supabase-flutter/assets/16697547/f6b62e5b-a54f-42e4-8f32-fa1e6ee4069f">

So, the question is how one would see incoming websocket errors... I believe this may be a necessary enhancement for the library. Please read on.

## Issue 2 - Unnecessary Exception
This is probably unrelated, but it's the reason I original started investigating. 

The endpoint returns 204 with an empty body, but the code tries to parse the response.

<img width="1005" alt="image" src="https://github.com/isoos/postgresql-dart/assets/16697547/590ed6c1-f791-4b64-b80a-31252200fc61">

This is a problem with the `_parseResponse` method. It is trying to decode an empty body. This gets caught and handled, but it breaks the execution flow of the debugging experience, and this led me to log the bug. I would recommend fixing this one. It is a slight performance hit at least.

## Pull Request Draft - Allow Websocket Payload Logging

This is only a [rough draft PR](https://github.com/supabase/supabase-flutter/pull/628), and far from perfect. The aim here is to add a callback so consumers can see all incoming websocket data. The aim here would be to see the incoming error so the consumer can tell when data has been removed due to quotas or any other reason.

If Supabase is sending a quote error, the would be that we the error here. Please review and let me know what needs to be done to bring this up to the standard for the codebase.

### Historical Information

This bug started out because I noticed and exception. It then evolved because it got a lot more complicated. This is here for a historical log of what happened.

**Edit: this was the problem when I first logged it, but it is not the actual problem. The bug is that when I listen to a stream on the table, the first emitted value is correct, but the second emitted value (after updating the record) is missing a column from the table.** See this [comment](https://github.com/supabase/supabase-flutter/issues/627#issuecomment-1722116928)

**Edit: I just revered to http: ^0.13.6 and the problem is still occurring. This seems to have nothing to do with the `http` package.**
I just upgraded to http ^1.1.0. It looks like it's not compatible with the PostgREST SDK V1.5.0

The endpoint returns 204 with an empty body, but the code tries to parse the response.

<img width="1005" alt="image" src="https://github.com/isoos/postgresql-dart/assets/16697547/590ed6c1-f791-4b64-b80a-31252200fc61">

The problem is happening in `_parseResponse`. You can see that the body is an empty string here.

<img width="1120" alt="image" src="https://github.com/isoos/postgresql-dart/assets/16697547/372dcac1-34d2-48f3-b2f5-bf29ecfc6728">

It was a query for a table with an `eq` on the ID column. The method is `PATCH`. The content length here is actually 0, so it should be hitting a different code path, I would say.

**Comment by MelbourneDeveloper** [comment]
More info. Actually, the exception is getting caught and they the `body` local gets set to null

<img width="761" alt="image" src="https://github.com/supabase/supabase-flutter/assets/16697547/62b3d5ca-3c83-4c55-9fda-29ccd62ba03b">

**Comment by MelbourneDeveloper** [comment]
The bug I am experiencing is this...

I open a stream for the `profiles` table with `from` -> `stream`.

This correctly includes the `resume` column the first time I get data. Later, I update (patch) the record with some unrelated values, and this is where I see the exception above occur. 

Then another value gets emitted on the stream for the table. This time around, the `resume` value is missing from the map, even though it's right there on the record in Supabase.

**Comment by MelbourneDeveloper** [comment]
I've further pinned this down. When I update the table, it triggers the `UPDATE` event to appear on the stream.

The `new` map in `payload` has 8 values instead of 9. It is missing `resume`. This later shows up on the stream and the value is missing.

<img width="810" alt="image" src="https://github.com/supabase/supabase-flutter/assets/16697547/512c4eab-bf5a-4e57-8bdb-37cb2de342da">

**Comment by MelbourneDeveloper** [comment]
Notice that `streamData` does have the resume column, but the `payload` doesn't. So, the question is why the new `payload` is missing the column.

![image](https://github.com/supabase/supabase-flutter/assets/16697547/59bbf79b-87a5-4e51-9d99-061f6f746a3b)

**Comment by MelbourneDeveloper** [comment]
One piece of information is the resume column is a text column and quite long. Perhaps the server is deciding not to send the column to avoid bandwidth use.

**Comment by MelbourneDeveloper** [comment]
This is the `payload` data that arrives in the `trigger` method in the `RealtimeChannel` class. It seems that the incoming JSON is missing the resume column even though the payload explicitly mentions the column. Could supabase be omitting this column accidentally?

```json
{
    "data": {
        "columns": [
            {
                "name": "id",
                "type": "varchar"
            },
            {
                "name": "resume",
                "type": "text"
            },
            {
                "name": "embedding",
                "type": "vector"
            },
            {
                "name": "minsalaryperday",
                "type": "int4"
            },
            {
                "name": "minsalaryperyear",
                "type": "int4"
            },
            {
                "name": "locationtext",
                "type": "varchar"
            },
            {
                "name": "location",
                "type": "geography"
            },
            {
                "name": "preferredworktypes",
                "type": "_text"
            },
            {
                "name": "preferredcommutetypes",
                "type": "_text"
            }
        ],
        "commit_timestamp": "2023-09-16T04:25:21.598Z",
        "errors": null,
        "old_record": {
            "id": "c315090a-0cca-4f07-adfa-78c6fe433f2a"
        },
        "record": {
            "embedding": null,
            "id": "c315090a-0cca-4f07-adfa-78c6fe433f2a",
            "location": "",
            "locationtext": "Melbourne",
            "minsalaryperday": 156,
            "minsalaryperyear": 1003,
            "preferredcommutetypes": [
                "nonMandated"
            ],
            "preferredworktypes": [
                "permanent"
            ]
        },
        "schema": "public",
        "table": "profiles",
        "type": "UPDATE"
    },
    "ids": [
        109688006,
        12391632,
        13182892
    ]
}
```

**Comment by MelbourneDeveloper** [comment]
And when I explicitly update the resume column, it does send the resume column:

```JSON
{
    "data": {
        "columns": [
            {
                "name": "id",
                "type": "varchar"
            },
            {
                "name": "resume",
                "type": "text"
            },
            {
                "name": "embedding",
                "type": "vector"
            },
            {
                "name": "minsalaryperday",
                "type": "int4"
            },
            {
                "name": "minsalaryperyear",
                "type": "int4"
            },
            {
                "name": "locationtext",
                "type": "varchar"
            },
            {
                "name": "location",
                "type": "geography"
            },
            {
                "name": "preferredworktypes",
                "type": "_text"
            },
            {
                "name": "preferredcommutetypes",
                "type": "_text"
            }
        ],
        "commit_timestamp": "2023-09-16T04:31:13.660Z",
        "errors": null,
        "old_record": {
            "id": "c315090a-0cca-4f07-adfa-78c6fe433f2a"
        },
        "record": {
            "embedding": null,
            "id": "c315090a-0cca-4f07-adfa-78c6fe433f2a",
            "location": "",
            "locationtext": "Melbourne",
            "minsalaryperday": 156,
            "minsalaryperyear": 1003,
            "preferredcommutetypes": [
                "hybrid"
            ],
            "preferredworktypes": [
                "contract"
            ],
            "resume": "dfsdfsdf"
        },
        "schema": "public",
        "table": "profiles",
        "type": "UPDATE"
    },
    "ids": [
        109688006,
        12391632,
        13182892
    ]
}
```

Now that I understand more about this, I'm left wondering why Supabase sends the full record at all...

Why doesn't Supabase only send the updated columns? Perhaps I might want to know what the full record is, but I can calculate that myself. I'm really only interested in the changed values and streaming the rest eats bandwidth.

**Comment by MelbourneDeveloper** [comment]
Lastly, I made a change in a couple of libraries to listen to incoming data from Supabase. You can see the changes here:

https://github.com/supabase/supabase-flutter/compare/main...MelbourneDeveloper:supabase-flutter:main

Here is the example usage:

```dart
supabase.client.from(table).stream(
  primaryKey: ['id'],
  onTrigger: (
    type, [
    payload,
    ref,
  ]) {
    final json = jsonEncode(payload);
    // ignore: avoid_print
    print(json);
  },
).eq(column, value);
```

This is the JSON output that gets printed to the console. It's very useful for debugging what is coming in from Supabase

<img width="837" alt="image" src="https://github.com/supabase/supabase-flutter/assets/16697547/b9a16ac5-04c6-44db-b741-f307e1d7898e">

**Comment by MelbourneDeveloper** [comment]
As I said, the resume column is missing in the second payload. The quotas documentation might explain the issue. Let me confirm that.

Lastly, I added a feature in my fork. Take a look at that because I can clean that up for a PR. Let me know if you want me to rename it or change it.
________________________________

**Comment by MelbourneDeveloper** [comment]
The other bug mentioned in the first comment is that the `_parseResponse` method is throwing an exception because it's trying to decode an empty body. This gets caught and handled, but it still causes an exception when debugging that breaks flow of the debugging experience.

**Comment by MelbourneDeveloper** [comment]
@Vinzent03 

> Have you read the [quotas documentation](https://supabase.com/docs/guides/realtime/quotas)?

I suspect that the issue may be quota-related. The payload removes the `resume` column when it is very long, and only on UPDATE calls where I don't update that column.

However, the documentation says I will see the error in the backend logs and the client-side websocket logs. I don't see anything in the server-side logs:

<img width="996" alt="image" src="https://github.com/supabase/supabase-flutter/assets/16697547/5865b496-0799-4036-8d82-0c5fc927644b">

I don't see anything on the client-side web socket logs when I write up to print all the incoming payloads. This is a log of all the incoming payloads. I don't see any errors here:
<img width="734" alt="image" src="https://github.com/supabase/supabase-flutter/assets/16697547/96090c65-6c6a-4df8-b408-8b8e6be73d66">

**Comment by MelbourneDeveloper** [comment]
@Vinzent03 please see the edited issue at the top

**Comment by Vinzent03** [comment]
@w3b6x9 Are you the correct person to be tagged for [the above comment](https://github.com/supabase/supabase-flutter/issues/627#issuecomment-1722312062) ?

Will fix the format exception issue.

**Comment by dshukertjr** [comment]
@MelbourneDeveloper 
Thanks for the detailed issue. My one small ask is to open one GitHub issue per issue instead of including two different issues. That way, we can transfer the issue to other repo that might have more to do with it then this repo. 

For your issue 1 about the missing column, would you be able to open an issue in the [walrus repo](https://github.com/supabase/walrus/issues) providing (if possible) your table schema and how long your `resume` column could be specifically? I think those information would help out the team to find the cause. 

For issue 2, @Vinzent03 has created an [amazing fix for it](https://github.com/supabase/supabase-flutter/pull/631), which we plan to ship in the next 24 hours. 

Lastly about [the question of whether to finalize the exposing raw web socket messages PR or not](https://github.com/supabase/supabase-flutter/issues/627#issuecomment-1722136513), let's discuss anything about it in the PR itself 👍
