### ISSUE TITLE
No way to call supabase rpc function with particular schema.

### ISSUE THREAD

**Issue by preminsubhaprada** [supabase/supabase-flutter#639]
i am trying to call a database with supabase.rpc method. But only when functions are in public schema, i am able to call it. If function is in a custom schema, there is no method to declare schema in supabase.rpc function. Please help

**Comment by Vinzent03** [comment]
You can use the following
```dart
client.useSchema("my_schema").rpc("my_function");
```

**Comment by latifs** [comment]
hey guys,
Does this still work?

**Comment by dshukertjr** [comment]
@latifs 
Yes, but `useSchema()` was renamed to `schema()` in v2. The following should work.

```dart
await supabase.schema("my_schema").rpc("my_function");
```

**Comment by NaftuliSinger** [comment]
In my case (python), I had to divide this into 2 parts, and it worked.

```
supabase.schema("my_schema")
supabase.rpc("my_function").execute()
```

**Comment by OlegBezr** [comment]
@dshukertjr is it this supposed to work with default schemas? Trying to call a function from **storage** schema while running supabase locally - getting this error
```
{
  code: "PGRST106",
  details: null,
  hint: null,
  message: "The schema must be one of the following: public, graphql_public"
}
```

Result of calling `SELECT version();`
`PostgreSQL 15.8 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 13.2.0, 64-bit`

**Comment by NaftuliSinger** [comment]
@OlegBezr That's because you need to add that schema in the "exposed schemas" list in the data API settings. By default, for security reasons, only the public schema is exposed.
