### ISSUE TITLE
Cannot build web app with pure Dart

### ISSUE THREAD

**Issue by kaboc** [supabase/supabase-flutter#641]
**Describe the bug**

Building a web app not using Flutter fails due to the universal_io package that is currently lacking support for web.

**To Reproduce**

1. Create a project with `dart create -t web`.
2. Run `dart pub add supabase` and `dart pub get` to start using the supabase package.
4. Prepare to use Supabase by calling the SupabaseClient constructor.
5. Run the app by `webdev serve`.
6. See the warnings printed in the console.
7. Open `localhost:8080` in a browser.

main.dart should look like this:

```dart
import 'dart:html';

import 'package:supabase/supabase.dart';

void main() {
  SupabaseClient(
    'Your Supabase URL',
    'Your Supabase Key',
  );

  querySelector('#output')?.text = 'Your Dart app is running.';
}
```

**Expected behavior**

There is no warning during a build, and "Your Dart app is running." is shown in the browser.

**Screenshots**

N/A

**Version (please complete the following information):**

```
└── supabase 1.11.5
    ├── functions_client 1.3.2
    ├── gotrue 1.12.2
    ├── postgrest 1.5.1
    ├── realtime_client 1.2.2
    ├── storage_client 1.5.2
```

**Additional context**

```
[WARNING] build_web_compilers:entrypoint on web/main.dart: Skipping compiling bug|web/main.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

universal_io|lib/src/_exports_in_vm.dart
universal_io|lib/src/internet_address.dart
universal_io|lib/src/http_client.dart
```

**Comment by kaboc** [comment]
How about removing the dependency on universal_io to be less subject to external changes if it is not heavily used?

As far as I see,

- gotrue uses `SocketException`
- storage_client uses `SocketException` and `File`

It may be possible to replace `File` with [XFile](https://pub.dev/documentation/cross_file/latest/cross_file/XFile-class.html).

**Comment by kaboc** [comment]
Related issue: https://github.com/dint-dev/universal_io/issues/41

**Comment by Vinzent03** [comment]
I'm unsure on how to replace the `SocketException`. Does everything work except that warning?

**Comment by kaboc** [comment]
> Does everything work except that warning?

main.dart.js is not created due to the dependency on universal_io. I cannot start the web app at all. If you have to see what actually happens, please try building an app, following the steps I wrote earlier.

I was thinking `SocketException` was reimplementation in universal_io. However, having looked at the source code, it looks like the `SocketException` itself from dart:io via universal_io if I'm not wrong. It means the package depends on dart:io, whether the app is for mobile / desktop or for web. It seems like the cause of the issue.

I was able to build my blog site made with Dart + [Jaspr](https://pub.dev/packages/jaspr) + Supabase when I was using supabase 1.4.0. I'm not sure about other versions between that version and the latest. Investigating how universal_io was handling `SocketException` in the past would probably be a way to find a solution.
