### ISSUE TITLE
Storage api does not have upsert functionality.

### ISSUE THREAD

**Issue by HoussemBousmaha** [supabase/supabase-flutter#648]
**Is your feature request related to a problem? Please describe.**
I am pretty sure that this can be achieved very easily but if it was a part of the api that would be great!

**Comment by dshukertjr** [comment]
@HoussemBousmaha 
You can perform upsert like this:
```dart
await supabase.storage.from('bucket').upload(
      '/my/path',
      file,
      fileOptions: FileOptions(upsert: true),
    );
```

I realize this wasn't very well documented. Will update the docs and the comments within the code base so that this is more obvious! Thanks for reporting!
