### ISSUE TITLE
Cant broadcast event without subscription

### ISSUE THREAD

**Issue by Yogesh-Dubey-Ayesavi** [supabase/supabase-flutter#652]
```text
E/flutter ( 7089): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: tried to push 'broadcast' to 'realtime:ea25d91d-d424-4da6-a246-19bc9effce52' before joining. Use channel.subscribe() before pushing events
E/flutter ( 7089): #0      RealtimeChannel.push (package:realtime_client/src/realtime_channel.dart:376:7)
E/flutter ( 7089): #1      RealtimeChannel.send (package:realtime_client/src/realtime_channel.dart:402:23)
E/flutter ( 7089): #2      BroadcastChannelController.sendDirectMessage (package:example/src/controllers/broadcast_channel_controller.dart:50:43)
E/flutter ( 7089): #3      SuperwizerChatController.updateMessage (package:example/src/controllers/superwizer_chat_controller.dart:47:45)
E/flutter ( 7089): #4      _ChatScreenState._onSendTap.<anonymous closure> (package:example/src/screens/bottom_navigation_bar_screens/chat/chat_screen.dart:354:23)
E/flutter ( 7089): #5      new Future.delayed.<anonymous closure> (dart:async/future.dart:427:39)
E/flutter ( 7089): #6      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 7089): #7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 7089): #8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 7089): #9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```
I want to send a broadcast message by making http request to realtime servers, however i'am unable to it with my dart client
as mentioned [here](https://supabase.com/docs/guides/realtime/broadcast#send-messages-using-rest-calls) to do in js

**This is my dart code** 
```dart
 void  sendDirectMessage(
      JSONMap map, String event, RealtimeChannel sendingChannel) async {
    final response = await sendingChannel.send(
        type: RealtimeListenTypes.broadcast, event: event, payload: map);
    debugPrint(response.toString());
  }

```
@dshukertjr

**Comment by Vinzent03** [comment]
This got just merged a few days ago in realtime-js https://github.com/supabase/realtime-js/pull/251

**Comment by Yogesh-Dubey-Ayesavi** [comment]
Cant i do the same in flutter, if not how can how using just rest api

**Comment by Vinzent03** [comment]
@dshukertjr I have an implementation ready. Though without tests currently, but will look into that. Do we wanna ship it to v1 or v2? We could ship together with #653

**Comment by dshukertjr** [comment]
@Vinzent03 Thanks for the quick work. I think it's fine to slip it into v1 then!

**Comment by Yogesh-Dubey-Ayesavi** [comment]
when you guys are releasing new version at pub.dev i need this feature asap

**Comment by dshukertjr** [comment]
@Yogesh-Dubey-Ayesavi 
It will probably be out within the next 24 hours. We would ask you to wait patiently.

**Comment by Yogesh-Dubey-Ayesavi** [comment]
Thanks @dshukertjr  @Vinzent03

**Comment by Yogesh-Dubey-Ayesavi** [comment]
> ```dart
>  void  sendDirectMessage(
>       JSONMap map, String event, RealtimeChannel sendingChannel) async {
>     final response = await sendingChannel.send(
>         type: RealtimeListenTypes.broadcast, event: event, payload: map);
>     debugPrint(response.toString());
>   }
> ```

I'am still not able to send message neither it's throwing any error like before nor sending messages

**Comment by Vinzent03** [comment]
Works fine for me. You may place a breakpoint in the send method (line 438) to see the reason for that error. Or first try the following: Since the dashboard doesn't show the realtime server version, please try pausing and unpausing your project to update your realtime server.

**Comment by dshukertjr** [comment]
@Yogesh-Dubey-Ayesavi 
You have the wrong URL for your `RealtimeClient`. Try passing `'$supabaseUrl/realtime/v1'.replaceAll('http', 'ws')` where `supabaseUrl` is your Supabase URL from the dashboard. 

If after fixing the URL you are still not able to receive the message, please share the receiving end of the code as well.

**Comment by Yogesh-Dubey-Ayesavi** [comment]
Yeah resolved!

**Comment by Yogesh-Dubey-Ayesavi** [comment]
This must be mentioned in documentation
