### ISSUE TITLE
No redirect on after login windows

### ISSUE THREAD

**Issue by mrnotepad** [supabase/supabase-flutter#657]
Windows seems not to work. I followed the instructions but was not redirected to log in. is there any working example for Windows? thanks

**Comment by gadfly361** [comment]
@mrnotepad Can you provide a link to the instructions you are referencing?

To my understanding supabase_flutter doesn't perform a redirect on log in. Instead it will emit an AuthChangeEvent that you can listen to. One of the AuthChangeEvent's is specific to signing in. Here is an example of a listener, that is found in this [documentation](https://supabase.com/blog/flutter-authentication).

```dart
 void _setupAuthListener() {
    supabase.auth.onAuthStateChange.listen((data) {
      final event = data.event;
      if (event == AuthChangeEvent.signedIn) {
        Navigator.of(context).pushReplacement(
          MaterialPageRoute(
            builder: (context) => const ProfileScreen(),
          ),
        );
      }
    });
  }
```

**Comment by Vinzent03** [comment]
I'm closing this, because of no response. Please open a new issue with a more detailed description of what you expected and what actually happened if you encounter something similar.
