### ISSUE TITLE
Cannot build a Dart web app due to dependency on dart:io in gotrue 1.12.3

### ISSUE THREAD

**Issue by kaboc** [supabase/supabase-flutter#658]
**Describe the bug**

Thank you for fixing the issue #641 I reported. Dependency on universal_io was certainly removed by #653. However, gotrue_client.dart now depends on dart:io and it has caused another issue similar to #641.

```
[INFO] Serving `web` on http://127.0.0.1:8080
[WARNING] build_web_compilers:entrypoint on web/main.dart: Skipping compiling bug|web/main.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

gotrue|lib/src/gotrue_client.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings
```

**To Reproduce**

Follow the steps written in #641.

**Expected behavior**

Pure Dart web apps using Supabase run without any issue.

**Screenshots**

N/A

**Version (please complete the following information):**

```
└── supabase 1.11.8
    ├── functions_client 1.3.2
    ├── gotrue 1.12.3
    ├── postgrest 1.5.1
    ├── realtime_client 1.3.0
    ├── storage_client 1.5.3
```

**Comment by Vinzent03** [comment]
I could have sworn I tested gotrue as well, but doesn't seem so. It doesn't even use `dart:io` really, but is only imported for a now outdated comment.
I'm unsure if we want to do another release just for that. For now you can simply edit that file yourself locally and remove the `dart:io` import as it's no longer used.

**Comment by kaboc** [comment]
@Vinzent03 
I made a PR anyway. You can decide whether to release a new version only for the fix. I can use the local version with the bug fix for the time being.
