### ISSUE TITLE
Firefox private browsing is broken with default HiveLocalStorage

### ISSUE THREAD

**Issue by cgestes** [supabase/supabase-flutter#67]
While private browsing using Firefox IndexedDB will throw if used. (this is a wontfix bug from Firefox).

This lead to hive throwing also.

There is no easy way to detect if we are in private browsing mode from flutter. (and in general).

I guess we should proceed if Hive fail to init or work.

```supabase.initialize``` will throw but still initialize.

Then when authenticating we will get a Box not found and it will be impossible to proceed further. :/

I would expect the system the login normally while not having a persistent session.

**Comment by DanMossa** [comment]
I'm wondering if this is the issue I'm experiencing on #711

**Comment by dshukertjr** [comment]
I think we can close this issue now that we are using local storage to store auth tokens.
