### ISSUE TITLE
Storage and Auth headers incorrect?

### ISSUE THREAD

**Issue by talamaska** [supabase/supabase-flutter#681]
**Describe the bug**
I have created a SupabaseCacheManager to use in CachedNetworkImage that is not working anymore with supabase_flutter 1.10.23

```dart
class SupabaseCacheManager extends CacheManager with ImageCacheManager {
  SupabaseCacheManager({
    required SupabaseClient supabaseClient,
  }) : super(
          Config(
            key,
            stalePeriod: const Duration(days: 7),
            repo: JsonCacheInfoRepository(databaseName: key),
            maxNrOfCacheObjects: 1000,
            fileService: SupabaseFileService(
              supabaseClient: supabaseClient,
            ),
          ),
        );

  static const key = 'supabaseCache';
}

class SupabaseFileService extends HttpFileService {
  SupabaseFileService({
    required SupabaseClient supabaseClient,
  }) : _supabaseClient = supabaseClient;
  final SupabaseClient _supabaseClient;

  @override
  Future<FileServiceResponse> get(
    String url, {
    Map<String, String>? headers,
  }) async {
    const renderPath = 'object';
    final storageUrl = _supabaseClient.storage.url;
    final fetchUrl = Uri.parse('$storageUrl/$renderPath/$url');
    final response = await super.get(
      fetchUrl.toString(),
      headers: _supabaseClient.storage.headers,
    );

    return response;
  }
}
```

And using it like this 
```dart
CachedNetworkImage(
                imageUrl: state.avatarPath,
                width: radius * 2,
                height: radius * 2,
                fit: BoxFit.fill,
                placeholder: (context, url) {
                  return const SizedBox.square(
                    dimension: 16,
                    child: Center(
                      child: CircularProgressIndicator(
                        strokeWidth: 1,
                      ),
                    ),
                  );
                },
                errorWidget: (context, url, error) {
                  return const Icon(
                    Icons.error,
                    size: 24,
                  );
                },
                cacheManager: context.read<SupabaseCacheManager>(),
              ),
```

This worked fine in supabase_flutter 1.9.0

In 1.10.23 this doesn't work anymore.
By placing breakpoint right before final response = await super.get, I saw the first issue: supabaseClient.storage.headers now have a map with only one record which is the x-client-info, previously this had all the needed headers. 

I tried using the supabase.auth.headers, but it turned out apikey and jwt token are the same, which is incorrect.

Eventually when I change it to use the token from supabaseClient.auth.currentSession?.accessToken and the key from supabaseClient.supabaseKey and it worked.

**To Reproduce**
Place breakpoints in any request you are making to Supabase and inspect the supabaseClient.storage and supabaseClient.auth headers

**Expected behavior**
I would expect 
a. storage and auth headers to be the same
b. to have correct records in the map for the Authorization and apikey headers
c. apikey and jwt token are different things I'm not sure how this thing got messed up.

**Version (please complete the following information):**

On Windows
supabase_flutter 1.10.23
supabase 1.11.10
functions_client 1.3.2
gotrue 1.12.5
postgrest 1.5.2
realtime_client 1.4.0
storage_client 1.5.4

**Additional information**
By inspecting all of the SupabaseClient features,
functions headers are just these 2
```
"Content-Type" -> "application/json"
"X-Client-Info" -> "supabase-flutter/1.10.23"
```

rest has only "X-Client-Info" -> "supabase-flutter/1.10.23"
storage has only "X-Client-Info" -> "supabase-flutter/1.10.23"
realtime has only "X-Client-Info" -> "supabase-flutter/1.10.23", but it also has accessToken property which has a correct value

**Comment by talamaska** [comment]
I hope this won't be closed due to inactivity. That's why I'm leaving this comment here - to prevent closure without resolving.

**Comment by dshukertjr** [comment]
@talamaska 
Supabase provides methods for retrieving URLs to retrieve URLs for the image, but is there a reason why you are not using them?

You shouldn't need to create your own CacheManager class at all, and you can just pass the image URL to `CachedNetworkImage` widget directly.

For public bucket: https://supabase.com/docs/reference/dart/storage-from-getpublicurl
For private bucket: https://supabase.com/docs/reference/dart/storage-from-createsignedurl

**Comment by talamaska** [comment]
I don't think createSignedUrl cares about any policies I have set. I need the policies to be taken into account. Even if I start using it, I don't want to make the calls prematurely, so I will still need to implement custom url resolver in the cache manager. I have seen issues when these signed urls expire in the worst moment, in different projects, but still aws based. Plus having 2 cashing layers is a problem waiting to happen.

**Comment by dshukertjr** [comment]
@talamaska 
> I don't think createSignedUrl cares about any policies I have set.

Just to make sure you understand how Supabase storage and RLS works, only those users that are allowed to `select` the files in a private bucket can create signed URLs and that is when the RLS takes effect. Once a signed URL is issued, the file will be accessible by anyone with the URL until the expiry time comes, and RLS does nothing there. So you have to design your system in a way that only those that should be able to access the file can obtain the signed URLs. 

Knowing this behavior, a better caching strategy might be to use the image path as the cache key and call the `createSignedUrl` whenever the cache expires.

**Comment by dshukertjr** [comment]
> Eventually when I change it to use the token from supabaseClient.auth.currentSession?.accessToken and the key from supabaseClient.supabaseKey and it worked.

Also, it sounds like you did find a work around for this issue. 

The current behavior was introduced to guarantee fresh auth tokens when making request to Supabase, and since there is a work around for it, I'm going to close this issue.

**Comment by talamaska** [comment]
> Once a signed URL is issued, the file will be accessible by anyone with the URL until the expiry time comes, and RLS does nothing there.

This is exactly my concern.

**Comment by dshukertjr** [comment]
@talamaska 
That's why typically for accessing files in private buckets, you set the token expiration time to something very short so that you can just download the file and be done with it.

**Comment by talamaska** [comment]
Ok, you convinced me :)

**Comment by talamaska** [comment]
Ok, well I researched how this can be done with CachedNetworkImage, with or without a CustomCacheManager. There is no way to for me pass the bucket and/or the expiration for a CustomCacheManager. A the fileService is initialized once, and the get method is called somewhere internally in the CachedNetworkImage. Without the cache manage I can only wrap the whole thing with a FutureProvider, which doesn't help at all, cause it will request a new signed url on every build, instead of just when the cache of the CacheManager.
