### ISSUE TITLE
I'm unable to build for web due to `Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.`

### ISSUE THREAD

**Issue by DanMossa** [supabase/supabase-flutter#685]
**Describe the bug**
When building Flutter for web, I'm experiencing the following error:
```
Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
 - 'File/*1*/' is from 'dart:io'.
 - 'File/*2*/' is from 'package:storage_client/src/file_stub.dart' ('../../../.pub-cache/hosted/pub.dev/storage_client-1.5.4/lib/src/file_stub.dart').
          .upload(path, file, fileOptions: FileOptions(upsert: true, contentType: xFile.mimeType));
```

The code being called is
```
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:universal_io/io.dart';

  static Future<String?> _upsertFile(String userId, XFile xFile, int i) async {
    final String path = '$userId/${i.toString()}';
    final String res;
    if (kIsWeb) {
      final Uint8List fileAsBytes = await xFile.readAsBytes();
      res = await _supabase.storage.from('profile-pictures').uploadBinary(path, fileAsBytes,
          fileOptions: FileOptions(upsert: true, contentType: xFile.mimeType));
    } else {
      final File file = File(xFile.path);
      res = await _supabase.storage
          .from('profile-pictures')
          .upload(path, file, fileOptions: FileOptions(upsert: true, contentType: xFile.mimeType));
    }

    return res;
  }
```

**Expected behavior**
I would expect the web version to build.

**Version (please complete the following information):**
MacOS
```
dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"
├── supabase_flutter 1.10.23
│   ├── supabase 1.11.10
│   │   ├── functions_client 1.3.2
│   │   ├── gotrue 1.12.5
│   │   ├── postgrest 1.5.2
│   │   ├── realtime_client 1.4.0
│   │   ├── storage_client 1.5.4
```

**Additional context**
This error has not happened before. I'm unsure what has specifically changed since I haven't built the web version of my app in a while.

**Comment by johannesvedder** [comment]
Is there any fix or workaround available for this?

**Comment by DanMossa** [comment]
@johannesvedder I've switched to using uploadBinary everywhere in the meantime

**Comment by Navil** [comment]
Instead of 
final File file = File(xFile.path)

Try
dynamic file = File(xFile.path)

**Comment by BALU2000-creator** [comment]
> @johannesvedder I've switched to using upload binary everywhere in the meantime

```
      onPressed: () async {
        try{
        final file = File('lib/example.txt');
        final file_bytes = file.readAsBytesSync();
        supabase.storage
            .from('myBucket')
            .uploadBinary('my/path/to/files/example.txt', file_bytes);
        }catch(e){
          print(e);
        }
      },
```

I also switched to the binary file uploading after getting the above error, But it didn't work for me, It threw an Unsupported operation: _Namespace.



> @johannesvedder I've switched to using uploadBinary everywhere in the meantime

**Comment by DanMossa** [comment]
Try using `file.readAsBytes` instead and try awaiting the `uploadBinary` future and let me know if you're still having a problm @BALU2000-creator

**Comment by NicoEssi** [comment]
For anyone who was having the error `Unsupported operation: _Namespace`, consider using https://pub.dev/packages/cross_file and writing the line `final bytes = await XFile(path).readAsBytes();` instead of `final file_bytes = file.readAsBytes();`

This is what finally worked for me - to upload arbitrary blob files from Flutter web to Supabase.
