### ISSUE TITLE
feat(postgrest): return specific exceptions

### ISSUE THREAD

**Issue by alestiago** [supabase/supabase-flutter#689]
### Description

I would like to have a subclassing exception for each of the errors documented by Postgrest (see the [docs](https://postgrest.org/en/stable/references/errors.html#postgrest-error-codes)), so that I can catch specific exceptions easily in Dart. Consequently, this will improve the developer experience when using this package or the Dart Supabase client.

### Describe the solution you'd like

After this feature lands:
```dart
class PostgrestConnectionInvalidUriException extends PostgrestException { ... }

try {
 // query
} on PostgrestConnectionInvalidUriException catch (e) {
 // some logic
}
```

Before this feature lands (currently):
```dart
try {
// query
} on PostgrestException catch (e) {
  if (e.code == 'PGRST116') {
    // some logic
  } else rethrow;
}
```

### Additional context
- Parsing logic https://github.com/supabase/supabase-flutter/blob/6b7bad76e0e51a0dcb96f5d8c8bd7b3484ce0bdd/packages/postgrest/lib/src/postgrest_builder.dart#L321
- I'm willing to work on this feature, let me know first if you're willing to accept this feature and external contributors.

**Comment by bdlukaa** [comment]
There are many, many error codes - and I don't think we can maintain all of them. I don't think this is viable and won't have much of a use for most of the developers.

There are other things to think about, like documentation, backwards compatibility, etc.

**Comment by alestiago** [comment]
> There are many, many error codes

 Besides the error codes that referenced from the [documentation](https://postgrest.org/en/stable/references/errors.html#postgrest-error-codes) are there any others worth considering?

>  I don't think this is viable and won't have much of a use for most of the developers.

I will definitely be of use for my usecase. I do see it viable, if we make use of a template generator like mason it should be very simple to generate and maintain these exceptions given the data.

**Comment by DanMossa** [comment]
@alestiago thoughts on creating sealed exceptions and creating your own switch case helper?

**Comment by alestiago** [comment]
> @alestiago thoughts on creating sealed exceptions and creating your own switch case helper?

I feel this it not the solution, since this is a problem many developers can fase. I would expect the PostgREST client itself ro provide a solution to this issue.

[Here](https://github.com/alestiago/postgrest_errors/blob/main/packages/postgrest_errors/lib/src/postgrest_errors.dart) you can find a Dart library with all PostgREST errors and exceptions generated from the official documentation.

**Comment by alestiago** [comment]
Any updates, thoughts or follow-ups? If you wish I can push a draft Pull Request to illustrate the change or close if the team feels strong against this.

**Comment by dshukertjr** [comment]
@alestiago 
Thanks for the suggestion, but we will not be implementing this as it will make supabase-flutter deviate from other client libraries.
