### ISSUE TITLE
How to use coordinate?

### ISSUE THREAD

**Issue by flaviopopoff** [supabase/supabase-flutter#695]
I have a table with coordinate 
```sql
create table if not exists public.location (
    cap text primary key,
    city varchar(24) not null,
    province varchar(24) not null,
    coordinate geography(POINT) not null
);
```

How I can get back the coordinate in an acceptable format using the classic select and not an rpc with the use of `st_astext`.
`supabase.from('location').select(cap, city, province, coordinate);`

There is a way to convert the result of the classic select and convert this
`0101000020E61000002545BF1138914540E7FD7F9C30212A40` in the classic format lat long?

**Comment by DanMossa** [comment]
I can post what I've done in a little bit!

**Comment by DanMossa** [comment]
I have a column in my table 
    location_ewkt text GENERATED ALWAYS AS (st_asewkt(location)) STORED

You can do something similar as a workaround.

**Comment by flaviopopoff** [comment]
@DanMossa but in this way I can do calculation with coordinate? Like calculate the distance between two coordinate?

**Comment by DanMossa** [comment]
@flaviopopoff Did you end up trying it and seeing if it worked for you?

**Comment by dshukertjr** [comment]
@DanMossa 
Using a generated column to convert `geography(Point)` to human readable format is brilliant! Maybe we could use `st_y()` and `st_x()` to get latitude and longitude respectively. 

@flaviopopoff 
If you want to find the list of data within a bounding box, within certain distance from a given point, or sort data from closest to farthest from a point, you would need to use `.rpc()`. More on this in the PostGis guide here. https://supabase.com/docs/guides/database/extensions/postgis

If you just want to get the lat/lng of your location data, you can use the workaround that @DanMossa proposed. You could calculate the distance between two points on client side as well. https://stackoverflow.com/questions/54138750/total-distance-calculation-from-latlng-list

**Comment by thedalelakes** [comment]
ChatGPT helped me with this one.

If you want to convert the WKB string to lat / lng on the client, here's Dart code:

```dart
import 'dart:typed_data';

Map<String, double> parseWKBPoint(String wkbString) {
  // Convert the hex string to bytes
  Uint8List bytes = Uint8List.fromList(List<int>.generate(
      wkbString.length ~/ 2,
      (index) => int.parse(wkbString.substring(index * 2, index * 2 + 2), radix: 16)));

  ByteData byteData = bytes.buffer.asByteData();

  // Assuming little endian byte order
  bool isLittleEndian = byteData.getUint8(0) == 1;

  // Skip the first 5 bytes (1 for byte order, 4 for type indicator)
  double lon = byteData.getFloat64(5, isLittleEndian);
  double lat = byteData.getFloat64(13, isLittleEndian);

  return {'lat': lat, 'lng': lon};
}

void main() {
  String wkbPoint = '0101000020E6100000A4DFBE0E9C91614044FAEDEBC0494240';
  Map<String, double> coordinates = parseWKBPoint(wkbPoint);
  print('Latitude: ${coordinates['lat']}, Longitude: ${coordinates['lng']}');
}
```

**Comment by 21prnv** [comment]
> ChatGPT helped me with this one.
> 
> If you want to convert the WKB string to lat / lng on the client, here's Dart code:
> 
> ```dart
> import 'dart:typed_data';
> import 'latlong2/latlong.dart';
> 
> static LatLng _parseWKBPoint(String wkbString) {
>   // Convert the hex string to bytes
>   final bytes = Uint8List.fromList(
>     List<int>.generate(
>       wkbString.length ~/ 2,
>       (index) => int.parse(
>         wkbString.substring(index * 2, index * 2 + 2),
>         radix: 16,
>       ),
>     ),
>   );
> 
>   final byteData = bytes.buffer.asByteData();
> 
>   // Assuming little endian byte order
>   final isLittleEndian = byteData.getUint8(0) == 1;
> 
>   // Skip the first 5 bytes (1 for byte order, 4 for type indicator)
>   final lon = byteData.getFloat64(
>     5,
>     isLittleEndian ? Endian.little : Endian.big,
>   );
>   final lat = byteData.getFloat64(
>     13,
>     isLittleEndian ? Endian.little : Endian.big,
>   );
> 
>   return LatLng(lat, lon);
> }
> 
> 
> void usage() {
>   String wkbPoint = '0101000020E6100000A4DFBE0E9C91614044FAEDEBC0494240';
>   LatLng coordinates = _parseWKBPoint(wkbPoint);
>   print(coordinates);
> }
> ```

is thik workes perfectly ?
