### ISSUE TITLE
How does the new native Apple sign-in work?

### ISSUE THREAD

**Issue by volkankoc** [supabase/supabase-flutter#697]
Describe the bug
I'm trying the new native login apple. But the application does not react at all.
I created the app from my Apple developer account. I added the app id to the auth provider on the supabase side.
What could be the problem?
The application does not react

Version (please complete the following information):
On Linux/macOS
Please run dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client" in your project directory and paste the output here.
supabase_flutter 1.10.24
│ ├── supabase 1.11.11
│ │ ├── functions_client 1.3.2
│ │ ├── gotrue 1.12.6
│ │ ├── postgrest 1.5.2
│ │ ├── realtime_client 1.4.0
│ │ ├── storage_client 1.5.4

**Comment by volkankoc** [comment]
I My problem still persists
<img width="1026" alt="image" src="https://github.com/supabase/supabase-flutter/assets/22777823/f5ec47cb-dd88-444a-9710-da839f81fe5f">
<img width="389" alt="image" src="https://github.com/supabase/supabase-flutter/assets/22777823/5eff7ffa-94da-4178-b0be-6bfa5a51b8c7">

**Comment by dshukertjr** [comment]
@volkankoc 
>But account not showing supabase auth page.

If you have a session shown in the debug console, you are signed in. If you are not seeing a certain page after signing in, the core issue is likely somewhere else. Without sharing your code and/ or giving me a precise description of what is happening with your app, I cannot assist you. If you are still experiencing issues, I would kindly ask you reopen another issue and to follow the issue template so that we can get the context we need.

**Comment by volkankoc** [comment]
> @volkankoc
> 
> > But account not showing supabase auth page.
> 
> If you have a session shown in the debug console, you are signed in. If you are not seeing a certain page after signing in, the core issue is likely somewhere else. Without sharing your code and/ or giving me a precise description of what is happening with your app, I cannot assist you. If you are still experiencing issues, I would kindly ask you reopen another issue and to follow the issue template so that we can get the context we need.

I see token information on the terminal screen. Yes, the session is verified by Apple. But no auth information indicating that the session has been opened does not appear in the supabase auth page.
my apple login code
<img width="651" alt="image" src="https://github.com/supabase/supabase-flutter/assets/22777823/5d835627-18ce-4af0-9db1-1c91922135ff">

**Comment by volkankoc** [comment]
Yes, I cannot see the logged in user on this screen.

**Comment by dshukertjr** [comment]
@volkankoc 
You can also view your `auth.users` table by changing the schema from the table editor. You should see it there. If not, double check that you are viewing the correct Supabase instance. 
<img width="663" alt="Screenshot 2023-11-09 at 1 04 48" src="https://github.com/supabase/supabase-flutter/assets/18113850/78c085df-3040-4a07-9fc8-0ae1d76db85f">

Either way, you have a valid session, so there is nothing you need to worry about. You can just resume to working on your app.

**Comment by volkankoc** [comment]
I am sorry. This problem is caused by me. I did not notice the login because I had previously logged in with Google with the same email. Again again sorry

**Comment by dshukertjr** [comment]
@volkankoc Glad to hear that the cause is found 😁
