### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by jhlabs** [supabase/supabase-flutter#7]
# Feature request
Thanks for this great package!

I would like to use the `supabase-flutter` package with my app that runs on both the web and macOS.

## Is your feature request related to a problem? Please describe.

I am using Google OAuth and it works well on the web. When running the macOS app, I can open the Google SignIn page. The callback scheme does not open my app, however. Instead, the Google Request keeps loading and the browser window loses focus.

Is a totally different implementation for macOS required? It seems to me that as long as the callback scheme is correct, I should be able to retrieve the resulting callback and handle the authentication logic from there as usual.

**Comment by himeshp** [comment]
Supabase flutter uses uni links package which does not support flutter desktop apps yet.
More info here 

https://github.com/supabase/supabase-flutter/issues/1

**Comment by bdlukaa** [comment]
The plugin [uni_links](https://pub.dev/packages/uni_links) has to add support for it in order to this happen. Once that happens, macOS app will work.

**Comment by jhlabs** [comment]
Thanks for the info!

**Comment by jhlabs** [comment]
It looks like the [uni_links](https://pub.dev/packages/uni_links) is not well maintained anymore. It does not seem likely that desktop support will land there anytime soon...

**Comment by lijy91** [comment]
I developed desktop implementation of uni_links plugin. maybe it's time to finish this feature.

https://github.com/leanflutter/uni_links_desktop

**Comment by dshukertjr** [comment]
That is amazing @lijy91 . Would you like to submit a PR?
