### ISSUE TITLE
cannot init Supabase Client with local supabase cli

### ISSUE THREAD

**Issue by chirastefan** [supabase/supabase-flutter#709]
**Describe the bug**
Cannot initialize Supabase Client when local supabase is started with supbase-cli with `supabase start`.

```
         API URL: http://127.0.0.1:54321
     GraphQL URL: http://127.0.0.1:54321/graphql/v1
          DB URL: postgresql://postgres:postgres@127.0.0.1:54322/postgres
      Studio URL: http://127.0.0.1:54323
    Inbucket URL: http://127.0.0.1:54324
      JWT secret: <JWT token>
        anon key: <anon key>
service_role key: <service_role key>
```

![Screenshot 2023-11-13 at 22 53 37](https://github.com/supabase/supabase-flutter/assets/16649178/e319202a-34d5-4c2a-a257-a338a3a33958)

**Comment by chirastefan** [comment]
macos Montery 12.7, intel processor
supabase_flutter: ^1.10.25

**Comment by chirastefan** [comment]
`SupabaseClient('127.0.0.1:54322/postgres', 'anon_key')`
for this `SupabaseClient('postgresql://postgres:postgres@127.0.0.1:54322/postgres', 'anon_key')` I get 
![Screenshot 2023-11-17 at 01 05 46](https://github.com/supabase/supabase-flutter/assets/16649178/19dc8a3c-bc4c-4b52-9a08-9dd581eb3765)

**Comment by Vinzent03** [comment]
The last one is correct as that's the api url listed in the console output from `supabase start`
