### ISSUE TITLE
Calling signInWithProvider does not trigger onAuthStateChange

### ISSUE THREAD

**Issue by Shiba-Kar** [supabase/supabase-flutter#71]

**Comment by dshukertjr** [comment]
@Shiba-Kar Thank you for opening this issue. We will investigate this issue and get back to you on this thread as soon as we can, but the team is a bit busy with [Supabase launch week](https://supabase.com/blog/2022/03/25/supabase-launch-week-four), so it might take some time and I apologize in advance for it.

**Comment by Ashwaq3** [comment]
@dshukertjr @bdlukaa  Any progress as I was trying to use signInWithProvider since a month but once redirecting back to the app the session is null.

**Comment by bdlukaa** [comment]
@dshukertjr https://github.com/supabase-community/supabase-flutter/blob/main/lib/src/supabase_auth.dart#L155-L173

After investigating a little the issue, I believe the call should happen on the deep-link handling.

**Comment by Vinzent03** [comment]
I think this issue can be closed. Please open a new one if you still encounter this.
