### ISSUE TITLE
Hive is throwing an error on web

### ISSUE THREAD

**Issue by DanMossa** [supabase/supabase-flutter#711]
**Describe the bug**
When running my Flutter app on web, I get an error from Hive that the Box was not found.

**To Reproduce**
I haven't been able to come up with minimally reproducible example.

**Version (please complete the following information):**
On Windows
```
supabase_flutter 1.10.25
supabase 1.11.11
functions_client 1.3.2
gotrue 1.12.6
postgrest 1.5.2
realtime_client 1.4.0
storage_client 1.5.4
```

**Additional context**
This is the stack trace:
```
Error: HiveError: Box not found. Did you forget to call Hive.openBox()?
dart:sdk_internal 5402:11                                                     throw_
app/packages/hive/src/box_collection/box_collection_stub.dart.lib.js 3819:19  [_getBoxInternal]
app/packages/hive/src/box_collection/box_collection_stub.dart.lib.js 3827:51  box
app/packages/supabase_flutter/src/supabase_auth.dart.lib.js 1074:24           _persistSession
app/packages/supabase_flutter/src/supabase_auth.dart.lib.js 517:15            [_onAuthStateChange]
app/packages/supabase_flutter/src/supabase_auth.dart.lib.js 394:69            <fn>
dart:sdk_internal 39674:11                                                    runUnaryGuarded
dart:sdk_internal 33639:22                                                    [_sendData]
dart:sdk_internal 36942:28                                                    perform
dart:sdk_internal 37060:15                                                    handleNext
dart:sdk_internal 37032:16                                                    callback
dart:sdk_internal 40214:13                                                    _microtaskLoop
dart:sdk_internal 40220:13                                                    _startMicrotaskLoop
dart:sdk_internal 35968:9                                                     <fn>
```

Looks to be related to
```
  static String? encryptionKey;

  static Future<void> _initialize() async {
    HiveCipher? encryptionCipher;
    if (encryptionKey != null) {
      encryptionCipher = HiveAesCipher(base64Url.decode(encryptionKey!));
    }
    await Hive.initFlutter('auth');
    await Hive.openBox(_hiveBoxName, encryptionCipher: encryptionCipher);
  }
  ```
  
  `encryptionKey` is null and the error occurs `await Hive.openBox(_hiveBoxName, encryptionCipher: encryptionCipher);`

**Comment by dshukertjr** [comment]
I haven't tried to reproduce this yet on my end, but does this happen every time you initialize Supabase on web for you, or just once in a while?

**Comment by DanMossa** [comment]
I want to say that it wasn't a problem before but now it always happens.

I'm also using Hive on my project and am having issues with it not actually persisting on Web.

I was reading through issues and it seems that Hive has general issues on Web and the creator has moved on to Isar. They made a post that they're still working on Hive but there's no expected update for fixes.

I don't remember but was there a reason we didn't use the secure storage plugin, or my preference is reusing shared_preferences and another package for encrypting.

@dshukertjr

**Comment by dshukertjr** [comment]
@DanMossa 
Thanks for the additional info. We will start using shared_preferences starting v2, so although it will still effect the existing v1 users, hopefully this doesn't become a huge issue in the future.

**Comment by DanMossa** [comment]
@dshukertjr Do you think it's worth me making a PR to migrate to shared preferences in v1? Or are we basically only updating v2 at this point?

**Comment by dshukertjr** [comment]
@DanMossa 
Hmm, I think it's alright not creating a PR. Maybe the issue could be resolved by using an older version of Hive? I tried it out quickly on Mac and Chrome, and session was persisted fine with v1.0 of supabase_flutter. 
If existing v1 projects update to v2, there will be a automated script that will retrieve the session from hive and migrate it to shared preferences, so those that are using supabase_flutter v1 already could migrate to v2 to keep using auth on web if there are issues.
