### ISSUE TITLE
onAuthStateChange is not triggered when signing in using signInWithOAuth() on iOS

### ISSUE THREAD

**Issue by quozhang** [supabase/supabase-flutter#713]
Hello Supabase team,

For my case, I'm testing with iPhone simulator 8, iOS 16.4 and found that the `onAuthStateChange` was not triggered after social logins (Google, Facebook) while it works normally with others features: logout, email/password login, native Google sign in (by google_sign_in package) and on Android.

**To Reproduce**
1. I have a Sign in with Facebook button, which will call
```
void onClick() {
  await client.auth
          .signInWithOAuth(
            Provider.facebook,
            redirectTo: 'my.app.id://login-callback',
          );
  return;
}
```
2. It opens the Safari browser, shows the facebook login form in Safari browser and I submit my login credentials.
3. Wait for seconds and the Safari displays a Popup to open in my app. Click Open.
4. It backs to my app. 
At this step, when be back at my app, I expect that the `onAuthStateChange` should be triggered but it's not.
 I also check my Supabase Dashboard > Authentication > Manage Users >  Search for my email, and the `Last Sign In` was updated successfully.

**Version:**
`flutter doctor`:
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.3.1 22E261 darwin-x64)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources
• No issues found!

supabase_flutter: ^1.10.25

**Additional context**
I tried with Google login and it has the same issue.

Please let me know if you need any more information. Thank you.

**Comment by dshukertjr** [comment]
@quozhang 
Thanks for providing details on this issue. 

At step 4 when you come back to the app, would you be able to see if `supabase.auth.currentSession` returns `null` or a `Session` object?

**Comment by quozhang** [comment]
Hi @dshukertjr , the session after coming back is `null`.

**Comment by dshukertjr** [comment]
@quozhang Hmm, it sounds like the auth information is somehow lost when the user opens the app. Would you be able to share how you are calling `Supabase.initialize()` in your main function? I want to check what options are being passed.

**Comment by quozhang** [comment]
@dshukertjr of course:
the main() function is calling this:
```
await supabase.Supabase.initialize(
    url: Constants.authServerUrl,
    anonKey: ConfigService.instance.authServerAnonKey,
  );
```

**Comment by dshukertjr** [comment]
@quozhang 
Thanks for sharing. Hmm, a standard initialization I see. I wonder what the reason could be...

Would you be able to try magic link login like this and see if the same thing happens?

```dart
await supabase.auth.signInWithOtp(
  email: 'example@email.com',
  emailRedirectTo: 'my.app.id://login-callback',
);
```

**Comment by quozhang** [comment]
@dshukertjr 
it's ok, let me try this.

**Comment by quozhang** [comment]
@dshukertjr 
I did take reference from this link to make sure that I'm not missing any codes: https://supabase.com/docs/guides/getting-started/tutorials/with-flutter?platform=ios#setup-deep-links
but it doesn't work either. There was no `onAuthStateChange` event emitted when be back to the app. The session is `null` also.

The link is like: https://<supabase_id>.supabase.co/auth/v1/verify?token=<token>&type=magiclink&redirect_to=my.app.id://login-callback/

**Comment by dshukertjr** [comment]
@quozhang 
Hmm, you are being returned to the app automatically after clicking on the link, so the deep link is working properly, but it seems that the SDK isn't recognizing the auth tokens in the deep links. 

In step 4 when you return to the app, do you see `onReceivedAuthDeeplink uri: ` printed in the console? If so, what URL do you see after the `uri: `?

**Comment by quozhang** [comment]
@dshukertjr There's nothing printed in the console from the supabase sdk at that time. In `supabase_auth.dart`, I did try printing any events at line 245  but nothing changed.
On Android app, I can see the logs clearly.

**Comment by dshukertjr** [comment]
@quozhang 
Hmm, at this point, I'm not sure what the problem could be. Is the repo open sourced? If so, could you share the link here? If not, could you create a open sourced version of it with minimal reproducible code and share it here?

**Comment by quozhang** [comment]
> @quozhang Hmm, at this point, I'm not sure what the problem could be. Is the repo open sourced? If so, could you share the link here? If not, could you create a open sourced version of it with minimal reproducible code and share it here?
In that case, there's no choice but to create another code 😵

**Comment by dshukertjr** [comment]
@quozhang 
Sounds good. Will take a look once you share a reproducible code.

**Comment by quozhang** [comment]
@dshukertjr This is resolved. Thank you for your support. 
These code below shouldn't be added into `AppDelegate.swift`:

```
 override func application(
        _ app: UIApplication,
        open url: URL,
        options: [UIApplication.OpenURLOptionsKey : Any] = [:]
    ) -> Bool {
        ApplicationDelegate.shared.application(
            app,
            open: url,
            sourceApplication: options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String,
            annotation: options[UIApplication.OpenURLOptionsKey.annotation]
        )
  }  
```

**Comment by dshukertjr** [comment]
@quozhang 
Great to hear that the issue is resolved, and thanks for sharing a solution as well!

**Comment by bahaafathi** [comment]
### I encountered the same bug in both Android and iOS. 

After two days of investigation and reading the Supabase internal SDK source code, I found that the **_handleDeeplink(uri)** function in **supabase_auth.dart** on **line 216** fails to catch the returned deep link automatically. 
This means you will never be able to catch the new session.

### To solve this issue, you need to manually catch the returned deep link and call the following code:
`await Supabase.instance.client.auth.getSessionFromUrl(uri);
`

Here is my full code:
```
AppLinks().uriLinkStream.listen((uri) async {
  await supabase.auth.getSessionFromUrl(uri);
});
```
Note: I am using the [package:app_links ](https://pub.dev/packages/app_links)to catch the deep link. After implementing this, everything will work fine on both iOS and Android.

@dshukertjr
