### ISSUE TITLE
Session is removed when app is resumed without network

### ISSUE THREAD

**Issue by giorgiogross** [supabase/supabase-flutter#716]
**Describe the bug**
The locally stored auth credentials of the current session are removed when app is resumed without network after user already successfully logged in before.

**To Reproduce**
1. Launch an app with Supabase Auth while you have access to network.
2. Log in
3. Turn on airplane mode
4. Leave app, but don't close it! Eg go to your home screen
5. Wait for the access token to expire. Eg set the session duration to 30sec in Supabase dashboard.
6. Then return to the app. I set a breakpoint at my currently installed supabase version in `supabase_auth.dart -> _recoverSupabaseSession()` I can see this: <img width="764" alt="Screenshot 2023-11-20 at 11 25 56" src="https://github.com/supabase/supabase-flutter/assets/18177722/da7cf7bf-58f5-46ca-b03a-5ff505e0a844">
7. You can see that the local session has been removed
8. Fully close the app, and restart it. Supabase attempts to resume the session, but the session got deleted. Therefore, your user is logged out.

On physical iOS devices, this seems to be a bit tricker: The above behaviour happens already when launching the app while device is in airplane mode. As It's hard for me to debug this, I can only make an assumption atm. From experience, connection errors that come from active airplace mode resolve almost immediately, so that it could be possible that the `WidgetsBindingObserver` which `SupabaseAuth`  is implementing attaches much quicker than in simulator debug builds (where I simply turn off Wifi) so that the `didChangeAppLifecycleState` is already triggered when the app is launched. So when my state management logic checks supabase's auth store, it already sees that the session is delted on app-launch, and therefore navigates to the sign in screen.

**Expected behavior**
I can launch and resume the app while offline, and app can go offline and online while using it, and session never gets deleted unless user explicitly signs out.

**Version (please complete the following information):**
On macOS, tested on iOS Simulator & iOS physical device
```
── supabase_flutter 2.0.0-dev.2
│   ├── supabase 2.0.0-dev.2
│   │   ├── functions_client 2.0.0-dev.0
│   │   ├── gotrue 2.0.0-dev.1
│   │   ├── postgrest 2.0.0-dev.0
│   │   ├── realtime_client 2.0.0-dev.1
│   │   ├── storage_client 2.0.0-dev.0

```

**Additional context**
This also happens on any other kind of network error, eg time outs. In my app, I'm passing my own instance of `SharedPreferencesLocalStorage` for the local storage so that my app can check cached session data upon launching.

**Comment by giorgiogross** [comment]
I also noticed that on [supabase_auth.dartL119](https://github.com/supabase/supabase-flutter/blob/main/packages/supabase_flutter/lib/src/supabase_auth.dart#L119) errors are catched during initialization. So I'm wondering, would it be a possible solution to do something similar in the `_recoverSupabaseSession()` method?

**Comment by dshukertjr** [comment]
This should be fixed, and you should now be able to launch your app while being offline.
