### ISSUE TITLE
range() No effect, only the first n items are returned.

### ISSUE THREAD

**Issue by disonwei** [supabase/supabase-flutter#718]
**Describe the bug**

I am using flutter as well as supabase database. I'm going to query the data by paging. The range() method mentioned in the documentation is used.
But I now range() does not work.
 For example,

```dart
 final data = await supabase
.from('record')
.select()
.range(start, end); 
```

When start = 0 and end = 2, the first 3 results are returned, when start = 3 end = 5, the first 3 results are returned, and when start = 6 end = 8, the first 3 results are returned.. range(start, end); It did not take effect, and all the first n results were returned.

**Expected behavior**
range(start, end); should be the correct offset query data, not always return the first few items

**Screenshots**
The following is loading more logic, as well as the output result：

<img width="536" alt="image" src="https://github.com/supabase/supabase-flutter/assets/55089487/ee01ea54-1f84-46e6-8ae7-f5550096876d">

<img width="705" alt="image" src="https://github.com/supabase/supabase-flutter/assets/55089487/34384dac-2e3f-4baa-9bc1-cfeb705beafb">

<img width="756" alt="image" src="https://github.com/supabase/supabase-flutter/assets/55089487/f5925912-3887-4c85-9ca7-73354a249170">

**Version (please complete the following information):**
macOS

➜ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale zh-Hans-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (4 available)
[✓] Network resources

  supabase_flutter: ^2.0.0-dev.2

**Comment by dshukertjr** [comment]
Closing as this one is fixed.
