### ISSUE TITLE
Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)

### ISSUE THREAD

**Issue by MishaCM** [supabase/supabase-flutter#727]
**Describe the bug**
The exception arises when attempting to execute the `Supabase.initialize()` method due to platform-specific code, resulting in the error: `[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)`.

**To Reproduce**
1. Try to write some native android code in MainActivity.kt
2. Run Supabase.initialize() in main.dart

**Expected behavior**
Should be able to write platform-specific code in project without encountering errors like the one mentioned when calling Supabase.initialize().

supabase_flutter_example 1.0.0+1
└── supabase_flutter 1.10.25
    ├── supabase 1.11.11
    │   ├── functions_client 1.3.2
    │   ├── gotrue 1.12.6
    │   ├── postgrest 1.5.2
    │   ├── realtime_client 1.4.0
    │   ├── storage_client 1.5.4

![Screenshot 2023-11-23 at 12 21 36 PM](https://github.com/supabase/supabase-flutter/assets/97153112/9acc885d-de05-401b-9676-6f28147ff16f)

**Comment by dshukertjr** [comment]
@MishaCM Would you be able to create a repo with minimal reproducible code that demonstrates this phenomena? I really do not think the supabase_flutter library has to do with the error you are facing, and you should be able to create platform channels as you would like.

**Comment by Vinzent03** [comment]
We've removed Hive anyway now.
