### ISSUE TITLE
When i update password then still recceived AuthChangeEvent.passwordRecovery event

### ISSUE THREAD

**Issue by liuchuancong** [supabase/supabase-flutter#729]
I forgot my password,and I reseted ,when hot load i still received this event.
![image](https://github.com/supabase/supabase-flutter/assets/36957912/081222f0-252b-4bd8-abba-5bc01c9b669c)

**Comment by dshukertjr** [comment]
You can find a summary of why this happens [here](https://github.com/supabase/supabase-flutter/issues/245#issuecomment-1287797807), but long story short, this is how deep links behave on debug mode, and it won't be an issue on published apps.
