### ISSUE TITLE
Warning during building apk: Module was compiled with an incompatible version of Kotlin

### ISSUE THREAD

**Issue by HeartwinJ** [supabase/supabase-flutter#732]
**Describe the bug**
I am trying to create an apk for my app, I get errors saying `Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.`. This not only happens on my app, but also on a new flutter project that only has `supabase_flutter`. Even the example apps do not build right. The build does generate an apk, but after installation, the app does not load, it just gets stuck on the splash screen, or shows a blank page.

**To Reproduce**
1. Create a new flutter project
2. Run `flutter pub add supabase_flutter`
3. Add 
```
await Supabase.initialize(
    url: 'YOUR URL',
    anonKey: 'YOUR KEY',
 );
```
to `main()` in `main.dart`
4. Run `flutter build apk`

**Expected behavior**
Build completes successfully without errors, and the resulting apk runs fine.

**Version**
On Windows, running `dart pub deps | findstr "supabase gotrue postgrest storage_client realtime_client functions_client"`  gives:
```
└── supabase_flutter 1.10.25
    ├── supabase 1.11.11
    │   ├── functions_client 1.3.2
    │   ├── gotrue 1.12.6
    │   ├── postgrest 1.5.2
    │   ├── realtime_client 1.4.0
    │   ├── storage_client 1.5.4
```

**Comment by dshukertjr** [comment]
Hopefully this StackOverflow post can solve your issue. 
https://stackoverflow.com/questions/67699823/module-was-compiled-with-an-incompatible-version-of-kotlin-the-binary-version-o

**Comment by HeartwinJ** [comment]
@dshukertjr As per the StackOverflow post you have shared, I tried updating my Kotlin version to the latest, but that still leaves me with the same error. Downgrading Kotlin to `1.6.0` also does not work saying that my project requires a newer version of the Kotlin Gradle Plugin.

In my `build.gradle`:
```
buildscript {
    ext.kotlin_version = '1.9.21'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

In my `gradle-wrapper.properties`:
```

distributionUrl=https\://services.gradle.org/distributions/gradle-8.1-all.zip
```

**Comment by dshukertjr** [comment]
@HeartwinJ 
Could you update your `Steps to reproduce` to include the command you used to build the apk?

**Comment by HeartwinJ** [comment]
@dshukertjr I have used `flutter build apk`, and have updated the same in the `Steps to reproduce`.

**Comment by dshukertjr** [comment]
@HeartwinJ What version of Flutter are you using? You can get this by running `flutter --version`

**Comment by HeartwinJ** [comment]
@dshukertjr Running `flutter --version` gives me:
```
Flutter 3.16.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db7ef5bf9f (9 days ago) • 2023-11-15 11:25:44 -0800
Engine • revision 74d16627b9
Tools • Dart 3.2.0 • DevTools 2.28.2
```

**Comment by dshukertjr** [comment]
@HeartwinJ 

Are you sure the build is failing? When I try it, I get similar warnings, but the build succeeds. If the build is actually failing, the cause is likely something else. 

```bash
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1336 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
e: /Users/tylershukert/Desktop/versionsample/build/sign_in_with_apple/.transforms/185a97cfbc76c905cbf90dfcae7e528d/transformed/out/jars/classes.jar!/META-INF/sign_in_with_apple_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /Users/tylershukert/.gradle/caches/transforms-3/889ce5bd12f1117e5357d5fcdb5e1305/transformed/core-1.10.1/jars/classes.jar!/META-INF/core_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /Users/tylershukert/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.22/636bf8b320e7627482771bbac9ed7246773c02bd/kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /Users/tylershukert/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.22/636bf8b320e7627482771bbac9ed7246773c02bd/kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /Users/tylershukert/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.22/636bf8b320e7627482771bbac9ed7246773c02bd/kotlin-stdlib-1.8.22.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /Users/tylershukert/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.8.22/1a8e3601703ae14bb58757ea6b2d8e8e5935a586/kotlin-stdlib-common-1.8.22.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
Running Gradle task 'assembleRelease'...                           51.7s
✓  Built build/app/outputs/flutter-apk/app-release.apk (18.8MB).
```

**Comment by HeartwinJ** [comment]
@dshukertjr 

The build is not failing, I have tried it a couple of times with other sample apps, and the generated apk seems to run fine. But the errors do show up, and that is a call for concern. Do the errors mean, that part of my code was not built right, or if some feature is not gonna work right.

The original app, for which I reported this issue had another bug that caused the blank screen.

**Comment by dshukertjr** [comment]
@HeartwinJ 
If the build succeeds and the apk is fine, then it's not an error, it's an warning, and it's nothing to be concerned about. 

The warning is coming from the sign_in_with_apple dependencies that we have. If it's bothering you that much, you can use the v2 developer preview. We have removed the sign_in_with_apple dependencies, so you should not receive this warning.
