### ISSUE TITLE
How Can i limit user update database?

### ISSUE THREAD

**Issue by liuchuancong** [supabase/supabase-flutter#735]
I found ```upstash```.```zuplo```.is there has simple methods in flutter?

**Comment by Vinzent03** [comment]
Please elaborate more what exactly you mean.

**Comment by liuchuancong** [comment]
Rate limiting, I want five requests per hour allowed to update.The database attack cost me a lot of credits.
![image](https://github.com/supabase/supabase-flutter/assets/36957912/845d6cd0-b61f-4f06-aa80-1c9096ec5e1e)

**Comment by liuchuancong** [comment]
Even I can't manually add a blacklist.

**Comment by liuchuancong** [comment]
zuplo provides interceptors, but my previous version didn't use interceptors, and if I continue to use the previous version without updating it, I'm still getting attacked all the time, with more than 6000 calls a day by that user, and I can't do anything about it!

**Comment by dshukertjr** [comment]
@liuchuancong 
Please follow the issue format and provide the necessary details. 

Also, this repo is the Flutter client library. Rate limiting is not something you do on the client library, as attackers can always access the service without using the client library. 

I'm going to close this issue, and if you want to submit a proper request, you can do so on our Github discussions page. 
https://github.com/orgs/supabase/discussions
