### ISSUE TITLE
importing breaks build

### ISSUE THREAD

**Issue by Rohan-raftlabs** [supabase/supabase-flutter#750]
importing the latest supabase_flutter package 1.10.25  to an otherwise empty project on flutter 3.13.6 breaks the build with loads of errors.

upgrading flutter to 3.16+ fixes the issue

**Comment by Vinzent03** [comment]
When upgrading flutter fixes the issue, what's the issue here?

**Comment by Rohan-raftlabs** [comment]
Nothing else just informed so there could be a warning you can close down
this issue but mention upgrading solves the issue so anyone else facing it
could simply upgrade in case they havent tried yet
I couldn't find a package compatibility list with flutter versions on pub
so maybe this will help.

Thanks for maintaining supabase_flutter
