### ISSUE TITLE
Proposal: Add caching to storage download

### ISSUE THREAD

**Issue by DanMossa** [supabase/supabase-flutter#751]
**Is your feature request related to a problem? Please describe.**
I've been creating the URLs and Auth headers and sending them to `CachedNetworkImage` to use due to me wanting to cache the images.

This prevents me from using a lot of the benefits that this packages includes when retrieving images.

**Describe the solution you'd like**
I would like for the ability to toggle a flag in order to cache images.
I should be able to cache per bucket, and override per image.

I was thinking of a field like
`Set<String> cacheStorageBuckets`

```dart
static Future<Supabase> initialize({
  required String url,
  required String anonKey,
  String? schema,
  Map<String, String>? headers,
  String? authCallbackUrlHostname,
  LocalStorage? localStorage,
  Client? httpClient,
  int storageRetryAttempts = 0,
  Set<String> cacheStorageBuckets,
  RealtimeClientOptions realtimeClientOptions = const RealtimeClientOptions(),
  AuthFlowType authFlowType = AuthFlowType.implicit,
  GotrueAsyncStorage? pkceAsyncStorage,
  bool? debug,
})
```

```dart
await Supabase.initialize(
  url: constants.URL,
  anonKey: constants.ANON_KEY,
  storageRetryAttempts: 2,
  cacheStorageBuckets : {'bucketOne', 'bucketTwo'}
);
```

```dart
/// Downloads a file.
///
/// [path] is the file path to be downloaded, including the path and file
/// name. For example `download('folder/image.png')`.
///
/// [transform] download a transformed variant of the image with the provided options
/// 
/// [useCache] is used to override the default set during initialization
Future<Uint8List> download(String path, {TransformOptions? transform, bool useCache}) async 
```

**Comment by dshukertjr** [comment]
The person here seemed like was trying to do the same thing that you are trying to do if I'm not wrong. 
https://github.com/supabase/supabase-flutter/issues/681

What exactly would happen if `useCache` is enabled for a `download()` operation here?

>This prevents me from using a lot of the benefits that this packages includes when retrieving images.

What are some benefits that are being lost when using `CachedNetworkImage` that you mention?

**Comment by DanMossa** [comment]
> What exactly would happen if `useCache` is enabled for a `download()` operation here?
If the bucket/file is cached, then I won't fetch the file over the internet if it's already been downloaded before.
I would use `https://pub.dev/packages/flutter_cache_manager` or the already used `shared_preferences` plugin to implement an LRU cache of X items.

> What are some benefits that are being lost when using `CachedNetworkImage` that you mention?
When just passing in the `imageUrl` and the reverse engineered `headers`:
```dart
  return CachedNetworkImage(
    cacheKey: cacheKey,
    imageUrl: imageUrl,
    width: width,
    height: height,
    memCacheHeight: cacheHeight < 0 ? null : cacheHeight,
    fit: fit,
    httpHeaders: headers,
    placeholder: (context, url) {
      return loadingBuilder!;
    },
    errorWidget: (context, url, error) {
      Logger.error(
        'Unable to load image from $url',
        error: error,
        location: 'networkImageWidget.CachedNetworkImage',
      );
      return const Icon(Icons.error);
    },
  );
}
```
* There can be drift if Supabase required a different set of headers and my custom implementation isn't updated.
* CachedNetworkImage does not stream the file, which can cause memory issues compared to the `supabase_flutter` implementation.
* The `supabase_flutter` implementation uses a retry mechanism which `CachedNetworkImage` does not.

@dshukertjr

**Comment by dshukertjr** [comment]
@DanMossa 
Sorry for the delayed response.

Just to double check, we are talking about displaying an image stored in a private bucket, correct? I don't quite understand how the auth header comes into the conversation. You should be able to obtain the image URL from `createSignedURL` method, and shouldn't have to pass the auth header to any widgets, but if I'm missing some context, please do let me know.

For public buckets, things are simple. You have a single URL that you can access the image file. You can just pass the URL to `CachedNetworkImage` to have it cached on the client side, and when the client-side cache has expired, the `CachedNetworkImage` can go fetch the image again with the same URL.

For private buckets on the other hand, since the URL changes every time the signed URL is generated, the image URL cannot be used as the cache key. You could probably use the image path as the cache key. You could probably use the `errorListener` to update the image URL as needed like this:

```dart
final imagePath = 'path/to/image.png';

/// It doesn't matter what we have here as we will get the correct URL if the `CachedNetworkImage` throws an error
String _imageUrl = '';
...
/// If the cache is available with the imagePath, then it will be displayed. Otherwise, the a new imageURL is obtained within the `errorListener()` callback.
CachedNetworkImage(
  cacheKey: imagePath,
  imageUrl: _imageUrl,
  errorWidget: (context, url, error) {
    // users will just see a loader while a new URL is being fetched.
    return Center(child: CircularProgressIndicator());
  },
  errorListener: (_) async {
    // Create a new signed URL when the cache is no longer available
    final imageUrl = await supabase.storage
        .from('bucket')
        .createSignedUrl('path/to/image.png', 300);
    setState(() {
      _imageUrl = imageUrl;
    });
  },
);
```

**Comment by dshukertjr** [comment]
I want to close this issue with the [comment above](https://github.com/supabase/supabase-flutter/issues/751#issuecomment-1851494588), but if I had misinterpreted anything and am not providing the ideal solution, let me know and we can reopen it!
