### ISSUE TITLE
Supabase auth admin missing proper getUser function

### ISSUE THREAD

**Issue by pyciko** [supabase/supabase-flutter#752]
**Is your feature request related to a problem? Please describe.**
The NodeJS version has an admin function called getUser, this function accepts a custom token and practically allows verifying the user identity when handling a request in a custom server environment. This function seems to be missing in the current Dart package.

**Describe the solution you'd like**
A function with the same functionality being added to the package

**Describe alternatives you've considered**
At least describe the API request needed to get the same information (I tried reading the source code and trying to replicate the desired API request myself, but I couldn't find all the needed info)

**Additional context**
Example use case: There's a custom-made Dart TCP server that needs to be integrated into the project. The server first needs to verify the identity of the connecting socket and drop the connection if it's not authentic. It gets a special auth request package, parses it, gets the user access token sent by them, passes this token to a supabase.auth.admin.getUser(token) function and in return either gets a valid user object or null, indicating that the verification has failed.

Edit: added example use case

**Comment by pyciko** [comment]
Yeah I know and I'm doing exactly that right now, but the downside is that I have to store it as env var on the server side which means a) it has to be manually updated if I change it in Supabase settings b) it's just a sensitive info that I want to avoid storing:) Huge thanks for the pull request!

**Comment by pyciko** [comment]
Also, just to make sure that I understand everything correctly, you said
>  You can use the jwt secret to encrypt the header and payload 
but I guess you meant "sign" instead of "encrypt", right?

**Comment by Vinzent03** [comment]
Yeah I meant to sign the header and payload.
