### ISSUE TITLE
Recovering a session does not fully validate that the JWT will work on the backend

### ISSUE THREAD

**Issue by point-source** [supabase/supabase-flutter#755]
**Describe the bug**
It seems that it's possible under a few specific conditions to have supabase_flutter restore a JWT from a persisted session which, while valid on its own, is not valid for the current supabase backend to which it is connected.

Conditions under which this can occur:
- Switching between dev / staging / prod instances using env flags
- Changing supabase URLs or Keys of the production instance and publishing an app update
- Passing a manually stored persisted session string to the recoverSession() method

**To Reproduce**
1. Set up a local instance of supabase (via cli tool)
2. Use supabase_flutter according to the documentation to sign a user in and persist the session
3. Switch the env vars to point to a remote supabase instance instead of local
4. Relaunch the app and try to restore the session
5. Observe that the session appears to have successfully restored and the app is now attempting to nav to a protected page
6. Observe that once a request is made to the backend for data (like a db request, etc), it fails with a "PGRST301" error

**Expected behavior**
It should not be possible to restore a session from one supabase instance onto another without throwing an error.

I realize this is an event that is unlikely to happen in real world use but it is quite inconvenient as a dev. We frequently switch between building for local vs staging vs prod and having it throw auth errors every time I switch can be irritating.

It could also affect real world users if the devs choose to point an app at a new supabase instance (changing url or key) and don't realize they need to manually clear persisted strings when users launch the new version of the app.

Additionally, there is a potential security concern here in that if the app developer caches sensitive data locally and relies on an authenticated state to access that data, a valid but mismatched persistence token could allow a bad actor to access parts of the app that would normally require sign-in. (of course, anything cached locally or encoded into the app can only ever be so secure so this reasoning is limited)

Furthermore, since the current restoration happens completely offline, it seems that a user could make use of a revoked JWT as well but this risk is already well documented in supabase docs and likely out of scope for this ticket.

**Possible Solutions**
- Keep existing behavior and require devs to wrap all backend calls with error handling that can detect this error and sign the user out (tedious for the dev and prone to error since exceptions can throw inside futures or streams across the api surface)
- Require devs to perform a check to see if the env has changed (requires encoding env state into the persisted app state)
- Make a call to the backend when a session is recovered in order to make sure the JWT is valid and not mismatched or revoked (requires an extra API call for every restoration)
- Hash the supabase connection info (URL + Token) and store it as part of the persistence string. This way it can be checked on restore to make sure that persistence data belongs to the same server it is now being sent to and that the supabase access tokens have not been rotated. (secure + offline, allows an error to be thrown instantly)

I recommend the last approach be integrated into this library as default behavior. Additionally, a flag could be added to the restore method that allows an online backend validation to be requested/forced.

Additionally, once a session recovery fails, it may be a good idea to emit an `AuthChangeEvent.signedOut` as [described here](https://github.com/supabase/supabase-flutter/issues/452).

**Version (please complete the following information):**
- OS: macOS Sonoma 14.1.2 (23B92)
- Dart SDK version: 3.2.3
```sh
Flutter 3.16.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0366e0a3f (6 days ago) • 2023-12-05 19:46:39 -0800
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
```
```sh
├── supabase_flutter 1.10.25
│   ├── supabase 1.11.11
│   │   ├── functions_client 1.3.2
│   │   ├── gotrue 1.12.6
│   │   ├── postgrest 1.5.2
│   │   ├── realtime_client 1.4.0
│   │   ├── storage_client 1.5.4
```

**Additional context**
This issues seems adjacent / related to #452

**Comment by dshukertjr** [comment]
Thanks for opening this issue. This issue should be solved in coming up v2 of supabase_flutter as the session is stored with different local storage key for every supabase project.

You can check out the developer preview for v2 here, or there should be a stable v2 released very soon.
https://pub.dev/packages/supabase_flutter/versions/2.0.0-dev.4
