### ISSUE TITLE
[2.0.0] Can we have a migration guide from `SupabaseClient.auth.signInWithOAuth()`

### ISSUE THREAD

**Issue by mariopepe** [supabase/supabase-flutter#762]
Before I was using `SupabaseClient.auth.signInWithOAuth(...)` on the web.

In `2.0.0` this method is not available anymore.

How to replace? Can we add it to the readme too?

In the actual readme it is still mentioned the now removed method `signInWithOAuth`

**Comment by dshukertjr** [comment]
Oops, `signInWithOAuth` should be available. Fixing this right now.

**Comment by dshukertjr** [comment]
With v2.0.1 of supabase_flutter you should see the missing `signInWithOAuth()` again!
