### ISSUE TITLE
Supabase OAuth with LaunchMode.inAppWebView can't redirect to deeplink.

### ISSUE THREAD

**Issue by Elias-AR** [supabase/supabase-flutter#766]
**Describe the bug**
I'm using supabase Oauth for social log in within my flutter app. At first I didn't have a Launch mode defined and it was working fine, however, Apple rejected the app because the log in process was made in an external browser instead of inside the app. this is where I added the launch mode.

**old code:** works fine
```
final supabase = SupaFlow.client;
const bool kIsWeb = bool.fromEnvironment('dart.library.js_util');
Future signInWithGoogle(BuildContext context) async {
  await supabase.auth.signInWithOAuth(
    Provider.google,
    context: context,
    redirectTo: kIsWeb ? null : 'redirect deeplink',
  );
```

**new code:**

```
final supabase = SupaFlow.client;
const bool kIsWeb = bool.fromEnvironment('dart.library.js_util');
Future signInWithGoogle(BuildContext context) async {
  await supabase.auth.signInWithOAuth(
    Provider.google,
    authScreenLaunchMode: LaunchMode.inAppWebView,
    context: context,
    redirectTo: kIsWeb ? null : 'redirect deeplink',
  );
```
**Result**

Google sign in would open inApp, and sign in successfully done, however, a page appears with "Open link in app?" mention and it doesn't redirect to the link when Open is clicked. Some empty text selection appears and nothing happens. (see screenshots).

**Logs**
10.9.0 - [FirebaseAnalytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    "_cpb" = 1;
    "_cpt" = cpit;
    "_fpb" = "CKQHEK4D***==";
    "_iumchkactval" = 1;
    "_iumenbl" = 1;
    "_osl" = "https://***.page.link/N8fh";
    "_plt" = 10**;
    "_uit" = 104***;
    apn = "io.***.***";
    cid = 20**********7;
    ibi = "io.*******";
    isi = 647*****9;
    link = "https://...";
}

**To Reproduce**
call signInWithGoogle(context) on login button tap. redirect link could be the home page.
log in with google account the hit Open when "Open link in app" appears 

**Expected behavior**
after sign in with google, redirect to home page defined in the deeplink.

**Screenshots**
![image](https://github.com/supabase/supabase-flutter/assets/133224976/ab08141e-191b-4a28-858c-0bb0c4f284b0)

**Version (please complete the following information):**
├── functions_client 1.3.2
├── gotrue 1.12.6
├── postgrest 1.5.2
├── realtime_client 1.4.0
├── storage_client 1.5.4
├── supabase 1.11.11
│   ├── functions_client...
│   ├── gotrue...
│   ├── postgrest...
│   ├── realtime_client...
│   ├── storage_client...
├── supabase_flutter 1.10.24
│   ├── supabase...

**Additional context**
the logs are weird because the same link works when it's an external browser.
when running from Android studio, 

on another note, is there a way to disable the "open link in app" page and automatically redirect to app ?

**Comment by dshukertjr** [comment]
On what platform are you running this on, iOS, Android, web? If you are using iOS or Android, you should use native Google sign in instead of signInWithOAuth. 
https://supabase.com/docs/guides/auth/social-login/auth-google?platform=flutter

**Comment by Elias-AR** [comment]
> On what platform are you running this on, iOS, Android, web? If you are using iOS or Android, you should use native Google sign in instead of signInWithOAuth. https://supabase.com/docs/guides/auth/social-login/auth-google?platform=flutter

I managed to make the redirection work with this:

```
final supabase = SupaFlow.client;
const bool kIsWeb = bool.fromEnvironment('dart.library.js_util');
Future signInWithGoogle(BuildContext context) async {
  await supabase.auth.signInWithOAuth(
    Provider.google,
    authScreenLaunchMode: LaunchMode.inAppWebView,
    context: context,
  );
```

However, both google and apple are not taking the accounts used on the phone. instead they're asking to sign in again which defies the purpose of social sign in.

I'll try native
