### ISSUE TITLE
signInWithOAuth not redirection to my app via deeplink

### ISSUE THREAD

**Issue by Padi142** [supabase/supabase-flutter#767]
**Describe the bug**
Hey! I've been following [this guide](https://supabase.com/docs/guides/getting-started/tutorials/with-flutter) to implement Supabase auth in my app. I wanted to use Discord as an OAUTH solution. I was following the steps from [here](https://supabase.com/docs/guides/auth/social-login/auth-discord) but I got stuck at the final step.

When I log in via discord, I believe it should redirect me to my app via the deep link. Instead I get redirected to an url that goes somethink like `https://myProject.supabase.co/[MyDeepLink]/code?XXXX` and in the device browser. I get `NO API KEY FOUND IN REQUEST` error. 
Any Idea how to fix this ?

**To Reproduce**

I call this when trying to log in 
```
final supabase = Supabase.instance.client;
    await supabase.auth.signInWithOAuth(
      OAuthProvider.discord,
      redirectTo: "io.supabase.myapp//login-callback/",
    );
  }
```

I initialize supabase like this
```
await Supabase.initialize(
      url: 'https://projectRef.supabase.co',
      anonKey: 'myAnonKey',
      debug: true,
      authOptions: const FlutterAuthClientOptions(
        authFlowType: AuthFlowType.pkce,
      ));
```

Ive added this to my AndroidManifest

```
<activity>
...
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <!-- Accepts URIs that begin with YOUR_SCHEME://YOUR_HOST -->
                <data android:scheme="io.supabase.myapp" android:host="login-callback"/>
            </intent-filter>
        </activity>
```

My supabase auth panel settings
![image](https://github.com/supabase/supabase-flutter/assets/30501084/df4da494-79c3-4bbe-b811-6029e882adcf)

Discord redirect
![image](https://github.com/supabase/supabase-flutter/assets/30501084/9bf87c48-8000-4d5d-8142-c92b90f95e4a)

**Expected behavior**
I expect the redirect to end up in my app via deeplink

**Screenshots**
![image](https://github.com/supabase/supabase-flutter/assets/30501084/9bf1c975-f6e8-4ac7-bb2e-652e9fcb86b7)
![image](https://github.com/supabase/supabase-flutter/assets/30501084/d64d7ffc-b364-4157-8a56-189a8dccddba)

**Version (please complete the following information):**

Android

**Additional context**

Ive tried different providers but I always end up at the NO API KEY page :/

If anyone can help me figure this out, I would be very thankfull

**Comment by dshukertjr** [comment]
You seem to have an invalid deep link. Between your scheme (io.supabase.myapp) and host (login-callback), you need `://`, but you are missing the `:`. 

Try using the following to implement it!
`io.supabase.myapp://login-callback/`
