### ISSUE TITLE
[auth] `Site URL` redirects me to my prod domain, hence I cannot be authenticated while debugging, this is destroying my dx

### ISSUE THREAD

**Issue by mariopepe** [supabase/supabase-flutter#776]
I have set up the `Site URL` parameter in `Authentication > URL Configuration` with my production domain (of course).

As a result If i login with Flutter Web running on my Chrome debug development environment (on `http://localhost:3000/`) after I perform sign in with any Oauth2 provider (Google, Apple, etc.) I am redirected from `http://localhost:3000/` to `https://my-production-domain.com/`

So that I never enter authenticated state on my debug/development machine.

And I cannot test all the states of my app when I am authenticated.

How to solve this?

ib4: when I do `signInWithOAuth` I already put a `redirectTo` parameter but it is always ignored and overridden from the `Site URL` configured on the Supabase dashboard...

```dart
await _supabaseClient.auth.signInWithOAuth(
    Provider.google,
    redirectTo: 'http://localhost:3000',
);
```

<img width="531" alt="Screenshot 2023-12-22 at 12 00 01" src="https://github.com/supabase/supabase-flutter/assets/14803862/74b4b0e6-07be-462a-8c8d-52507999495e">

**Comment by dshukertjr** [comment]
@mariopepe 
What you have in your `Redirect URLs` in your dashboard and what you pass to the `redirectTo` parameter has to exactly match, or match using the [wild card patterns](https://supabase.com/docs/guides/auth/concepts/redirect-urls#use-wildcards-in-redirect-urls).

You have a `/` at the end in your dashboard and no `/` in your code.
