### ISSUE TITLE
upgrade error

### ISSUE THREAD

**Issue by andim27** [supabase/supabase-flutter#777]
In supabase flutter version 1.* working code was:

1) String sUrl = Supabase.instance.client.supabaseUrl;
2) await sbClient.auth.signInWithOAuth(Provider.github);

In version 2.* it's not works:

Error:
1)The getter 'supabaseUrl' isn't defined for the type 'SupabaseClient'.
2)Undefined name 'Provider'.

How to correct such calls?
Please correct the documentation

**Comment by dshukertjr** [comment]
@andim27 
Sorry for the inconvenience. Would you be able to point me to the out-dated documentation that you found these codes?

`supabaseUrl` is now a private variable, and is not accessible, but there shouldn't be much use cases for accessing it. What are you using it for?

`Provider` has been renamed to `OAuthProvider`
```dart
await sbClient.auth.signInWithOAuth(OAuthProvider.github);
```

You can find the major updates from v1 to v2 [here](https://supabase.com/docs/reference/dart/upgrade-guide)

**Comment by andim27** [comment]
Please correct documentation:
[](https://supabase.com/docs/reference/dart/auth-signout)
Mentioned to : 
`await supabase.auth.signInWithOAuth(Provider.github);`

**Comment by dshukertjr** [comment]
@andim27 
It seems like there was a hiccup on the docs. Will look into it and make sure the upgrade guide is back up. 

By the way, I asked this in my previous comment as well, but would you be able to point me to the out-dated documentation that you found these codes?

**Comment by dshukertjr** [comment]
Upgrade guide is back up. Sorry for the hiccup. 
https://supabase.com/docs/reference/dart/upgrade-guide
