### ISSUE TITLE
Add serialization to withConverter 

### ISSUE THREAD

**Issue by DanMossa** [supabase/supabase-flutter#78]
We currently are able to specify withConverter when retrieving data from the database, but we're unable to to use convert the data back to your model.

https://github.com/supabase-community/postgrest-dart/pull/48
Basically like this PR but add `toSupabase`

**Comment by bdlukaa** [comment]
like a `toJson`? I believe it'd be a lot better to do this on your model.

#### Model
```dart
class User {
  final String id;
  
  const User(this.id);
  
  Map<String, dynamic> toJson() {
    return {
      'id': id,
    };
  }
}
```

#### Postgrest call
```dart
final newUser = User('new-user-id');
postgrest.from('users').insert(
  newUser.toJson(),
);
```

Is this what you're talking about?

**Comment by dshukertjr** [comment]
@DanMossa Yeah, Firestore has something like this right? I never quite understood the benefit of it, and I always do it like @bdlukaa as well. What is the benefit of having such method?

**Comment by DanMossa** [comment]
Yeah! It was mostly for feature parity. It just seemed a little weird to have it on the response but not the request. Nothing urgent but would be nice to have.

**Comment by bdlukaa** [comment]
@DanMossa how's it like on firestore?

**Comment by dshukertjr** [comment]
Coming back to this in a super long time. 

I actually like the current implementation of `withConverter`, and don't find the `withConverter` implementation on Firestore that useful. 

The `toSupabase` parameter suggested [here](https://github.com/supabase/supabase-flutter/issues/78#issue-1206439927) is to convert the objects to `Map<String, dynamic>` when writing to the database, but you can actually pass custom class directly to `insert` or `upsert` as long as the class has `toJson` implemented. 

```dart
class Foo {
  Foo(this.bar);
  final int bar;

  Map<String, dynamic> toJson() {
    return {'bar': bar};
  }
}
...
await supabase.from('foo').insert(Foo(1));
await supabase.from('foo').insert([Foo(2)]);
```
