### ISSUE TITLE
Supabase functions on flutter? how to call them

### ISSUE THREAD

**Issue by nokia6290** [supabase/supabase-flutter#780]
Hello all,

Would like to ask for direction.

Supabase is great as a tool but **Nightmare** when it comes to documentation...

I setup the project, created basic tables, sql query function.

and now on Flutter I want to run that query and fetch my data.

 Except the data is always empty list, but on SQL query the query returns me all the data I'm looking for.
 
 I see that supabase_flutter plugin before used to add .exceute() at the end. But now its not available.
 
 How does one run functions on supabase/flutter?
 
   Future<List<SupabaseExerciseModel>> fetchExerciseDetails2() async {
    final response = await Supabase.instance.client.rpc('get_exercise_details');

    // Check if the response is a list
    if (response is! List) {
      throw Exception('Unexpected response format');
    }

    // If the list is empty, it might indicate an issue or simply no data
    if (response.isEmpty) {
      throw Exception('No data received or possible error in fetching data');
    }

    // Process the data
    final dataNew =
        response.map((e) => SupabaseExerciseModel.fromJson(e as Map<String, dynamic>)).toList();
    print(dataNew.length);

    return dataNew;
  }

**Comment by dshukertjr** [comment]
@nokia6290 
You probably have [row level security](https://supabase.com/docs/guides/auth/row-level-security) on with no policies. 

Create appropriate policies or turn off RLS for your tables and you should see the data with the following call from your Flutter app!
```dart
final data = await Supabase.instance.client.rpc('get_exercise_details'); // data should contain whatever your `get_exercise_details` function returns.
```

**Comment by nokia6290** [comment]
@dshukertjr Thank you.

That helped !

Thank you very much.

**Comment by dshukertjr** [comment]
By the way @nokia6290, was there a particular tutorial or an article you followed when you were working on the code you shared? I want to better understand the path you took so that we can better guide people like you in the future.
