### ISSUE TITLE
Support Distinct functionality in Flutter SDK

### ISSUE THREAD

**Issue by jassirr** [supabase/supabase-flutter#782]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way provided by the SDK to get the distinct records of a particular query.

**Describe the solution you'd like**
```dart
await supabaseClient
  .from(Constants.TABLE_NAME)
  .select('id', distinct: true)
  .eq('user_id', userId);
```
or
```dart
await supabaseClient
  .from(Constants.TABLE_NAME)
  .select('id',)
  .eq('user_d', roomId).distinct;
```

**Additional context**
This can reduce a burden of additionally not writing a method of providing the distinct results of queries.

**Comment by jassirr** [comment]
@dshukertjr @bdlukaa @DanMossa

**Comment by dshukertjr** [comment]
Hi @jassirr 

Thanks for this feature request. Currently, PostgREST, the automatic API generation tool that Supabase use, does not provide a distinct select functionality. You can read some of the reasonings why it's not implemented [here](https://github.com/PostgREST/postgrest/issues/915#issuecomment-322500725).

However, `Group By` is coming to PostgREST, which you could use to query similar results. You can read more about it here:
https://supabase.com/blog/postgrest-12#aggregate-functions

Note that aggregate functions are not yet supported on Supabase at this point. 

I'm going to close this issue as aggregate functions will be available without requiring any updates on the supabase-flutter client library, but if you have further questions/ comments, feel free to leave them!

**Comment by anshunjain** [comment]
When will postgrest-12 be available on SUPABASE. My logs seem to suggest that we are on postgrest 11.2 @dshukertjr

**Comment by Vinzent03** [comment]
@anshunjain In case you still miss the update, here's the [documentation](https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects#upgrade-your-project)
