### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by ishanvaghani** [supabase/supabase-flutter#784]
Recently, I started making open-source contributions. I made some contributions to Flutter and Android apps. Now I want to make a contribution to some libraries. I have used Supabase personally for one of my Flutter projects, so it will be great if I can contribute to this library. Let me know if there is anything for me (bug fix, feature, improvement, or unit test).

**Comment by dshukertjr** [comment]
@ishanvaghani Thanks for your interest. Feel free to play around with the library or go through the issues and find anything you can help with! Feel free to submit a PR at any time!
