### ISSUE TITLE
Supabase stops initialization on safari after page refresh

### ISSUE THREAD

**Issue by kaliosek** [supabase/supabase-flutter#794]
**Describe the bug**
On flutter web on safari flutter app doesn't finish  await Supabase.initialize if page is refreshed.
In log I have: 
"***** Supabase init completed Instance of 'Supabase'"
"Creating objectStore box in database supabase_authentication..."
and stops here.

This works well on Chrome or osx app.

If I delete app data from browser app run with no problem. but one or many refreshes stops app.

**To Reproduce**
1. Create new flutter project
2. Add supabase_flutter dependency
3. add initialisation code:
`Future<void> main() async {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  await Supabase.initialize(
    url: 'correct url',
    anonKey:' correct anon key',
  );
  runApp(const MyApp());
}`
4. Build and run default app in safari.
5. If page is loaded correctly, refresh page.

**Expected behavior**
Supabase should be initialised even if data in local storage exist.

**Screenshots**
app has white screen

**Version (please complete the following information):**
On Linux/macOS
Please run `dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"` in your project directory and paste the output here.
supabase_safari_localstorage_error 1.0.0+1
└── supabase_flutter 2.2.0
    ├── supabase 2.0.4
    │   ├── functions_client 2.0.0
    │   ├── gotrue 2.3.0
    │   ├── postgrest 2.1.0
    │   ├── realtime_client 2.0.0
    │   ├── storage_client 2.0.0

On Windows
Please run `dart pub deps | findstr "supabase gotrue postgrest storage_client realtime_client functions_client"` in your project directory and paste the output here.

**Additional context**
I think this is related with use SharedPreferences on web. Before 2.0.0 it works well.
This behaviour is always the same if I push new version of app to server.

**Comment by dshukertjr** [comment]
I am unable to reproduce the issue with the steps you provided, and works just fine for me. Are there any extra steps that you haven't mentioned like authenticating or something?

**Comment by kaliosek** [comment]
Hi I can reproduce this in every case :(
I attached video that shows this problem:

https://github.com/supabase/supabase-flutter/assets/67379323/f5c386ca-7f52-41c8-9bb0-e2fe3942306c

**Comment by dshukertjr** [comment]
@kaliosek 
Okay, I can reproduce it now. It seems like this only happens when you refresh after opening the dev tools, but is that the behavior you are seeing as well?

**Comment by dshukertjr** [comment]
It seems like for some reason when the dev tool is open on Safari, `await Hive.openBox(_hiveBoxName, encryptionCipher: encryptionCipher);` hangs and never completes or fails. 

Possibly related to https://github.com/isar/hive/issues/1024

**Comment by Vinzent03** [comment]
But why does it try to open a hive box? Shouldn't it delete the box after migrating to Shared Preferences, which should have happened on the web page load before?

**Comment by dshukertjr** [comment]
@Vinzent03 
Good point. I did some more digging, and here are some findings. 

With Safari dev tool open, [`Hive.boxExists(_hiveBoxName)`](https://github.com/supabase/supabase-flutter/blob/main/packages/supabase_flutter/lib/src/local_storage.dart#L194) always returns `true`. This causes the code to attempt to open or delete a non-existing hive box, which just hangs without throwing errors. 

It might not be a beautiful solution, but I wonder if we can just set a timeout for opening the hive box so that when it times out, it just aborts the migration process.
