### ISSUE TITLE
If you specify TransformOptions in the getPublicUrl method and retrieve the URL, an error will occur when retrieving it.

### ISSUE THREAD

**Issue by Pregum** [supabase/supabase-flutter#795]
Hello, thanks for this useful software !
I have one question regarding "Supabase Storage".

**Describe the bug**

If you specify TransformOptions when using the getPublicUrl method to retrieve images stored in the public bucket, the issued URL will be different and a retrieval error will occur.

If the usage is different, it would be helpful if you could tell me the correct way to use it.

Below is a sample of the URL that will be issued.

* URL when TransformOptions is specified

https://msluaclncpyqmjcvgssh.supabase.co/storage/v1/render/image/public/artworks/17/CAP_384866B9-5121-48AB-87C8-74EEEF3A72ED.jpg?width=480&height=560&resize=contain

* URL when TransformOptions is not specified

https://msluaclncpyqmjcvgssh.supabase.co/storage/v1/object/public/artworks/15/CAP_EDD85C63-8C1E-42DF-A8BD-3AF404FF913A.jpg?resize=contain

**To Reproduce**

1. Create a Supabase bucket. A bucket called ('artworks' in the example) is created.
2. Upload the image to bucket.
   * At this time, FileOptions is not specified
3. Generate a public URL using the `getPublicUrl()` method of the supabase-flutter plugin.

```dart
         final uploadPath = '$artworkImageId/$filePath';
         debugPrint('uploadPath: $uploadPath for sample');
         final response =
             await _client.storage.from('artworks').upload(uploadPath, file);

         final imageUrl = _client.storage.from('artworks').getPublicUrl(
               uploadPath,
               transform: TransformOptions(
                 resize: ResizeMode.contain,
                 width: width ?? 480,
                 height: height ?? 560,
               ),
             );
````

We have confirmed that it can be obtained if TransformOptions is not specified.

**Expected behavior**

If you find that it is being used in an unintended manner, we would appreciate it if you could point it out to us.

**Screenshots**

* Attached is a screenshot of artwork storage settings.

<img width="958" alt="image" src="https://github.com/supabase/supabase-flutter/assets/19755685/325a19c3-9f5d-42fc-bb4c-55ffefeebdea">

<img width="1379" alt="image" src="https://github.com/supabase/supabase-flutter/assets/19755685/75d995b0-41d3-480f-a3a7-93a9c08acee2">

**Version (please complete the following information):**

* supabase-flutter: 2.1.0

```sh
├── supabase_flutter 2.1.0
│   ├── supabase 2.0.3
│   │   ├── functions_client 2.0.0
│   │   ├── gotrue 2.2.0
│   │   ├── postgrest 2.1.0
│   │   ├── realtime_client 2.0.0
│   │   ├── storage_client 2.0.0
```

* Flutter version: 3.16.4

```sh
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.1.1 23B81 darwin-arm64, locale ja-JP)
    • Flutter version 3.16.4 on channel stable at /Users/pregum/fvm/versions/3.16.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (5 weeks ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4
```

**Additional context**

The reason I want to use TransformOptions is because I want to get the thumbnail image from the original.

**Comment by dshukertjr** [comment]
Hi @Pregum,

Currently image transformations feature is available on Supabase pro plan and above, but is your Supabase instance a pro instance? If so, you can reach out to supabase.help about the image transformation not working properly. 
<img width="1230" alt="Screenshot 2024-01-17 at 10 34 28" src="https://github.com/supabase/supabase-flutter/assets/18113850/37da3891-5fb1-4b38-9de7-84b942c6cb38">

**Comment by Pregum** [comment]
Hi @dshukertjr,

thank you for your reply!

> The image conversion feature is currently available on Supabase Pro plans and above, but is my Supabase instance a Pro instance?

I should have looked for the documentation.
Thank you for the information.
No, I'm currently using the free plan.
Since the app is not large enough to require the Pro plan yet, we would like to focus on implementing other features first.

My question is solved!
Thank you for your quick reply.
