### ISSUE TITLE
im getting Function not found error in my  flutter app when invoke the function but this exact function run properly in sql editor 

### ISSUE THREAD

**Issue by 21prnv** [supabase/supabase-flutter#796]
![Screenshot from 2024-01-15 14-53-40](https://github.com/supabase/supabase-flutter/assets/110466571/b845beb4-173b-4bd2-9ea4-a85e6efdc3ef)

Code:
![Screenshot from 2024-01-15 14-55-14](https://github.com/supabase/supabase-flutter/assets/110466571/a744df84-69ac-4f0d-a5c4-95c0f96cfbb1)

Error: 
![Screenshot from 2024-01-15 14-56-12](https://github.com/supabase/supabase-flutter/assets/110466571/862023e7-e082-4fde-bbbb-b3d49bbb58d9)

Sql output:
![image](https://github.com/supabase/supabase-flutter/assets/110466571/2a56ffff-92c3-4b83-9732-223828709cc3)

**Comment by Vinzent03** [comment]
You have a database function, which you have to call over the REST endpoint as shown [here](https://supabase.com/docs/reference/dart/rpc). In your flutter code you are trying to call an edge function, which is a different Supabase product.
