### ISSUE TITLE
Use hive instead of shared_preferences

### ISSUE THREAD

**Issue by bdlukaa** [supabase/supabase-flutter#8]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, the way to store the user session is made by the plugin `shared_preferences`. It is not a secure storage, making the user info vunerable.

## Describe the solution you'd like

Make use of a more secure storage solution, such as [hive](https://pub.dev/packages/hive), since it's lightweight, fast and has encryption built-in. This is the storage solution used by [firedart](https://pub.dev/packages/firedart), the pure-dart firebase implementation.

## Describe alternatives you've considered

Some other storage solutions, but they have some downsides:

- [shared_preferences](https://pub.dev/packages/shared_preferences): it's not secure, making the user info vunerable.
- [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage): it doesn't support all the platforms, it's not lightweight and is slow.
- [sqflite](https://pub.dev/packages/sqflite): it's not fast and doesn't support all the platforms.

With all the downsides presented above, hive is the best storage solution to store the user session: it's fast, lightweight and has built-in encryption.

**Comment by dshukertjr** [comment]
Hi @bdlukaa, 

You raise a good point about hive being fast according to its bench mark test. 
One question, and I do apologize if I am wrong, but doesn't hive also require additional secure storage if you want to make it secure?
https://docs.hivedb.dev/#/advanced/encrypted_box?id=encrypted-box

**Comment by bdlukaa** [comment]
@dshukertjr it does, but it shouldn't be a big deal.

Flutter apps are encrypted by default (and it's very hard to reverse engineer it) and the key will likely not leak, specially if the app is obfuscated using the `--obfuscate` param is used when building the app. See https://flutter.dev/docs/deployment/obfuscate#obfuscating-your-app for more info

**Comment by bdlukaa** [comment]
Note that the key, once defined, can't be changed. If so, it'll result in wrong user information
