### ISSUE TITLE
Supabase Storage Buckets Not Visible When Using Supbase Dart Client

### ISSUE THREAD

**Issue by caseycrogers** [supabase/supabase-flutter#800]
**Describe the bug**
Querying storage from a Dart (not flutter) supabase client with the anon api key silently fails. Would be nice if it would fail loudly or just work.

**To Reproduce**

With at least one public bucket present in storage:
```dart
import 'package:supabase/supabase.dart';

Future<void> readBuckets() async {
  final SupabaseClient supabase = SupabaseClient(
    '<my supa url>',
    '<my anon key>',
  );
  print(await supabase.storage.listBuckets()); // prints an empty list.
}

```

**Expected behavior**
Either:
1. An exception on client initialization telling me anon keys aren't supported here
2. A forbidden exception when attempting an unsupported action (eg list buckets)
or
3. The client supports anon keys

**Comment by dshukertjr** [comment]
@caseycrogers 
To query bucket information, you need to add a select RLS policy. The reason why it does not throw any errors is because Postgres is designed to just return whatever the user has access to. In your case, you don't have access to anything, so it just returns an empty array. 

Generally, though, you shouldn't need to get the list of buckets from the client, as buckets are not meant to be dynamic. 

You can learn more about it in the access control section of the docs:
https://supabase.com/docs/guides/storage/security/access-control

**Comment by caseycrogers** [comment]
Thanks! Listing buckets was just a contrived example, some requests were returning empty data, some were throwing with 404.

Since the bucket is public, shouldn't trying to read a given bucket+path succeed regardless of my RLS policies?
IIRC that was failing as well but maybe I'm misremembering.

**Comment by dshukertjr** [comment]
@caseycrogers 
>Thanks! Listing buckets was just a contrived example, some requests were returning empty data, some were throwing with 404.

Yes, we inherit how Postgres works. Postgres will throw for invalid insert, but will just perform an "empty" operation for select, update, or delete without proper permission. That is why we have the benefit of being able to just query the entire table from the client side and get back only those that the user has permission to read. It's pretty nice once you get used to it. 

>Since the bucket is public, shouldn't trying to read a given bucket+path succeed regardless of my RLS policies?
IIRC that was failing as well but maybe I'm misremembering.

When the bucket is public, you can access the storage object using the [public URL](https://supabase.com/docs/reference/dart/storage-from-getpublicurl), and that's it. You cannot access the bucket information itself.

**Comment by pdurasie** [comment]
I have run into the same problem as well. The confusion stems from the fact that it makes no difference what RLS policies you define on your individual buckets when you do not define any policy on the `storage.buckets` level. [I needed to allow read access to `storage.buckets`](https://github.com/orgs/supabase/discussions/1761#discussioncomment-802551) before any buckets were able to be found by my client (and therefore before the RLS policies on my individual buckets made any difference).

> When the bucket is public, you can access the storage object using the [public URL](https://supabase.com/docs/reference/dart/storage-from-getpublicurl), and that's it. You cannot access the bucket information itself.

This doesn't seem to be true. After providing read access as I linked above, you can go `await supabase.storage.getBucket("public-bucket")` and receive bucket information just fine, such as `allowedMimeTypes`, `createdAt`, `fileSizeLimit`, etc.
