### ISSUE TITLE
Update README and docs to explain JWT refresh flow

### ISSUE THREAD

**Issue by ellmaki** [supabase/supabase-flutter#805]
Right now it is very confusing how to handle the JWT refresh flow for supabase with flutter. It is my understanding that the supabase package is supposed to generate a new access token automatically, but this is not a clear flow.

For example: are currentUser and currentSession reliably not-null anytime a user is authenticated? I have run into situations where they appear temporarily null inspite of the user being logged in. This has broken key parts of my app UI.

Is there any code needed on the client side to handle JWT refresh?

Are we supposed to listen to onAuthStateChanged to handle the JWT refresh?

Really a simple guide for Supabase and Flutter using something like Provider around persisting auth state and handling the JWT refresh would be immensely appreciated. As it stands this flow is very hard to figure out.

**Comment by ellmaki** [comment]
For example I see this code 
```
supabase.auth.onAuthStateChanged
.listen((data) {})
.onError((error) {
  supabase.auth.refreshSession();  
});```
from another issue: https://github.com/supabase/supabase-flutter/issues/452#issuecomment-1588906208

Is this the recommended way to handle refresh?

**Comment by ellmaki** [comment]
I am also not relying on the session state for any of my UI since I have found it to be unreliable. I am relying only on my user state Provider for that. Should we be able to depend on session state for UI? If it is true that we cannot this is something else which I think should be really explicitly documented.

**Comment by dshukertjr** [comment]
@ellmaki 
supabase_flutter will automatically refresh your access token, and there is nothing you need to do. The SDK will automatically update the token if the session has expired when making requests. You shouldn't ever have to call `refreshSession()` either. 

Would you explain why you thought you had to implement the complicated workarounds you have shared?

**Comment by dshukertjr** [comment]
>
I am also not relying on the session state for any of my UI since I have found it to be unreliable. I am relying only on my user state Provider for that. Should we be able to depend on session state for UI? If it is true that we cannot this is something else which I think should be really explicitly documented.

Yes, you can rely on the Supabase auth state in your UI. If `supabase.auth.currentSession` is not null, the user is signed in.

**Comment by ellmaki** [comment]
I think this was possibly the source of all of my problems https://github.com/supabase/supabase-flutter/pull/806

**Comment by dshukertjr** [comment]
That sounds good, and sorry for the confusion.

**Comment by ellmaki** [comment]
Thanks for addressing it quickly.

**Comment by ellmaki** [comment]
@dshukertjr I want to verify that things are fixed on my end - do you have advice for simulating a JWT expiration event?

**Comment by dshukertjr** [comment]
@ellmaki 
Yeah, it's not really a simulation, but the easiest way to test it would be to set the JWT expiry limit to something very short. I have it set to 60 seconds here. Then your access token will expire every 60 seconds. 

<img width="1440" alt="Screenshot 2024-01-24 at 14 55 53" src="https://github.com/supabase/supabase-flutter/assets/18113850/8d53d3de-bd2c-4b57-9961-9b1533764599">

**Comment by ellmaki** [comment]
Thank you. Through forcing the expiration I have confirmed that my bugs came from the currentUser null issue.

**Comment by dshukertjr** [comment]
Glad to hear that things are working out for you now!
