### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED issue on my service.

### ISSUE THREAD

**Issue by growthondev** [supabase/supabase-flutter#810]
**Describe the bug**
It shows CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393) error

**To Reproduce**
It happens after January 26th. And it shows certificate error

**Expected behavior**
should not have any problem.

**Screenshots**
![Screenshot 2024-01-26 at 5 25 44 AM](https://github.com/supabase/supabase-flutter/assets/101177734/d9b3865c-c485-4a4a-9a4f-ddcffb42b7b1)

**Version (please complete the following information):**
On Linux/macOS
Please run `dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"` in your project directory and paste the output here.

![Screenshot 2024-01-26 at 5 26 44 AM](https://github.com/supabase/supabase-flutter/assets/101177734/96044f4e-a3eb-43ce-9a08-53e4fb92ac24)

On Windows
Please run `dart pub deps | findstr "supabase gotrue postgrest storage_client realtime_client functions_client"` in your project directory and paste the output here.

**Additional context**
It happens after Jan 26th.

**Comment by dshukertjr** [comment]
What OS are you running your application on? 

We've had similar reports in the past, and back then the cause was using an outdated version of Android. 
https://github.com/dart-lang/io/issues/83

**Comment by growthondev** [comment]
Hi @dshukertjr ! Thank you for your comment!
I'm having the same error message both android and ios.
I've been using supabase since 2022 and I don't have any problem so far but I got the error today on both ios and android..
Was there anything I should do for IPv4 deprecation even if I use flutter supabase package ?
My working app is down now..

**Comment by dshukertjr** [comment]
@growthondev 
>Was there anything I should do for IPv4 deprecation even if I use flutter supabase package ?

No, there isn't anything that you needed to do if you are just using the Flutter package. 

It might be an instance-specific issue. Could you open a support ticket from supabase.help?

**Comment by growthondev** [comment]
hi @dshukertjr 
I just provisioned a new instance using a new account and test if it works but it worked.
I guess there is something wrong in my original account since all two instances are showing the same error message.
I will create a ticket as you recommended! thanks a lot!
