### ISSUE TITLE
Complex query

### ISSUE THREAD

**Issue by andim27** [supabase/supabase-flutter#817]
I can not find how to execute query with  "left join and inner join in the query body" .The documentation for dart/flutter do not describe such queries.Is any examples? What is a correct way to make query with " inner join and left join" ?

**Comment by dshukertjr** [comment]
@andim27 For anything very specific and complex, it's easier to use [Database functions](https://supabase.com/docs/guides/database/functions). You define it using SQL, so you can perform any joins and filters with it.
