### ISSUE TITLE
Issue with redirect back to app after loggining using signInWithOAuth with provider Spotify on IOS

### ISSUE THREAD

**Issue by benjaminmountain** [supabase/supabase-flutter#819]
I am running into an issue with redirecting back to my app after logging in with Spotify using the signInWithOAuth method on IOS. I am able to get to the spotify login screen and login but then nothing happens. If I close the in app browser and trigger the login again the in app browser is opened and stops on a blank white screen like below.

![Simulator Screenshot - iPhone 15 - 2024-01-30 at 17 27 59](https://github.com/supabase/supabase-flutter/assets/49491200/62133b54-db6e-4979-8231-c03252ffe996)

I have added my Supabase Callback URL to my Spotify app.

I have added my Spotify credentials to my Supabase project.

Here is my redirect URL

<img width="888" alt="Screenshot 2024-01-30 at 4 26 17 PM" src="https://github.com/supabase/supabase-flutter/assets/49491200/a80ab36b-7bdc-488b-9052-cbfa66f6fba6">

I am using the supabase UI widget to trigger `signInWithOAuth` but I have gotten the same result by calling the method directly with the same params.

```dart
SupaSocialsAuth(
              socialProviders: const [OAuthProvider.spotify],
              redirectUrl: kIsWeb ? null : 'record://auth',
              onSuccess: (Session session) {
                log(session.toString());
              },
              onError: (e) {
                log(e.toString());
              },
            )
```

Here is the error I get from the above method.
```
PlatformException(Error, Error while launching https://ayjhezlfczlzymyzwngk.supabase.co/auth/v1/authorize?provider=spotify&redirect_to=record%3A%2F%2Fauth&flow_type=pkce&code_challenge=z45CR8YiGxFR5gi_AKB5TdcGGHbOHViCxi8Yivo9d8E&code_challenge_method=s256, null, null)
```

Here is what I added to my `info.plist`

```plist
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>record</string>
			</array>
		</dict>
	</array>
```

dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"

here is the result of the above command

├── supabase_auth_ui 0.4.1
│   └── supabase_flutter...
├── supabase_flutter 2.1.0
│   ├── supabase 2.0.3
│   │   ├── functions_client 2.0.0
│   │   ├── gotrue 2.2.0
│   │   ├── postgrest 2.1.0
│   │   ├── realtime_client 2.0.0
│   │   ├── storage_client 2.0.0
    ├── supabase_flutter...

**Comment by dshukertjr** [comment]
Could you re-open the issue on the Flutter Auth UI repository?
https://github.com/supabase-community/flutter-auth-ui

**Comment by benjaminmountain** [comment]
Sorry I shouldn't have used the flutter auth UI as my example. I am experiencing this issue regardless of if I use the UI package or not. This should not be an issue with the flutter auth UI. Here is my method that directly calls `singInWithOAuth` and results in the same behavior described above. 

```dart
Future<void> _onSignUp(SignUpSubimtted event, Emitter emit) async {
    if (state.isValid) {
      emit(state.copyWith(status: FormzSubmissionStatus.inProgress));
      try {
        await _supabase.auth.signInWithOAuth(OAuthProvider.spotify,
            redirectTo: kIsWeb ? null : 'record://auth');
        emit(state.copyWith(status: FormzSubmissionStatus.success));
      } catch (e) {
        emit(state.copyWith(status: FormzSubmissionStatus.failure));
      }
    }
  }
```

**Comment by dshukertjr** [comment]
@benjaminmountain 
Could you try it with the `authScreenLaunchMode` option like this?
```dart
supabase.auth.signInWithOAuth(
  OAuthProvider.spotify,
  authScreenLaunchMode: LaunchMode.externalApplication,
);
```

**Comment by benjaminmountain** [comment]
@dshukertjr 
Ah, that worked for the redirect, thank you. I still don't see `onAuthStateChange` being triggered when I sign in though.

**Comment by dshukertjr** [comment]
@benjaminmountain 
What event are you expecting to be triggered and not seeing? Please provide detailed step-by-step of what you did to get the result you got.

**Comment by benjaminmountain** [comment]
@dshukertjr 
My steps are as follows: `singInWithOAuth` (with above provider, redirect, and authScreenLaunchMode) is called -> app is redirected to external spotify login page -> user logs in successfully -> user redirected back to mobile app

My expectation was that once I have logged in to spotify successfully and am redirected back to the mobile app, `onAuthStateChange` would fire with `event = AuthChangeEvent.signedIn`

**Comment by dshukertjr** [comment]
@benjaminmountain 
Upon coming back to the app after completing the sign in process on Spotify, are you signed in? You can check if you are signed in by checking if `supabase.auth.currentSession` is not null. If you are signed in, then you should have gotten a `AuthChangeEvent.signedIn` event on `onAuthStateChange`. Please double check the console.

**Comment by benjaminmountain** [comment]
@dshukertjr 
Yes what you described was the expected behavior. I was able to get the same behavior only after I confirmed my email via the confirmation email sent by supabase. In my previous comment, I was not seeing the expected AuthChangeEvent _even after signing in via spotify and being redirected back the the app_. After confirming my email I made another call to `signInWithOAuth`, was redirected to safari and then directly back to the app and the expected AuthChangeEvent.signedIn occurred.

If it is expected behavior that the first time I attempt to sign in with OAuth there is no AuthChangeEvent and the only action taken is a confirmation email is sent then this can be considered closed. Thanks for assisting.

**Comment by dshukertjr** [comment]
>Yes what you described was the expected behavior. I was able to get the same behavior only after I confirmed my email via the confirmation email sent by supabase.

You hadn't mentioned anything about confirming email address in the [steps you took](https://github.com/supabase/supabase-flutter/issues/819#issuecomment-1920140149) that you described earlier. After what step did you receive a confirmation email, because you shouldn't receive any confirmation emails after performing OAuth sign-ins. 

>If it is expected behavior that the first time I attempt to sign in with OAuth there is no AuthChangeEvent and the only action taken is a confirmation email is sent then this can be considered closed. Thanks for assisting.

If you have a session after coming back to the app, then you did receive a `signIn` event and you probably just missed it. If you didn't have a session after coming back to the app, then there should be an error thrown that you can catch with `onAuthStateChange.onError()`.

**Comment by benjaminmountain** [comment]
When I wrote the earlier steps I did not realize a confirmation email was being sent. Here are the steps I have followed for the behavior described in my last comment: 

Before starting I confirm that my supabase project has no registered user with the email connected to my Spotify account.

Then I open the app and press sign in to trigger the `signInWithOAuth` method. 

I am sent to the spotify login page and I enter my spotify login information and press submit.

I am then redirected back to the app and `onAuthStateChange` is **not** triggered.

I check my email and see I have an email from noreply@mail.app.supabase.io with title 'Confirm your signup' and a link. I click the link. I then check my Supabase project and see the email for the account I just created has been confirmed.

Now I go back to the app and press sign in again to trigger  the `signInWithOAuth` method.

I am taken to the browser and then immediately back to the app and now `onAuthStateChange` _is_ triggered with the expected signIn event.

**Comment by dshukertjr** [comment]
Okay, and at every step that you expect an auth state change callback, but didn't get it, can you check if `currentSession` is null or not. Also, do you have an error listener on the `onAuthStateChange`? It would be good to see if there are any errors being thrown at each time.

**Comment by dshukertjr** [comment]
Okay, can you try to initialize Supabase with `authFlowType: AuthFlowType.implicit`? 

```dart
Supabase.initialize(
  url: 'url',
  anonKey: 'anonKey',
  authOptions: const FlutterAuthClientOptions(
    authFlowType: AuthFlowType.implicit,
  ),
);
```

The above option eliminates the need for the user to sign in with OAuth twice. With the above initialization, the flow with Spotify login will be like this:
1. The user clicks the sign-in button, which calls `signInWithOAuth()`
2. The user is taken to an external browser where they are presented with the OAuth sign-in screen for Spotify
3. Upon completing the OAuth sign-in, the user is brought back to the app, but the user is not signed in yet. A confirmation email from Supabase is also sent to the user at the same time. 
4. Upon the user clicking the link in the confirmation email, the user is taken back to the app and is finally signed in.

Spotify does not expose whether the email address has been confirmed or not, so we have to send confirmation email from Supabase for security reasons.

**Comment by benjaminmountain** [comment]
I am not getting an error on `onAuthStateChange` when the user is brought back to the app after the initial sign-in described in step 3.

**Comment by dshukertjr** [comment]
@benjaminmountain On step 3, could you share the deep link URI? It should be printed on your debug console.

**Comment by benjaminmountain** [comment]
When I am returned to the app in step 3 nothing new is printed to the console. 

Once I have confirmed my email then when I signInWithOAuth again I get the onReceivedAuthDeeplink uri: record://auth#access_token=ey...

**Comment by dshukertjr** [comment]
@benjaminmountain Could you run your app on flutter web to see the URL on step 3 then?

**Comment by benjaminmountain** [comment]
Sure, here's the url after being returned to the app in step 3 running on web. http://localhost:57917/#error=unauthorized_client&error_code=401&error_description=Unverified+email+with+spotify.+A+confirmation+email+has+been+sent+to+your+spotify+email

**Comment by dshukertjr** [comment]
Thanks for sharing the URL. At step 4 though, are you able to complete the sign-in? If not, could you share the URL at step 4 as well?

**Comment by benjaminmountain** [comment]
When I click the confirmation link in the email it does take me to the app and sign me in.

**Comment by dshukertjr** [comment]
@benjaminmountain Great, it sounds like your app is working as [expected](https://github.com/supabase/supabase-flutter/issues/819#issuecomment-1920595130) 👍

**Comment by benjaminmountain** [comment]
Thanks, the only question I still have is that I don't receive an error at step 3 on mobile. I only get the error in the url on web. If that is the expected behavior that is fine I can work around it, but currently on mobile there is no indication that something went wrong after step 3.

**Comment by dshukertjr** [comment]
@benjaminmountain 
Right, that is unexpected. Will ship a fix for that!

**Comment by dshukertjr** [comment]
@benjaminmountain The error not being thrown issue should be resolved with the latest release.
