### ISSUE TITLE
RefreshToken fail without feedback if offline

### ISSUE THREAD

**Issue by cgestes** [supabase/supabase-flutter#82]
If offline when _saveSession is called, the call to refresh the token fail (which is expected) but the error is swallowed. We don't get notified that something is wrong and all other requests to Supabase start failing.

We could detect connectivity and retry when we are back online using something like https://pub.dev/packages/connectivity_plus 

Also we should probably emit an event in onAuthStateChange that we are signed out when there is no chance to recover the session.

I can help implement this if given some direction on what is the expected behavior. :D

**Comment by Vinzent03** [comment]
I think this is fixed via https://github.com/supabase/gotrue-dart/pull/71

**Comment by ConProgramming** [comment]
This is not fixed by that. If `refreshSession` happens when offline, it will fail.
