### ISSUE TITLE
GitHub OAuth sign in fails with invalid URL

### ISSUE THREAD

**Issue by Akash4097** [supabase/supabase-flutter#821]
**Describe the bug**

i am trying to integrating github oauth for authentication in my app but when i use the following code snippet(given in docs):

```
await supabase.auth.signInWithOAuth(
          OAuthProvider.github,
          redirectTo: kIsWeb ? null : 'io.supabase.flutter://reset-callback/',
        );

```

then i got the following exception:

```
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(open_error, Failed to open %22%22/auth/v1/authorize?provider=github&redirect_to=io.supabase.flutter%3A%2F%2Freset-callback%2F&flow_type=pkce&code_challenge=veok_nEBkj_jY3HfthUlvBtzsuo0Ey-B97VF2i2uFjs&code_challenge_method=s256: ShellExecute error code 2, null, null)
#0      UrlLauncherApi.launchUrl (package:url_launcher_windows/src/messages.g.dart:76:7)
<asynchronous suspension>
#1      GoTrueClientSignInProvider.signInWithOAuth (package:supabase_flutter/src/supabase_auth.dart:289:20)
<asynchronous suspension>
#2      _LoginButton.build.<anonymous closure> (package:free_chat/ui/widgets/chat_header.dart:46:24)
<asynchronous suspension>
```

please help me what should i do here or am i miss something?

**Comment by dshukertjr** [comment]
Could you outline what steps you took to setup GitHub login on Supabase?

**Comment by Akash4097** [comment]
> Could you outline what steps you took to setup GitHub login on Supabase?

okay:
- first i created an OAuth app on github in order to getting client id and client secret 
- then i enable the github authentication under (Authentication > Provider) on supabase
- after i done the above steps, i already setup my supabase in flutter by adding supabase_flutter lib,
- then as i mentioned in my previous post, i used the  following code 

```

await supabase.auth.signInWithOAuth(
  Provider.github,
  redirectTo: kIsWeb ? null : 'io.supabase.flutter://reset-callback/',
);
```
in order to check whether
  authentication work or not but it failed to give the exception as mentioned in my previous post.

**Comment by dshukertjr** [comment]
Can you print the `url` property of the `getOAuthSignInUrl()` method like this and paste exactly what you see in the console?

```dart
final res = await getOAuthSignInUrl(
  provider: OAuthProvider.github,
  redirectTo: kIsWeb ? null : 'io.supabase.flutter://reset-callback/',
);
print(res.url);
```

**Comment by Akash4097** [comment]
> Can you print the `url` property of the `getOAuthSignInUrl()` method like this and paste exactly what you see in the console?
> 
> ```dart
> final res = await getOAuthSignInUrl(
>   provider: OAuthProvider.github,
>   redirectTo: kIsWeb ? null : 'io.supabase.flutter://reset-callback/',
> );
> print(res.url);
> ```

ya i got the following resutl:

`INFO: 2024-01-31 14:25:42.739389:=> Github OAuth:URL ""/auth/v1/authorize?provider=github&redirect_to=io.supabase.flutter%3A%2F%2Freset-callback%2F&flow_type=pkce&code_challenge=t9FgmhU_kpeUzjWQXNEkoc7eWNwSkBWnXgns2Ncchzc&code_challenge_method=s256`

**Comment by dshukertjr** [comment]
Okay, double-check how you are initializing Supabase. You most likely are passing `""` as the Supabase URL.

**Comment by Akash4097** [comment]
> Okay, double-check how you are initializing Supabase. You most likely are passing `""` as the Supabase URL.

ya you are right.... actually project url is not properly return from .env file...

just one more question: as i don't have production level url because my app is in developing phase right now....so what url should i give here(see in screenshot) so that it won't redirect to unknown page...
![supabase](https://github.com/supabase/supabase-flutter/assets/12380680/d87f5ba4-7a3a-4877-9157-cc245d0f66e9)

**Comment by dshukertjr** [comment]
@Akash4097 
Glad it was solved. 

>just one more question: as i don't have production level url because my app is in developing phase right now....so what url should i give here(see in screenshot) so that it won't redirect to unknown page...

You can ask GitHub what to enter there in your circumstance.
