### ISSUE TITLE
Error: AuthException(message: Database error saving new user, statusCode: 500) when I try create new user

### ISSUE THREAD

**Issue by AsanovAlbek** [supabase/supabase-flutter#822]
I trying to create new user in my flutter project with sign up method, but I catch AuthException(message: Database error saving new user, statusCode: 500)

this is my function
```dart
Future<void> signUp(
      {required String email,
      required String password,
      required String teacherName}) async {
    await _auth.signUp(email: email, password: password);
    // other code...
  }
```

and my stack trace, when I trying to create new user
Error: AuthException(message: Unable to validate email address: invalid format, statusCode: 422)
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3  throw_
packages/gotrue/src/fetch.dart 99:7                                          request
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 721:7                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>

Whats interesting, sign in works well, and when i try to add a user to the table via the supabase website, I get the same error
p.s. Before it I used the same database on another project, that is, my database is connected to two projects, and all functions that I used except sign up, works well
![image](https://github.com/supabase/supabase-flutter/assets/87094098/4f9b0a6e-49e6-49c3-bdc0-404ac3c20027)

**Comment by dshukertjr** [comment]
You can find more information about the error in the logs section of your Supabase dashboard. Typically when these unknown errors happen, you have a database trigger set that is causing it.

**Comment by AsanovAlbek** [comment]
> Вы можете найти более подробную информацию об ошибке в разделе "Журналы" вашей информационной панели Supabase. Обычно, когда возникают эти неизвестные ошибки, у вас есть установленный триггер базы данных, который является их причиной.

Your advice led me to a decision, thank you
When I started to learning supabase, I paste template database 'profiles' from your tutorial video and forget, what this database has some trigger, I edited this trigger and solved my problem
Thank you! Have a nice day :)
