### ISSUE TITLE
Refresh token is triggered continuesly until getting AuthException(message: Rate limit exceeded, statusCode: 429)

### ISSUE THREAD

**Issue by BharathKumar-99** [supabase/supabase-flutter#828]
from yesterday iam getting a issue with tokens it refreshes the token until the rate limit is reached can any one help

static Future initialize() => Supabase.initialize(
      url: KeyConstants.SUPABASE_URL!,
      anonKey: KeyConstants.SUPABASE_ANON_KEY!,
      debug: true);

I then thought maybe I was being rate limited,but i checked the supabase config in website and that was not the case

**Comment by dshukertjr** [comment]
@BharathKumar-99 Please follow the issue template and provide all necessary information for us to debug the issue.
