### ISSUE TITLE
tokens it refreshes the token until the rate limit is reached

### ISSUE THREAD

**Issue by BharathKumar-99** [supabase/supabase-flutter#829]
from yesterday iam getting a issue with tokens it refreshes the token until the rate limit is reached can any one help

iam not sure if this helps but here is my code 

 `  static Future initialize() => Supabase.initialize(
      url: KeyConstants.SUPABASE_URL!,
      anonKey: KeyConstants.SUPABASE_ANON_KEY!,
      debug: true);`

this the auth change stream code
`final supabaseAuth = SupaFlow.client.auth.onAuthStateChange
    .map<String>((response) => response.session!.user.id)
    .switchMap((id) => id.isEmpty
        ? Stream.value(null)
        : getFilteredRowStream(id).map((row) => log(row.toString())))
    .asBroadcastStream();`

iam refresh token should not triggers until the code 429 is thrown

I am using supabase_flutter: ^2.3.2

**Comment by dshukertjr** [comment]
Again, we need you to follow the issue format for us to assist you. Please provide a detailed step-by-step of the actions you are performing and provide clear expected results and actual results you are getting with the issue you are facing.

**Comment by BharathKumar-99** [comment]
iam not sure how to reproduce this as iam getting this error with out soing anything when app starts

**Comment by dshukertjr** [comment]
So you are getting the error as a result of calling `Supabase.initialize()`? Could you copy and paste the content of the error here?
