### ISSUE TITLE
 tokens it refreshes the token until the rate limit is reached

### ISSUE THREAD

**Issue by BharathKumar-99** [supabase/supabase-flutter#830]
from yesterday iam getting a issue with tokens it refreshes the token until the rate limit is reached because of this the supabase is being requested 5000 times by a single user 

i dont know how to reproduce this as iam getting this when iam starting the app and calling the supabase 

**Expected behavior**
token regeneration should only trigger when expected

```
 static Future initialize() => Supabase.initialize(
      url: KeyConstants.SUPABASE_URL!,
      anonKey: KeyConstants.SUPABASE_ANON_KEY!,
      debug: true);
```

if it helps please check this 
```
final supabaseAuth = SupaFlow.client.auth.onAuthStateChange
    .map<String>((response) => response.session!.user.id)
    .switchMap((id) => id.isEmpty
        ? Stream.value(null)
        : getFilteredRowStream(id).map((row) => log(row.toString())))
    .asBroadcastStream();
```

iam not sure if this the issue from flutter side or supabase

**Comment by dshukertjr** [comment]
Please stop creating new issues with the same content, and answer the question I have posted on the other issue. 
https://github.com/supabase/supabase-flutter/issues/829
