### ISSUE TITLE
setInitialSession not awaited

### ISSUE THREAD

**Issue by whymatter** [supabase/supabase-flutter#831]
Shouldn't this call to setInitialSession be awaited?

https://github.com/supabase/supabase-flutter/blob/a72166268facd97f07cf9588415a2f3d31f68c22/packages/supabase_flutter/lib/src/supabase_auth.dart#L57

**Comment by Vinzent03** [comment]
Reason for closing is noted [here](https://github.com/supabase/supabase-flutter/pull/832#issuecomment-1961491722)
