### ISSUE TITLE
iOS does not automatically return to the app after social login.

### ISSUE THREAD

**Issue by Jay-flow** [supabase/supabase-flutter#84]
# iOS does not automatically return to the app after social login.

When I log in on social on iOS, the social login window appears on the web, and I want to log in and return to the app, but the app doesn't open.

The console says you are logged in as below.
```bash
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
```

However, the loading window continues to appear as below and does not return to the app.

![KakaoTalk_Photo_2022-01-25-13-21-43](https://user-images.githubusercontent.com/29420674/150910428-1c4143c8-a071-4a7d-b4eb-060129497e6a.jpeg)

It works normally when deep link is tested manually by Safa.

https://user-images.githubusercontent.com/29420674/150911355-bf1fe7bd-338a-4bdc-8ca2-e3402a0ce82f.mp4

I implemented social login for Apple, Google, and Facebook, and each has a different result screen, but the symptoms are all the same.

**When I open the app manually, I log in normally.**
Is it supposed to be like that?
Android automatically opens the app after social login.

**Comment by Jay-flow** [comment]
There is a temporary workaround below.

https://github.com/supabase-community/supabase-flutter/issues/16#issuecomment-1119322566

**Comment by dshukertjr** [comment]
I want to say this issue has been fixed in the latest version of supabase-flutter. Could you try it out and see if you still have this issue?
