### ISSUE TITLE
Handshake Exception

### ISSUE THREAD

**Issue by moesaid** [supabase/supabase-flutter#846]
**Describe the bug**
Authentication on windows throwing Handshake Exception, MacOS works fine , Windows not really. 

i open a support ticket `2414267651` but with `no guaranteed support response` i wanted to put this here.

<img width="1312" alt="Screenshot 2024-02-26 at 9 50 55 PM" src="https://github.com/supabase/supabase-flutter/assets/38924585/89aeaa0c-d2bd-4be9-97ec-cd9664648866">
<img width="1312" alt="Screenshot 2024-02-26 at 9 52 04 PM" src="https://github.com/supabase/supabase-flutter/assets/38924585/24e7dc8b-feac-4eef-8768-b083d3aaff75">

**Comment by Vinzent03** [comment]
What is the reason you think our packages are responsible? Which packages are you using? How are you initializing them? Can you access other websites? Does this happen all the time/is reproducible? Please open a new issue and follow the issue template.
