### ISSUE TITLE
It is not possible to put more than one filter in real-time stream

### ISSUE THREAD

**Issue by codefutura** [supabase/supabase-flutter#857]
**error when trying to add more than one filter in real-time stream**
example: supabase
         .from('tbl')
         .stream(primaryKey: ['id']).gte('created_at', dateInit)
           .lte('created_at', dateEnd)

**Comment by dshukertjr** [comment]
Closing as duplicate of https://github.com/supabase/supabase-flutter/issues/338

**Comment by codefutura** [comment]
thank you
