### ISSUE TITLE
Titmeout error

### ISSUE THREAD

**Issue by andim27** [supabase/supabase-flutter#858]
supabase_flutter: ^2.3.4
I do next code:
```
try {
final data = await sbClient
          .from("my_table")
          .select...
} catch (e) {
print(e)
}
```
But sometimes I've got error:
ClientException with SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = ***
Question:
-what is it?
- Is a method in flutter_supabase to verify Supabase server status ?

**Comment by dshukertjr** [comment]
The error indicates that you likely do not have internet connections. 
https://stackoverflow.com/questions/60155822/i-flutter-30720-socketexception-os-error-connection-timed-out-errno-110

**Comment by andim27** [comment]
Is a method in flutter_supabase to verify Supabase server status ?

**Comment by dshukertjr** [comment]
@andim27 No, there isn't.
