### ISSUE TITLE
PostgresChangePayload.newRow doesn't exist

### ISSUE THREAD

**Issue by Amonc** [supabase/supabase-flutter#859]
When subscribing to channels on Postgress Update Event  the data contains different names of the keys eg: `newRow` and `oldRow`. 

But it expects to have `newRecord` and `oldRecord`  as PostgresChangePayload.newRow doesn't exist.

├── supabase_flutter 2.3.4
│   ├── supabase 2.0.8
│   │   ├── functions_client 2.0.0
│   │   ├── gotrue 2.5.1
│   │   ├── postgrest 2.1.1
│   │   ├── realtime_client 2.0.1
│   │   ├── storage_client 2.0.1

**Comment by mateusz-grzegorzek** [comment]
@Amonc 
Was it fixed?
I'm still experiencing this issue on the supabase_flutter 2.5.3 version.

**Comment by dshukertjr** [comment]
@mateusz-grzegorzek You are not receiving `newRow` in your payload?

**Comment by mateusz-grzegorzek** [comment]
@dshukertjr  My bad. Sorry to bother you. Everything is ok. I was trying to access `newRecord` on `newRecord` object

**Comment by dshukertjr** [comment]
Great to hear it's working for you 👍
