### ISSUE TITLE
Match dependency version for latest `app_links` version

### ISSUE THREAD

**Issue by yasinarik** [supabase/supabase-flutter#863]
**Describe the bug**

I am using the below `app_links` version in the app alongside with `flutter v3.19.3`.

I am trying to add `supabase_flutter` package at the same time.

```yaml
  app_links: 4.0.0
  supabase_flutter: 2.3.4
```

```
Resolving dependencies...
Because supabase_flutter >=2.2.0 depends on app_links ^3.5.0 and MY_APP_NAME_HERE depends on app_links 4.0.0, supabase_flutter >=2.2.0 is forbidden.
So, because MY_APP_NAME_HERE depends on supabase_flutter 2.3.4, version solving failed.

You can try one of the following suggestions to make the pubspec resolve:
* Consider downgrading your constraint on supabase_flutter: flutter pub add supabase_flutter:^0.3.3
* Consider downgrading your constraint on app_links: flutter pub add app_links:^3.5.1
```

For now, I will downgrade `app_links` to `v3.5.1` but can you update `supabase_flutter` so it can work alongside with `app_links`?

**Comment by thudaydelight** [comment]
I need to use Flutter Web with wasm for the application, but supabase_flutter is using app_links 3.5.0, which does not support wasm. Please update the app_links library to 4.x.x

**Comment by thubv** [comment]
Still error when add app_links 4.x vs supabase 2.4.0

<img width="923" alt="image" src="https://github.com/supabase/supabase-flutter/assets/7010816/b8fe7585-1417-4a29-9efc-7d204c4fe9c8">

**Comment by dshukertjr** [comment]
@thubv A version containing this update hasn't been released yet. It will be released within the next week.

**Comment by thubv** [comment]
@dshukertjr 
thanks sir
