### ISSUE TITLE
Google sign in automatically selects that account.

### ISSUE THREAD

**Issue by volkankoc** [supabase/supabase-flutter#868]
**Describe the bug**
When there is only one account on Android phone. Google sign in automatically selects that account. Is there a way to bring up the selection screen again?

**Expected behavior**
I want to show account page

**Screenshots**

**Comment by dshukertjr** [comment]
The Supabase SDK doesn't control how the Google account is selected. 

You should look deeper into how the [google_sign_in](https://pub.dev/packages/google_sign_in) package works, and see if there is a way to achieve what you want to achieve. If it's not possible currently, I suggest you to open an issue on their package.

**Comment by Fintasys** [comment]
I solved it by using additionally the `google_sign_in` package.
```
  final auth = Supabase.instance.client.auth;
  final provider = auth.currentUser?.identities?.first.provider;
  await auth.signOut();
  if (provider == "google") {
    await GoogleSignIn().signOut();
  }
```
