### ISSUE TITLE
[auth] Add support for `signInAnonymously()`

### ISSUE THREAD

**Issue by pedromassango** [supabase/supabase-flutter#874]
**Is your feature request related to a problem? Please describe.**
The JavaScript SDK has support for [signInAnonymously()](https://supabase.com/docs/reference/javascript/auth-signinanonymously), this is a request to add the same feature on the Flutter sdk.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
There is no alternatives.

**Additional context**
N/A

**Comment by dshukertjr** [comment]
I like how closely you keep an eye on the js sdk. It will come to the Flutter SDK soon as well.

**Comment by pedromassango** [comment]
> I like how closely you keep an eye on the js sdk. It will come to the Flutter SDK soon as well.

Is the work being done in public? I can't ship without this feature / random email not an option

**Comment by dshukertjr** [comment]
We ask you to wait patiently. It will arrive as soon as possible. Note that due to the current limitation of the auth server of Supabase, you will only be able to upgrade the anonymous users to a authenticated users through email + password or the web based OAuth login. Open ID connect (native Google and Apple sign-in) will not yet be supported.

**Comment by pedromassango** [comment]
Sure. We can live with that!

**Comment by muezz** [comment]
Hey @dshukertjr, do you have an ETA on this? Coincidentally, I happen to be working on a project which would greatly benefit from this. If it is going to be within a few days, I would rather just wait for it.

**Comment by antonkarliner** [comment]
+++ also waiting to implement this in flutter 🙏🏼

**Comment by moriosoft** [comment]
Waiting as well. Looking forward to it :)
