### ISSUE TITLE
[AuthExeption] anonymous sign-ins are disabled

### ISSUE THREAD

**Issue by hamzabouakoura** [supabase/supabase-flutter#877]
Hi , I'm new to supabase and i was trying to use it for authentication with my flutter app
Therefore i used signup() method to create a new user , but it is not working and I'm getting the exeption above .

Any ideas ?

**Comment by dshukertjr** [comment]
Could you provide step by step of what you did? I didn't get the error you are getting by calling the following on a fresh Supabase project.

```dart
await supabase.auth.signUp(email: 'my@email.com', password: 'password');
```

**Comment by hamzabouakoura** [comment]
@dshukertjr 

Well simply, i created the the following method and called it in the onPressed in order to create a new user :

Future<AuthResponse> signUpUser(
{required String email, required String password}) async {
final response = await Supabase.instance.client.auth.signUp(
email: email,
password: password,
);
return response;
}

But i'm getting the AuthExeption(anonymous sign-ins are disabled).

It's not supposed to give this error cuz i'm using the signUp() method which creates a normal user that need to confirm his email , isn't it ?

**Comment by dshukertjr** [comment]
@hamzabouakoura Can you actually open a ticket from here: [supabase.help](https://supabase.help)

**Comment by dshukertjr** [comment]
@hamzabouakoura Could you try to call the signUp method with hard-coded values something like the following and see if you get the same error?
```dart
await Supabase.instance.client.auth.signUp(
  email:'sample@gmail.com',
  password: 'password',
);
```

**Comment by hamzabouakoura** [comment]
@dshukertjr 
Yes , it's working.

The problem was stupid mistake on my part on passing the controllers to the method

Thanks a lot for your help Tayler 🙏
