### ISSUE TITLE
Realtime randomly stops working

### ISSUE THREAD

**Issue by mattermoran** [supabase/supabase-flutter#886]
**Describe the bug**

I'm running into a very strange issue that I'm having trouble reproducing but it's being reported a lot on production. 
The app uses realtime streams extensively for pretty much all the queries. That seems to be ok and there were no issues on firestore before but now that we migrated to supabase streams sometimes just stop emitting any data and it only gets fixed after app restart. 
As I said I can't really reproduce locally so I'm not sure if there's maybe some connection drop or we hitting some kind of a limit. 

The usage of streams is just typical
```dart
  Stream<List<T>> watchMany() {
    return supabase.from(tableName).stream(primaryKey: ['id']).map(
      (data) => data.map((e) => fromJson(e)).toList(),
    );
  }
  ```

Is there any tips to debug this or idea what could be going on?

**Comment by JakesMD** [comment]
Same here :confused: Realtime just stops after a while when connected to a remote database. We can't reproduce the issue locally and no error ist thrown. Updates just stop coming through.

This issue has been around for well over a year, though, with no solution. (https://github.com/supabase/supabase-flutter/issues/388)

Pretty poor show. Superbase is cool. But we really don't care about any other fancy features you guys might be implementing if the basics don't work.

And as with any open source project, most of us users don't have the time or the knowledge to mess around in the supabase code ourselves.

I'll open a bottle of champagne on your behalf when you get this fixed. :champagne:

**Comment by dshukertjr** [comment]
Yup, this is a known issue, and we are sorry that we haven't been able to fix it yet. We have allocated some time to take a deeper look at the issue, but we have yet to find the cause, but the same issue does not happen on JS SDK, so we know it's the Flutter SDK's issue. I will take another stab at it soon. 

Closing as a duplicate of https://github.com/supabase/supabase-flutter/issues/388

**Comment by JasonChiu-dev** [comment]
> duplicate of #388

I don't think this is a duplicate of issue #388. We've been experiencing instability with Supabase for the past two weeks, resulting in unpredictable errors. This has caused significant disruption.

**Comment by JasonChiu-dev** [comment]
> **Describe the bug**
> 
> I'm running into a very strange issue that I'm having trouble reproducing but it's being reported a lot on production. The app uses realtime streams extensively for pretty much all the queries. That seems to be ok and there were no issues on firestore before but now that we migrated to supabase streams sometimes just stop emitting any data and it only gets fixed after app restart. As I said I can't really reproduce locally so I'm not sure if there's maybe some connection drop or we hitting some kind of a limit.
> 
> The usage of streams is just typical
> 
> ```dart
>   Stream<List<T>> watchMany() {
>     return supabase.from(tableName).stream(primaryKey: ['id']).map(
>       (data) => data.map((e) => fromJson(e)).toList(),
>     );
>   }
> ```
> 
> Is there any tips to debug this or idea what could be going on?

I'm facing a similar issue. The stream listener isn't emitting the initial data, and it seems to be behaving unpredictably.

For the past two weeks, I've been experiencing instability with Supabase, leading to unpredictable errors. This has caused significant disruptions.

Have you been able to resolve the problem you mentioned?

**Comment by mattermoran** [comment]
Well given that I can't rely on realtime I decided to go oldschool and just do without streams. Instead I manually refresh my providers on creates/updates etc so I know it's always up to date in those cases. 

Also to still have the realtime I manually subscribed to all db changes and refresh providers based on what changed. 
In this case it's more of a nice to have and if it stops working I still have the manual one.

**Comment by Yhali-Z** [comment]
Here is a regular channel listener in Supabase:
```
channel.on("postgres_changes",
      { event: "*", schema: "public", table: "users" },
      (payload) => {
        console.log(payload);
      }
).subscribe();
```

Turns out you can use the `subscribe()` part to add a function that listens to the channel status, such as follows:
```subscribe( status => { console.log(status) })```

And I noticed that when the subscription stops working, this function is fired with `status="CHANNEL_ERROR"`, so we can use that to detect when the connection is cut and resubscribe to real-time updates right away - therefore continuing to listen to changes.
I made a function that takes care of the resubscription stuff:
```
function fixedChannelOn(channelRef, ...args) {
  let launchedOnce = false; //prevent relaunching multiple times.
  const channel = channelRef.current;

  channel.on(...args).subscribe( status => {
    console.log(status);//just for inspections.

    if (status == "CHANNEL_ERROR" && !launchedOnce) {//when the listener stops working.
      console.log("channel error, relaunching subscription");
      launchedOnce = true;
      channel.unsubscribe();
      channelRef.current = supabase.channel('table-db-changes');
      fixedChannelOn(channelRef, ...args);
    }
  });
}
```
This is how you use it:
```
const channelRef = { current: supabase.channel('table-db-changes') };

fixedChannelOn(channelRef,
   "postgres_changes",
   { event: "*", schema: "public", table: "users" },
   (payload) => {
      console.log(payload);
   }
);
```
Then to unsubscribe from Realtime:
```channelRef.current.unsubscribe();```

Notes: 
1) It isn't a "natural" solution because it does not prevent the channel from stopping the listening, only detects when it happens, to resubscribe right away.
2) While it is true that the "CHANNEL_ERROR" is given when this happens, sometimes this error is due to other causes, such as an internet connection loss, server shutting down, security issues, etc. So if it matters to you you need to detect when the resubscription to the channel also doesn't work - I tried to do it the simple way with try{} catch{}, but turns out that channel.on() does not throw an error here, only logs it out to the console. You can probably pass something extra in the arguments of the `fixedChannelOn` function to fix this.

Here is a simple app I wrote with react-native where I use this:
```
import supabase from './supabaseClient';
import { Text, View, Button } from 'react-native';
import { useEffect, useRef, useState } from 'react';


function fixedChannelOn(channelRef, ...args) {
  let launchedOnce = false;
  const channel = channelRef.current;

  channel.on(...args).subscribe( status => {
    console.log(status);//just for inspections.

    if (status == "CHANNEL_ERROR" && !launchedOnce) {//when the listener stops working.
      console.log("channel error, relaunching subscription");
      launchedOnce = true;
      channel.unsubscribe();
      channelRef.current = supabase.channel('table-db-changes');
      fixedChannelOn(channelRef, ...args);
    }
  });
}

export default function App() {
  const channelRef = useRef();

  useEffect(() => {
    // const channelRef = {current: supabase.channel('table-db-changes')};
    channelRef.current = supabase.channel('table-db-changes');

    fixedChannelOn(channelRef,
      "postgres_changes",
      { event: "*", schema: "public", table: "users" },
      (payload) => {
        console.log(payload);
      }
    );

    return () => {
      channelRef.current.unsubscribe();
    };
  }, []);
  
  
  return (
    <View style={{ flex: 1, backgroundColor: "lightblue", justifyContent: "center", alignItems: "center"}}>
      
      <Button title="unsubscribe" onPress={() => {
        channelRef.current?.unsubscribe();
      }} />

    </View>
  );
}
```
