### ISSUE TITLE
Dynamic database schema

### ISSUE THREAD

**Issue by pedromassango** [supabase/supabase-flutter#887]
It would be great for Supabase to give us the ability to create dynamic schemas for apps that support dynamic subdomains.

**Comment by dshukertjr** [comment]
@pedromassango Could you explain more about what exactly you mean by "dynamic schema" and what exactly the use cases are?

**Comment by pedromassango** [comment]
When running the following code, I want Supabase to create a new schema called `brand-new-schema` (if it doesn't exist) and use it for all my write/read operations.

Our product have multiple clients, and we're trying to find a way to isolate their data by saving it in separate schemas.

```dart
  await Supabase.initialize(
    url: supabaseUrl,
    anonKey: supabaseAnonKey,
    debug: kDebugMode,
    postgrestOptions: PostgrestClientOptions(
      schema: 'brand-new-schema'
    )
  );
```

**Comment by dshukertjr** [comment]
@pedromassango That is not how schema is designed to be used in Postgres. You shouldn't have an enormously large number of schemas in your database. 

You might want to look into partitioning.
https://supabase.com/blog/postgres-dynamic-table-partitioning
