### ISSUE TITLE
Q: How can I modify the package?

### ISSUE THREAD

**Issue by leeeeeoy** [supabase/supabase-flutter#890]
Hello, I would like to modify the gotrue package. The suppbase_flutter can be modified well, but I'm not sure what to do with the rest of the project. Can you explain how I can modify it?

**Comment by bdlukaa** [comment]
This repo is a monorepo powered by [Melos](https://melos.invertase.dev/) containing [supabase_flutter](https://github.com/supabase/supabase-flutter/tree/main/packages/supabase_flutter) and its sub-libraries. All packages are located in the `/packages` directory.

All instructions are described in the [README](https://github.com/supabase/supabase-flutter/tree/main?tab=readme-ov-file#run-locally).

You can modify the files and submit a pull-request!
