### ISSUE TITLE
AuthRetryableFetchError on Windows

### ISSUE THREAD

**Issue by TC3000** [supabase/supabase-flutter#896]
**Describe the bug**
My Flutter desktop app is working fine on macOS but login on Windows is throwing an `AuthRetryableFetchError`. 

**To Reproduce**
1. Create a Windows desktop app with support for Email OTP auth.
2. Run the app.
3. Attempt to login into the app.
4. Observe that instead of a successful login, you'll see `AuthRetryableFetchError`.

**Expected behavior**
User should receive an email with an OTP which they'll then use to login into the app.

**Additional context**
At first I thought maybe the problem was with my supabase.co url or anon key, but that wasn't the issue. I thought also that maybe it was my network, but again, that was not the problem as I could make http calls successfully.

**Comment by dshukertjr** [comment]
@TC3000 Without digging too deep, I feel like that error happens when the app is not able to make network requests. Is the app able to make any network requests at all? Have you tried making an API request to Supabase before signing in?

**Comment by TC3000** [comment]
> @TC3000 Without digging too deep, I feel like that error happens when the app is not able to make network requests. Is the app able to make any network requests at all? Have you tried making an API request to Supabase before signing in?

I'm not so sure as to what API request I could make to Supabase without signing in first. I did however made some http calls that were successful. Can you reproduce the bug on your side?

**Comment by dshukertjr** [comment]
>I'm not so sure as to what API request I could make to Supabase without signing in first.

You can make API requests whether you are signed in or not. 

I do not have a windows device to test this out, but could you share the stack trace of when the error happens?

**Comment by TC3000** [comment]
> > I'm not so sure as to what API request I could make to Supabase without signing in first.
> 
> You can make API requests whether you are signed in or not.
> 
> I do not have a windows device to test this out, but could you share the stack trace of when the error happens?

So, after trying to make some API request to Supabase I got the error `CERTIFICATE_VERIFY_FAILED` which I was able to resolve. I can now login into the app. Thanks @dshukertjr
