### ISSUE TITLE
auth.resetPasswordForEmail throws AuthRetryableFetchException when SMTP settings are wrong

### ISSUE THREAD

**Issue by devj3ns** [supabase/supabase-flutter#902]
**Describe the bug**
When the auth SMTP settings are wrong/invalid in the Supabase dashboard and  the `auth.resetPasswordForEmail(...)` function is invoked, it throws an `AuthRetryableFetchException`. This kind of `AuthException` is very generic and not helpful at all.

**To Reproduce**
1. Go to the supabase dashboard and use invalid SMTP credentials
2. invoke the `auth.resetPasswordForEmail` function
3. `AuthRetryableFetchException` is thrown

**Expected behavior**
I would expect the function to return an Exception that tells the client what is gone wrong. Examples would be a `InvalidSMTPCredentials` or more generic a `ServerException` with an error message.

**Expected behavior**

The following code inside this repository is responsible for this:
https://github.com/supabase/supabase-flutter/blob/4f5b853cfb72f92bdceb8446397057ec434f1da3/packages/gotrue/lib/src/fetch.dart#L36

**Version:**
????????? supabase_flutter 2.5.1
???   ????????? supabase 2.1.1
???   ???   ????????? functions_client 2.0.0
???   ???   ????????? gotrue 2.6.0
???   ???   ????????? postgrest 2.1.1
???   ???   ????????? realtime_client 2.0.4
???   ???   ????????? storage_client 2.0.1

**Additional context**
With debugging, I found out that under the hood the following json is returned by the server in my case: `{"code":500,"error_code":"unexpected_failure","msg":"Unable to process request","error_id":"87968bc5f6e035ed-FRA"}`

**Comment by devj3ns** [comment]
I am having the same problem again, but now because of an error with a postgres hook.

When logging in, the `auth.signInWithPassword` function throws an `AuthRetryableFetchException` which does not contain any details about the error. By adding a print statement inside the supabase_flutter code before the exception is thrown, I could see that the actual error coming from the backend has the following body:

`{code: 500, error_code: unexpected_failure, msg: Error running hook URI: pg functions://postgres/public/custom_access_token_hook, error_id: 8994bc8f030e912e-FRA}`

I would expect that the `AuthRetryableFetchException` would at least contain the error message, but it does not.

If I find some time in the next days, I will create a PR to fix this.

**Comment by Vinzent03** [comment]
Where exactly did you put the print statement?

**Comment by devj3ns** [comment]
> Where exactly did you put the print statement?

At the top of the `_handleError` method

**Comment by Vinzent03** [comment]
Unknown errors are now properly stored in the thrown exception, so the dev can see the cause. (Not released yet). So I think this issue can be closed now.
