### ISSUE TITLE
How are you supposed to sign up with OAuth providers ?

### ISSUE THREAD

**Issue by TheCarpetMerchant** [supabase/supabase-flutter#914]
The only sign up function I can find is the email/password one. I want the user to be able to sign up using OAuth, how can I achieve that ?

**Comment by bdlukaa** [comment]
If the user exists, the user will be signed in. If the user doesn't exist, it will sign up from a single function. There is no need to split this into two different functions because they perform the same functionality.

**Comment by dshukertjr** [comment]
Yup, you can use the same `signInWithOAuth()` or `signInWithIdToken()` method to both sign-up and sign-in.

**Comment by TheCarpetMerchant** [comment]
As, might be good to mention this in the docs.
