### ISSUE TITLE
Allow to pass query params when invoking function

### ISSUE THREAD

**Issue by grdsdev** [supabase/supabase-flutter#924]
**Is your feature request related to a problem? Please describe.**
When invoking a function I want to be able to pass custom query params.

**Describe the solution you'd like**
```dart
final res = await supabase.functions
    .invoke(
        'hello',
        query: { 'key' : 'value' }
    )
```

We should be able to edit the Uri [here](https://github.com/supabase/supabase-flutter/blob/main/packages/functions_client/lib/src/functions_client.dart#L78) to include the new query parameters accepted on the `invoke()` method.

**Additional context**
https://github.com/supabase/supabase-swift/pull/376

**Comment by DanMossa** [comment]
Unless I misunderstood, you can already do this.
```dart
final data = await supabase
  .rpc('echo_city', params: { 'say': '👋' });
```

https://supabase.com/docs/reference/dart/rpc

**Comment by Vinzent03** [comment]
@DanMossa You are talking about postgres functions which are completely different from the requested query parameters for edge functions.

**Comment by dshukertjr** [comment]
Let's keep this issue open for community members to work on 👍 I think it's an excellent opportunity for new people to contribute!
