### ISSUE TITLE
Handling initial deeplink in password recovery

### ISSUE THREAD

**Issue by bruiken** [supabase/supabase-flutter#937]
**Is your feature request related to a problem? Please describe.**
When implementing the password recovery flow, we noticed that the initial deeplink handling does not yield for much customisability. The function ` _handleInitialUri()` is called as await from the initialisation function of the `Supabase` client. 
If that initial deeplink is concerning a password recovery, then it seems to be impossible to catch that event in the `supabase.auth.onAuthStateChange` listener. The same holds for the error cases, which are never even brought to that stream (this has been pointed out by #664 before too). Yet in that case it wasn't about a password recovery but a magic link.
For magic links this all is not that big of an issue, at the end of the day the user is authenticated and there is a session. For password recovery it to us seems impossible to direct the user to the "reset your password" screen when the app was fully closed.

**Describe the solution you'd like**
We'd like to see a solution where it is made possible to detect password recovery and possible errors from initial deeplink handling. A solution in this most definitely extends to any event, not just password recovery. 

**Describe alternatives you've considered**
- We could use the new functionality to block the deeplink handling by supabase and do it all manually. 
- We could not support the case where the user force closes the app after pressing reset password.

**Additional context**
Besides this, it's also quite difficult to catch errors specific to deeplink handling, our code now contains a number of checks based on the `AuthException.message` field. It would seem like a good idea to create more different error subclasses of `AuthException` so it is possible to do checks that are not reliant on error message changes. 

If directions are given for how to possibly fix this, I'd be okay with submitting a PR. One possible avenue could be to allow giving the `supabase.auth.onAuthStateChange` in the `Supabase.initialize` function. I don't think that would be nice behaviour as listeners in different places get access to different events. Maybe a more specific event handler for the initial deeplink handling? Or then some way to get access to past events.

**Comment by bruiken** [comment]
After a bit further investigation in how we can do this, it seems this issue could be resolved by using `AppLinks.allUriLinkStream` instead of `AppLinks.uriLinkStream`. The former includes the initial link. This is different from the current implementation because this initial link will not be awaited and can thus be caught by our listeners.

A different solution for us would be if the deeplink integration had a bit more customisability. Allowing e.g. an enum option such as `enum DeeplinkHandlingOption { all, none, nonInitial }`. I don't really like this because this would just be duplicate implementation.

**Comment by bruiken** [comment]
> The initial link for password recovery events is handled like other events and should fire without issues. I have tested it with app_links v6.1.1 and supabase_flutter supabase_flutter v2.5.3, and can confirm I get a `AuthChangeEvent.passwordRecovery` event right after the `AuthChangeEvent.initialSession` event upon app launch.

@dshukertjr thanks for the reply! I indeed see the event getting fired. It is just that I see no way to actually receive that `AuthChangeEvent.passwordRecovery` in a listener, if it is caused by the initial deeplink handling. It seems impossible to create the subscription to the steam in time to get the event surfaced to our app logic.

**Comment by dshukertjr** [comment]
Hm, you should be able to catch the `passwordRecovery` event within your app. I was able to listen to it with the following code:

```dart
Future<void> main() async {
  await Supabase.initialize(
    url: supabaseUrl,
    anonKey: supabaseKey,
  );

  runApp(const MyApp());
}

final supabase = Supabase.instance.client;

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Playground',
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  String? _userId;
  late final RealtimeChannel channel;

  @override
  void initState() {
    super.initState();

    supabase.auth.onAuthStateChange.listen((event) {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        content: Text(event.event.name),
      ));
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(_userId ?? 'no user'),
            const SizedBox(height: 12),
            ElevatedButton(
              onPressed: () async {
                await supabase.auth.resetPasswordForEmail(
                  'dshukertjr@gmail.com',
                  redirectTo: redirectTo,
                );
              },
              child: const Text('Press'),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by bruiken** [comment]
> Hmm, you should be able to catch the `passwordRecovery` event within your app. I was able to listen to it with the following code:

@dshukertjr interestingly, I am running the same versions and do not see the events with the same code. I want to once again verify, I don't just mean starting the app from a paused/minimised state. I am only having issues with the app starting up fully (from a cold state) from a deeplink. This is tricky to test to legitimate flow because I don't see an easy way to set the initial deeplink when booting the app (I just set it manually in `SupabaseAuth`).

If the app is running in the background, I see the `passwordRecovery` event as expected. If the app is fully shut down I only get `initialSession`.

I'm putting the listener _immediately_ after the supabase initialisation as follows:
```dart
Future<void> main() async {
  await Supabase.initialize(
    url: dotenv.get('SUPABASE_URL'),
    anonKey: dotenv.get('SUPABASE_ANON_KEY'),
    authOptions: const FlutterAuthClientOptions(
      authFlowType: AuthFlowType.pkce,
    ),
    realtimeClientOptions: const RealtimeClientOptions(
      logLevel: RealtimeLogLevel.debug,
    ),
  );

  supabase.auth.onAuthStateChange.listen(
    (event) {
      log(event.event.name);
    },
    onError: (e) {
      log(e.toString());
    },
  );

  runApp(...);
}
```

With this, I test handling an initial deeplink as follows:
1. Reset password in app
2. Click link in browser on non-simulator
3. Copy the redirect uri to the app
4. Paste it as the result of `SupabaseAuth::_handleInitialUri()` as something like this:

    ```dart
    Uri? uri;
      try {
        // before app_links 6.0.0
        uri = await (_appLinks as dynamic).getInitialAppLink();
      } on NoSuchMethodError catch (_) {
        // Needed to keep compatible with 5.0.0 and 6.0.0
        // https://pub.dev/packages/app_links/changelog
        // after app_links 6.0.0
        uri = await (_appLinks as dynamic).getInitialLink();
      }

      // temp hack to test password forget link that is not already used
      uri = Uri.parse('REDIRECT LINK FROM (3) HERE');

      if (uri != null) {
        await _handleDeeplink(uri);
      }
    ```

5. stop and start the app

Then the output of my logging from the earlier snippet is as follows:

```
Xcode build done.                                           20.9s
Connecting to VM Service at ws://127.0.0.1:55185/LpjTqO-S8r8=/ws
flutter: ***** Supabase init completed Instance of 'Supabase'
flutter: ***** SupabaseDeepLinkingMixin startAuthObserver
flutter: ***** SupabaseAuthState handleDeeplink deeplink.test:?code=54cc8f0e-5292-46fa-8ae8-61cce09b4225
flutter: onReceivedAuthDeeplink uri: deeplink.test:?code=54cc8f0e-5292-46fa-8ae8-61cce09b4225
flutter: **** onAuthStateChange: AuthChangeEvent.passwordRecovery
flutter: {"access_token": ...
[log] initialSession
flutter: **** onAuthStateChange: AuthChangeEvent.initialSession
flutter: {"access_token":"...
```

I see the supabase event being fired, but it's not coming up in the listener. This makes sense as the listener subscribes after the whole processing of the deeplink is done (this seems to be the problem to me). Somehow it needs to be possible to get access to that stream during the _initial_ deeplink handling.

If I were to keep the app paused in the background and then do the password reset redirection logic I see the following:

```
flutter: ***** SupabaseAuthState handleDeeplink deeplink.test:?code=4800a17f-b5ae-46ae-97cb-1153d44106d9
flutter: onReceivedAuthDeeplink uri: deeplink.test:?code=4800a17f-b5ae-46ae-97cb-1153d44106d9
flutter: **** onAuthStateChange: AuthChangeEvent.passwordRecovery
flutter: {"access_token"...
[log] passwordRecovery
```

Which makes sense to me.


All of this is just for the legimate flow (when the password recovery link is valid). If the link is NOT valid, all of the errors are catched by the `SupabaseAuth` logic, so we cannot even catch those errors in the auth stream subscription. This is an equally big problem to me, as we can then show nothing to the user.

**Comment by dshukertjr** [comment]
>With this, I test handling an initial deeplink as follows:

I believe the reason why you are not seeing the password recovery event is because you are not testing it with the actual flow that the user goes through. 

Just run through the password recovery flow like usual and the password recovery event will show up whether the app is terminated or not. 

1. Call the `resetPasswordForEmail()` from the app
1. Terminate the app
1. Open the email from the same phone/ emulator and click the link
1. The app opens and password recovery event is observed after the initial session event.

**Comment by Mr-Pepe** [comment]
@dshukertjr On web, I am not able to catch the `passwordRecovery` event from a listener with your example code. 

I only modified the `initState` method as follows:
```dart
@override
void initState() {
  super.initState();

  print("Registering auth state change listener");
  supabase.auth.onAuthStateChange.listen((event) {
    print("Auth state changed: ${event.event}");
  });
}
```

1. Press the button
2. Click on the magic link in the password reset email
3. Get the following log output

```
***** Supabase init completed Instance of 'Supabase'

***** SupabaseDeepLinkingMixin startAuthObserver

**** onAuthStateChange: AuthChangeEvent.initialSession

{"access_token":"eyJhbGciOiJIU......

***** SupabaseAuthState handleDeeplink http://localhost:8000/?code=994226de-69df-4915-a9cd-f2dc2aa09652

onReceivedAuthDeeplink uri: http://localhost:8000/?code=994226de-69df-4915-a9cd-f2dc2aa09652

**** onAuthStateChange: AuthChangeEvent.passwordRecovery

{"access_token":"eyJhbGciOiJIU......

**** onAuthStateChange: AuthChangeEvent.initialSession

{"access_token":"eyJhbGciOiJIU......

Registering auth state change listener

Auth state changed: AuthChangeEvent.initialSession
```

Registering the listener directly after the Supabase initialization also does not catch the event.

**Comment by Mr-Pepe** [comment]
Or is there some way to get the events that were fired in the current session to determine whether the current session is a password reset session?

**Comment by bruiken** [comment]
@Mr-Pepe not sure if you have figured it out already, but the solution we made was as follows:

1. Disable deeplink listening on supabase side: this can be done by setting
   
   ```dart
     await Supabase.initialize(
       ...
       authOptions: const FlutterAuthClientOptions(
         ...
         detectSessionInUri: false,
       ),
     );
   ```

2. Listen to deeplinks yourself with the `app_links` package. When using the most recent version, the initial link will be exposed on the start of the subscription automatically, no special handling is needed:

```dart
bool _uriIsAuthDeeplink(Uri uri) {
  return uri.queryParameters.containsKey('code') ||
      uri.fragment.contains('error_description');
}

Future<void> _handleAuthDeeplink(Uri uri) async {
  try {
    await Supabase.instance.client.auth.getSessionFromUrl(uri);
  } on AuthException catch (e) {
    // handle error from supabase
  } catch (e, s) {
    log('Error handling auth deeplink', error: e, stackTrace: s);
  }
}

void startDeeplinkSubscription() {
  final appLinks = AppLinks();
  _deepLinkSubscription = appLinks.uriLinkStream.listen(
    (uri) async {
      if (_uriIsAuthDeeplink(uri)) {
        await _handleAuthDeeplink(uri);
      }
    },
    onError: (e, s) {
      log('Error receiving deeplink', error: e, stackTrace: s);
    },
  );
}
```

This system has been reliably for us. Note that this code is only created for the password recovery flow. If you also use supabase deeplinks for some other purpose, changes might be needed!

**Comment by Mr-Pepe** [comment]
@bruiken Thank you very much! That approach seems to do the trick and I am now adding a boolean `supabaseAuthRedirect` query parameter to my redirect URLs to identify Supabase redirects. That seems more robust than checking for various URL parameters Supabase might set in different scenarios. Can you think of any downsides to this approach?

@dshukertjr I'd still prefer it if there was no need for a workaround. This issue should probably be reopened. The feature is clearly not working as intended, because it is impossible to catch the auth state change.

**Comment by bruiken** [comment]
@Mr-Pepe I think that's fine, our redirects flow though another web page so we already have full control over the parameters. That's why we saw no need for another query parameter!

I also agree that this issue is still not solved. Didn't test for web personally but when cold booting mobile apps it also didn't work, for the same reason as you found.

The support for multiple `app_links` versions seems to have other side effects too, as the newer versions push the initial link though the listener stream by default. I think the Supabase implementation does this manually in all cases. This means that the initial link is handled twice on initialisation when using the newer versions of `app_links`.

In terms of implementation, I think the easiest is to allow giving the listener callback in the initialiser function for Supabase, or something like that.

**Comment by Mr-Pepe** [comment]
Yes, it seems it doesn't work on web at all because every new tab is a "cold boot".

I am not sure I fully understand the rest of your comment but that seems to explain why I get two `initialSession` events every time I start my web app.

Passing callbacks into `initialize` seems reasonable. The auth client is not initialized before that and adding listeners afterwards is already too late.

**Comment by bruiken** [comment]
I'll try to explain just for full context:
[This code in `supabase_auth.dart`](https://github.com/supabase/supabase-flutter/blob/main/packages/supabase_flutter/lib/src/supabase_auth.dart#L193) does a try-catch to get the initial app link because of breaking changes in the `app_links` package v6. 

Now note that the source of the `uriLinkSteam` Stream from `app_links` uses [this code](https://github.com/llfbandit/app_links/blob/master/app_links_web/lib/app_links_web.dart#L26), which spits out the initial link as well. This causes the initial link to be handled twice. I think this was changed in version 6.0.0 of the `app_links` package. Changelog [here](https://pub.dev/packages/app_links/changelog#600).

**Comment by dshukertjr** [comment]
> Or is there some way to get the events that were fired in the current session to determine whether the current session is a password reset session?

You can simply redirect the user to a different page for password reset.

**Comment by Mr-Pepe** [comment]
Generally, I don't like the idea of allowing users to change their password without authorization (for example via entering their current password).

In the password reset scenario, the user has already confirmed that they are authorized because they clicked the magic link sent to their email address. However, without the `passwordRecovery` event, it's not possible to distinguish a session started via that link from any other session.

A dedicated password reset page would still allow users to change their password without additional authorization from any session.

**Comment by dshukertjr** [comment]
>A dedicated password reset page would still allow users to change their password without additional authorization from any session.

No, it wouldn't, because Supabase auth does not allow an unauthenticated user to update passwords. 

So the way it works is when you call the `resetPasswordForEmail` method, you pass the password reset page via redirectTo. The user will land on the password reset page upon clicking on the recovery link. When they land on the page they are authenticated. If you would like, you could also check their authenticated state when they land on the page if you want the user to not be able to open the page by directly entering a URL.

```dart
supabase.auth.resetPasswordForEmail(
  'email',
  redirectTo: 'https://myapp.com/password-reset',
);
```

**Comment by Mr-Pepe** [comment]
Sorry, maybe I didn't express myself clearly. I understand that only authenticated users can update passwords. The emphasis is on "without *additional* authorization". There are two use cases:

1. The user knows their current password and wants to change it to a new password. In this case they should show that it's really them by entering the current password.
2. The user forgot their password and requests a password reset. In this case they show that it's really them by clicking the link in the password reset email.

With your solution any authenticated user could go to `https://myapp.com/password-reset` and change their password by simply typing in a new password. However, only if a user logged in via the magic link sent in a password reset email should they be able to directly set a new password. 

The problem is that it is currently not possible to know whether the current session was started by clicking a password reset link because it is not possible to listen to the `passwordRecovery` event.

**Comment by dshukertjr** [comment]
@Mr-Pepe 
>With your solution any authenticated user could go to https://myapp.com/password-reset and change their password by simply typing in a new password. However, only if a user logged in via the magic link sent in a password reset email should they be able to directly set a new password.

Supabase auth allows passwords to be updated if a user is simply authenticated, so you having the users enter their password again is just security through obscurity. You should understand and accept how Supabase works, and make your application work with it. t

**Comment by Mr-Pepe** [comment]
Thanks for the advice :)

To get back to the topic of this issue: Is this a bug from your point of view? Or is reacting to the `passwordRecovery` event not a use case that Supabase wants to support?

**Comment by dshukertjr** [comment]
@Mr-Pepe Yeah, it's a bug that happens on Flutter web.
