### ISSUE TITLE
 NoSuchMethodError: Class 'AppLinks' has no instance method 'getInitialAppLink'

### ISSUE THREAD

**Issue by murshidm** [supabase/supabase-flutter#941]
This bug report describes a NoSuchMethodError encountered when using the supabase_flutter package with the AppLinks dependency.

### Create a Flutter project and include the following dependencies in your pubspec.yaml:
```
YAML
dependencies:
  supabase_flutter: 2.5.4
  app_links: 6.1.1

```
### Initialize Supabase in your main.dart file:

```
Dart
void main() async {
  await Supabase.initialize(
    url: 'YOUR_SUPABASE_URL',
    anonKey: 'YOUR_SUPABASE_ANON_KEY',
  );
  runApp(MyApp());
}

```
### Run the application in debug mode with the setting "Capture all exceptions" enabled.

Observe the error in the console:

```
Exception has occurred.
NoSuchMethodError (NoSuchMethodError: Class 'AppLinks' has no instance method 'getInitialAppLink'.
Receiver: Instance of 'AppLinks'
Tried calling: getInitialAppLink())
Expected Behavior:
```

## Expected Behavior:

The Supabase.initialize call should initialize the Supabase client without errors.

## Additional Information:

VSCode Version: 1.89.1 (Universal)
Operating System: Apple Silicon macOS Sonoma
Supabase Client Version: 2.5.4
AppLinks Version: 6.1.1

## Possible Cause:

The getInitialAppLink method might be deprecated in newer versions of the app_links package.

## Please note:

I have already tried ignoring debugSdkLibraries and debugExternalPackageLibraries in VSCode settings, but the error persists.

**Comment by dshukertjr** [comment]
The SDK is working as expected, and the error that you see is being caught within the SDK. Set your VS code to only catch uncaught exceptions, and you will be fine.

**Comment by saropa** [comment]
We have the same issue here. Disabling error reporting (even within the SDK) isn't ideal. It would be nice if an exception was not raised.

**Comment by Dev-Adnani** [comment]
Facing Same Issue @dshukertjr

**Comment by icodeyou** [comment]
Facing same issue. @dshukertjr Please reopen the issue !

**Comment by bqubique** [comment]
Weird thing is, the initialization logic already handles this exception, but it still throws...

**Comment by Delthoid** [comment]
Still an issue on supabase_flutter: ^2.9.1, and it's kinda annoying.

**Comment by Barzi-Yassin** [comment]
I have been facing the same problem.
### Solved for me by disabling the `detectSessionInUri` at `FlutterAuthClientOptions` in the Supabase initialize method `authOptions` property:


```
    await Supabase.initialize(
      url: yourSupabaseUrl,
      anonKey: yourSupabaseAnonKey,
      authOptions: FlutterAuthClientOptions(
        detectSessionInUri: false,
      ),
    );

```
_"Now the Supabase auth with email & password works properly as intended"._ ✅ (on Apple Silicon MacbookPro) 

The only packages I have in my project:
```
dependencies:
  supabase_flutter: ^2.9.1
  provider: ^6.1.5
  google_sign_in: ^7.1.0
```

My Flutter version:
```
myproject % flutter --version
Flutter 3.32.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b25305a883 (6 weeks ago) • 2025-05-29 10:40:06 -0700
Engine • revision 1425e5e9ec (6 weeks ago) • 2025-05-28 14:26:27 -0700
Tools • Dart 3.8.1 • DevTools 2.45.1
```

**Comment by Barzi-Yassin** [comment]
I have been facing the same problem.
### Solved for me by disabling the `detectSessionInUri` at `FlutterAuthClientOptions` in the Supabase initialize method `authOptions` property:


```
    await Supabase.initialize(
      url: yourSupabaseUrl,
      anonKey: yourSupabaseAnonKey,
      authOptions: FlutterAuthClientOptions(
        detectSessionInUri: false,
      ),
    );

```
_"Now the Supabase auth with email & password works properly as intended"._ ✅ (on Apple Silicon MacbookPro) 
But, I'm not sure if it causes any side effects to other Auth providers！

The only packages I have in my project:
```
dependencies:
  supabase_flutter: ^2.9.1
  provider: ^6.1.5
```

My Flutter version:
```
myproject % flutter --version
Flutter 3.32.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b25305a883 (6 weeks ago) • 2025-05-29 10:40:06 -0700
Engine • revision 1425e5e9ec (6 weeks ago) • 2025-05-28 14:26:27 -0700
Tools • Dart 3.8.1 • DevTools 2.45.1
```

**Comment by gwangbaekun** [comment]
Think this error is as expected. Set your debugger to break on uncaught exceptions only. In my case All Exceptions were checked.

**Comment by bqubique** [comment]
> Think this error is as expected. Set your debugger to break on uncaught exceptions only. In my case All Exceptions were checked.

Ignoring an issue does not mean it is fixed.
