### ISSUE TITLE
flutter: `app_links_linux` threw an error

### ISSUE THREAD

**Issue by arkryonia** [supabase/supabase-flutter#956]
**Describe the bug**
flutter: `app_links_linux` threw an error: 
```
'package:flutter/src/services/platform_channel.dart': Failed assertion: line 554 pos 7: '_binaryMessenger != null || BindingBase.debugBindingType() != null': Cannot set the method call handler before the binary messenger has been initialized. This happens when you call setMethodCallHandler() before the WidgetsFlutterBinding has been initialized. You can fix this by either calling WidgetsFlutterBinding.ensureInitialized() before this or by passing a custom BinaryMessenger instance to MethodChannel().. The app may not function as expected until you remove this plugin from pubspec.yaml

════════ Exception caught by services library ══════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel com.llfbandit.app_links/events:
MissingPluginException(No implementation found for method listen on channel com.llfbandit.app_links/events)
```

**To Reproduce**
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Supabase.initialize(
    url: AppSecret.supabaseUrl,
    anonKey: AppSecret.supabaseAnonKey,
  );

  runApp(const MyApp());
}
```

**Version :**
On Linux/macOS
└── supabase_flutter 2.5.6
    ├── supabase 2.2.2
    │   ├── functions_client 2.2.0
    │   ├── gotrue 2.8.1
    │   ├── postgrest 2.1.2
    │   ├── realtime_client 2.1.0
    │   ├── storage_client 2.0.2

**Comment by Vinzent03** [comment]
Seems related to this [issue](https://github.com/llfbandit/app_links/issues/84). Which `app_links` version are you using?

**Comment by arkryonia** [comment]
> Seems related to this [issue](https://github.com/llfbandit/app_links/issues/84). Which `app_links` version are you using?

Hi.

I'm not using `app_links` directly in my project. It's a Supabase Dependency. I used to install the latest version but the error is still throwing.

**Comment by arkryonia** [comment]
I fixed the bug. I installed the 3.5.0 version of `app_links` and everything is ok.

**Comment by arkryonia** [comment]
I fixed the bug. I installed the 3.5.0 version of `app_links` and everything is ok.
