### ISSUE TITLE
 A package may not list itself as a dependency

### ISSUE THREAD

**Issue by pepie** [supabase/supabase-flutter#957]
**Describe the bug**
Unable to install supabase_flutter 2.5.6. 
```flutter pub get``` returns 
``` Because supabase depends on supabase_flutter ^2.5.6 which depends on supabase 2.2.2, supabase 2.2.2 is required.
So, because supabase is 1.0.0+1, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on supabase_flutter: flutter pub add supabase_flutter:^1.0.1```

**To Reproduce**
Steps to reproduce the behavior:
1. Add ```supabase_flutter: ^2.5.6``` to pubspec.yaml
2. Run ```flutter pub get```
4. See error

**Expected behavior**
Package install and  ```flutter run``` completes successfully
<img width="791" alt="Screenshot 2024-06-26 at 11 32 17 PM" src="https://github.com/supabase/supabase-flutter/assets/4885426/3e9808c3-5095-42e1-96fe-937a184ff905">


**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version (please complete the following information):**
On Linux/macOS
Please run `dart pub deps | grep -E "supabase|gotrue|postgrest|storage_client|realtime_client|functions_client"` in your project directory and paste the output here.

```Because supabase depends on supabase_flutter ^2.5.6 which depends on supabase 2.2.2, supabase 2.2.2 is required.
So, because supabase is 1.0.0+1, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on supabase_flutter: dart pub add supabase_flutter:^1.0.1```

On Windows
Please run `dart pub deps | findstr "supabase gotrue postgrest storage_client realtime_client functions_client"` in your project directory and paste the output here.

**Additional context**
Add any other context about the problem here.

**Comment by dshukertjr** [comment]
You probably have `spuabase` package as a dependency in your project. Remove it and you are good to go!

**Comment by pepie** [comment]
> You probably have `spuabase` package as a dependency in your project. Remove it and you are good to go!

@dshukertjr See the updated ticket.
When using 'supabase_flutter 2.5.6.' by itself, it complains that ```Because supabase depends on supabase_flutter ^2.5.6 which depends on supabase 2.2.2, supabase 2.2.2 is required```

If I add 'supabase 2.2.2' then I get
```A package may not list itself as a dependency```

Here's my full pubspec file

First Error
```name: supabase
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
```

With both libraries:
```name: supabase
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase: 2.2.2
  supabase_flutter: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
```

**Comment by pepie** [comment]
I've ran "flutter clean" a few times already.

I also noticed that, running 'flutter pub add supabase_flutter' will install version 1.x and not the latest version (2.5.x)

**Comment by dshukertjr** [comment]
@pepie You probably messed up your pub cache. Try resetting it. 
https://dart.dev/tools/pub/cmd/pub-cache#clearing-the-global-system-cache

**Comment by pepie** [comment]
@dshukertjr I think this might be a bug with 2.5.6.
I cleaned the cache and stil get the same error
```
dart pub cache clean
flutter clean   (just to be redundant)
flutter pub get
flutter doctor
```
Still the same error.

I removed the packages from pubspec.yml and ran "flutter pub get" and everything was fine.

I then installed the package from the command line, with ```flutter pub add supabase_flutter```

This works, but the installed version is ``` supabase_flutter: ^1.0.1``` .  I expected this to install the latest version (2.5.6)

**Comment by dshukertjr** [comment]
@pepie I can assure you it's not a bug on Supabase's end. Not sure what it is, but it has to do with your local settings. `flutter pug add` command will [automatically install the latest stable version](https://dart.dev/tools/pub/cmd/pub-add#version-constraint). If it's not, it most likely has to do with your local configuration or perhaps the Flutter version.

If you cannot figure out what is wrong, I might try removing Flutter and re-installing it.

**Comment by pepie** [comment]
I don't think it's my flutter installation. I don't experience this with other packages.

I just executed the following sequence in the same project, to test this issue:

% flutter pub add amplify_flutter
Result: Installed amplify_flutter 2.1.0 - the latest package
  
% flutter pub add supabase
Result: Because supabase depends on supabase, version solving failed.

% flutter pub add supabase_flutter
Result:  "supabase_flutter 1.0.1 (2.5.6 available) "
** Here, again, version 1.0.1 was instaleld when 2.5.6 is available

% flutter pub add uuid
Result: installed   uuid 4.4.0 (latest package)
  
% flutter pub add supabase:2.5.6
Result: "Because supabase depends on supabase, version solving failed."


It seems supabse is reference itself.

**Comment by pepie** [comment]
@dshukertjr I think I figured it .
I named my test project 'supabase', which collided with the package name. This explains the self-referencing error.

I renamed the project 'supabase_test'  and ran 'flutter pub add supabase_flutter'. Everything seems to work now

**Comment by dshukertjr** [comment]
😅
