### ISSUE TITLE
Redirect link in email change confirmation email wrong

### ISSUE THREAD

**Issue by Mr-Pepe** [supabase/supabase-flutter#961]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have a Flutter web app. 

Calling `updateUser` with a new email sends two confirmation emails. 

Both emails contain a confirmation link ending with
 `&type=email_change&redirect_to=http://localhost:8000/#/settings?enableUserSignIn`. 

However, clicking one of the two links redirects to 
`http://localhost:8000/#message=Confirmation+link+accepted.+Please+proceed+to+confirm+link+sent+to+the+other+email`. 

Clicking the other link (order doesn't seem to matter) redirects to 
`http://localhost:8000/#/settings?enableUserSignIn#access_token=eyJhbGciblablabla&token_type=bearer&type=email_change` 
which is also not a valid URL with the hashtag instead of an ampersand.

## Expected behavior

Supabase honors the redirect link I provided and adds query parameters correctly.  

## System information

- OS: Arch Linux
- Browser: 127.0.1 (64-bit)

## Additional context

I couldn't find any documentation on how the workflow should be implemented correctly. Not gonna lie, implementing basic user management functionalities with Supabase (Auth) and its Flutter client has been mostly disappointing so far due to stuff like https://github.com/supabase/supabase/issues/27554, https://github.com/supabase/supabase-flutter/issues/937, and https://github.com/supabase/auth/issues/1517.

**Comment by dshukertjr** [comment]
@Mr-Pepe The implicit flow isn't going to work on Flutter web by default due to it using # for different pages. You can use the [url_strategy](https://pub.dev/packages/url_strategy) package so that it will use query parameters instead of # so that the supabase_flutter package can properly process the auth fragments.

**Comment by Mr-Pepe** [comment]
I think it's not even necessary to use that package. The URL strategy can be changed as described [here](https://docs.flutter.dev/ui/navigation/url-strategies). I did that and it seems to work as expected. 

Is it documented somewhere that Supabase Auth and Flutter don't work well together out-of-the-box? It could potentially save some people some time if it was explicitly mentioned that the URL strategy needs to be changed. 

One issue remains though: After clicking the second email change confirmation link, `client.auth.currentUser?.email` still contains the old email. Should I create a separate issue for that?

**Comment by dshukertjr** [comment]
@Mr-Pepe 
Not at the moment. Feel free to open a PR if you would like. 

>Should I create a separate issue for that?

Feel free to do so.
