### ISSUE TITLE
Auth Exception: Bad ID Token with status code 400

### ISSUE THREAD

**Issue by binhdowkm** [supabase/supabase-flutter#972]
### Steps to reproduce the behavior:
1. Config Google Sign In for Flutter app follow Supabase Documents
2. Sign in and got `idToken`, `accessToken`
3. Using these tokens to sign in supabase by `signInWithIdToken`
4. Got error: 
`AuthException(message: Bad ID token, statusCode: 400)`
6. Check **Auth Logs** on Supabase Console: 
For Android
`"error": "oidc: failed to unmarshal claims: invalid character 'k' looking for beginning of value"`
For iOS:
`"error": "oidc: malformed jwt: oidc: malformed jwt payload: illegal base64 data at input byte 212"`

### Version:

Dart SDK 3.4.0
Flutter SDK 3.22.0
supabase_flutter 2.5.8

Thanks ❤️

**Comment by yegormi** [comment]
@binhdowkm Hey, can you give a comment on how did you resolve this issue?

**Comment by manojtr** [comment]
@binhdowkm did you solve this? Please share if you dont mind. Thanks
