### ISSUE TITLE
Supabase Auth on Flutter Web does not detect access token in url (Google & Apple)

### ISSUE THREAD

**Issue by UntitledApps** [supabase/supabase-flutter#974]
**Bug Report**

**Describe the Bug**

When attempting to log in via Apple or Google and being redirected back to [my app](https://askrudi.app), Supabase does nothing. Apple and Google authentication are set up correctly (they work on iOS & Android), but the web functionality has stopped working. Logging in via email works. The strange thing is that Apple & Google login on the web was working just a week ago, but now it doesn't work anymore. I'm using the latest package version and am listening to Supabase Auth changes.

Tested on Mac with Safari & Chrome.

**To Reproduce**
1. Go to [Account Settings](https://www.askrudi.app/settings/account)
2. Click on Login/Signup
3. Log in with either Google or Apple
4. Get redirected back to the app with the access token clearly in the URL, but nothing happens. No error logs appear in the console.

**Expected Behavior**
Supabase should log me in.

**Screenshots**
![Screenshot](https://github.com/user-attachments/assets/86bb7aae-93ed-4888-b969-abe7c7b5ad4a)

**Version (please complete the following information):**
├── supabase_flutter 2.5.8
│   ├── supabase 2.2.4
│   │   ├── functions_client 2.2.0
│   │   ├── gotrue 2.8.3
│   │   ├── postgrest 2.1.2
│   │   ├── realtime_client 2.2.0
│   │   ├── storage_client 2.0.2

**Comment by Vinzent03** [comment]
@UntitledApps We should be able to release it within the next two days, but you can always specify the package by the GitHub repo to get the latest branch version.
